// build.js — Ahead-of-time JSX → JS compiler.
//
// ════════════════════════════════════════════════════════════════════════════
// WHY THIS EXISTS
// ─────────────────────────────────────────────────────────────────────────────
// The site originally shipped raw .jsx and transpiled it IN THE BROWSER with
// babel-standalone (~3 MB script + a multi-second main-thread transpile on
// every page load — brutal on weak devices).
//
// This script does that transpile ONCE, offline. It reads every .jsx under
// src/components/, runs Babel's React preset, and writes a plain .js sibling.
// index.html then loads the compiled .js as ordinary <script> — no babel,
// no in-browser compile.
//
// USAGE
// ─────────────────────────────────────────────────────────────────────────────
//   node build.js
//
// Run this after editing ANY .jsx file. The .jsx files remain the source of
// truth; the .js files are generated artifacts.
//
// IMPLEMENTATION NOTES
// ─────────────────────────────────────────────────────────────────────────────
// We reuse the babel-standalone bundle already vendored in vendor/babel.min.js
// rather than adding an npm dependency. Loaded in a Node CommonJS context it
// exposes `Babel.transform`. The "react" preset converts JSX → React.create-
// Element; no module transform is applied because the components are plain
// browser scripts that share globals (window.*), not ES modules.
// ════════════════════════════════════════════════════════════════════════════

"use strict";

const fs = require("fs");
const path = require("path");
const validateSite = require("./scripts/validate-site.js").validate;

// ── Configuration ──────────────────────────────────────────────────────────
const COMPONENTS_DIR = path.join(__dirname, "src", "components");
const BABEL_BUNDLE = path.join(__dirname, "vendor", "babel.min.js");
// JSX entry files, in load order. Order matters: later files depend on
// globals defined by earlier ones.
const JSX_FILES = [
  "tweaks-panel.jsx",
  "components-1.jsx",
  "components-2.jsx",
  "app.jsx",
];
// Babel preset configuration. "react" → JSX transform only.
const BABEL_OPTIONS = { presets: ["react"], compact: false, comments: true };
// Banner prepended to every generated file so it's never mistaken for source.
const GENERATED_BANNER =
  "/* AUTO-GENERATED by build.js from $SRC — DO NOT EDIT.\n" +
  "   Edit the .jsx source and re-run `node build.js`. */\n";

function loadBabel() {
  // babel-standalone UMD: in a CommonJS context it assigns module.exports.
  // require() returns the Babel object directly.
  const babel = require(BABEL_BUNDLE);
  if (!babel || typeof babel.transform !== "function") {
    throw new Error("babel-standalone did not expose transform()");
  }
  return babel;
}

function compileFile(babel, jsxName) {
  const srcPath = path.join(COMPONENTS_DIR, jsxName);
  if (!fs.existsSync(srcPath)) {
    throw new Error("source not found: " + srcPath);
  }
  const source = fs.readFileSync(srcPath, "utf8");
  const result = babel.transform(source, BABEL_OPTIONS);
  if (!result || typeof result.code !== "string") {
    throw new Error("transform produced no code for " + jsxName);
  }
  const outName = jsxName.replace(/\.jsx$/, ".js");
  const outPath = path.join(COMPONENTS_DIR, outName);
  const banner = GENERATED_BANNER.replace("$SRC", jsxName);
  fs.writeFileSync(outPath, banner + result.code, "utf8");
  return { outName: outName, bytes: Buffer.byteLength(result.code, "utf8") };
}

// ── Product landings ────────────────────────────────────────────────────────
// Generate a static /projects/<slug>/index.html for each product that a visitor
// can't see live (they used to link straight to a GitHub card). Content +
// template come from src/projects/{landings-data,render}.js — the SAME render()
// the page loads client-side, so the baked HTML and the language switcher never
// drift. Real files → clean shareable URLs, own <title>/OG, indexable, instant.
const SITE_BASE = "https://samandarmansurkhodjaev2713.github.io/CV-Samandar/";

function readLandingVersion() {
  try {
    const idx = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
    const m = idx.match(/\?v=(\d+)/);
    return m ? m[1] : "";
  } catch (e) { return ""; }
}

function htmlAttr(s) {
  return String(s == null ? "" : s)
    .replace(/&/g, "&amp;").replace(/"/g, "&quot;")
    .replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function renderLandingPage(p, R, version) {
  const ru = (p.i18n && p.i18n.ru) || {};
  const v = version ? "?v=" + version : "";
  const title = p.name + (ru.tag ? " — " + ru.tag.replace(/ · /g, " / ") : "");
  const desc = ru.signal || "";
  const ogUrl = SITE_BASE + "projects/" + p.slug + "/";
  // Each case owns a photographic 3:1 social preview instead of sharing the
  // portfolio cover. This keeps Telegram/LinkedIn links visually distinct.
  const ogImg = SITE_BASE + "assets/proj/" + p.visual;
  const body = R.LP_render(p, "ru");
  return [
    "<!doctype html>",
    '<html lang="ru">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    "<title>" + htmlAttr(title) + "</title>",
    '<meta name="description" content="' + htmlAttr(desc) + '">',
    '<meta name="robots" content="index,follow">',
    '<link rel="canonical" href="' + htmlAttr(ogUrl) + '">',
    '<meta property="og:type" content="website">',
    '<meta property="og:title" content="' + htmlAttr(title) + '">',
    '<meta property="og:description" content="' + htmlAttr(desc) + '">',
    '<meta property="og:url" content="' + htmlAttr(ogUrl) + '">',
    '<meta property="og:image" content="' + htmlAttr(ogImg) + '">',
    '<meta property="og:image:width" content="1536">',
    '<meta property="og:image:height" content="512">',
    '<meta name="twitter:card" content="summary_large_image">',
    '<meta name="theme-color" content="#171713">',
    '<link rel="icon" href="../../favicon.svg">',
    '<link rel="stylesheet" href="../../src/styles/fonts.css' + v + '">',
    '<link rel="stylesheet" href="../../src/projects/landing.css' + v + '">',
    "</head>",
    "<body>",
    '<div id="lp-root">' + body + "</div>",
    "<script>window.__LP_SLUG__=" + JSON.stringify(p.slug) + ";</script>",
    '<script src="../../src/content/product-registry.js' + v + '"></script>',
    '<script src="../../src/projects/landings-new.js' + v + '"></script>',
    '<script src="../../src/projects/landings-data.js' + v + '"></script>',
    '<script src="../../src/projects/render.js' + v + '"></script>',
    '<script src="../../src/projects/landing.js' + v + '"></script>',
    "</body>",
    "</html>",
    "",
  ].join("\n");
}

function buildLandings() {
  const dataPath = path.join(__dirname, "src", "projects", "landings-data.js");
  const renderPath = path.join(__dirname, "src", "projects", "render.js");
  if (!fs.existsSync(dataPath) || !fs.existsSync(renderPath)) return 0;
  // Fresh load so a `node build.js` re-run picks up edits within one process.
  delete require.cache[require.resolve(dataPath)];
  delete require.cache[require.resolve(renderPath)];
  const LANDINGS = require(dataPath);
  const R = require(renderPath);
  const version = readLandingVersion();
  const slugs = Object.keys(LANDINGS);
  slugs.forEach(function (slug) {
    const p = LANDINGS[slug];
    const dir = path.join(__dirname, "projects", slug);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, "index.html"), renderLandingPage(p, R, version), "utf8");
    process.stdout.write("[build] landing -> projects/" + slug + "/index.html\n");
  });
  return slugs.length;
}

function main() {
  try {
    const contract = validateSite({ generated: false });
    process.stdout.write(
      "[build] contract OK — " + contract.products + " products, " +
      contract.cases + " case routes, " + contract.locales + " locales\n"
    );
  } catch (err) {
    process.stderr.write("[build] contract FAILED: " + err.message + "\n");
    process.exit(1);
    return;
  }

  let babel;
  try {
    babel = loadBabel();
  } catch (err) {
    process.stderr.write("[build] failed to load Babel: " + err.message + "\n");
    process.exit(1);
    return;
  }

  let totalBytes = 0;
  for (let i = 0; i < JSX_FILES.length; i++) {
    const jsxName = JSX_FILES[i];
    try {
      const info = compileFile(babel, jsxName);
      totalBytes += info.bytes;
      process.stdout.write("[build] " + jsxName + " -> " + info.outName + "  (" + info.bytes + " bytes)\n");
    } catch (err) {
      process.stderr.write("[build] FAILED on " + jsxName + ": " + err.message + "\n");
      process.exit(1);
      return;
    }
  }
  let landingCount = 0;
  try {
    landingCount = buildLandings();
    validateSite({ generated: true });
  } catch (err) {
    process.stderr.write("[build] landings FAILED: " + err.message + "\n");
    process.exit(1);
    return;
  }
  process.stdout.write(
    "[build] done — " + JSX_FILES.length + " files, " + totalBytes +
    " bytes total; " + landingCount + " landing(s).\n"
  );
}

main();
