// build.js — Ahead-of-time JSX → JS compiler.
//
// ════════════════════════════════════════════════════════════════════════════
// WHY THIS EXISTS
// ─────────────────────────────────────────────────────────────────────────────
// The site originally shipped raw .jsx and transpiled it IN THE BROWSER with
// babel-standalone (~3 MB script + a multi-second main-thread transpile on
// every page load — brutal on weak devices).
//
// This script does that transpile ONCE, offline. It reads every .jsx under
// src/components/, runs Babel's React preset, and writes a plain .js sibling.
// index.html then loads the compiled .js as ordinary <script> — no babel,
// no in-browser compile.
//
// USAGE
// ─────────────────────────────────────────────────────────────────────────────
//   node build.js
//
// Run this after editing ANY .jsx file. The .jsx files remain the source of
// truth; the .js files are generated artifacts.
//
// IMPLEMENTATION NOTES
// ─────────────────────────────────────────────────────────────────────────────
// We reuse the babel-standalone bundle already vendored in vendor/babel.min.js
// rather than adding an npm dependency. Loaded in a Node CommonJS context it
// exposes `Babel.transform`. The "react" preset converts JSX → React.create-
// Element; no module transform is applied because the components are plain
// browser scripts that share globals (window.*), not ES modules.
// ════════════════════════════════════════════════════════════════════════════

"use strict";

const fs = require("fs");
const path = require("path");

// ── Configuration ──────────────────────────────────────────────────────────
const COMPONENTS_DIR = path.join(__dirname, "src", "components");
const BABEL_BUNDLE = path.join(__dirname, "vendor", "babel.min.js");
// JSX entry files, in load order. Order matters: later files depend on
// globals defined by earlier ones.
const JSX_FILES = [
  "tweaks-panel.jsx",
  "components-1.jsx",
  "components-2.jsx",
  "app.jsx",
];
// Babel preset configuration. "react" → JSX transform only.
const BABEL_OPTIONS = { presets: ["react"], compact: false, comments: true };
// Banner prepended to every generated file so it's never mistaken for source.
const GENERATED_BANNER =
  "/* AUTO-GENERATED by build.js from $SRC — DO NOT EDIT.\n" +
  "   Edit the .jsx source and re-run `node build.js`. */\n";

function loadBabel() {
  // babel-standalone UMD: in a CommonJS context it assigns module.exports.
  // require() returns the Babel object directly.
  const babel = require(BABEL_BUNDLE);
  if (!babel || typeof babel.transform !== "function") {
    throw new Error("babel-standalone did not expose transform()");
  }
  return babel;
}

function compileFile(babel, jsxName) {
  const srcPath = path.join(COMPONENTS_DIR, jsxName);
  if (!fs.existsSync(srcPath)) {
    throw new Error("source not found: " + srcPath);
  }
  const source = fs.readFileSync(srcPath, "utf8");
  const result = babel.transform(source, BABEL_OPTIONS);
  if (!result || typeof result.code !== "string") {
    throw new Error("transform produced no code for " + jsxName);
  }
  const outName = jsxName.replace(/\.jsx$/, ".js");
  const outPath = path.join(COMPONENTS_DIR, outName);
  const banner = GENERATED_BANNER.replace("$SRC", jsxName);
  fs.writeFileSync(outPath, banner + result.code, "utf8");
  return { outName: outName, bytes: Buffer.byteLength(result.code, "utf8") };
}

function main() {
  let babel;
  try {
    babel = loadBabel();
  } catch (err) {
    process.stderr.write("[build] failed to load Babel: " + err.message + "\n");
    process.exit(1);
    return;
  }

  let totalBytes = 0;
  for (let i = 0; i < JSX_FILES.length; i++) {
    const jsxName = JSX_FILES[i];
    try {
      const info = compileFile(babel, jsxName);
      totalBytes += info.bytes;
      process.stdout.write("[build] " + jsxName + " -> " + info.outName + "  (" + info.bytes + " bytes)\n");
    } catch (err) {
      process.stderr.write("[build] FAILED on " + jsxName + ": " + err.message + "\n");
      process.exit(1);
      return;
    }
  }
  process.stdout.write("[build] done — " + JSX_FILES.length + " files, " + totalBytes + " bytes total.\n");
}

main();
