// build.js — Ahead-of-time JSX → JS compiler.
//
// ════════════════════════════════════════════════════════════════════════════
// WHY THIS EXISTS
// ─────────────────────────────────────────────────────────────────────────────
// The site originally shipped raw .jsx and transpiled it IN THE BROWSER with
// babel-standalone (~3 MB script + a multi-second main-thread transpile on
// every page load — brutal on weak devices).
//
// This script does that transpile ONCE, offline. It reads every .jsx under
// src/components/, runs Babel's React preset, and writes a plain .js sibling.
// index.html then loads the compiled .js as ordinary <script> — no babel,
// no in-browser compile.
//
// USAGE
// ─────────────────────────────────────────────────────────────────────────────
//   node build.js
//
// Run this after editing ANY .jsx file. The .jsx files remain the source of
// truth; the .js files are generated artifacts.
//
// IMPLEMENTATION NOTES
// ─────────────────────────────────────────────────────────────────────────────
// We reuse the babel-standalone bundle already vendored in vendor/babel.min.js
// rather than adding an npm dependency. Loaded in a Node CommonJS context it
// exposes `Babel.transform`. The "react" preset converts JSX → React.create-
// Element; no module transform is applied because the components are plain
// browser scripts that share globals (window.*), not ES modules.
// ════════════════════════════════════════════════════════════════════════════

"use strict";

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const lightningcss = require("lightningcss");
const validateSite = require("./scripts/validate-site.js").validate;

// ── Configuration ──────────────────────────────────────────────────────────
const COMPONENTS_DIR = path.join(__dirname, "src", "components");
const BABEL_BUNDLE = path.join(__dirname, "vendor", "babel.min.js");
// JSX entry files, in load order. Order matters: later files depend on
// globals defined by earlier ones.
const JSX_FILES = [
  "tweaks-panel.jsx",
  "components-1.jsx",
  "components-2.jsx",
  "app.jsx",
];
// Authoring remains split by responsibility, while production receives one
// blocking stylesheet in the exact same cascade order. This cuts six network
// requests and minifies without asking contributors to edit generated CSS.
const STYLE_SOURCES = [
  "fonts.css",
  "styles.css",
  "sections.css",
  "cursor.css",
  "cv-doc.css",
  "features.css",
  "art-direction.css",
  "release-polish.css",
  "release-proof.css",
];
const STYLES_DIR = path.join(__dirname, "src", "styles");
const STYLE_BUNDLE = "app.bundle.min.css";
// Babel preset configuration. "react" → JSX transform only.
// Generated component scripts are shipped directly, so whitespace/comments
// are deployment bytes and parser work. Keep authored JSX readable and emit a
// compact deterministic classic-script representation.
const BABEL_OPTIONS = { presets: ["react"], compact: true, comments: false };
// Banner prepended to every generated file so it's never mistaken for source.
const GENERATED_BANNER =
  "/* AUTO-GENERATED by build.js from $SRC — DO NOT EDIT.\n" +
  "   Edit the .jsx source and re-run `node build.js`. */\n";

const RETRYABLE_WRITE_CODES = new Set(["EACCES", "EBUSY", "EPERM", "UNKNOWN"]);
const WRITE_RETRY_DELAYS_MS = [20, 40, 80, 120, 180, 260];

function sleepSync(ms) {
  // Builds are synchronous by design. Atomics.wait avoids a CPU-burning busy
  // loop while Windows Defender/indexers release a short-lived file handle.
  const signal = new Int32Array(new SharedArrayBuffer(4));
  Atomics.wait(signal, 0, 0, ms);
}

function normalizeLf(value) {
  // Generated artifacts are deployed from Linux but are also built on Windows.
  // Canonical LF bytes keep CSP hashes and committed output platform-neutral.
  return String(value).replace(/\r\n?/g, "\n");
}

function writeUtf8IfChanged(filePath, content) {
  const next = normalizeLf(content);
  try {
    // Do not rewrite byte-identical artifacts. Apart from preserving mtimes,
    // this makes immediate repeated builds immune to transient Windows locks.
    if (fs.readFileSync(filePath, "utf8") === next) return false;
  } catch (error) {
    if (error && error.code !== "ENOENT" && !RETRYABLE_WRITE_CODES.has(error.code)) throw error;
  }

  let lastError = null;
  for (let attempt = 0; attempt <= WRITE_RETRY_DELAYS_MS.length; attempt += 1) {
    try {
      fs.writeFileSync(filePath, next, "utf8");
      return true;
    } catch (error) {
      lastError = error;
      if (!error || !RETRYABLE_WRITE_CODES.has(error.code) || attempt === WRITE_RETRY_DELAYS_MS.length) {
        throw error;
      }
      sleepSync(WRITE_RETRY_DELAYS_MS[attempt]);
    }
  }
  throw lastError;
}

function loadBabel() {
  // babel-standalone UMD: in a CommonJS context it assigns module.exports.
  // require() returns the Babel object directly.
  const babel = require(BABEL_BUNDLE);
  if (!babel || typeof babel.transform !== "function") {
    throw new Error("babel-standalone did not expose transform()");
  }
  return babel;
}

function compileFile(babel, jsxName) {
  const srcPath = path.join(COMPONENTS_DIR, jsxName);
  if (!fs.existsSync(srcPath)) {
    throw new Error("source not found: " + srcPath);
  }
  const source = fs.readFileSync(srcPath, "utf8");
  const result = babel.transform(source, BABEL_OPTIONS);
  if (!result || typeof result.code !== "string") {
    throw new Error("transform produced no code for " + jsxName);
  }
  const outName = jsxName.replace(/\.jsx$/, ".js");
  const outPath = path.join(COMPONENTS_DIR, outName);
  const banner = GENERATED_BANNER.replace("$SRC", jsxName);
  writeUtf8IfChanged(outPath, banner + result.code);
  return { outName: outName, bytes: Buffer.byteLength(result.code, "utf8") };
}

function buildStyleBundle() {
  const source = STYLE_SOURCES.map(function readStyle(name) {
    const filePath = path.join(STYLES_DIR, name);
    if (!fs.existsSync(filePath)) throw new Error("style source not found: " + filePath);
    return "/* source: " + name + " */\n" + normalizeLf(fs.readFileSync(filePath, "utf8"));
  }).join("\n");
  const result = lightningcss.transform({
    filename: STYLE_BUNDLE,
    code: Buffer.from(source, "utf8"),
    minify: true,
    sourceMap: false,
  });
  if (!result || !result.code || !result.code.length) {
    throw new Error("Lightning CSS produced an empty style bundle");
  }
  const banner = "/*! AUTO-GENERATED by build.js from src/styles/*.css — DO NOT EDIT. */\n";
  const output = banner + result.code.toString("utf8") + "\n";
  writeUtf8IfChanged(path.join(STYLES_DIR, STYLE_BUNDLE), output);
  const sourceBytes = Buffer.byteLength(source, "utf8");
  const outputBytes = Buffer.byteLength(output, "utf8");
  process.stdout.write(
    "[build] styles -> src/styles/" + STYLE_BUNDLE + "  (" + outputBytes +
    " bytes; " + Math.round((1 - outputBytes / sourceBytes) * 100) + "% smaller)\n"
  );
  return outputBytes;
}

// ── Product landings ────────────────────────────────────────────────────────
// Generate a static /projects/<slug>/index.html for each product that a visitor
// can't see live (they used to link straight to a GitHub card). Content +
// template come from src/projects/{landings-data,render}.js — the SAME render()
// the page loads client-side, so the baked HTML and the language switcher never
// drift. Real files → clean shareable URLs, own <title>/OG, indexable, instant.
const SITE_BASE = "https://samandarmansurkhodjaev2713.github.io/CV-Samandar/";

function scriptHash(source) {
  return "'sha256-" + crypto.createHash("sha256").update(normalizeLf(source), "utf8").digest("base64") + "'";
}

function contentSecurityPolicy(inlineScripts) {
  const hashes = (inlineScripts || []).map(scriptHash).join(" ");
  return [
    "default-src 'self'",
    "script-src 'self'" + (hashes ? " " + hashes : ""),
    "style-src 'self'",
    "style-src-elem 'self'",
    "style-src-attr 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "font-src 'self' data:",
    "connect-src 'self' https://api.github.com",
    "media-src 'self'",
    "worker-src 'self' blob:",
    "object-src 'none'",
    "frame-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
  ].join("; ");
}

function refreshMainCsp() {
  const indexPath = path.join(__dirname, "index.html");
  let source = normalizeLf(fs.readFileSync(indexPath, "utf8"));
  const inlineScripts = [];
  const inlinePattern = /<script\b(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi;
  let match;
  while ((match = inlinePattern.exec(source))) inlineScripts.push(match[1]);
  const meta = '<meta http-equiv="Content-Security-Policy" content="' +
    htmlAttr(contentSecurityPolicy(inlineScripts)) + '">';
  const existing = /<meta\s+http-equiv=["']Content-Security-Policy["'][^>]*>/i;
  if (existing.test(source)) {
    source = source.replace(existing, meta);
  } else {
    source = source.replace(
      /(<meta\s+name=["']viewport["'][^>]*>)/i,
      "$1\n  " + meta
    );
  }
  writeUtf8IfChanged(indexPath, source);
  process.stdout.write("[build] CSP -> index.html (" + inlineScripts.length + " hashed inline data block(s))\n");
  return inlineScripts.length;
}

function readLandingVersion() {
  try {
    const idx = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
    const m = idx.match(/\?v=(\d+)/);
    return m ? m[1] : "";
  } catch (e) { return ""; }
}

function htmlAttr(s) {
  return String(s == null ? "" : s)
    .replace(/&/g, "&amp;").replace(/"/g, "&quot;")
    .replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function renderLandingPage(p, R, version, lang, base) {
  const copy = (p.i18n && p.i18n[lang]) || (p.i18n && p.i18n.ru) || {};
  const v = version ? "?v=" + version : "";
  const caseTitle = lang === "en"
    ? "Product engineering case"
    : (lang === "uz" ? "Mahsulot ishlab chiqish keysi" : "Кейс продуктовой разработки");
  const title = p.name + " — " + caseTitle + " | Samandar";
  const desc = copy.signal || "";
  const route = "projects/" + p.slug + "/" + (lang === "ru" ? "" : lang + "/");
  const ogUrl = SITE_BASE + route;
  const localeCode = lang === "en" ? "en_US" : (lang === "uz" ? "uz_UZ" : "ru_RU");
  // Each case owns a photographic 3:1 social preview instead of sharing the
  // portfolio cover. This keeps Telegram/LinkedIn links visually distinct.
  const ogImg = SITE_BASE + "assets/proj/" + p.visual;
  const personId = SITE_BASE + "#person";
  const pageId = ogUrl + "#page";
  const workId = ogUrl + "#case";
  const structuredData = JSON.stringify({
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "CreativeWork",
        "@id": workId,
        name: p.name,
        description: desc,
        url: ogUrl,
        image: ogImg,
        inLanguage: lang,
        author: { "@id": personId },
        mainEntityOfPage: { "@id": pageId },
        keywords: (p.stack || []).join(", "),
      },
      {
        "@type": "Person",
        "@id": personId,
        name: "Samandar Mansurkhodjaev",
        url: SITE_BASE,
      },
      {
        "@type": "WebPage",
        "@id": pageId,
        url: ogUrl,
        name: title,
        description: desc,
        inLanguage: lang,
        mainEntity: { "@id": workId },
        isPartOf: { "@id": SITE_BASE + "#website" },
        breadcrumb: { "@id": ogUrl + "#breadcrumb" },
      },
      {
        "@type": "BreadcrumbList",
        "@id": ogUrl + "#breadcrumb",
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Samandar", item: SITE_BASE },
          { "@type": "ListItem", position: 2, name: p.name, item: ogUrl },
        ],
      },
    ],
  }).replace(/</g, "\\u003c");
  const csp = contentSecurityPolicy([structuredData]);
  const body = R.LP_render(p, lang, base);
  return [
    "<!doctype html>",
    '<html lang="' + lang + '" data-lp-slug="' + htmlAttr(p.slug) + '" data-lp-lang="' + lang + '" data-lp-base="' + htmlAttr(base) + '">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    '<meta http-equiv="Content-Security-Policy" content="' + htmlAttr(csp) + '">',
    "<title>" + htmlAttr(title) + "</title>",
    '<meta name="description" content="' + htmlAttr(desc) + '">',
    '<meta name="robots" content="index,follow">',
    '<link rel="canonical" href="' + htmlAttr(ogUrl) + '">',
    '<link rel="alternate" hreflang="ru" href="' + htmlAttr(SITE_BASE + "projects/" + p.slug + "/") + '">',
    '<link rel="alternate" hreflang="en" href="' + htmlAttr(SITE_BASE + "projects/" + p.slug + "/en/") + '">',
    '<link rel="alternate" hreflang="uz" href="' + htmlAttr(SITE_BASE + "projects/" + p.slug + "/uz/") + '">',
    '<link rel="alternate" hreflang="x-default" href="' + htmlAttr(SITE_BASE + "projects/" + p.slug + "/") + '">',
    '<meta property="og:type" content="website">',
    '<meta property="og:site_name" content="Samandar — Product Engineer · AI Automation · QA">',
    '<meta property="og:title" content="' + htmlAttr(title) + '">',
    '<meta property="og:description" content="' + htmlAttr(desc) + '">',
    '<meta property="og:url" content="' + htmlAttr(ogUrl) + '">',
    '<meta property="og:image" content="' + htmlAttr(ogImg) + '">',
    '<meta property="og:image:width" content="1536">',
    '<meta property="og:image:height" content="512">',
    '<meta property="og:image:type" content="image/webp">',
    '<meta property="og:image:alt" content="' + htmlAttr(p.name + " — editorial product study") + '">',
    '<meta property="og:locale" content="' + localeCode + '">',
    '<meta property="og:locale:alternate" content="' + (lang === "ru" ? "en_US" : "ru_RU") + '">',
    '<meta property="og:locale:alternate" content="' + (lang === "uz" ? "en_US" : "uz_UZ") + '">',
    '<meta name="twitter:card" content="summary_large_image">',
    '<meta name="twitter:title" content="' + htmlAttr(title) + '">',
    '<meta name="twitter:description" content="' + htmlAttr(desc) + '">',
    '<meta name="twitter:image" content="' + htmlAttr(ogImg) + '">',
    '<meta name="twitter:image:alt" content="' + htmlAttr(p.name + " — editorial product study") + '">',
    '<script type="application/ld+json">' + structuredData + '</script>',
    '<meta name="theme-color" content="#171713">',
    '<link rel="icon" href="' + base + 'favicon.svg">',
    '<link rel="stylesheet" href="' + base + 'src/styles/fonts.css' + v + '">',
    '<link rel="stylesheet" href="' + base + 'src/projects/landing.css' + v + '">',
    "</head>",
    "<body>",
    '<div id="lp-root">' + body + "</div>",
    '<script src="' + base + 'src/content/product-registry.js' + v + '"></script>',
    '<script src="' + base + 'src/projects/landings-data.js' + v + '"></script>',
    '<script src="' + base + 'src/projects/render.js' + v + '"></script>',
    '<script src="' + base + 'src/projects/landing.js' + v + '"></script>',
    "</body>",
    "</html>",
    "",
  ].join("\n");
}

function buildLandings() {
  const dataPath = path.join(__dirname, "src", "projects", "landings-data.js");
  const renderPath = path.join(__dirname, "src", "projects", "render.js");
  if (!fs.existsSync(dataPath) || !fs.existsSync(renderPath)) return 0;
  // Fresh load so a `node build.js` re-run picks up edits within one process.
  delete require.cache[require.resolve(dataPath)];
  delete require.cache[require.resolve(renderPath)];
  const LANDINGS = require(dataPath);
  const R = require(renderPath);
  const version = readLandingVersion();
  const slugs = Object.keys(LANDINGS);
  slugs.forEach(function (slug) {
    const p = LANDINGS[slug];
    const dir = path.join(__dirname, "projects", slug);
    fs.mkdirSync(dir, { recursive: true });
    writeUtf8IfChanged(path.join(dir, "index.html"), renderLandingPage(p, R, version, "ru", "../../"));
    ["en", "uz"].forEach(function buildLocale(lang) {
      const localeDir = path.join(dir, lang);
      fs.mkdirSync(localeDir, { recursive: true });
      writeUtf8IfChanged(path.join(localeDir, "index.html"), renderLandingPage(p, R, version, lang, "../../../"));
    });
    process.stdout.write("[build] landing -> projects/" + slug + "/ (ru/en/uz)\n");
  });
  return slugs.length * 3;
}

function buildSitemap() {
  const registryPath = path.join(__dirname, "src", "content", "product-registry.js");
  delete require.cache[require.resolve(registryPath)];
  const registry = require(registryPath);
  const urls = [SITE_BASE];
  registry
    .filter(function (product) { return product.presentation === "case"; })
    .sort(function (a, b) { return a.featuredRank - b.featuredRank; })
    .forEach(function addCaseLocales(product) {
      urls.push(SITE_BASE + product.casePage);
      urls.push(SITE_BASE + product.casePage + "en/");
      urls.push(SITE_BASE + product.casePage + "uz/");
    });
  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ].concat(urls.map(function (url) {
    return "  <url><loc>" + url.replace(/&/g, "&amp;").replace(/</g, "&lt;") + "</loc></url>";
  }), ["</urlset>", ""]).join("\n");
  writeUtf8IfChanged(path.join(__dirname, "sitemap.xml"), xml);
  process.stdout.write("[build] sitemap -> sitemap.xml (" + urls.length + " URLs)\n");
  return urls.length;
}

function main() {
  try {
    const contract = validateSite({ generated: false });
    process.stdout.write(
      "[build] contract OK — " + contract.products + " products, " +
      contract.cases + " case routes, " + contract.locales + " locales\n"
    );
  } catch (err) {
    process.stderr.write("[build] contract FAILED: " + err.message + "\n");
    process.exit(1);
    return;
  }

  let babel;
  try {
    babel = loadBabel();
  } catch (err) {
    process.stderr.write("[build] failed to load Babel: " + err.message + "\n");
    process.exit(1);
    return;
  }

  let totalBytes = 0;
  for (let i = 0; i < JSX_FILES.length; i++) {
    const jsxName = JSX_FILES[i];
    try {
      const info = compileFile(babel, jsxName);
      totalBytes += info.bytes;
      process.stdout.write("[build] " + jsxName + " -> " + info.outName + "  (" + info.bytes + " bytes)\n");
    } catch (err) {
      process.stderr.write("[build] FAILED on " + jsxName + ": " + err.message + "\n");
      process.exit(1);
      return;
    }
  }
  try {
    buildStyleBundle();
  } catch (err) {
    process.stderr.write("[build] styles FAILED: " + err.message + "\n");
    process.exit(1);
    return;
  }
  let landingCount = 0;
  let sitemapCount = 0;
  try {
    refreshMainCsp();
    landingCount = buildLandings();
    sitemapCount = buildSitemap();
    validateSite({ generated: true });
  } catch (err) {
    process.stderr.write("[build] landings FAILED: " + err.message + "\n");
    process.exit(1);
    return;
  }
  process.stdout.write(
    "[build] done — " + JSX_FILES.length + " files, " + totalBytes +
    " bytes total; " + landingCount + " landing(s); " + sitemapCount + " sitemap URL(s).\n"
  );
}

main();
