// content.jsx — i18n content config (RU/EN/UZ)
// Replace placeholder values to ship real CV. Keys are 1:1 across languages.

const CONTENT = {
  ru: {
    nav: {
      about: "О себе",
      projects: "Проекты",
      skills: "Стек",
      services: "Услуги",
      cv: "Опыт",
      contact: "Контакт",
    },
    hero: {
      eyebrow: "Executive AI Code Lab — v.2026",
      name: "Samandar",
      title_lines: ["Full-stack.", "AI Automation.", "Product Engineer."],
      tagline:
        "Проектирую и собираю production-системы: веб-приложения, AI-автоматизации, Telegram-боты и админ-панели для бизнеса.",
      cta_primary: "Обсудить проект",
      cta_secondary: "Смотреть работы",
      status: "доступен для проектов",
      boot_lines: [
        "init core.engine ... ok",
        "load /modules/full-stack ... ok",
        "load /modules/ai-automation ... ok",
        "compile portfolio.v26 ... ok",
        "deploy READY",
      ],
    },
    signal: {
      eyebrow: "10-second signal",
      title: "Что я собираю",
      cards: [
        { code: "01", k: "Full-stack", v: "Web-приложения, MVP, продуктовые системы" },
        { code: "02", k: "AI Automation", v: "Workflow, агенты, обработка данных" },
        { code: "03", k: "Telegram-боты", v: "Автоматизация задач и коммуникации" },
        { code: "04", k: "Dashboards", v: "Админ-панели, CRM, операционные дашборды" },
        { code: "05", k: "Landing & Web", v: "Premium-сайты и продуктовые лендинги" },
        { code: "06", k: "Product MVP", v: "От идеи до работающего прототипа" },
      ],
    },
    about: {
      eyebrow: "Profile",
      title: "Инженер, который доводит продукты до production",
      lead:
        "Я строю системы, а не сайты. Каждый проект — это связка фронта, бэка, AI-слоя и инфраструктуры, упакованная в продукт, которым реально пользуются.",
      paragraphs: [
        "Работаю на стыке инженерной дисциплины и продуктового мышления. Принимаю решения по архитектуре, выбираю стек под задачу, не под моду, и довожу до релиза без раздутого скоупа.",
        "Сильные стороны — full-stack TypeScript, AI-интеграции (LLM, агенты, RAG), автоматизация бизнес-процессов и админ-системы. Беру проекты, где нужно думать, а не просто верстать.",
      ],
      stats: [
        { v: "6+", k: "лет в коде" },
        { v: "30+", k: "релизов" },
        { v: "12", k: "AI-интеграций" },
        { v: "RU/EN/UZ", k: "языки работы" },
      ],
    },
    projects: {
      eyebrow: "Selected work",
      title: "Featured projects",
      items: [
        {
          tag: "TELEGRAM · AI",
          name: "Task Orchestrator Bot",
          problem: "Команды теряют задачи в чатах и забывают исполнителей.",
          solution: "Telegram-бот с очередью задач, AI-парсингом голоса и напоминаниями.",
          role: "Lead Developer",
          stack: ["Node.js", "Telegraf", "OpenAI", "Postgres"],
          outcome: "—40% потерянных задач за квартал",
          status: "PROD",
        },
        {
          tag: "DASHBOARD · IOT",
          name: "Biogas Operations Panel",
          problem: "Операторы смотрят сырые SCADA-данные без аналитики.",
          solution: "Real-time дашборд с метриками, инцидентами и AI-рекомендациями.",
          role: "Full-stack",
          stack: ["Next.js", "TimescaleDB", "MQTT", "Recharts"],
          outcome: "часовой отчёт сократился до 4 минут",
          status: "PROD",
        },
        {
          tag: "LANDING · INFRA",
          name: "Railway Infrastructure Site",
          problem: "Корпоративный сайт с 90-х, не объяснявший продукт.",
          solution: "Премиум-лендинг с интерактивной картой и расчётом маршрутов.",
          role: "Design + Dev",
          stack: ["Astro", "GSAP", "Mapbox", "TypeScript"],
          outcome: "+3.2× времени на сайте",
          status: "LIVE",
        },
        {
          tag: "BRAND · PROTO",
          name: "DRM Futuristic Landing",
          problem: "Нужен сайт, ощущаемый как продукт будущего.",
          solution: "Cinematic-прототип с 3D-объектом и многоязычной структурой.",
          role: "Concept + Build",
          stack: ["Three.js", "React", "GLSL"],
          outcome: "конверсия в заявку 7.4%",
          status: "PROTO",
        },
        {
          tag: "AI · VOICE",
          name: "Group Voice Task Bot",
          problem: "Голосовые в групповых чатах не превращаются в действия.",
          solution: "Бот, который слышит голосовое и создаёт задачу с исполнителем.",
          role: "Lead Developer",
          stack: ["Whisper", "GPT-4o", "Node.js"],
          outcome: "MVP за 11 дней",
          status: "BETA",
        },
        {
          tag: "AI · WORKFLOW",
          name: "Business Automation Engine",
          problem: "Менеджеры тратили 2 часа в день на ручную обработку заявок.",
          solution: "AI-конвейер: классификация, обогащение, маршрутизация в CRM.",
          role: "Architect",
          stack: ["n8n", "OpenAI", "Postgres", "Redis"],
          outcome: "+18 часов команды/неделя",
          status: "PROD",
        },
      ],
      cta: "Смотреть кейс",
    },
    skills: {
      eyebrow: "Stack radar",
      title: "Технический стек",
      lead: "Не зоопарк логотипов — сетка инструментов, которыми реально работаю.",
      groups: [
        {
          k: "Frontend",
          items: ["TypeScript", "React", "Next.js", "Astro", "GSAP", "Three.js", "Tailwind"],
        },
        { k: "Backend", items: ["Node.js", "Fastify", "tRPC", "Postgres", "Redis", "Prisma"] },
        { k: "AI / Automation", items: ["OpenAI", "Anthropic", "LangChain", "n8n", "RAG", "Vector DBs"] },
        { k: "DevOps", items: ["Docker", "GitHub Actions", "Cloudflare", "Railway", "Linux"] },
        { k: "Product", items: ["Figma", "Architecture", "Product strategy", "Tech spec"] },
        { k: "Telegram", items: ["Telegraf", "Bot API", "MTProto", "Web Apps"] },
      ],
    },
    services: {
      eyebrow: "Services",
      title: "Что можно заказать",
      items: [
        { k: "Web Apps", v: "Полноценные продукты, MVP, SaaS-приложения", io: "spec → prod app" },
        { k: "Landing & Sites", v: "Премиум-лендинги, корпоративные и продуктовые", io: "brief → site" },
        { k: "Telegram Bots", v: "Боты для команд, продаж, автоматизации", io: "task → bot" },
        { k: "AI Automation", v: "Workflow с LLM, агентами, обработкой данных", io: "process → engine" },
        { k: "Dashboards", v: "Админ-панели, CRM, операционные дашборды", io: "data → ops view" },
        { k: "MVP / Prototype", v: "От идеи до работающего прототипа за недели", io: "idea → demo" },
        { k: "Internal Tools", v: "CRM, кабинеты, инструменты для команды", io: "team → tool" },
        { k: "Tech Consulting", v: "Архитектура, аудит, стек, тех-стратегия", io: "question → plan" },
      ],
    },
    cv: {
      eyebrow: "Experience",
      title: "CV / Timeline",
      lead: "Коммит-граф карьеры. Каждая нода — закрытый этап.",
      timeline: [
        {
          y: "2024 — now",
          role: "Independent Engineer · AI / Full-stack",
          org: "Freelance & contract",
          tag: "main",
          points: [
            "AI-автоматизации и продуктовые системы для бизнеса",
            "Telegram-боты и операционные дашборды",
            "Архитектура и tech-консалтинг",
          ],
        },
        {
          y: "2022 — 2024",
          role: "Senior Full-stack Developer",
          org: "Product company (placeholder)",
          tag: "feature",
          points: [
            "Веб-приложения и админ-системы на TypeScript",
            "Внедрение AI-features в продукт",
            "Менторство джунов, code review",
          ],
        },
        {
          y: "2020 — 2022",
          role: "Full-stack Developer",
          org: "Agency (placeholder)",
          tag: "release",
          points: [
            "Корпоративные сайты и лендинги",
            "Интеграции с CRM и платежами",
            "Frontend на React и Next.js",
          ],
        },
        {
          y: "2018 — 2020",
          role: "Frontend Developer",
          org: "Studio (placeholder)",
          tag: "init",
          points: ["Старт в индустрии", "JS, React, продуктовая разработка"],
        },
      ],
      edu_title: "Образование и сертификаты",
      edu: [
        { y: "—", k: "BSc Computer Science (placeholder)" },
        { y: "—", k: "AI Engineering · self-directed" },
        { y: "—", k: "Сертификаты — заменить на реальные" },
      ],
    },
    process: {
      eyebrow: "Method",
      title: "Как я работаю",
      lead: "Один пайплайн от первого звонка до saturday-night-prod.",
      steps: [
        { k: "Discovery", v: "Бизнес-цель, метрики, ограничения" },
        { k: "Architecture", v: "Стек, контракт, риски" },
        { k: "Prototype", v: "Кликабельный прототип ключевых сценариев" },
        { k: "UI / UX", v: "Дизайн под продукт, не под Behance" },
        { k: "Development", v: "Чистый стек, типизация, тесты на критическом пути" },
        { k: "AI Automation", v: "LLM-слой, ретривал, эвалы" },
        { k: "Testing", v: "QA, нагрузка, edge-кейсы" },
        { k: "Deploy", v: "CI/CD, мониторинг, алерты" },
        { k: "Support", v: "Стабилизация и развитие после релиза" },
      ],
    },
    trust: {
      eyebrow: "Signal",
      title: "Trust panels",
      lead: "Заглушки. Замените на реальные отзывы клиентов и команд.",
      items: [
        {
          q: "Client testimonial placeholder — оцените инженерное качество, скорость и владение продуктом.",
          who: "Client A",
          role: "Product owner · placeholder",
        },
        {
          q: "Team testimonial placeholder — отметьте архитектуру, чистоту кода и менторство.",
          who: "Team Lead B",
          role: "Engineering · placeholder",
        },
        {
          q: "Founder testimonial placeholder — расскажите про MVP, AI-автоматизацию, бизнес-эффект.",
          who: "Founder C",
          role: "Startup · placeholder",
        },
      ],
    },
    contact: {
      eyebrow: "Deploy request",
      title: "Запустим проект",
      lead: "Опишите задачу — отвечу с архитектурным черновиком и оценкой за 24 часа.",
      form: {
        name: "Имя",
        email: "Email или Telegram",
        scope: "Тип проекта",
        msg: "Кратко о задаче",
        submit: "Отправить запрос",
        sent: "Запрос принят. На связи в течение 24 часов.",
      },
      scope_opts: ["Web App / MVP", "AI Automation", "Telegram Bot", "Dashboard / CRM", "Landing", "Consulting"],
      links: [
        { k: "Telegram", v: "t.me/your-username" },
        { k: "GitHub", v: "github.com/your-username" },
        { k: "Email", v: "hello@example.com" },
      ],
    },
    footer: {
      copy: "© 2026 — Executive AI Code Lab",
      built: "собрано на TypeScript, Three.js, React",
    },
  },

  en: {
    nav: { about: "About", projects: "Work", skills: "Stack", services: "Services", cv: "CV", contact: "Contact" },
    hero: {
      eyebrow: "Executive AI Code Lab — v.2026",
      name: "Samandar",
      title_lines: ["Full-stack.", "AI Automation.", "Product Engineer."],
      tagline:
        "I design and ship production systems — web apps, AI automations, Telegram bots, and admin panels for serious businesses.",
      cta_primary: "Discuss a project",
      cta_secondary: "View work",
      status: "available for projects",
      boot_lines: [
        "init core.engine ... ok",
        "load /modules/full-stack ... ok",
        "load /modules/ai-automation ... ok",
        "compile portfolio.v26 ... ok",
        "deploy READY",
      ],
    },
    signal: {
      eyebrow: "10-second signal",
      title: "What I build",
      cards: [
        { code: "01", k: "Full-stack", v: "Web apps, MVPs, product systems" },
        { code: "02", k: "AI Automation", v: "Workflows, agents, data pipelines" },
        { code: "03", k: "Telegram bots", v: "Task and comms automation" },
        { code: "04", k: "Dashboards", v: "Admin panels, CRM, ops dashboards" },
        { code: "05", k: "Landing & Web", v: "Premium and product landings" },
        { code: "06", k: "Product MVP", v: "Idea to working prototype" },
      ],
    },
    about: {
      eyebrow: "Profile",
      title: "An engineer who actually ships",
      lead:
        "I build systems, not sites. Every project is frontend, backend, AI layer and infrastructure, packaged into a product people use.",
      paragraphs: [
        "I work at the intersection of engineering discipline and product thinking. I make architecture decisions, pick the stack the task needs, not the one that's trending, and ship without scope creep.",
        "Strong on full-stack TypeScript, AI integrations (LLMs, agents, RAG), business process automation and admin systems. I take projects that require thinking — not just markup.",
      ],
      stats: [
        { v: "6+", k: "years coding" },
        { v: "30+", k: "releases" },
        { v: "12", k: "AI integrations" },
        { v: "RU/EN/UZ", k: "working languages" },
      ],
    },
    projects: {
      eyebrow: "Selected work",
      title: "Featured projects",
      items: [
        {
          tag: "TELEGRAM · AI",
          name: "Task Orchestrator Bot",
          problem: "Teams lose tasks in chat threads and forget assignees.",
          solution: "Telegram bot with task queue, AI voice parsing, and reminders.",
          role: "Lead Developer",
          stack: ["Node.js", "Telegraf", "OpenAI", "Postgres"],
          outcome: "−40% lost tasks per quarter",
          status: "PROD",
        },
        {
          tag: "DASHBOARD · IOT",
          name: "Biogas Operations Panel",
          problem: "Operators staring at raw SCADA data with no analytics.",
          solution: "Real-time dashboard with metrics, incidents, AI recommendations.",
          role: "Full-stack",
          stack: ["Next.js", "TimescaleDB", "MQTT", "Recharts"],
          outcome: "Hourly report 60min → 4min",
          status: "PROD",
        },
        {
          tag: "LANDING · INFRA",
          name: "Railway Infrastructure Site",
          problem: "Corporate site from the 90s, didn't explain the product.",
          solution: "Premium landing with interactive map and route calculator.",
          role: "Design + Dev",
          stack: ["Astro", "GSAP", "Mapbox", "TypeScript"],
          outcome: "+3.2× time on site",
          status: "LIVE",
        },
        {
          tag: "BRAND · PROTO",
          name: "DRM Futuristic Landing",
          problem: "Need a site that feels like a product from the future.",
          solution: "Cinematic prototype with 3D core and multilingual structure.",
          role: "Concept + Build",
          stack: ["Three.js", "React", "GLSL"],
          outcome: "7.4% lead conversion",
          status: "PROTO",
        },
        {
          tag: "AI · VOICE",
          name: "Group Voice Task Bot",
          problem: "Voice notes in group chats never become real tasks.",
          solution: "Bot that hears voice notes and creates tasks with assignees.",
          role: "Lead Developer",
          stack: ["Whisper", "GPT-4o", "Node.js"],
          outcome: "MVP in 11 days",
          status: "BETA",
        },
        {
          tag: "AI · WORKFLOW",
          name: "Business Automation Engine",
          problem: "Managers spent 2h/day manually processing leads.",
          solution: "AI pipeline: classify, enrich, route into CRM.",
          role: "Architect",
          stack: ["n8n", "OpenAI", "Postgres", "Redis"],
          outcome: "+18 team-hours/week",
          status: "PROD",
        },
      ],
      cta: "Open case",
    },
    skills: {
      eyebrow: "Stack radar",
      title: "Technical stack",
      lead: "Not a logo zoo — the toolkit I actually ship with.",
      groups: [
        { k: "Frontend", items: ["TypeScript", "React", "Next.js", "Astro", "GSAP", "Three.js", "Tailwind"] },
        { k: "Backend", items: ["Node.js", "Fastify", "tRPC", "Postgres", "Redis", "Prisma"] },
        { k: "AI / Automation", items: ["OpenAI", "Anthropic", "LangChain", "n8n", "RAG", "Vector DBs"] },
        { k: "DevOps", items: ["Docker", "GitHub Actions", "Cloudflare", "Railway", "Linux"] },
        { k: "Product", items: ["Figma", "Architecture", "Product strategy", "Tech spec"] },
        { k: "Telegram", items: ["Telegraf", "Bot API", "MTProto", "Web Apps"] },
      ],
    },
    services: {
      eyebrow: "Services",
      title: "What you can hire me for",
      items: [
        { k: "Web Apps", v: "Full products, MVPs, SaaS applications", io: "spec → prod app" },
        { k: "Landing & Sites", v: "Premium landings, corporate and product", io: "brief → site" },
        { k: "Telegram Bots", v: "Bots for teams, sales, automation", io: "task → bot" },
        { k: "AI Automation", v: "Workflows with LLMs, agents, data pipelines", io: "process → engine" },
        { k: "Dashboards", v: "Admin panels, CRM, ops dashboards", io: "data → ops view" },
        { k: "MVP / Prototype", v: "Idea to working prototype in weeks", io: "idea → demo" },
        { k: "Internal Tools", v: "CRM, portals, team-only software", io: "team → tool" },
        { k: "Tech Consulting", v: "Architecture, audit, stack, strategy", io: "question → plan" },
      ],
    },
    cv: {
      eyebrow: "Experience",
      title: "CV / Timeline",
      lead: "Career commit graph. Each node — a closed chapter.",
      timeline: [
        {
          y: "2024 — now",
          role: "Independent Engineer · AI / Full-stack",
          org: "Freelance & contract",
          tag: "main",
          points: [
            "AI automations and product systems for businesses",
            "Telegram bots and operational dashboards",
            "Architecture and tech consulting",
          ],
        },
        {
          y: "2022 — 2024",
          role: "Senior Full-stack Developer",
          org: "Product company (placeholder)",
          tag: "feature",
          points: ["TypeScript web apps and admin systems", "AI features in production", "Mentoring, code review"],
        },
        {
          y: "2020 — 2022",
          role: "Full-stack Developer",
          org: "Agency (placeholder)",
          tag: "release",
          points: ["Corporate sites and landings", "CRM and payment integrations", "React / Next.js frontends"],
        },
        {
          y: "2018 — 2020",
          role: "Frontend Developer",
          org: "Studio (placeholder)",
          tag: "init",
          points: ["Industry start", "JS, React, product development"],
        },
      ],
      edu_title: "Education & certificates",
      edu: [
        { y: "—", k: "BSc Computer Science (placeholder)" },
        { y: "—", k: "AI Engineering · self-directed" },
        { y: "—", k: "Certificates — replace with real ones" },
      ],
    },
    process: {
      eyebrow: "Method",
      title: "How I work",
      lead: "One pipeline from first call to saturday-night-prod.",
      steps: [
        { k: "Discovery", v: "Business goal, metrics, constraints" },
        { k: "Architecture", v: "Stack, contracts, risks" },
        { k: "Prototype", v: "Clickable proto of key flows" },
        { k: "UI / UX", v: "Design for the product, not Behance" },
        { k: "Development", v: "Clean stack, types, tests on the critical path" },
        { k: "AI Automation", v: "LLM layer, retrieval, evals" },
        { k: "Testing", v: "QA, load, edge cases" },
        { k: "Deploy", v: "CI/CD, monitoring, alerts" },
        { k: "Support", v: "Post-release stabilization & growth" },
      ],
    },
    trust: {
      eyebrow: "Signal",
      title: "Trust panels",
      lead: "Placeholders. Replace with real client and team testimonials.",
      items: [
        { q: "Client testimonial placeholder — speak to engineering quality, speed, product ownership.", who: "Client A", role: "Product owner · placeholder" },
        { q: "Team testimonial placeholder — speak to architecture, code quality, mentorship.", who: "Team Lead B", role: "Engineering · placeholder" },
        { q: "Founder testimonial placeholder — speak to MVP, AI automation, business impact.", who: "Founder C", role: "Startup · placeholder" },
      ],
    },
    contact: {
      eyebrow: "Deploy request",
      title: "Let's ship something",
      lead: "Describe the task — I'll come back with an architecture sketch and estimate within 24 hours.",
      form: {
        name: "Name",
        email: "Email or Telegram",
        scope: "Project type",
        msg: "Briefly about the task",
        submit: "Send request",
        sent: "Request received. I'll reply within 24 hours.",
      },
      scope_opts: ["Web App / MVP", "AI Automation", "Telegram Bot", "Dashboard / CRM", "Landing", "Consulting"],
      links: [
        { k: "Telegram", v: "t.me/your-username" },
        { k: "GitHub", v: "github.com/your-username" },
        { k: "Email", v: "hello@example.com" },
      ],
    },
    footer: { copy: "© 2026 — Executive AI Code Lab", built: "built on TypeScript, Three.js, React" },
  },

  uz: {
    nav: { about: "Men haqimda", projects: "Loyihalar", skills: "Stek", services: "Xizmatlar", cv: "Tajriba", contact: "Aloqa" },
    hero: {
      eyebrow: "Executive AI Code Lab — v.2026",
      name: "Samandar",
      title_lines: ["Full-stack.", "AI Avtomatlashtirish.", "Product muhandis."],
      tagline:
        "Production darajadagi tizimlarni loyihalayman va ishga tushiraman — veb-ilovalar, AI-avtomatlashtirish, Telegram-botlar va biznes uchun admin paneller.",
      cta_primary: "Loyihani muhokama qilish",
      cta_secondary: "Ishlarni ko'rish",
      status: "loyihalar uchun ochiqman",
      boot_lines: [
        "init core.engine ... ok",
        "load /modules/full-stack ... ok",
        "load /modules/ai-automation ... ok",
        "compile portfolio.v26 ... ok",
        "deploy READY",
      ],
    },
    signal: {
      eyebrow: "10 soniyalik signal",
      title: "Men nima quraman",
      cards: [
        { code: "01", k: "Full-stack", v: "Veb-ilovalar, MVP, mahsulot tizimlari" },
        { code: "02", k: "AI Avtomatlashtirish", v: "Workflow, agentlar, ma'lumotlar" },
        { code: "03", k: "Telegram-botlar", v: "Vazifa va aloqa avtomatlashtirish" },
        { code: "04", k: "Dashboardlar", v: "Admin panellar, CRM, operatsion ko'rinishlar" },
        { code: "05", k: "Landing va Veb", v: "Premium va mahsulot saytlari" },
        { code: "06", k: "Mahsulot MVP", v: "Goyadan ishlovchi prototipgacha" },
      ],
    },
    about: {
      eyebrow: "Profil",
      title: "Mahsulotni production'ga olib boradigan muhandis",
      lead:
        "Men saytlar emas, tizimlar quraman. Har bir loyiha — frontend, backend, AI qatlami va infratuzilma, mahsulotga jamlangan holatda.",
      paragraphs: [
        "Muhandislik intizomi va mahsulot tafakkuri kesishmasida ishlayman. Arxitektura qarorlarini qabul qilaman, vazifaga mos stekni tanlayman — modaga emas — va qamrovni shishirmasdan relizgacha olib chiqaman.",
        "Kuchli tomonlarim — full-stack TypeScript, AI integratsiyalari (LLM, agentlar, RAG), biznes-jarayonlarni avtomatlashtirish va admin tizimlar. Faqat verstka emas, fikrlash kerak bo'lgan loyihalarni olaman.",
      ],
      stats: [
        { v: "6+", k: "yil kod" },
        { v: "30+", k: "reliz" },
        { v: "12", k: "AI integratsiya" },
        { v: "RU/EN/UZ", k: "ish tillari" },
      ],
    },
    projects: {
      eyebrow: "Tanlangan ishlar",
      title: "Asosiy loyihalar",
      items: [
        {
          tag: "TELEGRAM · AI",
          name: "Task Orchestrator Bot",
          problem: "Jamoalar chatda vazifalarni yo'qotadi va ijrochilarni unutadi.",
          solution: "Vazifalar navbati, AI ovoz tahlili va eslatmali Telegram-bot.",
          role: "Lead Developer",
          stack: ["Node.js", "Telegraf", "OpenAI", "Postgres"],
          outcome: "Choragiga −40% yo'qolgan vazifa",
          status: "PROD",
        },
        {
          tag: "DASHBOARD · IOT",
          name: "Biogas Operations Panel",
          problem: "Operatorlar xom SCADA-ma'lumotlarga analitikasiz qarayapti.",
          solution: "Metrik, hodisa va AI tavsiyalari bilan real-time dashboard.",
          role: "Full-stack",
          stack: ["Next.js", "TimescaleDB", "MQTT", "Recharts"],
          outcome: "Soatlik hisobot: 60 → 4 daqiqa",
          status: "PROD",
        },
        {
          tag: "LANDING · INFRA",
          name: "Railway Infrastructure Site",
          problem: "90-yillardagi korporativ sayt mahsulotni ko'rsata olmayotgan edi.",
          solution: "Interaktiv xarita va marshrut hisoblagichli premium-landing.",
          role: "Design + Dev",
          stack: ["Astro", "GSAP", "Mapbox", "TypeScript"],
          outcome: "Saytdagi vaqt +3.2×",
          status: "LIVE",
        },
        {
          tag: "BRAND · PROTO",
          name: "DRM Futuristic Landing",
          problem: "Kelajak mahsulotidek his qilinadigan sayt kerak edi.",
          solution: "3D-yadro va ko'p tilli tuzilmali kinematik prototip.",
          role: "Concept + Build",
          stack: ["Three.js", "React", "GLSL"],
          outcome: "7.4% lead konversiyasi",
          status: "PROTO",
        },
        {
          tag: "AI · OVOZ",
          name: "Group Voice Task Bot",
          problem: "Guruh chatlardagi ovozli xabarlar vazifaga aylanmaydi.",
          solution: "Ovozni eshitib, ijrochi bilan vazifa yaratadigan bot.",
          role: "Lead Developer",
          stack: ["Whisper", "GPT-4o", "Node.js"],
          outcome: "MVP — 11 kunda",
          status: "BETA",
        },
        {
          tag: "AI · WORKFLOW",
          name: "Business Automation Engine",
          problem: "Menejerlar kuniga 2 soat qo'lda arizalarni qayta ishlardi.",
          solution: "AI quvuri: tasniflash, boyitish, CRM'ga yo'naltirish.",
          role: "Architect",
          stack: ["n8n", "OpenAI", "Postgres", "Redis"],
          outcome: "Haftasiga +18 jamoa-soati",
          status: "PROD",
        },
      ],
      cta: "Keysni ochish",
    },
    skills: {
      eyebrow: "Stek radari",
      title: "Texnik stek",
      lead: "Logotiplar to'plami emas — haqiqatan ishlatadigan asboblar.",
      groups: [
        { k: "Frontend", items: ["TypeScript", "React", "Next.js", "Astro", "GSAP", "Three.js", "Tailwind"] },
        { k: "Backend", items: ["Node.js", "Fastify", "tRPC", "Postgres", "Redis", "Prisma"] },
        { k: "AI / Automation", items: ["OpenAI", "Anthropic", "LangChain", "n8n", "RAG", "Vector DBs"] },
        { k: "DevOps", items: ["Docker", "GitHub Actions", "Cloudflare", "Railway", "Linux"] },
        { k: "Product", items: ["Figma", "Architecture", "Product strategy", "Tech spec"] },
        { k: "Telegram", items: ["Telegraf", "Bot API", "MTProto", "Web Apps"] },
      ],
    },
    services: {
      eyebrow: "Xizmatlar",
      title: "Nima buyurtma qilish mumkin",
      items: [
        { k: "Web Apps", v: "To'liq mahsulotlar, MVP, SaaS-ilovalar", io: "spec → prod app" },
        { k: "Landing va saytlar", v: "Premium landing, korporativ va mahsulot", io: "brief → site" },
        { k: "Telegram-botlar", v: "Jamoa, sotuv, avtomatlashtirish uchun", io: "task → bot" },
        { k: "AI Avtomatlashtirish", v: "LLM, agentlar, ma'lumot quvurlari", io: "process → engine" },
        { k: "Dashboardlar", v: "Admin paneller, CRM, ops dashboardlar", io: "data → ops view" },
        { k: "MVP / Prototip", v: "Goyadan ishlovchi prototipgacha", io: "idea → demo" },
        { k: "Ichki asboblar", v: "CRM, kabinetlar, jamoa uchun", io: "team → tool" },
        { k: "Texnik konsalting", v: "Arxitektura, audit, stek, strategiya", io: "question → plan" },
      ],
    },
    cv: {
      eyebrow: "Tajriba",
      title: "CV / Vaqt jadvali",
      lead: "Karyera commit-grafi. Har bir tugun — yopilgan bosqich.",
      timeline: [
        {
          y: "2024 — hozir",
          role: "Mustaqil muhandis · AI / Full-stack",
          org: "Freelance va kontrakt",
          tag: "main",
          points: [
            "Biznes uchun AI-avtomatlashtirish va mahsulot tizimlari",
            "Telegram-botlar va operatsion dashboardlar",
            "Arxitektura va tex-konsalting",
          ],
        },
        {
          y: "2022 — 2024",
          role: "Senior Full-stack Developer",
          org: "Product company (placeholder)",
          tag: "feature",
          points: ["TypeScript veb-ilovalar va admin tizimlar", "Mahsulotda AI-funksiyalar", "Mentorlik, code review"],
        },
        {
          y: "2020 — 2022",
          role: "Full-stack Developer",
          org: "Agency (placeholder)",
          tag: "release",
          points: ["Korporativ sayt va landinglar", "CRM va to'lov integratsiyalari", "React / Next.js frontend"],
        },
        {
          y: "2018 — 2020",
          role: "Frontend Developer",
          org: "Studio (placeholder)",
          tag: "init",
          points: ["Sohaga kirish", "JS, React, mahsulot ishlab chiqish"],
        },
      ],
      edu_title: "Ta'lim va sertifikatlar",
      edu: [
        { y: "—", k: "BSc Computer Science (placeholder)" },
        { y: "—", k: "AI Engineering · mustaqil ta'lim" },
        { y: "—", k: "Sertifikatlar — haqiqiylariga almashtiring" },
      ],
    },
    process: {
      eyebrow: "Metod",
      title: "Qanday ishlayman",
      lead: "Birinchi qo'ng'iroqdan saturday-night-prod gacha bitta quvur.",
      steps: [
        { k: "Discovery", v: "Biznes maqsad, metrikalar, cheklovlar" },
        { k: "Arxitektura", v: "Stek, kontraktlar, risklar" },
        { k: "Prototip", v: "Asosiy stsenariylar uchun klikabel proto" },
        { k: "UI / UX", v: "Mahsulot uchun dizayn, Behance uchun emas" },
        { k: "Ishlab chiqish", v: "Toza stek, tiplar, kritik yo'lda testlar" },
        { k: "AI Avtomatlashtirish", v: "LLM qatlami, retrieval, evals" },
        { k: "Test", v: "QA, yuklama, edge-keyslar" },
        { k: "Deploy", v: "CI/CD, monitoring, alertlar" },
        { k: "Qo'llab-quvvatlash", v: "Reliz keyingi barqarorlik va o'sish" },
      ],
    },
    trust: {
      eyebrow: "Signal",
      title: "Trust panellar",
      lead: "Placeholderlar. Haqiqiy mijoz va jamoa fikrlariga almashtiring.",
      items: [
        { q: "Client testimonial placeholder — muhandislik sifati, tezligi, mahsulotga egalik haqida.", who: "Client A", role: "Product owner · placeholder" },
        { q: "Team testimonial placeholder — arxitektura, kod sifati, mentorlik haqida.", who: "Team Lead B", role: "Engineering · placeholder" },
        { q: "Founder testimonial placeholder — MVP, AI-avtomatlashtirish, biznes-ta'sir haqida.", who: "Founder C", role: "Startup · placeholder" },
      ],
    },
    contact: {
      eyebrow: "Deploy so'rovi",
      title: "Loyihani ishga tushiramiz",
      lead: "Vazifani tasvirlang — 24 soat ichida arxitektura eskizi va baho bilan qaytaman.",
      form: {
        name: "Ism",
        email: "Email yoki Telegram",
        scope: "Loyiha turi",
        msg: "Vazifa haqida qisqacha",
        submit: "So'rovni yuborish",
        sent: "So'rov qabul qilindi. 24 soat ichida bog'lanaman.",
      },
      scope_opts: ["Web App / MVP", "AI Avtomatlashtirish", "Telegram Bot", "Dashboard / CRM", "Landing", "Konsalting"],
      links: [
        { k: "Telegram", v: "t.me/your-username" },
        { k: "GitHub", v: "github.com/your-username" },
        { k: "Email", v: "hello@example.com" },
      ],
    },
    footer: { copy: "© 2026 — Executive AI Code Lab", built: "TypeScript, Three.js, React asosida" },
  },
};

window.CONTENT = CONTENT;
