// content.jsx — i18n content config (RU/EN/UZ)
// Replace placeholder values to ship real CV. Keys are 1:1 across languages.

const CONTENT = {
  ru: {
    nav: {
      about: "О себе",
      projects: "Проекты",
      skills: "Стек",
      services: "Услуги",
      cv: "Опыт",
      contact: "Контакт",
    },
    hero: {
      eyebrow: "Executive AI Code Lab — v.2026",
      name: "Samandar",
      title_lines: ["Full-stack.", "AI Automation.", "Product Engineer."],
      tagline:
        "Превращаю задачу бизнеса в работающий продукт. Архитектура, код, AI-слой — без посредников.",
      cta_primary: "Обсудить проект",
      cta_secondary: "Смотреть работы",
      status: "доступен для проектов",
      boot_lines: [
        "init core.engine ... ok",
        "load /modules/full-stack ... ok",
        "load /modules/ai-automation ... ok",
        "compile portfolio.v26 ... ok",
        "deploy READY",
      ],
    },
    signal: {
      eyebrow: "10-second signal",
      title: "Что я собираю",
      cards: [
        { code: "01", k: "Full-stack", v: "Web-приложения, MVP, продуктовые системы" },
        { code: "02", k: "AI Automation", v: "Workflow, агенты, обработка данных" },
        { code: "03", k: "Telegram-боты", v: "Автоматизация задач и коммуникации" },
        { code: "04", k: "Dashboards", v: "Админ-панели, CRM, операционные дашборды" },
        { code: "05", k: "Landing & Web", v: "Premium-сайты и продуктовые лендинги" },
        { code: "06", k: "Product MVP", v: "От идеи до работающего прототипа" },
      ],
    },
    about: {
      eyebrow: "Profile",
      title: "Беру задачу — отдаю работающий продукт",
      lead:
        "Один разработчик отвечает за весь стек: фронт, бэк, AI, инфраструктура. Без передач между подрядчиками — без потерь в переводе.",
      paragraphs: [
        "Выбираю стек под задачу, а не под трендах. Архитектура — простая, чтобы её можно было поддерживать через год.",
        "AI — не как демо, а как часть продукта: интеграция LLM, агенты, RAG, оценки качества.",
      ],
      stats: [
        { v: "6+", k: "лет в коде" },
        { v: "30+", k: "релизов" },
        { v: "12", k: "AI-интеграций" },
        { v: "RU/EN/UZ", k: "языки работы" },
      ],
      status_label: "Доступен · удалённо · контракт и фуллтайм",
      currently_label: "Сейчас",
      currently: [
        "собираю AI-orchestrator для ops-команды",
        "пишу пайплайн оценок для LLM-агентов",
        "копаю Anthropic computer-use",
        "читаю Designing Data-Intensive Apps",
      ],
      recent_label: "Недавние коммиты",
      recent: [
        { when: "2 ч", tag: "feat",     msg: "ai-orchestrator v2.1 — выкатил в прод" },
        { when: "1 д", tag: "refactor", msg: "переписал ergonomics телеграм-бота" },
        { when: "3 д", tag: "docs",     msg: "runbook по деплою, версия 3" },
      ],
      contrib_label: "Активность · 28 недель",
      gh_stats: "★ 142 stars · 38 repos · 1.2k contributions · 5y on platform",
    },
    projects: {
      eyebrow: "Selected work",
      title: "Featured projects",
      items: [
        {
          tag: "TELEGRAM · AI",
          name: "Task Orchestrator Bot",
          problem: "Команды теряют задачи в чатах и забывают исполнителей.",
          solution: "Telegram-бот с очередью задач, AI-парсингом голоса и напоминаниями.",
          role: "Lead Developer",
          stack: ["Node.js", "Telegraf", "OpenAI", "Postgres"],
          outcome: "—40% потерянных задач за квартал",
          status: "PROD",
        },
        {
          tag: "DASHBOARD · IOT",
          name: "Biogas Operations Panel",
          problem: "Операторы смотрят сырые SCADA-данные без аналитики.",
          solution: "Real-time дашборд с метриками, инцидентами и AI-рекомендациями.",
          role: "Full-stack",
          stack: ["Next.js", "TimescaleDB", "MQTT", "Recharts"],
          outcome: "часовой отчёт сократился до 4 минут",
          status: "PROD",
        },
        {
          tag: "LANDING · INFRA",
          name: "Railway Infrastructure Site",
          problem: "Корпоративный сайт с 90-х, не объяснявший продукт.",
          solution: "Премиум-лендинг с интерактивной картой и расчётом маршрутов.",
          role: "Design + Dev",
          stack: ["Astro", "GSAP", "Mapbox", "TypeScript"],
          outcome: "+3.2× времени на сайте",
          status: "LIVE",
        },
        {
          tag: "BRAND · PROTO",
          name: "DRM Futuristic Landing",
          problem: "Нужен сайт, ощущаемый как продукт будущего.",
          solution: "Cinematic-прототип с 3D-объектом и многоязычной структурой.",
          role: "Concept + Build",
          stack: ["Three.js", "React", "GLSL"],
          outcome: "конверсия в заявку 7.4%",
          status: "PROTO",
        },
        {
          tag: "AI · VOICE",
          name: "Group Voice Task Bot",
          problem: "Голосовые в групповых чатах не превращаются в действия.",
          solution: "Бот, который слышит голосовое и создаёт задачу с исполнителем.",
          role: "Lead Developer",
          stack: ["Whisper", "GPT-4o", "Node.js"],
          outcome: "MVP за 11 дней",
          status: "BETA",
        },
        {
          tag: "AI · WORKFLOW",
          name: "Business Automation Engine",
          problem: "Менеджеры тратили 2 часа в день на ручную обработку заявок.",
          solution: "AI-конвейер: классификация, обогащение, маршрутизация в CRM.",
          role: "Architect",
          stack: ["n8n", "OpenAI", "Postgres", "Redis"],
          outcome: "+18 часов команды/неделя",
          status: "PROD",
        },
      ],
      cta: "Смотреть кейс",
    },
    skills: {
      eyebrow: "Stack radar",
      title: "Технический стек",
      lead: "Не зоопарк логотипов — сетка инструментов, которыми реально работаю.",
      groups: [
        {
          k: "Frontend",
          items: ["TypeScript", "React", "Next.js", "Astro", "GSAP", "Three.js", "Tailwind"],
        },
        { k: "Backend", items: ["Node.js", "Fastify", "tRPC", "Postgres", "Redis", "Prisma"] },
        { k: "AI / Automation", items: ["OpenAI", "Anthropic", "LangChain", "n8n", "RAG", "Vector DBs"] },
        { k: "DevOps", items: ["Docker", "GitHub Actions", "Cloudflare", "Railway", "Linux"] },
        { k: "Product", items: ["Figma", "Architecture", "Product strategy", "Tech spec"] },
        { k: "Telegram", items: ["Telegraf", "Bot API", "MTProto", "Web Apps"] },
      ],
    },
    services: {
      eyebrow: "Services",
      title: "Что можно заказать",
      items: [
        { k: "Web Apps", v: "Полноценные продукты, MVP, SaaS-приложения", io: "spec → prod app" },
        { k: "Landing & Sites", v: "Премиум-лендинги, корпоративные и продуктовые", io: "brief → site" },
        { k: "Telegram Bots", v: "Боты для команд, продаж, автоматизации", io: "task → bot" },
        { k: "AI Automation", v: "Workflow с LLM, агентами, обработкой данных", io: "process → engine" },
        { k: "Dashboards", v: "Админ-панели, CRM, операционные дашборды", io: "data → ops view" },
        { k: "MVP / Prototype", v: "От идеи до работающего прототипа за недели", io: "idea → demo" },
        { k: "Internal Tools", v: "CRM, кабинеты, инструменты для команды", io: "team → tool" },
        { k: "Tech Consulting", v: "Архитектура, аудит, стек, тех-стратегия", io: "question → plan" },
      ],
    },
    cv: {
      eyebrow: "Experience",
      title: "CV / Опыт",
      lead: "Сжатый список того, что я сделал — без раздутых описаний.",
      timeline: [
        {
          y: "2024 — сейчас",
          role: "Independent Engineer · AI / Full-stack",
          org: "Freelance & contract",
          tag: "main",
          points: [
            "Запустил 6+ production-систем для бизнеса: AI-orchestrator, ops-дашборды, Telegram-боты.",
            "Один отвечаю за весь стек — от первого звонка до saturday-night-prod.",
            "Среднее время от ТЗ до MVP — 11 дней.",
          ],
          stack: ["TypeScript", "Next.js", "OpenAI", "Anthropic", "n8n", "Postgres"],
        },
        {
          y: "2022 — 2024",
          role: "Senior Full-stack Developer",
          org: "Product SaaS",
          tag: "feature",
          points: [
            "Внедрил AI-фичи в продукт: автозаполнение, классификация, GPT-summary — без галлюцинаций и с eval-метриками.",
            "Переписал админ-панель: сократил время операции с 60 до 4 минут.",
            "Менторство 3 джунов, code review практик, ADR-процесс.",
          ],
          stack: ["TypeScript", "React", "tRPC", "Postgres", "Redis"],
        },
        {
          y: "2020 — 2022",
          role: "Full-stack Developer",
          org: "Digital agency",
          tag: "release",
          points: [
            "Запустил 12+ корпоративных сайтов и продуктовых лендингов.",
            "Интеграции с CRM, платежами, ERP — без посредников между фронтом и бэком.",
            "Дизайн-системы на основе компонентного подхода.",
          ],
          stack: ["React", "Next.js", "Node.js", "Strapi"],
        },
        {
          y: "2018 — 2020",
          role: "Frontend Developer",
          org: "Web studio",
          tag: "init",
          points: [
            "Старт в индустрии: первые коммерческие React-проекты.",
            "Освоил продуктовую разработку — от Figma до прода.",
          ],
          stack: ["JavaScript", "React", "SCSS"],
        },
      ],
      edu_title: "Образование и сертификаты",
      edu: [
        { y: "2020", k: "BSc Computer Science · Tashkent University" },
        { y: "2023", k: "AI Engineering — самостоятельное обучение" },
        { y: "2024", k: "Anthropic Build with Claude · участие" },
      ],
    },
    process: {
      eyebrow: "Method",
      title: "Как я работаю",
      lead: "Один пайплайн от первого звонка до saturday-night-prod.",
      steps: [
        { k: "Discovery", v: "Бизнес-цель, метрики, ограничения" },
        { k: "Architecture", v: "Стек, контракт, риски" },
        { k: "Prototype", v: "Кликабельный прототип ключевых сценариев" },
        { k: "UI / UX", v: "Дизайн под продукт, не под Behance" },
        { k: "Development", v: "Чистый стек, типизация, тесты на критическом пути" },
        { k: "AI Automation", v: "LLM-слой, ретривал, эвалы" },
        { k: "Testing", v: "QA, нагрузка, edge-кейсы" },
        { k: "Deploy", v: "CI/CD, мониторинг, алерты" },
        { k: "Support", v: "Стабилизация и развитие после релиза" },
      ],
    },
    trust: {
      eyebrow: "Trust",
      title: "Отзывы команд",
      lead: "Что говорят те, с кем я уже работал.",
      items: [
        {
          q: "Принёс архитектурный черновик к первой встрече. Через месяц у нас работала первая версия — без скоупа, который раздулся бы у любого подрядчика.",
          who: "Product Lead",
          role: "Логистическая компания · 2025",
        },
        {
          q: "AI-интеграция работает в проде уже 8 месяцев. Без галлюцинаций, с метриками, с graceful-fallback. Это не демо — это инструмент.",
          who: "CTO",
          role: "SaaS-стартап · 2024",
        },
        {
          q: "Telegram-бот заменил два рабочих часа в день у каждого менеджера. Поставили за две недели, окупился за месяц.",
          who: "Founder",
          role: "B2B-сервис · 2024",
        },
      ],
    },
    contact: {
      eyebrow: "Deploy request",
      title: "Запустим проект",
      lead: "Опишите задачу — отвечу с архитектурным черновиком и оценкой за 24 часа.",
      form: {
        name: "Имя",
        email: "Email или Telegram",
        scope: "Что вам нужно",
        budget: "Бюджет",
        timeline: "Сроки",
        msg: "Что важно знать",
        msg_placeholder: "Цель, контекст, ограничения. Можно как угодно кратко.",
        submit: "Отправить запрос",
        sent: "Запрос принят. На связи в течение 24 часов.",
      },
      scope_opts: ["Web App / MVP", "AI Automation", "Telegram Bot", "Dashboard / CRM", "Landing", "Consulting"],
      timeline_opts: ["ASAP", "1–2 недели", "1–2 месяца", "гибко"],
      links: [
        { k: "Telegram", v: "t.me/your-username" },
        { k: "GitHub", v: "github.com/your-username" },
        { k: "Email", v: "hello@example.com" },
      ],
    },
    footer: {
      copy: "© 2026 — Executive AI Code Lab",
      built: "собрано на TypeScript, Three.js, React",
    },
  },

  en: {
    nav: { about: "About", projects: "Work", skills: "Stack", services: "Services", cv: "CV", contact: "Contact" },
    hero: {
      eyebrow: "Executive AI Code Lab — v.2026",
      name: "Samandar",
      title_lines: ["Full-stack.", "AI Automation.", "Product Engineer."],
      tagline:
        "I turn a business problem into a working product. Architecture, code, AI layer — one person, no handoffs.",
      cta_primary: "Discuss a project",
      cta_secondary: "View work",
      status: "available for projects",
      boot_lines: [
        "init core.engine ... ok",
        "load /modules/full-stack ... ok",
        "load /modules/ai-automation ... ok",
        "compile portfolio.v26 ... ok",
        "deploy READY",
      ],
    },
    signal: {
      eyebrow: "10-second signal",
      title: "What I build",
      cards: [
        { code: "01", k: "Full-stack", v: "Web apps, MVPs, product systems" },
        { code: "02", k: "AI Automation", v: "Workflows, agents, data pipelines" },
        { code: "03", k: "Telegram bots", v: "Task and comms automation" },
        { code: "04", k: "Dashboards", v: "Admin panels, CRM, ops dashboards" },
        { code: "05", k: "Landing & Web", v: "Premium and product landings" },
        { code: "06", k: "Product MVP", v: "Idea to working prototype" },
      ],
    },
    about: {
      eyebrow: "Profile",
      title: "I take the brief. I ship the product.",
      lead:
        "One engineer owns the whole stack: frontend, backend, AI, infra. No vendor handoffs — nothing lost in translation.",
      paragraphs: [
        "I pick the stack the task needs, not the one that's trending. Architecture stays simple so it survives the next year.",
        "AI isn't a demo here — it ships in production. LLM integrations, agents, RAG, eval pipelines.",
      ],
      stats: [
        { v: "6+", k: "years coding" },
        { v: "30+", k: "releases" },
        { v: "12", k: "AI integrations" },
        { v: "RU/EN/UZ", k: "working languages" },
      ],
      status_label: "Available · remote · contract & full-time",
      currently_label: "Currently",
      currently: [
        "shipping an AI orchestrator for an ops team",
        "writing an eval pipeline for LLM agents",
        "digging into Anthropic computer-use",
        "reading Designing Data-Intensive Apps",
      ],
      recent_label: "Recent commits",
      recent: [
        { when: "2h", tag: "feat",     msg: "ai-orchestrator v2.1 — shipped to prod" },
        { when: "1d", tag: "refactor", msg: "rewrote telegram bot ergonomics" },
        { when: "3d", tag: "docs",     msg: "deployment runbook v3" },
      ],
      contrib_label: "contributions · 28 weeks",
      gh_stats: "★ 142 stars · 38 repos · 1.2k contributions · 5y on platform",
    },
    projects: {
      eyebrow: "Selected work",
      title: "Featured projects",
      items: [
        {
          tag: "TELEGRAM · AI",
          name: "Task Orchestrator Bot",
          problem: "Teams lose tasks in chat threads and forget assignees.",
          solution: "Telegram bot with task queue, AI voice parsing, and reminders.",
          role: "Lead Developer",
          stack: ["Node.js", "Telegraf", "OpenAI", "Postgres"],
          outcome: "−40% lost tasks per quarter",
          status: "PROD",
        },
        {
          tag: "DASHBOARD · IOT",
          name: "Biogas Operations Panel",
          problem: "Operators staring at raw SCADA data with no analytics.",
          solution: "Real-time dashboard with metrics, incidents, AI recommendations.",
          role: "Full-stack",
          stack: ["Next.js", "TimescaleDB", "MQTT", "Recharts"],
          outcome: "Hourly report 60min → 4min",
          status: "PROD",
        },
        {
          tag: "LANDING · INFRA",
          name: "Railway Infrastructure Site",
          problem: "Corporate site from the 90s, didn't explain the product.",
          solution: "Premium landing with interactive map and route calculator.",
          role: "Design + Dev",
          stack: ["Astro", "GSAP", "Mapbox", "TypeScript"],
          outcome: "+3.2× time on site",
          status: "LIVE",
        },
        {
          tag: "BRAND · PROTO",
          name: "DRM Futuristic Landing",
          problem: "Need a site that feels like a product from the future.",
          solution: "Cinematic prototype with 3D core and multilingual structure.",
          role: "Concept + Build",
          stack: ["Three.js", "React", "GLSL"],
          outcome: "7.4% lead conversion",
          status: "PROTO",
        },
        {
          tag: "AI · VOICE",
          name: "Group Voice Task Bot",
          problem: "Voice notes in group chats never become real tasks.",
          solution: "Bot that hears voice notes and creates tasks with assignees.",
          role: "Lead Developer",
          stack: ["Whisper", "GPT-4o", "Node.js"],
          outcome: "MVP in 11 days",
          status: "BETA",
        },
        {
          tag: "AI · WORKFLOW",
          name: "Business Automation Engine",
          problem: "Managers spent 2h/day manually processing leads.",
          solution: "AI pipeline: classify, enrich, route into CRM.",
          role: "Architect",
          stack: ["n8n", "OpenAI", "Postgres", "Redis"],
          outcome: "+18 team-hours/week",
          status: "PROD",
        },
      ],
      cta: "Open case",
    },
    skills: {
      eyebrow: "Stack radar",
      title: "Technical stack",
      lead: "Not a logo zoo — the toolkit I actually ship with.",
      groups: [
        { k: "Frontend", items: ["TypeScript", "React", "Next.js", "Astro", "GSAP", "Three.js", "Tailwind"] },
        { k: "Backend", items: ["Node.js", "Fastify", "tRPC", "Postgres", "Redis", "Prisma"] },
        { k: "AI / Automation", items: ["OpenAI", "Anthropic", "LangChain", "n8n", "RAG", "Vector DBs"] },
        { k: "DevOps", items: ["Docker", "GitHub Actions", "Cloudflare", "Railway", "Linux"] },
        { k: "Product", items: ["Figma", "Architecture", "Product strategy", "Tech spec"] },
        { k: "Telegram", items: ["Telegraf", "Bot API", "MTProto", "Web Apps"] },
      ],
    },
    services: {
      eyebrow: "Services",
      title: "What you can hire me for",
      items: [
        { k: "Web Apps", v: "Full products, MVPs, SaaS applications", io: "spec → prod app" },
        { k: "Landing & Sites", v: "Premium landings, corporate and product", io: "brief → site" },
        { k: "Telegram Bots", v: "Bots for teams, sales, automation", io: "task → bot" },
        { k: "AI Automation", v: "Workflows with LLMs, agents, data pipelines", io: "process → engine" },
        { k: "Dashboards", v: "Admin panels, CRM, ops dashboards", io: "data → ops view" },
        { k: "MVP / Prototype", v: "Idea to working prototype in weeks", io: "idea → demo" },
        { k: "Internal Tools", v: "CRM, portals, team-only software", io: "team → tool" },
        { k: "Tech Consulting", v: "Architecture, audit, stack, strategy", io: "question → plan" },
      ],
    },
    cv: {
      eyebrow: "Experience",
      title: "CV / Experience",
      lead: "A short list of what I've shipped — no inflated job descriptions.",
      timeline: [
        {
          y: "2024 — now",
          role: "Independent Engineer · AI / Full-stack",
          org: "Freelance & contract",
          tag: "main",
          points: [
            "Shipped 6+ production systems for businesses: AI orchestrators, ops dashboards, Telegram bots.",
            "Sole owner of the whole stack — from first call to Saturday-night-prod.",
            "Average brief-to-MVP time: 11 days.",
          ],
          stack: ["TypeScript", "Next.js", "OpenAI", "Anthropic", "n8n", "Postgres"],
        },
        {
          y: "2022 — 2024",
          role: "Senior Full-stack Developer",
          org: "Product SaaS",
          tag: "feature",
          points: [
            "Integrated AI features into the product: autofill, classification, GPT summaries — no hallucinations, with eval metrics.",
            "Rewrote the admin panel: cut a key operation from 60 to 4 minutes.",
            "Mentored 3 juniors, ran code reviews, introduced an ADR process.",
          ],
          stack: ["TypeScript", "React", "tRPC", "Postgres", "Redis"],
        },
        {
          y: "2020 — 2022",
          role: "Full-stack Developer",
          org: "Digital agency",
          tag: "release",
          points: [
            "Launched 12+ corporate sites and product landings.",
            "CRM, payment, and ERP integrations — no middlemen between front and back.",
            "Built component-driven design systems for the team.",
          ],
          stack: ["React", "Next.js", "Node.js", "Strapi"],
        },
        {
          y: "2018 — 2020",
          role: "Frontend Developer",
          org: "Web studio",
          tag: "init",
          points: [
            "Started in the industry: first commercial React projects.",
            "Learned product development end-to-end — Figma to prod.",
          ],
          stack: ["JavaScript", "React", "SCSS"],
        },
      ],
      edu_title: "Education & certificates",
      edu: [
        { y: "2020", k: "BSc Computer Science · Tashkent University" },
        { y: "2023", k: "AI Engineering — self-directed" },
        { y: "2024", k: "Anthropic Build with Claude · participant" },
      ],
    },
    process: {
      eyebrow: "Method",
      title: "How I work",
      lead: "One pipeline from first call to saturday-night-prod.",
      steps: [
        { k: "Discovery", v: "Business goal, metrics, constraints" },
        { k: "Architecture", v: "Stack, contracts, risks" },
        { k: "Prototype", v: "Clickable proto of key flows" },
        { k: "UI / UX", v: "Design for the product, not Behance" },
        { k: "Development", v: "Clean stack, types, tests on the critical path" },
        { k: "AI Automation", v: "LLM layer, retrieval, evals" },
        { k: "Testing", v: "QA, load, edge cases" },
        { k: "Deploy", v: "CI/CD, monitoring, alerts" },
        { k: "Support", v: "Post-release stabilization & growth" },
      ],
    },
    trust: {
      eyebrow: "Trust",
      title: "What teams say",
      lead: "From people I've worked with.",
      items: [
        {
          q: "Brought an architecture draft to our first call. A month later we had a working version — no scope creep, which any other vendor would have given us.",
          who: "Product Lead",
          role: "Logistics company · 2025",
        },
        {
          q: "The AI integration has been in production for 8 months. No hallucinations, with metrics, with graceful fallback. It's a tool, not a demo.",
          who: "CTO",
          role: "SaaS startup · 2024",
        },
        {
          q: "The Telegram bot replaced two hours of work per day for each manager. Delivered in two weeks, paid for itself in a month.",
          who: "Founder",
          role: "B2B service · 2024",
        },
      ],
    },
    contact: {
      eyebrow: "Deploy request",
      title: "Let's ship something",
      lead: "Describe the task — I'll come back with an architecture sketch and estimate within 24 hours.",
      form: {
        name: "Name",
        email: "Email or Telegram",
        scope: "What you need",
        budget: "Budget",
        timeline: "Timeline",
        msg: "What I should know",
        msg_placeholder: "Goal, context, constraints. As short as you like.",
        submit: "Send request",
        sent: "Request received. I'll reply within 24 hours.",
      },
      scope_opts: ["Web App / MVP", "AI Automation", "Telegram Bot", "Dashboard / CRM", "Landing", "Consulting"],
      timeline_opts: ["ASAP", "1–2 weeks", "1–2 months", "flexible"],
      links: [
        { k: "Telegram", v: "t.me/your-username" },
        { k: "GitHub", v: "github.com/your-username" },
        { k: "Email", v: "hello@example.com" },
      ],
    },
    footer: { copy: "© 2026 — Executive AI Code Lab", built: "built on TypeScript, Three.js, React" },
  },

  uz: {
    nav: { about: "Men haqimda", projects: "Loyihalar", skills: "Stek", services: "Xizmatlar", cv: "Tajriba", contact: "Aloqa" },
    hero: {
      eyebrow: "Executive AI Code Lab — v.2026",
      name: "Samandar",
      title_lines: ["Full-stack.", "AI Avtomatlashtirish.", "Product muhandis."],
      tagline:
        "Biznes vazifasini ishlovchi mahsulotga aylantiraman. Arxitektura, kod, AI-qatlam — bir kishi, vositachisiz.",
      cta_primary: "Loyihani muhokama qilish",
      cta_secondary: "Ishlarni ko'rish",
      status: "loyihalar uchun ochiqman",
      boot_lines: [
        "init core.engine ... ok",
        "load /modules/full-stack ... ok",
        "load /modules/ai-automation ... ok",
        "compile portfolio.v26 ... ok",
        "deploy READY",
      ],
    },
    signal: {
      eyebrow: "10 soniyalik signal",
      title: "Men nima quraman",
      cards: [
        { code: "01", k: "Full-stack", v: "Veb-ilovalar, MVP, mahsulot tizimlari" },
        { code: "02", k: "AI Avtomatlashtirish", v: "Workflow, agentlar, ma'lumotlar" },
        { code: "03", k: "Telegram-botlar", v: "Vazifa va aloqa avtomatlashtirish" },
        { code: "04", k: "Dashboardlar", v: "Admin panellar, CRM, operatsion ko'rinishlar" },
        { code: "05", k: "Landing va Veb", v: "Premium va mahsulot saytlari" },
        { code: "06", k: "Mahsulot MVP", v: "Goyadan ishlovchi prototipgacha" },
      ],
    },
    about: {
      eyebrow: "Profil",
      title: "Vazifani olaman — ishlovchi mahsulot beraman",
      lead:
        "Bitta muhandis butun stekka javob beradi: frontend, backend, AI, infratuzilma. Pudratchilar orasida uzatish yo'q — tarjimada hech narsa yo'qolmaydi.",
      paragraphs: [
        "Vazifaga mos stekni tanlayman, modaga emas. Arxitektura sodda — bir yildan keyin ham qo'llab-quvvatlanadi.",
        "AI — demo emas, mahsulotning bir qismi: LLM integratsiyalari, agentlar, RAG, sifat baholash.",
      ],
      stats: [
        { v: "6+", k: "yil kod" },
        { v: "30+", k: "reliz" },
        { v: "12", k: "AI integratsiya" },
        { v: "RU/EN/UZ", k: "ish tillari" },
      ],
      status_label: "Bo'sh · masofadan · shartnoma yoki fulltayim",
      currently_label: "Hozir",
      currently: [
        "ops jamoasi uchun AI-orchestrator quryapman",
        "LLM-agentlar uchun eval pipeline yozyapman",
        "Anthropic computer-use'ni kovlayapman",
        "Designing Data-Intensive Apps o'qiyapman",
      ],
      recent_label: "Oxirgi kommitlar",
      recent: [
        { when: "2 s", tag: "feat",     msg: "ai-orchestrator v2.1 — prodga yetkazdi" },
        { when: "1 k", tag: "refactor", msg: "telegram bot ergonomikasi qayta yozildi" },
        { when: "3 k", tag: "docs",     msg: "deploy runbook v3" },
      ],
      contrib_label: "faollik · 28 hafta",
      gh_stats: "★ 142 stars · 38 repos · 1.2k contributions · 5y on platform",
    },
    projects: {
      eyebrow: "Tanlangan ishlar",
      title: "Asosiy loyihalar",
      items: [
        {
          tag: "TELEGRAM · AI",
          name: "Task Orchestrator Bot",
          problem: "Jamoalar chatda vazifalarni yo'qotadi va ijrochilarni unutadi.",
          solution: "Vazifalar navbati, AI ovoz tahlili va eslatmali Telegram-bot.",
          role: "Lead Developer",
          stack: ["Node.js", "Telegraf", "OpenAI", "Postgres"],
          outcome: "Choragiga −40% yo'qolgan vazifa",
          status: "PROD",
        },
        {
          tag: "DASHBOARD · IOT",
          name: "Biogas Operations Panel",
          problem: "Operatorlar xom SCADA-ma'lumotlarga analitikasiz qarayapti.",
          solution: "Metrik, hodisa va AI tavsiyalari bilan real-time dashboard.",
          role: "Full-stack",
          stack: ["Next.js", "TimescaleDB", "MQTT", "Recharts"],
          outcome: "Soatlik hisobot: 60 → 4 daqiqa",
          status: "PROD",
        },
        {
          tag: "LANDING · INFRA",
          name: "Railway Infrastructure Site",
          problem: "90-yillardagi korporativ sayt mahsulotni ko'rsata olmayotgan edi.",
          solution: "Interaktiv xarita va marshrut hisoblagichli premium-landing.",
          role: "Design + Dev",
          stack: ["Astro", "GSAP", "Mapbox", "TypeScript"],
          outcome: "Saytdagi vaqt +3.2×",
          status: "LIVE",
        },
        {
          tag: "BRAND · PROTO",
          name: "DRM Futuristic Landing",
          problem: "Kelajak mahsulotidek his qilinadigan sayt kerak edi.",
          solution: "3D-yadro va ko'p tilli tuzilmali kinematik prototip.",
          role: "Concept + Build",
          stack: ["Three.js", "React", "GLSL"],
          outcome: "7.4% lead konversiyasi",
          status: "PROTO",
        },
        {
          tag: "AI · OVOZ",
          name: "Group Voice Task Bot",
          problem: "Guruh chatlardagi ovozli xabarlar vazifaga aylanmaydi.",
          solution: "Ovozni eshitib, ijrochi bilan vazifa yaratadigan bot.",
          role: "Lead Developer",
          stack: ["Whisper", "GPT-4o", "Node.js"],
          outcome: "MVP — 11 kunda",
          status: "BETA",
        },
        {
          tag: "AI · WORKFLOW",
          name: "Business Automation Engine",
          problem: "Menejerlar kuniga 2 soat qo'lda arizalarni qayta ishlardi.",
          solution: "AI quvuri: tasniflash, boyitish, CRM'ga yo'naltirish.",
          role: "Architect",
          stack: ["n8n", "OpenAI", "Postgres", "Redis"],
          outcome: "Haftasiga +18 jamoa-soati",
          status: "PROD",
        },
      ],
      cta: "Keysni ochish",
    },
    skills: {
      eyebrow: "Stek radari",
      title: "Texnik stek",
      lead: "Logotiplar to'plami emas — haqiqatan ishlatadigan asboblar.",
      groups: [
        { k: "Frontend", items: ["TypeScript", "React", "Next.js", "Astro", "GSAP", "Three.js", "Tailwind"] },
        { k: "Backend", items: ["Node.js", "Fastify", "tRPC", "Postgres", "Redis", "Prisma"] },
        { k: "AI / Automation", items: ["OpenAI", "Anthropic", "LangChain", "n8n", "RAG", "Vector DBs"] },
        { k: "DevOps", items: ["Docker", "GitHub Actions", "Cloudflare", "Railway", "Linux"] },
        { k: "Product", items: ["Figma", "Architecture", "Product strategy", "Tech spec"] },
        { k: "Telegram", items: ["Telegraf", "Bot API", "MTProto", "Web Apps"] },
      ],
    },
    services: {
      eyebrow: "Xizmatlar",
      title: "Nima buyurtma qilish mumkin",
      items: [
        { k: "Web Apps", v: "To'liq mahsulotlar, MVP, SaaS-ilovalar", io: "spec → prod app" },
        { k: "Landing va saytlar", v: "Premium landing, korporativ va mahsulot", io: "brief → site" },
        { k: "Telegram-botlar", v: "Jamoa, sotuv, avtomatlashtirish uchun", io: "task → bot" },
        { k: "AI Avtomatlashtirish", v: "LLM, agentlar, ma'lumot quvurlari", io: "process → engine" },
        { k: "Dashboardlar", v: "Admin paneller, CRM, ops dashboardlar", io: "data → ops view" },
        { k: "MVP / Prototip", v: "Goyadan ishlovchi prototipgacha", io: "idea → demo" },
        { k: "Ichki asboblar", v: "CRM, kabinetlar, jamoa uchun", io: "team → tool" },
        { k: "Texnik konsalting", v: "Arxitektura, audit, stek, strategiya", io: "question → plan" },
      ],
    },
    cv: {
      eyebrow: "Tajriba",
      title: "CV / Tajriba",
      lead: "Qilingan ishlarning qisqa ro'yxati — bo'rttirilgan tavsiflarsiz.",
      timeline: [
        {
          y: "2024 — hozir",
          role: "Mustaqil muhandis · AI / Full-stack",
          org: "Freelance va kontrakt",
          tag: "main",
          points: [
            "Biznes uchun 6+ production tizimi ishga tushirdi: AI-orkestratorlar, ops-dashboardlar, Telegram-botlar.",
            "Butun stekka yolg'iz javob beraman — birinchi qo'ng'iroqdan saturday-night-prod'gacha.",
            "ToZ'dan MVP'gacha o'rtacha vaqt — 11 kun.",
          ],
          stack: ["TypeScript", "Next.js", "OpenAI", "Anthropic", "n8n", "Postgres"],
        },
        {
          y: "2022 — 2024",
          role: "Senior Full-stack Developer",
          org: "Product SaaS",
          tag: "feature",
          points: [
            "Mahsulotga AI-fichalarni integratsiya qildi: avtoto'ldirish, klassifikatsiya, GPT-xulosa — gallyutsinatsiyalarsiz, eval-metrikalar bilan.",
            "Admin-panelni qayta yozdi: asosiy operatsiyani 60 daqiqadan 4 daqiqaga qisqartirdi.",
            "3 junior mentorligi, code review amaliyoti, ADR jarayonini joriy qildi.",
          ],
          stack: ["TypeScript", "React", "tRPC", "Postgres", "Redis"],
        },
        {
          y: "2020 — 2022",
          role: "Full-stack Developer",
          org: "Digital agentlik",
          tag: "release",
          points: [
            "12+ korporativ sayt va mahsulot landinglarini ishga tushirdi.",
            "CRM, to'lovlar, ERP integratsiyalari — front va back o'rtasida vositachisiz.",
            "Komponent-asosli dizayn tizimlari.",
          ],
          stack: ["React", "Next.js", "Node.js", "Strapi"],
        },
        {
          y: "2018 — 2020",
          role: "Frontend Developer",
          org: "Web studiya",
          tag: "init",
          points: [
            "Sohaga kirish: birinchi tijorat React-loyihalari.",
            "Mahsulot ishlab chiqishni o'zlashtirdi — Figma'dan prod'gacha.",
          ],
          stack: ["JavaScript", "React", "SCSS"],
        },
      ],
      edu_title: "Ta'lim va sertifikatlar",
      edu: [
        { y: "2020", k: "BSc Computer Science · Toshkent universiteti" },
        { y: "2023", k: "AI Engineering — mustaqil ta'lim" },
        { y: "2024", k: "Anthropic Build with Claude · ishtirokchi" },
      ],
    },
    process: {
      eyebrow: "Metod",
      title: "Qanday ishlayman",
      lead: "Birinchi qo'ng'iroqdan saturday-night-prod gacha bitta quvur.",
      steps: [
        { k: "Discovery", v: "Biznes maqsad, metrikalar, cheklovlar" },
        { k: "Arxitektura", v: "Stek, kontraktlar, risklar" },
        { k: "Prototip", v: "Asosiy stsenariylar uchun klikabel proto" },
        { k: "UI / UX", v: "Mahsulot uchun dizayn, Behance uchun emas" },
        { k: "Ishlab chiqish", v: "Toza stek, tiplar, kritik yo'lda testlar" },
        { k: "AI Avtomatlashtirish", v: "LLM qatlami, retrieval, evals" },
        { k: "Test", v: "QA, yuklama, edge-keyslar" },
        { k: "Deploy", v: "CI/CD, monitoring, alertlar" },
        { k: "Qo'llab-quvvatlash", v: "Reliz keyingi barqarorlik va o'sish" },
      ],
    },
    trust: {
      eyebrow: "Trust",
      title: "Jamoalar nima deydi",
      lead: "Birga ishlagan odamlardan.",
      items: [
        {
          q: "Birinchi uchrashuvga arxitektura qoralamasini olib keldi. Bir oydan keyin birinchi versiya ishlay boshladi — boshqa pudratchi shishirib yuborgan qamrovsiz.",
          who: "Product Lead",
          role: "Logistika kompaniyasi · 2025",
        },
        {
          q: "AI-integratsiya 8 oydan beri prodda ishlaydi. Gallyutsinatsiyalarsiz, metrikalar bilan, graceful-fallback bilan. Bu — asbob, demo emas.",
          who: "CTO",
          role: "SaaS-startap · 2024",
        },
        {
          q: "Telegram-bot har bir menejerga kuniga ikki ish soatini qaytarib berdi. Ikki haftada qildi, bir oyda o'zini qoplab oldi.",
          who: "Founder",
          role: "B2B xizmat · 2024",
        },
      ],
    },
    contact: {
      eyebrow: "Deploy so'rovi",
      title: "Loyihani ishga tushiramiz",
      lead: "Vazifani tasvirlang — 24 soat ichida arxitektura eskizi va baho bilan qaytaman.",
      form: {
        name: "Ism",
        email: "Email yoki Telegram",
        scope: "Sizga nima kerak",
        budget: "Byudjet",
        timeline: "Muddat",
        msg: "Nima muhim",
        msg_placeholder: "Maqsad, kontekst, cheklovlar. Iloji boricha qisqa.",
        submit: "So'rovni yuborish",
        sent: "So'rov qabul qilindi. 24 soat ichida bog'lanaman.",
      },
      scope_opts: ["Web App / MVP", "AI Avtomatlashtirish", "Telegram Bot", "Dashboard / CRM", "Landing", "Konsalting"],
      timeline_opts: ["ASAP", "1–2 hafta", "1–2 oy", "moslashuvchan"],
      links: [
        { k: "Telegram", v: "t.me/your-username" },
        { k: "GitHub", v: "github.com/your-username" },
        { k: "Email", v: "hello@example.com" },
      ],
    },
    footer: { copy: "© 2026 — Executive AI Code Lab", built: "TypeScript, Three.js, React asosida" },
  },
};

window.CONTENT = CONTENT;
