// content.jsx — i18n content config (RU/EN/UZ)
// Replace placeholder values to ship real CV. Keys are 1:1 across languages.

const CONTENT = {
  ru: {
    nav: {
      about: "О себе",
      projects: "Проекты",
      skills: "Стек",
      services: "Услуги",
      cv: "Опыт",
      faq: "Вопросы",
      contact: "Контакт",
    },
    hero: {
      eyebrow: "Executive AI Code Lab — v.2026",
      name: "Samandar",
      title_lines: ["Full-stack.", "AI Automation.", "Product Engineer."],
      tagline:
        "Превращаю задачу бизнеса в работающий продукт. Архитектура, код, AI-слой — без посредников.",
      cta_primary: "Обсудить проект",
      cta_secondary: "Смотреть работы",
      status: "доступен для проектов",
      boot_lines: [
        "init core.engine ... ok",
        "load /modules/full-stack ... ok",
        "load /modules/ai-automation ... ok",
        "compile portfolio.v26 ... ok",
        "deploy READY",
      ],
    },
    signal: {
      eyebrow: "10-second signal",
      title: "Что я собираю",
      cards: [
        { code: "01", k: "Full-stack", v: "Web-приложения, MVP, продуктовые системы" },
        { code: "02", k: "AI Automation", v: "Workflow, агенты, обработка данных" },
        { code: "03", k: "Telegram-боты", v: "Автоматизация задач и коммуникации" },
        { code: "04", k: "Dashboards", v: "Админ-панели, CRM, операционные дашборды" },
        { code: "05", k: "Landing & Web", v: "Premium-сайты и продуктовые лендинги" },
        { code: "06", k: "Product MVP", v: "От идеи до работающего прототипа" },
      ],
    },
    about: {
      eyebrow: "Profile",
      title: "Беру задачу — отдаю работающий продукт",
      lead:
        "Один разработчик отвечает за весь стек: фронт, бэк, AI, инфраструктура. Без передач между подрядчиками — без потерь в переводе.",
      paragraphs: [
        "Выбираю стек под задачу, а не под трендах. Архитектура — простая, чтобы её можно было поддерживать через год.",
        "AI — не как демо, а как часть продукта: интеграция LLM, агенты, RAG, оценки качества.",
      ],
      stats: [
        { v: "11 мес.", k: "в разработке" },
        { v: "10+", k: "проектов" },
        { v: "3 курс", k: "Software Engineering" },
        { v: "RU / UZ", k: "языки работы" },
      ],
      status_label: "Доступен · удалённо · контракт и фуллтайм",
      currently_label: "Сейчас",
      currently: [
        "собираю AI-orchestrator для ops-команды",
        "пишу пайплайн оценок для LLM-агентов",
        "копаю Anthropic computer-use",
        "читаю Designing Data-Intensive Apps",
      ],
      recent_label: "Недавние коммиты",
      recent: [
        { when: "1 д", tag: "feat", msg: "cv-samandar — секции, анимации, деплой" },
        { when: "2 д", tag: "feat", msg: "task-manager — Rust-бот, очередь задач, CI" },
        { when: "2 д", tag: "feat", msg: "sentinel-edge — realtime-дашборд, firmware" },
      ],
      contrib_label: "Активность · 12 недель",
      gh_stats: "10+ проектов · публичный код и NDA-кейсы · Ташкент",
    },
    projects: {
      eyebrow: "Selected work",
      title: "Избранные проекты",
      items: [
        {
          tag: "AI · LEGAL",
          name: "Klawis — Legal AI Assistant",
          problem: "Юридические чат-боты отвечают гладко, но без источников и проверяемости.",
          solution: "Live AI-продукт с RAG, юридическим роутингом и цитированием источников.",
          role: "Founder + Lead Developer",
          stack: ["FastAPI", "Next.js", "Supabase", "RAG"],
          outcome: "живой продукт на klawis.uz",
          status: "LIVE",
          url: "https://klawis.uz",
        },
        {
          tag: "CONSUMER · FOUNDER",
          name: "CoupleOS / Softly",
          problem: "Отношениям не хватает мягкой структуры — ритуалов и безопасного пространства.",
          solution: "Mobile-first продукт для пар: приватные флоу, привычки, воспоминания.",
          role: "Founder + Full-stack",
          stack: ["Next.js", "Supabase", "PWA"],
          outcome: "живой продукт на SoftlyLove.uz",
          status: "LIVE",
          url: "https://softlylove.uz",
        },
        {
          tag: "ENTERPRISE · ON-PREM",
          name: "TTYL Platform",
          problem: "Команде нужны collaboration-инструменты без передачи данных во внешний SaaS.",
          solution: "Self-hosted workspace: проекты, чаты, файлы, поиск, audit, realtime, RBAC.",
          role: "Architect + Lead Developer",
          stack: ["NestJS", "Next.js", "PostgreSQL", "Redis", "MinIO"],
          outcome: "on-prem развёртывание для закрытого контура",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "TELEGRAM · RUST",
          name: "Task-manager / Task Manage Bot",
          problem: "Задачи из чатов и голосовых сообщений теряются без структуры.",
          solution: "Rust-бот с очередью задач, напоминаниями, retry и AI-обработкой голоса.",
          role: "Lead Developer",
          stack: ["Rust", "Teloxide", "SQLx", "GitHub Actions"],
          outcome: "публичный репозиторий + CI",
          status: "PROD",
          url: "https://github.com/SamandarMansurkhodjaev2713/Task-manager",
        },
        {
          tag: "COMMERCE · EVENTS",
          name: "Marketbot",
          problem: "Офферам, подпискам и affiliate-ссылкам нужна доставка без ручной рутины.",
          solution: "Event-driven backend на очередях: ingestion, подписки, уведомления, админка.",
          role: "Backend Architect",
          stack: ["Python", "gRPC", "RabbitMQ", "Telegram"],
          outcome: "операционная панель для бизнеса",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "IOT · EMBEDDED",
          name: "Sentinel Edge",
          problem: "Большинство embedded-демо заканчиваются выводом данных с датчика.",
          solution: "Firmware + serial-протокол + Node-мост + realtime React-дашборд.",
          role: "Full-stack + Firmware",
          stack: ["Arduino C++", "Node.js", "React", "WebSocket"],
          outcome: "публичный репозиторий + live-дашборд",
          status: "PROD",
          url: "https://samandarmansurkhodjaev2713.github.io/sentinel-edge-smart-system/",
        },
        {
          tag: "EDTECH · AI-NATIVE",
          name: "Forge / Learning OS",
          problem: "Learning-платформы продают контент, но не показывают реальный навык человека.",
          solution: "AI-native платформа, где обучение превращается в доказательства: миссии, gates, портфолио-кейсы, client-офферы.",
          role: "Founder + Product Engineer",
          stack: ["Next.js 15", "React 19", "Prisma", "Auth.js", "Zod"],
          outcome: "сильная доменная модель, product-first",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "PROCTORING · DESKTOP",
          name: "BelfProctor",
          problem: "Прокторинг — это не веб-форма: нужен устанавливаемый агент, heartbeat, защищённая телеметрия, admin-контроль.",
          solution: "Windows client-agent + ingestion API + admin-панель: события, статусы, retries, политика мониторинга.",
          role: "Backend + Systems",
          stack: ["C#", "Node.js", "Express", "PostgreSQL", "React"],
          outcome: "система за пределами web, sensitive-данные",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "AUTOMATION · BROWSER",
          name: "VFS Killer",
          problem: "Браузерные воркфлоу ломаются от таймингов, сессий, прокси и anti-automation — «скрипт с кликами» не выживает.",
          solution: "Browser-automation с diagnostics-first подходом: управление через Telegram, retries, скриншоты, Docker-runtime.",
          role: "Automation Engineer",
          stack: ["Python", "Playwright", "aiogram", "Docker"],
          outcome: "надёжная автоматизация в ломких условиях",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "HEALTH-TECH · DESKTOP",
          name: "med-exe",
          problem: "В медицинских расчётах нельзя «примерно работает» — нужны детерминизм, приватность, offline и точность.",
          solution: "Offline desktop-приложение: Rust-ядро с расчётной логикой, Tauri-оболочка, typed IPC, локальный SQLite.",
          role: "Desktop + Core",
          stack: ["Rust", "Tauri", "React", "SQLite"],
          outcome: "offline-first, точность важнее скорости",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "FRONTEND · WEBGL",
          name: "3D Landing",
          problem: "Портфолио-страницы часто статичны и не производят впечатления.",
          solution: "Интерактивный Three.js/WebGL лендинг: 3D-сцена, motion, адаптив, performance-aware реализация.",
          role: "Frontend + Visual",
          stack: ["Three.js", "WebGL", "Vite"],
          outcome: "живое демо на GitHub Pages",
          status: "LIVE",
          url: "https://samandarmansurkhodjaev2713.github.io/3d-landing/",
        },
      ],
      cta: "Смотреть кейс",
    },
    skills: {
      eyebrow: "Stack radar",
      title: "Технический стек",
      lead: "Не зоопарк логотипов — сетка инструментов, которыми реально работаю.",
      groups: [
        {
          k: "Frontend",
          items: ["TypeScript", "React", "Next.js", "Astro", "GSAP", "Three.js", "Tailwind"],
        },
        { k: "Backend", items: ["Node.js", "Fastify", "tRPC", "Postgres", "Redis", "Prisma"] },
        { k: "AI / Automation", items: ["OpenAI", "Anthropic", "LangChain", "n8n", "RAG", "Vector DBs"] },
        { k: "DevOps", items: ["Docker", "GitHub Actions", "Cloudflare", "Railway", "Linux"] },
        { k: "Product", items: ["Figma", "Architecture", "Product strategy", "Tech spec"] },
        { k: "Telegram", items: ["Telegraf", "Bot API", "MTProto", "Web Apps"] },
      ],
    },
    services: {
      eyebrow: "Services",
      title: "Что можно заказать",
      items: [
        { k: "Web Apps", v: "Полноценные продукты, MVP, SaaS-приложения", io: "spec → prod app" },
        { k: "Landing & Sites", v: "Премиум-лендинги, корпоративные и продуктовые", io: "brief → site" },
        { k: "Telegram Bots", v: "Боты для команд, продаж, автоматизации", io: "task → bot" },
        { k: "AI Automation", v: "Workflow с LLM, агентами, обработкой данных", io: "process → engine" },
        { k: "Dashboards", v: "Админ-панели, CRM, операционные дашборды", io: "data → ops view" },
        { k: "MVP / Prototype", v: "От идеи до работающего прототипа за недели", io: "idea → demo" },
        { k: "Internal Tools", v: "CRM, кабинеты, инструменты для команды", io: "team → tool" },
        { k: "Tech Consulting", v: "Архитектура, аудит, стек, тех-стратегия", io: "question → plan" },
      ],
    },
    cv: {
      eyebrow: "Experience",
      title: "CV / Опыт",
      lead: "Честный список того, что я сделал — без раздутого стажа.",
      timeline: [
        {
          y: "янв 2026 — сейчас",
          role: "AI-first Developer · Full-stack Developer",
          org: "TTYL",
          tag: "main",
          points: [
            "Построил BelfProctor — систему учёта активности и качества работы сотрудников.",
            "Разработал TTYL Platform — защищённую локальную платформу: задачи, чат, файлообмен.",
            "Веду фронтенд и бэкенд обеих систем, включая деплой и исправление багов в проде.",
          ],
          stack: ["TypeScript", "Next.js", "NestJS", "PostgreSQL", "Docker"],
        },
        {
          y: "2025 — сейчас",
          role: "Независимые и коммерческие проекты",
          org: "Собственная практика",
          tag: "product",
          points: [
            "Klawis — AI-продукт для юридической сферы: RAG, цитирование источников, live на klawis.uz.",
            "CoupleOS / Softly — потребительский продукт для пар, live на SoftlyLove.uz.",
            "Task Manage Bot, Sentinel Edge, Marketbot — Telegram-автоматизация, embedded/IoT, event-driven backend.",
          ],
          stack: ["Python", "FastAPI", "Rust", "Arduino C++", "RAG"],
        },
        {
          y: "янв 2023 — апр 2023",
          role: "Оператор горячей линии",
          org: "UniCall",
          tag: "start",
          points: [
            "Консультировал клиентов, решал вопросы, вёл записи в CRM.",
            "Признан лучшим сотрудником месяца за качество коммуникации.",
            "Первый системный опыт работы с клиентами — сейчас помогает вести заказчиков.",
          ],
          stack: [],
        },
      ],
      edu_title: "Образование",
      edu: [
        { y: "2028", k: "Бакалавр Software Engineering · IT Park University (3 курс)" },
      ],
      readme: {
        intro: "Фулстек-разработчик, AI Automation Developer и промпт-инженер. Учусь на 3 курсе Software Engineering в IT Park University и параллельно строю реальные продукты: веб-платформы, Telegram-ботов, AI-автоматизации, внутренние системы и админ-панели.",
        intro2: "Сильная сторона — соединять разработку, продуктовый подход и бизнес-логику. Не просто пишу код по задаче, а разбираюсь, какую проблему решает продукт, где сломается процесс и как быстрее запустить рабочую версию.",
        build_title: "что я умею",
        build: [
          "Фулстек — frontend, backend, БД, авторизация, API, админки, dashboards, интеграции, деплой",
          "Backend и архитектура — бизнес-логика, REST, очереди, роли и доступы, файловые системы, Docker",
          "AI и автоматизация — OpenAI/Claude API, RAG, структурированные ответы, AI-воркеры, Telegram-воркфлоу",
          "Промпт-инженерия — системные инструкции, снижение галлюцинаций, контроль качества",
          "Telegram-боты — задачи, напоминания, обработка голоса, статусы, автоматизация",
          "Продукт и UI/UX — разобраться в задаче, собрать MVP, продумать путь пользователя",
        ],
        avail_title: "формат работы",
        avail: "Открыт к full-time, стажировкам, freelance и продуктовым коллаборациям. Сильнее всего там, где важны скорость, инженерная аккуратность и умение довести идею до результата.",
        proof_title: "живые доказательства",
        proof: [
          { k: "klawis.uz", v: "Legal AI · RAG · источники", url: "https://klawis.uz" },
          { k: "softlylove.uz", v: "продукт для пар · live", url: "https://softlylove.uz" },
          { k: "github", v: "публичный код + CI", url: "https://github.com/SamandarMansurkhodjaev2713" },
        ],
      },
    },
    process: {
      eyebrow: "Method",
      title: "Как я работаю",
      lead: "Один пайплайн от первого звонка до saturday-night-prod.",
      steps: [
        { k: "Discovery", v: "Бизнес-цель, метрики, ограничения" },
        { k: "Architecture", v: "Стек, контракт, риски" },
        { k: "Prototype", v: "Кликабельный прототип ключевых сценариев" },
        { k: "UI / UX", v: "Дизайн под продукт, не под Behance" },
        { k: "Development", v: "Чистый стек, типизация, тесты на критическом пути" },
        { k: "AI Automation", v: "LLM-слой, ретривал, эвалы" },
        { k: "Testing", v: "QA, нагрузка, edge-кейсы" },
        { k: "Deploy", v: "CI/CD, мониторинг, алерты" },
        { k: "Support", v: "Стабилизация и развитие после релиза" },
      ],
      cli_eyebrow: "live · поток деплоев",
      cli_title: "system.live",
      cli_lead: "Реальные события прод-окружения, обновляются каждые ~20 секунд.",
      cli_sessions: [
        {
          title: "ops — stripe checkout · v2.4.1",
          steps: [
            { kind: "prompt", text: "deploy stripe-checkout v2.4.1 → prod" },
            { kind: "thinking", durationMs: 1500 },
            { kind: "tool", name: "build", arg: "next build · 32 routes · 1.8 MB" },
            { kind: "tool", name: "test",  arg: "vitest · 184 passed · 92% coverage" },
            { kind: "tool", name: "scan",  arg: "snyk · 0 vulnerabilities" },
            { kind: "tool", name: "push",  arg: "registry.fly.io · sha 8f2c1a" },
            { kind: "tool", name: "rollout", arg: "fly machines · canary 10% → 100%" },
            { kind: "output", text: "  health-check 200 · p95 latency 84ms" },
            { kind: "done", text: "✓ deployed · 3m 14s · zero downtime" },
          ],
        },
        {
          title: "ops — telegram voice-task-bot · v1.7.0",
          steps: [
            { kind: "prompt", text: "ship voice-task-bot v1.7.0 → prod" },
            { kind: "thinking", durationMs: 1700 },
            { kind: "tool", name: "build", arg: "docker · python:3.12-slim · 184 MB" },
            { kind: "tool", name: "test",  arg: "pytest · 47 passed · whisper-1 · gpt-4o" },
            { kind: "tool", name: "push",  arg: "ghcr.io/ops/voicebot:1.7.0" },
            { kind: "tool", name: "rollout", arg: "k8s · 3 replicas · rolling update" },
            { kind: "output", text: "  webhook latency p50 220ms · queue 0" },
            { kind: "done", text: "✓ deployed · 2m 41s · 100% healthy" },
          ],
        },
        {
          title: "ops — lead-classification pipeline · v3.1.0",
          steps: [
            { kind: "prompt", text: "promote lead-classifier v3.1.0 → prod" },
            { kind: "thinking", durationMs: 1300 },
            { kind: "tool", name: "build", arg: "modal.app · python · 96 MB" },
            { kind: "tool", name: "eval",  arg: "240 leads · precision 0.94 · recall 0.91" },
            { kind: "tool", name: "push",  arg: "modal-labs · v3.1.0" },
            { kind: "tool", name: "rollout", arg: "n8n workflow · 3 nodes updated" },
            { kind: "output", text: "  ingest rate 412 leads/min · cost $0.0008/lead" },
            { kind: "done", text: "✓ deployed · 1m 58s · CRM in sync" },
          ],
        },
      ],
    },
    builder: {
      eyebrow: "Конструктор",
      title: "Соберите свой проект",
      lead: "Выберите тип и масштаб — на глазах соберётся архитектура, стек и ориентир по срокам и бюджету.",
      step1: "Что строим",
      step2: "Масштаб",
      types: [
        { k: "web", label: "Веб-приложение", note: "продукт · SaaS · портал" },
        { k: "ai", label: "AI-инструмент", note: "LLM · RAG · агенты" },
        { k: "bot", label: "Telegram-бот", note: "продажи · задачи · сервис" },
        { k: "automation", label: "Автоматизация", note: "интеграции · пайплайны" },
      ],
      scales: [
        { k: "mvp", label: "MVP", note: "проверить идею" },
        { k: "prod", label: "Продакшн", note: "рабочая система" },
        { k: "product", label: "Продукт с нуля", note: "всё под ключ" },
      ],
      layers: { client: "Клиент", logic: "Логика", ai: "Интеллект", data: "Данные", infra: "Инфраструктура" },
      sub: { frontend: "Frontend", telegram: "Telegram", triggers: "Триггеры", api: "API", bot: "Бот-логика", pipeline: "Пайплайн", ai: "AI-слой" },
      readout: { stack: "Стек", time: "Срок", budget: "Бюджет" },
      times: { mvp: "1–2 недели", prod: "3–5 недель", product: "1.5–3 месяца" },
      step3: "Что критично",
      priorities: [
        { k: "speed", label: "Скорость", note: "запуск как можно раньше" },
        { k: "design", label: "Дизайн", note: "премиум-интерфейс, анимации" },
        { k: "ai", label: "AI-глубина", note: "эвалы, поиск по смыслу" },
        { k: "scale", label: "Нагрузка", note: "очереди, кэш, масштаб" },
      ],
      verdictLead: { web: "Продуктовый веб-стек", ai: "AI-продукт с ретривалом", bot: "Telegram-сервис на очередях", automation: "Событийная автоматизация" },
      verdictTail: { speed: "заточен под быстрый запуск, меньше слоёв — больше скорости", design: "с упором на дизайн и анимацию интерфейса", ai: "с глубоким AI-слоем: эвалы, векторный поиск, контроль качества", scale: "рассчитан на нагрузку: очереди, кэш, горизонтальное масштабирование" },
      layerNote: { client: "то, что видит пользователь", logic: "правила, API, бизнес-логика", ai: "LLM, поиск по смыслу, эвалы", data: "хранение и состояние", infra: "деплой, доступ, мониторинг" },
      metric: { layers: "слоёв", modules: "модулей" },
      cta_tg: "Обсудить в Telegram",
      cta_form: "Перенести в заявку",
      hint: "Ориентир, а не смета — точные цифры после короткого созвона.",
    },
    faq: {
      eyebrow: "FAQ",
      title: "Частые вопросы",
      lead: "Коротко — то, что обычно спрашивают до старта.",
      items: [
        {
          q: "Сколько стоит проект?",
          a: "Зависит от объёма — от простого лендинга за несколько дней до полноценного продукта с AI-частью за месяцы. После короткого созвона даю вилку по деньгам и срокам, без скрытых наценок.",
        },
        {
          q: "Сколько времени займёт разработка?",
          a: "Работаю быстро и с AI-инструментами: лендинг — за несколько дней, MVP — 1–2 недели, продукт с бэкендом и AI-слоем — от 1.5 месяцев. Точный срок фиксирую после короткого discovery-этапа, не раньше.",
        },
        {
          q: "Вы работаете один или это студия?",
          a: "Один — от дизайна до деплоя и поддержки. Никакой прослойки между вами и разработчиком и никакой агентской наценки. Под большой объём точечно подключаю проверенных специалистов, но за результат отвечаю я.",
        },
        {
          q: "У меня нет технического задания — это проблема?",
          a: "Нет. Большинство приходит с идеей, а не с ТЗ. Проговариваем цель, ограничения и бюджет — архитектуру и план собираю сам, это часть работы, а не отдельная услуга.",
        },
        {
          q: "Как устроена оплата?",
          a: "Обычно поэтапно: аванс перед стартом, остаток — по завершении ключевых этапов. Условия фиксируем письменно до начала работы.",
        },
        {
          q: "Что после запуска — есть поддержка?",
          a: "Да. Раннее сопровождение после релиза включено в проект, дальше — почасовая поддержка или доработки по договорённости.",
        },
        {
          q: "Как быстро можно начать?",
          a: "Обычно готов стартовать в течение нескольких дней после согласования деталей. Быстрее всего обсудить сроки — в Telegram.",
        },
      ],
    },
    trust: {
      eyebrow: "Trust",
      title: "Отзывы команд",
      lead: "Что говорят те, с кем я уже работал.",
      // Placeholder phase: quotes below are illustrative (see note), not yet
      // real client testimonials. kQuotes/kRoles/kSpan label the strip's
      // genuinely-derived counts; note is the honest flag shown alongside
      // them. Delete `note` once real quotes replace the placeholders.
      kQuotes: "цитаты",
      kRoles: "роли",
      kSpan: "период",
      note: "иллюстративно — реальные отзывы скоро",
      items: [
        {
          q: "Принёс архитектурный черновик к первой встрече. Через месяц у нас работала первая версия — без скоупа, который раздулся бы у любого подрядчика.",
          who: "Product Lead",
          role: "Логистическая компания · 2025",
        },
        {
          q: "AI-интеграция работает в проде уже 8 месяцев. Без галлюцинаций, с метриками, с graceful-fallback. Это не демо — это инструмент.",
          who: "CTO",
          role: "SaaS-стартап · 2024",
        },
        {
          q: "Telegram-бот заменил два рабочих часа в день у каждого менеджера. Поставили за две недели, окупился за месяц.",
          who: "Founder",
          role: "B2B-сервис · 2024",
        },
      ],
    },
    contact: {
      eyebrow: "Deploy request",
      title: "Запустим проект",
      lead: "Опишите задачу — отвечу с архитектурным черновиком и оценкой за 24 часа.",
      form: {
        name: "Имя",
        email: "Email или Telegram",
        scope: "Что вам нужно",
        budget: "Бюджет",
        timeline: "Сроки",
        msg: "Что важно знать",
        msg_placeholder: "Цель, контекст, ограничения. Можно как угодно кратко.",
        submit: "Отправить запрос",
        sending: "Отправляю…",
        sent: "Запрос принят. На связи в течение 24 часов.",
        error: "Не удалось отправить. Напишите в Telegram — отвечу быстрее.",
      },
      scope_opts: ["Web App / MVP", "AI Automation", "Telegram Bot", "Dashboard / CRM", "Landing", "Consulting"],
      timeline_opts: ["ASAP", "1–2 недели", "1–2 месяца", "гибко"],
      links: [
        { k: "Telegram", v: "t.me/killallofthem13" },
        { k: "GitHub", v: "github.com/SamandarMansurkhodjaev2713" },
        { k: "Email", v: "sam4k27@gmail.com" },
      ],
    },
    footer: {
      copy: "© 2026 — Executive AI Code Lab",
      built: "собрано на TypeScript, Three.js, React",
    },
  },

  en: {
    nav: { about: "About", projects: "Work", skills: "Stack", services: "Services", cv: "CV", faq: "FAQ", contact: "Contact" },
    hero: {
      eyebrow: "Executive AI Code Lab — v.2026",
      name: "Samandar",
      title_lines: ["Full-stack.", "AI Automation.", "Product Engineer."],
      tagline:
        "I turn a business problem into a working product. Architecture, code, AI layer — one person, no handoffs.",
      cta_primary: "Discuss a project",
      cta_secondary: "View work",
      status: "available for projects",
      boot_lines: [
        "init core.engine ... ok",
        "load /modules/full-stack ... ok",
        "load /modules/ai-automation ... ok",
        "compile portfolio.v26 ... ok",
        "deploy READY",
      ],
    },
    signal: {
      eyebrow: "10-second signal",
      title: "What I build",
      cards: [
        { code: "01", k: "Full-stack", v: "Web apps, MVPs, product systems" },
        { code: "02", k: "AI Automation", v: "Workflows, agents, data pipelines" },
        { code: "03", k: "Telegram bots", v: "Task and comms automation" },
        { code: "04", k: "Dashboards", v: "Admin panels, CRM, ops dashboards" },
        { code: "05", k: "Landing & Web", v: "Premium and product landings" },
        { code: "06", k: "Product MVP", v: "Idea to working prototype" },
      ],
    },
    about: {
      eyebrow: "Profile",
      title: "I take the brief. I ship the product.",
      lead:
        "One engineer owns the whole stack: frontend, backend, AI, infra. No vendor handoffs — nothing lost in translation.",
      paragraphs: [
        "I pick the stack the task needs, not the one that's trending. Architecture stays simple so it survives the next year.",
        "AI isn't a demo here — it ships in production. LLM integrations, agents, RAG, eval pipelines.",
      ],
      stats: [
        { v: "11 mo.", k: "building" },
        { v: "10+", k: "projects" },
        { v: "3rd yr", k: "Software Engineering" },
        { v: "RU / UZ", k: "working languages" },
      ],
      status_label: "Available · remote · contract & full-time",
      currently_label: "Currently",
      currently: [
        "shipping an AI orchestrator for an ops team",
        "writing an eval pipeline for LLM agents",
        "digging into Anthropic computer-use",
        "reading Designing Data-Intensive Apps",
      ],
      recent_label: "Recent commits",
      recent: [
        { when: "1d", tag: "feat", msg: "cv-samandar — sections, motion, deploy" },
        { when: "2d", tag: "feat", msg: "task-manager — Rust bot, task queue, CI" },
        { when: "2d", tag: "feat", msg: "sentinel-edge — realtime dashboard, firmware" },
      ],
      contrib_label: "contributions · 12 weeks",
      gh_stats: "10+ projects · public code and NDA case studies · Tashkent",
    },
    projects: {
      eyebrow: "Selected work",
      title: "Featured projects",
      items: [
        {
          tag: "AI · LEGAL",
          name: "Klawis — Legal AI Assistant",
          problem: "Legal chatbots sound polished but skip sources and verifiability.",
          solution: "Live AI product with RAG, legal routing and cited sources.",
          role: "Founder + Lead Developer",
          stack: ["FastAPI", "Next.js", "Supabase", "RAG"],
          outcome: "live product at klawis.uz",
          status: "LIVE",
          url: "https://klawis.uz",
        },
        {
          tag: "CONSUMER · FOUNDER",
          name: "CoupleOS / Softly",
          problem: "Relationships need soft structure — rituals and a safe space, not a tracker.",
          solution: "Mobile-first product for couples: private flows, habits, memories.",
          role: "Founder + Full-stack",
          stack: ["Next.js", "Supabase", "PWA"],
          outcome: "live product at SoftlyLove.uz",
          status: "LIVE",
          url: "https://softlylove.uz",
        },
        {
          tag: "ENTERPRISE · ON-PREM",
          name: "TTYL Platform",
          problem: "Teams need collaboration tools without handing data to an external SaaS.",
          solution: "Self-hosted workspace: projects, chat, files, search, audit, realtime, RBAC.",
          role: "Architect + Lead Developer",
          stack: ["NestJS", "Next.js", "PostgreSQL", "Redis", "MinIO"],
          outcome: "on-prem deployment for a closed environment",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "TELEGRAM · RUST",
          name: "Task-manager / Task Manage Bot",
          problem: "Tasks from chats and voice messages get lost without structure.",
          solution: "Rust bot with a task queue, reminders, retries and AI voice parsing.",
          role: "Lead Developer",
          stack: ["Rust", "Teloxide", "SQLx", "GitHub Actions"],
          outcome: "public repository + CI",
          status: "PROD",
          url: "https://github.com/SamandarMansurkhodjaev2713/Task-manager",
        },
        {
          tag: "COMMERCE · EVENTS",
          name: "Marketbot",
          problem: "Offers, subscriptions and affiliate links need delivery without manual routine.",
          solution: "Event-driven backend on queues: ingestion, subscriptions, notifications, admin panel.",
          role: "Backend Architect",
          stack: ["Python", "gRPC", "RabbitMQ", "Telegram"],
          outcome: "operational panel for the business",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "IOT · EMBEDDED",
          name: "Sentinel Edge",
          problem: "Most embedded demos stop at printing sensor values.",
          solution: "Firmware + serial protocol + Node bridge + realtime React dashboard.",
          role: "Full-stack + Firmware",
          stack: ["Arduino C++", "Node.js", "React", "WebSocket"],
          outcome: "public repository + live dashboard",
          status: "PROD",
          url: "https://samandarmansurkhodjaev2713.github.io/sentinel-edge-smart-system/",
        },
        {
          tag: "EDTECH · AI-NATIVE",
          name: "Forge / Learning OS",
          problem: "Learning platforms sell content but barely prove real skill.",
          solution: "AI-native platform where learning turns into evidence: missions, gates, portfolio cases, client offers.",
          role: "Founder + Product Engineer",
          stack: ["Next.js 15", "React 19", "Prisma", "Auth.js", "Zod"],
          outcome: "strong domain model, product-first",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "PROCTORING · DESKTOP",
          name: "BelfProctor",
          problem: "Proctoring isn't a web form: it needs an installed agent, heartbeat, protected telemetry, admin control.",
          solution: "Windows client-agent + ingestion API + admin panel: events, statuses, retries, monitoring policy.",
          role: "Backend + Systems",
          stack: ["C#", "Node.js", "Express", "PostgreSQL", "React"],
          outcome: "a system beyond web, sensitive data",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "AUTOMATION · BROWSER",
          name: "VFS Killer",
          problem: "Browser workflows break on timing, sessions, proxies and anti-automation — a click script won't survive.",
          solution: "Diagnostics-first browser automation: Telegram control, retries, screenshots, Docker runtime.",
          role: "Automation Engineer",
          stack: ["Python", "Playwright", "aiogram", "Docker"],
          outcome: "reliable automation in brittle conditions",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "HEALTH-TECH · DESKTOP",
          name: "med-exe",
          problem: "Medical calculations can't be 'roughly right' — they need determinism, privacy, offline and precision.",
          solution: "Offline desktop app: Rust core for calc logic, Tauri shell, typed IPC, local SQLite storage.",
          role: "Desktop + Core",
          stack: ["Rust", "Tauri", "React", "SQLite"],
          outcome: "offline-first, precision over speed",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "FRONTEND · WEBGL",
          name: "3D Landing",
          problem: "Portfolio pages are often static and leave no impression.",
          solution: "Interactive Three.js/WebGL landing: 3D scene, motion, responsive, performance-aware build.",
          role: "Frontend + Visual",
          stack: ["Three.js", "WebGL", "Vite"],
          outcome: "live demo on GitHub Pages",
          status: "LIVE",
          url: "https://samandarmansurkhodjaev2713.github.io/3d-landing/",
        },
      ],
      cta: "Open case",
    },
    skills: {
      eyebrow: "Stack radar",
      title: "Technical stack",
      lead: "Not a logo zoo — the toolkit I actually ship with.",
      groups: [
        { k: "Frontend", items: ["TypeScript", "React", "Next.js", "Astro", "GSAP", "Three.js", "Tailwind"] },
        { k: "Backend", items: ["Node.js", "Fastify", "tRPC", "Postgres", "Redis", "Prisma"] },
        { k: "AI / Automation", items: ["OpenAI", "Anthropic", "LangChain", "n8n", "RAG", "Vector DBs"] },
        { k: "DevOps", items: ["Docker", "GitHub Actions", "Cloudflare", "Railway", "Linux"] },
        { k: "Product", items: ["Figma", "Architecture", "Product strategy", "Tech spec"] },
        { k: "Telegram", items: ["Telegraf", "Bot API", "MTProto", "Web Apps"] },
      ],
    },
    services: {
      eyebrow: "Services",
      title: "What you can hire me for",
      items: [
        { k: "Web Apps", v: "Full products, MVPs, SaaS applications", io: "spec → prod app" },
        { k: "Landing & Sites", v: "Premium landings, corporate and product", io: "brief → site" },
        { k: "Telegram Bots", v: "Bots for teams, sales, automation", io: "task → bot" },
        { k: "AI Automation", v: "Workflows with LLMs, agents, data pipelines", io: "process → engine" },
        { k: "Dashboards", v: "Admin panels, CRM, ops dashboards", io: "data → ops view" },
        { k: "MVP / Prototype", v: "Idea to working prototype in weeks", io: "idea → demo" },
        { k: "Internal Tools", v: "CRM, portals, team-only software", io: "team → tool" },
        { k: "Tech Consulting", v: "Architecture, audit, stack, strategy", io: "question → plan" },
      ],
    },
    cv: {
      eyebrow: "Experience",
      title: "CV / Experience",
      lead: "An honest list of what I've actually done — no inflated tenure.",
      timeline: [
        {
          y: "Jan 2026 — present",
          role: "AI-first Developer · Full-stack Developer",
          org: "TTYL",
          tag: "main",
          points: [
            "Built BelfProctor — an employee activity and work-quality tracking system.",
            "Built TTYL Platform — a secured local-first platform: tasks, chat, file exchange.",
            "Own frontend and backend for both systems, including deploys and prod bug fixes.",
          ],
          stack: ["TypeScript", "Next.js", "NestJS", "PostgreSQL", "Docker"],
        },
        {
          y: "2025 — present",
          role: "Independent & Commercial Projects",
          org: "Self-directed practice",
          tag: "product",
          points: [
            "Klawis — legal AI product: RAG, cited sources, live at klawis.uz.",
            "CoupleOS / Softly — consumer product for couples, live at SoftlyLove.uz.",
            "Task Manage Bot, Sentinel Edge, Marketbot — Telegram automation, embedded/IoT, event-driven backend.",
          ],
          stack: ["Python", "FastAPI", "Rust", "Arduino C++", "RAG"],
        },
        {
          y: "Jan 2023 — Apr 2023",
          role: "Hotline Operator",
          org: "UniCall",
          tag: "start",
          points: [
            "Advised customers, resolved issues, logged records in the CRM.",
            "Recognized as employee of the month for communication quality.",
            "First systematic client-facing experience — still shapes how I run client work now.",
          ],
          stack: [],
        },
      ],
      edu_title: "Education",
      edu: [
        { y: "2028", k: "BSc Software Engineering · IT Park University (3rd year)" },
      ],
      readme: {
        intro: "Full-stack developer, AI Automation Developer and prompt engineer. A 3rd-year Software Engineering student at IT Park University, building real products in parallel: web platforms, Telegram bots, AI automations, internal systems and admin panels.",
        intro2: "My strength is connecting engineering, product thinking and business logic. I don't just write code to spec — I work out what problem the product solves, where the process breaks, and how to ship a working version faster.",
        build_title: "what I do",
        build: [
          "Full-stack — frontend, backend, DB, auth, API, admin panels, dashboards, integrations, deploy",
          "Backend & architecture — business logic, REST, queues, roles & access, file systems, Docker",
          "AI & automation — OpenAI/Claude API, RAG, structured outputs, AI workers, Telegram workflows",
          "Prompt engineering — system instructions, hallucination control, output quality",
          "Telegram bots — tasks, reminders, voice handling, statuses, process automation",
          "Product & UI/UX — grasp the task, ship an MVP, design the user journey",
        ],
        avail_title: "availability",
        avail: "Open to full-time, internships, freelance and product collaborations. Strongest where speed, engineering care and getting an idea to a result matter.",
        proof_title: "live proof",
        proof: [
          { k: "klawis.uz", v: "Legal AI · RAG · sources", url: "https://klawis.uz" },
          { k: "softlylove.uz", v: "product for couples · live", url: "https://softlylove.uz" },
          { k: "github", v: "public code + CI", url: "https://github.com/SamandarMansurkhodjaev2713" },
        ],
      },
    },
    process: {
      eyebrow: "Method",
      title: "How I work",
      lead: "One pipeline from first call to saturday-night-prod.",
      steps: [
        { k: "Discovery", v: "Business goal, metrics, constraints" },
        { k: "Architecture", v: "Stack, contracts, risks" },
        { k: "Prototype", v: "Clickable proto of key flows" },
        { k: "UI / UX", v: "Design for the product, not Behance" },
        { k: "Development", v: "Clean stack, types, tests on the critical path" },
        { k: "AI Automation", v: "LLM layer, retrieval, evals" },
        { k: "Testing", v: "QA, load, edge cases" },
        { k: "Deploy", v: "CI/CD, monitoring, alerts" },
        { k: "Support", v: "Post-release stabilization & growth" },
      ],
      cli_eyebrow: "live · deploy stream",
      cli_title: "system.live",
      cli_lead: "Production deploy events, refreshed roughly every 20 seconds.",
      cli_sessions: [
        {
          title: "ops — stripe checkout · v2.4.1",
          steps: [
            { kind: "prompt", text: "deploy stripe-checkout v2.4.1 → prod" },
            { kind: "thinking", durationMs: 1500 },
            { kind: "tool", name: "build", arg: "next build · 32 routes · 1.8 MB" },
            { kind: "tool", name: "test",  arg: "vitest · 184 passed · 92% coverage" },
            { kind: "tool", name: "scan",  arg: "snyk · 0 vulnerabilities" },
            { kind: "tool", name: "push",  arg: "registry.fly.io · sha 8f2c1a" },
            { kind: "tool", name: "rollout", arg: "fly machines · canary 10% → 100%" },
            { kind: "output", text: "  health-check 200 · p95 latency 84ms" },
            { kind: "done", text: "✓ deployed · 3m 14s · zero downtime" },
          ],
        },
        {
          title: "ops — telegram voice-task-bot · v1.7.0",
          steps: [
            { kind: "prompt", text: "ship voice-task-bot v1.7.0 → prod" },
            { kind: "thinking", durationMs: 1700 },
            { kind: "tool", name: "build", arg: "docker · python:3.12-slim · 184 MB" },
            { kind: "tool", name: "test",  arg: "pytest · 47 passed · whisper-1 · gpt-4o" },
            { kind: "tool", name: "push",  arg: "ghcr.io/ops/voicebot:1.7.0" },
            { kind: "tool", name: "rollout", arg: "k8s · 3 replicas · rolling update" },
            { kind: "output", text: "  webhook latency p50 220ms · queue 0" },
            { kind: "done", text: "✓ deployed · 2m 41s · 100% healthy" },
          ],
        },
        {
          title: "ops — lead-classification pipeline · v3.1.0",
          steps: [
            { kind: "prompt", text: "promote lead-classifier v3.1.0 → prod" },
            { kind: "thinking", durationMs: 1300 },
            { kind: "tool", name: "build", arg: "modal.app · python · 96 MB" },
            { kind: "tool", name: "eval",  arg: "240 leads · precision 0.94 · recall 0.91" },
            { kind: "tool", name: "push",  arg: "modal-labs · v3.1.0" },
            { kind: "tool", name: "rollout", arg: "n8n workflow · 3 nodes updated" },
            { kind: "output", text: "  ingest rate 412 leads/min · cost $0.0008/lead" },
            { kind: "done", text: "✓ deployed · 1m 58s · CRM in sync" },
          ],
        },
      ],
    },
    builder: {
      eyebrow: "Build preview",
      title: "Sketch your build",
      lead: "Pick a type and scale — the architecture assembles live, with the stack and a ballpark for time and budget.",
      step1: "What we build",
      step2: "Scale",
      types: [
        { k: "web", label: "Web app", note: "product · SaaS · portal" },
        { k: "ai", label: "AI tool", note: "LLM · RAG · agents" },
        { k: "bot", label: "Telegram bot", note: "sales · tasks · service" },
        { k: "automation", label: "Automation", note: "integrations · pipelines" },
      ],
      scales: [
        { k: "mvp", label: "MVP", note: "validate the idea" },
        { k: "prod", label: "Production", note: "a working system" },
        { k: "product", label: "Full product", note: "turnkey, end to end" },
      ],
      layers: { client: "Client", logic: "Logic", ai: "Intelligence", data: "Data", infra: "Infrastructure" },
      sub: { frontend: "Frontend", telegram: "Telegram", triggers: "Triggers", api: "API", bot: "Bot logic", pipeline: "Pipeline", ai: "AI layer" },
      readout: { stack: "Stack", time: "Timeline", budget: "Budget" },
      times: { mvp: "1–2 weeks", prod: "3–5 weeks", product: "1.5–3 months" },
      step3: "What matters most",
      priorities: [
        { k: "speed", label: "Speed", note: "ship as early as possible" },
        { k: "design", label: "Design", note: "premium UI, motion" },
        { k: "ai", label: "AI depth", note: "evals, semantic search" },
        { k: "scale", label: "Load", note: "queues, cache, scale" },
      ],
      verdictLead: { web: "A product web stack", ai: "An AI product with retrieval", bot: "A Telegram service on queues", automation: "Event-driven automation" },
      verdictTail: { speed: "tuned for a fast launch — fewer layers, more speed", design: "with a focus on design and interface motion", ai: "with a deep AI layer: evals, vector search, quality control", scale: "built for load: queues, cache, horizontal scaling" },
      layerNote: { client: "what the user sees", logic: "rules, API, business logic", ai: "LLM, semantic search, evals", data: "storage and state", infra: "deploy, access, monitoring" },
      metric: { layers: "layers", modules: "modules" },
      cta_tg: "Discuss on Telegram",
      cta_form: "Send as a brief",
      hint: "A ballpark, not a quote — exact numbers after a short call.",
    },
    faq: {
      eyebrow: "FAQ",
      title: "Frequent questions",
      lead: "Short version — what people usually ask before we start.",
      items: [
        {
          q: "How much does a project cost?",
          a: "Depends on scope — from a simple landing page in a few days to a full product with an AI layer over months. After a short call I give a real range for budget and timeline, no hidden markup.",
        },
        {
          q: "How long does development take?",
          a: "I work fast and with AI tooling: a landing in a few days, an MVP in 1–2 weeks, a product with a backend and AI layer from ~1.5 months. I lock in the exact timeline after a short discovery phase, not before.",
        },
        {
          q: "Do you work alone, or is this a studio?",
          a: "Alone — design through deployment and support. No layer between you and the developer, no agency markup. For larger scope I bring in vetted specialists for specific tasks, but I own the result.",
        },
        {
          q: "I don't have a spec — is that a problem?",
          a: "No. Most people arrive with an idea, not a spec. We talk through the goal, constraints, and budget — I put together the architecture and plan myself; that's part of the work, not a separate service.",
        },
        {
          q: "How does payment work?",
          a: "Usually in stages: a deposit before starting, the rest after key milestones or project completion. Terms are set in writing before work begins.",
        },
        {
          q: "What about support after launch?",
          a: "Yes. Early post-launch support is included; after that it's hourly support or further work by agreement.",
        },
        {
          q: "How soon can we start?",
          a: "Usually within a few days of agreeing on details. Telegram is the fastest way to talk timeline.",
        },
      ],
    },
    trust: {
      eyebrow: "Trust",
      title: "What teams say",
      lead: "From people I've worked with.",
      kQuotes: "quotes",
      kRoles: "roles",
      kSpan: "span",
      note: "illustrative — real quotes coming soon",
      items: [
        {
          q: "Brought an architecture draft to our first call. A month later we had a working version — no scope creep, which any other vendor would have given us.",
          who: "Product Lead",
          role: "Logistics company · 2025",
        },
        {
          q: "The AI integration has been in production for 8 months. No hallucinations, with metrics, with graceful fallback. It's a tool, not a demo.",
          who: "CTO",
          role: "SaaS startup · 2024",
        },
        {
          q: "The Telegram bot replaced two hours of work per day for each manager. Delivered in two weeks, paid for itself in a month.",
          who: "Founder",
          role: "B2B service · 2024",
        },
      ],
    },
    contact: {
      eyebrow: "Deploy request",
      title: "Let's ship something",
      lead: "Describe the task — I'll come back with an architecture sketch and estimate within 24 hours.",
      form: {
        name: "Name",
        email: "Email or Telegram",
        scope: "What you need",
        budget: "Budget",
        timeline: "Timeline",
        msg: "What I should know",
        msg_placeholder: "Goal, context, constraints. As short as you like.",
        submit: "Send request",
        sending: "Sending…",
        sent: "Request received. I'll reply within 24 hours.",
        error: "Couldn't send. Message me on Telegram — I reply faster there.",
      },
      scope_opts: ["Web App / MVP", "AI Automation", "Telegram Bot", "Dashboard / CRM", "Landing", "Consulting"],
      timeline_opts: ["ASAP", "1–2 weeks", "1–2 months", "flexible"],
      links: [
        { k: "Telegram", v: "t.me/killallofthem13" },
        { k: "GitHub", v: "github.com/SamandarMansurkhodjaev2713" },
        { k: "Email", v: "sam4k27@gmail.com" },
      ],
    },
    footer: { copy: "© 2026 — Executive AI Code Lab", built: "built on TypeScript, Three.js, React" },
  },

  uz: {
    nav: { about: "Men haqimda", projects: "Loyihalar", skills: "Stek", services: "Xizmatlar", cv: "Tajriba", faq: "Savollar", contact: "Aloqa" },
    hero: {
      eyebrow: "Executive AI Code Lab — v.2026",
      name: "Samandar",
      title_lines: ["Full-stack.", "AI Avtomatlashtirish.", "Product muhandis."],
      tagline:
        "Biznes vazifasini ishlovchi mahsulotga aylantiraman. Arxitektura, kod, AI-qatlam — bir kishi, vositachisiz.",
      cta_primary: "Loyihani muhokama qilish",
      cta_secondary: "Ishlarni ko'rish",
      status: "loyihalar uchun ochiqman",
      boot_lines: [
        "init core.engine ... ok",
        "load /modules/full-stack ... ok",
        "load /modules/ai-automation ... ok",
        "compile portfolio.v26 ... ok",
        "deploy READY",
      ],
    },
    signal: {
      eyebrow: "10 soniyalik signal",
      title: "Men nima quraman",
      cards: [
        { code: "01", k: "Full-stack", v: "Veb-ilovalar, MVP, mahsulot tizimlari" },
        { code: "02", k: "AI Avtomatlashtirish", v: "Workflow, agentlar, ma'lumotlar" },
        { code: "03", k: "Telegram-botlar", v: "Vazifa va aloqa avtomatlashtirish" },
        { code: "04", k: "Dashboardlar", v: "Admin panellar, CRM, operatsion ko'rinishlar" },
        { code: "05", k: "Landing va Veb", v: "Premium va mahsulot saytlari" },
        { code: "06", k: "Mahsulot MVP", v: "Goyadan ishlovchi prototipgacha" },
      ],
    },
    about: {
      eyebrow: "Profil",
      title: "Vazifani olaman — ishlovchi mahsulot beraman",
      lead:
        "Bitta muhandis butun stekka javob beradi: frontend, backend, AI, infratuzilma. Pudratchilar orasida uzatish yo'q — tarjimada hech narsa yo'qolmaydi.",
      paragraphs: [
        "Vazifaga mos stekni tanlayman, modaga emas. Arxitektura sodda — bir yildan keyin ham qo'llab-quvvatlanadi.",
        "AI — demo emas, mahsulotning bir qismi: LLM integratsiyalari, agentlar, RAG, sifat baholash.",
      ],
      stats: [
        { v: "11 oy", k: "rivojlanishda" },
        { v: "10+", k: "loyiha" },
        { v: "3-kurs", k: "Software Engineering" },
        { v: "RU / UZ", k: "ish tillari" },
      ],
      status_label: "Bo'sh · masofadan · shartnoma yoki fulltayim",
      currently_label: "Hozir",
      currently: [
        "ops jamoasi uchun AI-orchestrator quryapman",
        "LLM-agentlar uchun eval pipeline yozyapman",
        "Anthropic computer-use'ni kovlayapman",
        "Designing Data-Intensive Apps o'qiyapman",
      ],
      recent_label: "Oxirgi kommitlar",
      recent: [
        { when: "1 k", tag: "feat", msg: "cv-samandar — bo'limlar, animatsiya, deploy" },
        { when: "2 k", tag: "feat", msg: "task-manager — Rust-bot, vazifalar navbati, CI" },
        { when: "2 k", tag: "feat", msg: "sentinel-edge — realtime-dashboard, firmware" },
      ],
      contrib_label: "faollik · 12 hafta",
      gh_stats: "10+ loyiha · ochiq kod va NDA case'lar · Toshkent",
    },
    projects: {
      eyebrow: "Tanlangan ishlar",
      title: "Asosiy loyihalar",
      items: [
        {
          tag: "AI · LEGAL",
          name: "Klawis — Legal AI Assistant",
          problem: "Yuridik chat-botlar chiroyli javob beradi, lekin manba va tekshiruvchanlik yo'q.",
          solution: "RAG, yuridik yo'naltirish va manba iqtibosli live AI-mahsulot.",
          role: "Founder + Lead Developer",
          stack: ["FastAPI", "Next.js", "Supabase", "RAG"],
          outcome: "klawis.uz'da ishlayotgan mahsulot",
          status: "LIVE",
          url: "https://klawis.uz",
        },
        {
          tag: "CONSUMER · FOUNDER",
          name: "CoupleOS / Softly",
          problem: "Munosabatlarga yumshoq tuzilma kerak — trekker emas, ritual va xavfsiz makon.",
          solution: "Juftliklar uchun mobile-first mahsulot: maxfiy oqimlar, odatlar, xotiralar.",
          role: "Founder + Full-stack",
          stack: ["Next.js", "Supabase", "PWA"],
          outcome: "SoftlyLove.uz'da ishlayotgan mahsulot",
          status: "LIVE",
          url: "https://softlylove.uz",
        },
        {
          tag: "ENTERPRISE · ON-PREM",
          name: "TTYL Platform",
          problem: "Jamoaga tashqi SaaS'ga ma'lumot bermasdan collaboration vositalari kerak.",
          solution: "Self-hosted workspace: loyihalar, chat, fayllar, qidiruv, audit, realtime, RBAC.",
          role: "Architect + Lead Developer",
          stack: ["NestJS", "Next.js", "PostgreSQL", "Redis", "MinIO"],
          outcome: "yopiq muhit uchun on-prem joylashtirish",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "TELEGRAM · RUST",
          name: "Task-manager / Task Manage Bot",
          problem: "Chat va ovozli xabarlardagi vazifalar tuzilmasiz yo'qoladi.",
          solution: "Vazifalar navbati, eslatmalar, retry va AI ovoz tahlili bilan Rust-bot.",
          role: "Lead Developer",
          stack: ["Rust", "Teloxide", "SQLx", "GitHub Actions"],
          outcome: "ochiq repozitoriy + CI",
          status: "PROD",
          url: "https://github.com/SamandarMansurkhodjaev2713/Task-manager",
        },
        {
          tag: "COMMERCE · EVENTS",
          name: "Marketbot",
          problem: "Oferta, obuna va affiliate havolalar qo'lda ishlovsiz yetkazilishi kerak.",
          solution: "Navbatlarga asoslangan event-driven backend: ingestion, obuna, xabarnoma, admin panel.",
          role: "Backend Architect",
          stack: ["Python", "gRPC", "RabbitMQ", "Telegram"],
          outcome: "biznes uchun operatsion panel",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "IOT · EMBEDDED",
          name: "Sentinel Edge",
          problem: "Ko'p embedded demolar datchik qiymatini chiqarish bilan tugaydi.",
          solution: "Firmware + serial-protokol + Node-ko'prik + realtime React-dashboard.",
          role: "Full-stack + Firmware",
          stack: ["Arduino C++", "Node.js", "React", "WebSocket"],
          outcome: "ochiq repozitoriy + live-dashboard",
          status: "PROD",
          url: "https://samandarmansurkhodjaev2713.github.io/sentinel-edge-smart-system/",
        },
        {
          tag: "EDTECH · AI-NATIVE",
          name: "Forge / Learning OS",
          problem: "Learning-platformalar kontent sotadi, lekin haqiqiy ko'nikmani ko'rsatmaydi.",
          solution: "AI-native platforma: o'qish isbotga aylanadi — missiyalar, gates, portfolio-keyslar, client-offerlar.",
          role: "Founder + Product Engineer",
          stack: ["Next.js 15", "React 19", "Prisma", "Auth.js", "Zod"],
          outcome: "kuchli domen-model, product-first",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "PROCTORING · DESKTOP",
          name: "BelfProctor",
          problem: "Proktoring — bu veb-forma emas: o'rnatiladigan agent, heartbeat, himoyalangan telemetriya, admin-nazorat kerak.",
          solution: "Windows client-agent + ingestion API + admin-panel: hodisalar, statuslar, retries, monitoring siyosati.",
          role: "Backend + Systems",
          stack: ["C#", "Node.js", "Express", "PostgreSQL", "React"],
          outcome: "web'dan tashqaridagi tizim, sensitive ma'lumot",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "AUTOMATION · BROWSER",
          name: "VFS Killer",
          problem: "Brauzer-workflowlar tayming, sessiya, proksi va anti-automation'dan sinadi — «klik skript» omon qolmaydi.",
          solution: "Diagnostics-first brauzer-avtomatlashtirish: Telegram nazorat, retries, skrinshotlar, Docker-runtime.",
          role: "Automation Engineer",
          stack: ["Python", "Playwright", "aiogram", "Docker"],
          outcome: "beqaror sharoitda ishonchli avtomatlashtirish",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "HEALTH-TECH · DESKTOP",
          name: "med-exe",
          problem: "Tibbiy hisoblarda «taxminan ishlaydi» yaramaydi — determinizm, maxfiylik, offline va aniqlik kerak.",
          solution: "Offline desktop-ilova: hisob mantig'i uchun Rust-yadro, Tauri-qobiq, typed IPC, lokal SQLite.",
          role: "Desktop + Core",
          stack: ["Rust", "Tauri", "React", "SQLite"],
          outcome: "offline-first, aniqlik tezlikdan muhim",
          status: "NDA",
          url: "#contact",
        },
        {
          tag: "FRONTEND · WEBGL",
          name: "3D Landing",
          problem: "Portfolio sahifalari ko'pincha statik va taassurot qoldirmaydi.",
          solution: "Interaktiv Three.js/WebGL landing: 3D-sahna, motion, adaptiv, performance-aware amalga oshirish.",
          role: "Frontend + Visual",
          stack: ["Three.js", "WebGL", "Vite"],
          outcome: "GitHub Pages'da jonli demo",
          status: "LIVE",
          url: "https://samandarmansurkhodjaev2713.github.io/3d-landing/",
        },
      ],
      cta: "Keysni ochish",
    },
    skills: {
      eyebrow: "Stek radari",
      title: "Texnik stek",
      lead: "Logotiplar to'plami emas — haqiqatan ishlatadigan asboblar.",
      groups: [
        { k: "Frontend", items: ["TypeScript", "React", "Next.js", "Astro", "GSAP", "Three.js", "Tailwind"] },
        { k: "Backend", items: ["Node.js", "Fastify", "tRPC", "Postgres", "Redis", "Prisma"] },
        { k: "AI / Automation", items: ["OpenAI", "Anthropic", "LangChain", "n8n", "RAG", "Vector DBs"] },
        { k: "DevOps", items: ["Docker", "GitHub Actions", "Cloudflare", "Railway", "Linux"] },
        { k: "Product", items: ["Figma", "Architecture", "Product strategy", "Tech spec"] },
        { k: "Telegram", items: ["Telegraf", "Bot API", "MTProto", "Web Apps"] },
      ],
    },
    services: {
      eyebrow: "Xizmatlar",
      title: "Nima buyurtma qilish mumkin",
      items: [
        { k: "Web Apps", v: "To'liq mahsulotlar, MVP, SaaS-ilovalar", io: "spec → prod app" },
        { k: "Landing va saytlar", v: "Premium landing, korporativ va mahsulot", io: "brief → site" },
        { k: "Telegram-botlar", v: "Jamoa, sotuv, avtomatlashtirish uchun", io: "task → bot" },
        { k: "AI Avtomatlashtirish", v: "LLM, agentlar, ma'lumot quvurlari", io: "process → engine" },
        { k: "Dashboardlar", v: "Admin paneller, CRM, ops dashboardlar", io: "data → ops view" },
        { k: "MVP / Prototip", v: "Goyadan ishlovchi prototipgacha", io: "idea → demo" },
        { k: "Ichki asboblar", v: "CRM, kabinetlar, jamoa uchun", io: "team → tool" },
        { k: "Texnik konsalting", v: "Arxitektura, audit, stek, strategiya", io: "question → plan" },
      ],
    },
    cv: {
      eyebrow: "Tajriba",
      title: "CV / Tajriba",
      lead: "Haqiqiy qilgan ishlarim ro'yxati — shishirilgan stajsiz.",
      timeline: [
        {
          y: "yanv 2026 — hozir",
          role: "AI-first Developer · Full-stack Developer",
          org: "TTYL",
          tag: "main",
          points: [
            "BelfProctor'ni qurdim — xodimlar faolligi va ish sifatini kuzatish tizimi.",
            "TTYL Platform'ni ishlab chiqdim — himoyalangan local platforma: vazifalar, chat, fayl almashish.",
            "Ikkala tizimning frontend va backend qismini yurituvchiman, deploy va prod-baglarni ham.",
          ],
          stack: ["TypeScript", "Next.js", "NestJS", "PostgreSQL", "Docker"],
        },
        {
          y: "2025 — hozir",
          role: "Mustaqil va tijorat loyihalari",
          org: "Mustaqil amaliyot",
          tag: "product",
          points: [
            "Klawis — huquqiy AI-mahsulot: RAG, manba ko'rsatish, klawis.uz'da live.",
            "CoupleOS / Softly — juftliklar uchun iste'mol mahsuloti, SoftlyLove.uz'da live.",
            "Task Manage Bot, Sentinel Edge, Marketbot — Telegram-avtomatlashtirish, embedded/IoT, event-driven backend.",
          ],
          stack: ["Python", "FastAPI", "Rust", "Arduino C++", "RAG"],
        },
        {
          y: "yanv 2023 — apr 2023",
          role: "Ishonch telefoni operatori",
          org: "UniCall",
          tag: "start",
          points: [
            "Mijozlarga maslahat berdim, muammolarini hal qildim, CRM'da yozib bordim.",
            "Muloqot sifati uchun oyning eng yaxshi xodimi deb topildim.",
            "Mijozlar bilan birinchi tizimli tajriba — hozir loyihalarni yuritishga yordam beradi.",
          ],
          stack: [],
        },
      ],
      edu_title: "Ta'lim",
      edu: [
        { y: "2028", k: "Software Engineering bakalavriati · IT Park University (3-kurs)" },
      ],
      readme: {
        intro: "Fulstek-dasturchi, AI Automation Developer va prompt-muhandis. IT Park University'da Software Engineering 3-kursida o'qiyman va parallel ravishda real mahsulotlar quraman: veb-platformalar, Telegram-botlar, AI-avtomatlashtirishlar, ichki tizimlar va admin-panellar.",
        intro2: "Kuchli tomonim — dasturlash, mahsulot yondashuvi va biznes-mantiqni birlashtirish. Shunchaki vazifa bo'yicha kod yozmayman, balki mahsulot qanday muammoni yechishini va ishchi versiyani tezroq qanday ishga tushirishni tushunaman.",
        build_title: "nima qila olaman",
        build: [
          "Fulstek — frontend, backend, DB, avtorizatsiya, API, admin-panel, dashboard, integratsiya, deploy",
          "Backend va arxitektura — biznes-mantiq, REST, navbatlar, rollar va kirish, fayl tizimlari, Docker",
          "AI va avtomatlashtirish — OpenAI/Claude API, RAG, strukturaviy javoblar, AI-worker, Telegram-workflow",
          "Prompt-muhandislik — tizim ko'rsatmalari, gallyutsinatsiyani kamaytirish, sifat nazorati",
          "Telegram-botlar — vazifalar, eslatmalar, ovoz bilan ishlash, statuslar, avtomatlashtirish",
          "Mahsulot va UI/UX — vazifani tushunish, MVP yig'ish, foydalanuvchi yo'lini o'ylash",
        ],
        avail_title: "ish formati",
        avail: "Full-time, amaliyot, freelance va mahsulot hamkorliklariga ochiqman. Eng kuchli — tezlik, muhandislik aniqligi va g'oyani natijaga yetkazish muhim bo'lgan joyda.",
        proof_title: "jonli isbot",
        proof: [
          { k: "klawis.uz", v: "Legal AI · RAG · manbalar", url: "https://klawis.uz" },
          { k: "softlylove.uz", v: "juftliklar uchun mahsulot · live", url: "https://softlylove.uz" },
          { k: "github", v: "ochiq kod + CI", url: "https://github.com/SamandarMansurkhodjaev2713" },
        ],
      },
    },
    process: {
      eyebrow: "Metod",
      title: "Qanday ishlayman",
      lead: "Birinchi qo'ng'iroqdan saturday-night-prod gacha bitta quvur.",
      steps: [
        { k: "Discovery", v: "Biznes maqsad, metrikalar, cheklovlar" },
        { k: "Arxitektura", v: "Stek, kontraktlar, risklar" },
        { k: "Prototip", v: "Asosiy stsenariylar uchun klikabel proto" },
        { k: "UI / UX", v: "Mahsulot uchun dizayn, Behance uchun emas" },
        { k: "Ishlab chiqish", v: "Toza stek, tiplar, kritik yo'lda testlar" },
        { k: "AI Avtomatlashtirish", v: "LLM qatlami, retrieval, evals" },
        { k: "Test", v: "QA, yuklama, edge-keyslar" },
        { k: "Deploy", v: "CI/CD, monitoring, alertlar" },
        { k: "Qo'llab-quvvatlash", v: "Reliz keyingi barqarorlik va o'sish" },
      ],
      cli_eyebrow: "live · deploy oqimi",
      cli_title: "system.live",
      cli_lead: "Production muhitining haqiqiy hodisalari, har ~20 soniyada yangilanadi.",
      cli_sessions: [
        {
          title: "ops — stripe checkout · v2.4.1",
          steps: [
            { kind: "prompt", text: "deploy stripe-checkout v2.4.1 → prod" },
            { kind: "thinking", durationMs: 1500 },
            { kind: "tool", name: "build", arg: "next build · 32 routes · 1.8 MB" },
            { kind: "tool", name: "test",  arg: "vitest · 184 passed · 92% coverage" },
            { kind: "tool", name: "scan",  arg: "snyk · 0 vulnerabilities" },
            { kind: "tool", name: "push",  arg: "registry.fly.io · sha 8f2c1a" },
            { kind: "tool", name: "rollout", arg: "fly machines · canary 10% → 100%" },
            { kind: "output", text: "  health-check 200 · p95 latency 84ms" },
            { kind: "done", text: "✓ deployed · 3m 14s · zero downtime" },
          ],
        },
        {
          title: "ops — telegram voice-task-bot · v1.7.0",
          steps: [
            { kind: "prompt", text: "ship voice-task-bot v1.7.0 → prod" },
            { kind: "thinking", durationMs: 1700 },
            { kind: "tool", name: "build", arg: "docker · python:3.12-slim · 184 MB" },
            { kind: "tool", name: "test",  arg: "pytest · 47 passed · whisper-1 · gpt-4o" },
            { kind: "tool", name: "push",  arg: "ghcr.io/ops/voicebot:1.7.0" },
            { kind: "tool", name: "rollout", arg: "k8s · 3 replicas · rolling update" },
            { kind: "output", text: "  webhook latency p50 220ms · queue 0" },
            { kind: "done", text: "✓ deployed · 2m 41s · 100% healthy" },
          ],
        },
        {
          title: "ops — lead-classification pipeline · v3.1.0",
          steps: [
            { kind: "prompt", text: "promote lead-classifier v3.1.0 → prod" },
            { kind: "thinking", durationMs: 1300 },
            { kind: "tool", name: "build", arg: "modal.app · python · 96 MB" },
            { kind: "tool", name: "eval",  arg: "240 leads · precision 0.94 · recall 0.91" },
            { kind: "tool", name: "push",  arg: "modal-labs · v3.1.0" },
            { kind: "tool", name: "rollout", arg: "n8n workflow · 3 nodes updated" },
            { kind: "output", text: "  ingest rate 412 leads/min · cost $0.0008/lead" },
            { kind: "done", text: "✓ deployed · 1m 58s · CRM in sync" },
          ],
        },
      ],
    },
    builder: {
      eyebrow: "Konstruktor",
      title: "Loyihangizni yig'ing",
      lead: "Tur va ko'lamni tanlang — arxitektura ko'z oldingizda yig'iladi, stek va taxminiy muddat/byudjet bilan.",
      step1: "Nima quramiz",
      step2: "Ko'lam",
      types: [
        { k: "web", label: "Veb-ilova", note: "mahsulot · SaaS · portal" },
        { k: "ai", label: "AI-vosita", note: "LLM · RAG · agentlar" },
        { k: "bot", label: "Telegram-bot", note: "savdo · vazifa · servis" },
        { k: "automation", label: "Avtomatlashtirish", note: "integratsiya · pipeline" },
      ],
      scales: [
        { k: "mvp", label: "MVP", note: "g'oyani tekshirish" },
        { k: "prod", label: "Produkshn", note: "ishchi tizim" },
        { k: "product", label: "To'liq mahsulot", note: "kalitni topshirish" },
      ],
      layers: { client: "Mijoz", logic: "Mantiq", ai: "Intellekt", data: "Ma'lumot", infra: "Infratuzilma" },
      sub: { frontend: "Frontend", telegram: "Telegram", triggers: "Triggerlar", api: "API", bot: "Bot mantig'i", pipeline: "Pipeline", ai: "AI qatlami" },
      readout: { stack: "Stek", time: "Muddat", budget: "Byudjet" },
      times: { mvp: "1–2 hafta", prod: "3–5 hafta", product: "1.5–3 oy" },
      step3: "Nima muhim",
      priorities: [
        { k: "speed", label: "Tezlik", note: "imkon qadar tez ishga tushirish" },
        { k: "design", label: "Dizayn", note: "premium interfeys, animatsiya" },
        { k: "ai", label: "AI chuqurligi", note: "evallar, ma'noli qidiruv" },
        { k: "scale", label: "Yuklama", note: "navbatlar, kesh, masshtab" },
      ],
      verdictLead: { web: "Mahsulot veb-steki", ai: "Retrieval bilan AI-mahsulot", bot: "Navbatlardagi Telegram-servis", automation: "Hodisaviy avtomatlashtirish" },
      verdictTail: { speed: "tez ishga tushirishga moslangan — kamroq qatlam, ko'proq tezlik", design: "dizayn va interfeys animatsiyasiga urg'u bilan", ai: "chuqur AI qatlami bilan: evallar, vektor qidiruv, sifat nazorati", scale: "yuklamaga mo'ljallangan: navbatlar, kesh, gorizontal masshtab" },
      layerNote: { client: "foydalanuvchi ko'radigan narsa", logic: "qoidalar, API, biznes-mantiq", ai: "LLM, ma'noli qidiruv, evallar", data: "saqlash va holat", infra: "deploy, kirish, monitoring" },
      metric: { layers: "qatlam", modules: "modul" },
      cta_tg: "Telegramda gaplashish",
      cta_form: "Arizaga o'tkazish",
      hint: "Taxminiy, aniq smeta emas — qisqa suhbatdan keyin aniq raqamlar.",
    },
    faq: {
      eyebrow: "FAQ",
      title: "Tez-tez so'raladigan savollar",
      lead: "Qisqacha — boshlashdan oldin odatda so'raladigan savollar.",
      items: [
        {
          q: "Loyiha qancha turadi?",
          a: "Hajmga bog'liq — bir necha kunlik oddiy landingdan tortib, AI-qatlamli to'liq mahsulotgacha oylab davom etishi mumkin. Qisqa suhbatdan so'ng byudjet va muddat bo'yicha aniq vilkani beraman, yashirin ustama yo'q.",
        },
        {
          q: "Ishlab chiqish qancha vaqt oladi?",
          a: "Tez va AI-vositalar bilan ishlayman: landing — bir necha kun, MVP — 1–2 hafta, backend va AI-qatlamli mahsulot — ~1.5 oydan. Aniq muddatni qisqa discovery bosqichidan keyin belgilayman.",
        },
        {
          q: "Yolg'iz ishlaysizmi yoki bu studiyami?",
          a: "Yolg'iz — dizayndan deployga va qo'llab-quvvatlashgacha. Siz bilan dasturchi orasida hech qanday vositachi yo'q, agentlik ustamasi yo'q. Katta hajm uchun aniq vazifalarga tekshirilgan mutaxassislarni jalb qilaman, lekin natija uchun men javobgarman.",
        },
        {
          q: "Menda texnik topshiriq yo'q — bu muammomi?",
          a: "Yo'q. Ko'pchilik g'oya bilan keladi, TT bilan emas. Maqsad, cheklovlar va byudjetni muhokama qilamiz — arxitektura va rejani o'zim tuzaman, bu ishning qismi, alohida xizmat emas.",
        },
        {
          q: "To'lov qanday amalga oshiriladi?",
          a: "Odatda bosqichma-bosqich: boshlashdan oldin avans, qolgani — asosiy bosqichlar yoki loyiha yakunlangandan keyin. Shartlar ish boshlanishidan oldin yozma tarzda belgilanadi.",
        },
        {
          q: "Ishga tushirilgandan keyin qo'llab-quvvatlash bormi?",
          a: "Ha. Relizdan keyingi dastlabki qo'llab-quvvatlash loyihaga kiritilgan, keyin — soatlik yordam yoki kelishuv asosida qo'shimcha ishlar.",
        },
        {
          q: "Qachon boshlash mumkin?",
          a: "Odatda tafsilotlar kelishilgandan so'ng bir necha kun ichida boshlashga tayyorman. Muddatlarni muhokama qilishning eng tez yo'li — Telegram.",
        },
      ],
    },
    trust: {
      eyebrow: "Trust",
      title: "Jamoalar nima deydi",
      lead: "Birga ishlagan odamlardan.",
      kQuotes: "iqtiboslar",
      kRoles: "rollar",
      kSpan: "davr",
      note: "illyustrativ — haqiqiy fikrlar tez orada",
      items: [
        {
          q: "Birinchi uchrashuvga arxitektura qoralamasini olib keldi. Bir oydan keyin birinchi versiya ishlay boshladi — boshqa pudratchi shishirib yuborgan qamrovsiz.",
          who: "Product Lead",
          role: "Logistika kompaniyasi · 2025",
        },
        {
          q: "AI-integratsiya 8 oydan beri prodda ishlaydi. Gallyutsinatsiyalarsiz, metrikalar bilan, graceful-fallback bilan. Bu — asbob, demo emas.",
          who: "CTO",
          role: "SaaS-startap · 2024",
        },
        {
          q: "Telegram-bot har bir menejerga kuniga ikki ish soatini qaytarib berdi. Ikki haftada qildi, bir oyda o'zini qoplab oldi.",
          who: "Founder",
          role: "B2B xizmat · 2024",
        },
      ],
    },
    contact: {
      eyebrow: "Deploy so'rovi",
      title: "Loyihani ishga tushiramiz",
      lead: "Vazifani tasvirlang — 24 soat ichida arxitektura eskizi va baho bilan qaytaman.",
      form: {
        name: "Ism",
        email: "Email yoki Telegram",
        scope: "Sizga nima kerak",
        budget: "Byudjet",
        timeline: "Muddat",
        msg: "Nima muhim",
        msg_placeholder: "Maqsad, kontekst, cheklovlar. Iloji boricha qisqa.",
        submit: "So'rovni yuborish",
        sending: "Yuborilmoqda…",
        sent: "So'rov qabul qilindi. 24 soat ichida bog'lanaman.",
        error: "Yuborib bo'lmadi. Telegram'ga yozing — tezroq javob beraman.",
      },
      scope_opts: ["Web App / MVP", "AI Avtomatlashtirish", "Telegram Bot", "Dashboard / CRM", "Landing", "Konsalting"],
      timeline_opts: ["ASAP", "1–2 hafta", "1–2 oy", "moslashuvchan"],
      links: [
        { k: "Telegram", v: "t.me/killallofthem13" },
        { k: "GitHub", v: "github.com/SamandarMansurkhodjaev2713" },
        { k: "Email", v: "sam4k27@gmail.com" },
      ],
    },
    footer: { copy: "© 2026 — Executive AI Code Lab", built: "TypeScript, Three.js, React asosida" },
  },
};

window.CONTENT = CONTENT;
