// content.jsx — i18n content config (RU/EN/UZ)
// Replace placeholder values to ship real CV. Keys are 1:1 across languages.

const CONTENT = {
  ru: {
    nav: {
      about: "О себе",
      projects: "Проекты",
      skills: "Стек",
      services: "Услуги",
      cv: "Опыт",
      faq: "Вопросы",
      contact: "Контакт",
      skip: "К содержимому",
    },
    hero: {
      eyebrow: "Executive AI Code Lab — v.2026",
      name: "Samandar",
      title_lines: ["Full-stack.", "AI Automation.", "Product Engineer."],
      tagline:
        "Превращаю задачу бизнеса в работающий продукт — и сам отвечаю за его качество. Дизайн, код, AI, тесты — без посредников.",
      cta_primary: "Обсудить проект",
      cta_secondary: "Смотреть работы",
      status: "доступен для проектов",
      boot_lines: [
        "init core.engine ... ok",
        "load /modules/full-stack ... ok",
        "load /modules/ai-automation ... ok",
        "compile portfolio.v26 ... ok",
        "deploy READY",
      ],
    },
    signal: {
      eyebrow: "10-second signal",
      title: "Почему со мной",
      cards: [
        { code: "01", k: "Полный цикл", v: "Дизайн, фронт, бэк, деплой — один человек, без передач между подрядчиками", tail: "один за всё" },
        { code: "02", k: "AI внутри продукта", v: "AI — ядро системы, а не витрина: RAG, агенты, контроль качества", tail: "не для вида" },
        { code: "03", k: "Живые продукты", v: "В проде, с реальными пользователями — klawis.uz, softlylove.uz", tail: "в проде" },
        { code: "04", k: "Без прослойки", v: "Работаете напрямую со мной — без агентской наценки и испорченного телефона", tail: "напрямую" },
        { code: "05", k: "Быстрый запуск", v: "MVP за недели: AI-инструменты и опыт вместо раздутых сроков", tail: "недели, не кварталы" },
        { code: "06", k: "Отвечаю за результат", v: "Не «сдал и пропал»: тесты, CI, контроль регрессий — довожу до рабочего продукта и держу планку", tail: "до результата" },
      ],
    },
    about: {
      eyebrow: "Profile",
      title: "Беру задачу — отдаю работающий продукт",
      lead:
        "Один разработчик отвечает за весь стек: фронт, бэк, AI, инфраструктура. Без передач между подрядчиками — без потерь в переводе.",
      paragraphs: [
        "Выбираю стек под задачу, а не под трендах. Архитектура — простая, чтобы её можно было поддерживать через год.",
        "AI — не как демо, а как часть продукта: интеграция LLM, агенты, RAG, оценки качества.",
      ],
      stats: [
        { v: "1.5+ года", k: "в разработке" },
        { v: "10+", k: "проектов" },
        { v: "3 курс", k: "Software Engineering" },
        { v: "RU / UZ / EN", k: "языки работы" },
      ],
      status_label: "Доступен · удалённо · контракт и фуллтайм",
      currently_label: "Сейчас",
      currently: [
        "веду QA и full-stack на TTYL Platform",
        "публичное QA-портфолио: test design, API, SQL",
        "dostupnoe-pravo — legal-проект на TypeScript",
        "CardioGuard — cross-platform health-tech",
      ],
      recent_label: "Недавние коммиты",
      recent: [
        { when: "2 д", tag: "feat", msg: "qa-portfolio — test design, API, SQL, automation" },
        { when: "2 д", tag: "feat", msg: "dostupnoe-pravo — legal-платформа на TypeScript" },
        { when: "3 д", tag: "feat", msg: "cardioguard — health-tech, RN + Kotlin" },
      ],
      contrib_label: "Активность · 12 недель",
      gh_stats: "10+ проектов · публичный код и NDA-кейсы · Ташкент",
    },
    projects: {
      eyebrow: "Selected work",
      title: "Избранные проекты",
      items: [
        {
          tag: "AI · LEGAL",
          name: "Klawis — Legal AI Assistant",
          problem: "Юридические чат-боты отвечают гладко, но без источников и проверяемости.",
          solution: "Live AI-продукт с RAG, юридическим роутингом и цитированием источников.",
          role: "Founder + Lead Developer",
          stack: ["FastAPI", "Next.js", "Supabase", "RAG"],
          outcome: "живой продукт на klawis.uz",
          status: "LIVE",
          url: "https://klawis.uz",
        },
        {
          tag: "CONSUMER · FOUNDER",
          name: "CoupleOS / Softly",
          problem: "Отношениям не хватает мягкой структуры — ритуалов и безопасного пространства.",
          solution: "Mobile-first продукт для пар: приватные флоу, привычки, воспоминания.",
          role: "Founder + Full-stack",
          stack: ["Next.js", "Supabase", "PWA"],
          outcome: "живой продукт на SoftlyLove.uz",
          status: "LIVE",
          url: "https://softlylove.uz",
        },
        {
          tag: "ENTERPRISE · ON-PREM",
          name: "TTYL Platform",
          problem: "Команде нужны collaboration-инструменты без передачи данных во внешний SaaS.",
          solution: "Self-hosted workspace: проекты, чаты, файлы, поиск, audit, realtime, RBAC.",
          role: "Architect + Lead Developer",
          stack: ["NestJS", "Next.js", "PostgreSQL", "Redis", "MinIO"],
          outcome: "on-prem развёртывание для закрытого контура",
          status: "NDA",
          url: "projects/ttyl/",
        },
        {
          tag: "TELEGRAM · RUST",
          name: "Task-manager / Task Manage Bot",
          problem: "Задачи из чатов и голосовых сообщений теряются без структуры.",
          solution: "Rust-бот с очередью задач, напоминаниями, retry и AI-обработкой голоса.",
          role: "Lead Developer",
          stack: ["Rust", "Teloxide", "SQLx", "GitHub Actions"],
          outcome: "публичный репозиторий + CI",
          status: "PROD",
          url: "projects/task-manager/",
        },
        {
          tag: "COMMERCE · EVENTS",
          name: "Marketbot",
          problem: "Офферам, подпискам и affiliate-ссылкам нужна доставка без ручной рутины.",
          solution: "Event-driven backend на очередях: ingestion, подписки, уведомления, админка.",
          role: "Backend Architect",
          stack: ["Python", "gRPC", "RabbitMQ", "Telegram"],
          outcome: "операционная панель для бизнеса",
          status: "NDA",
          url: "projects/marketbot/",
        },
        {
          tag: "IOT · EMBEDDED",
          name: "Sentinel Edge",
          problem: "Большинство embedded-демо заканчиваются выводом данных с датчика.",
          solution: "Firmware + serial-протокол + Node-мост + realtime React-дашборд.",
          role: "Full-stack + Firmware",
          stack: ["Arduino C++", "Node.js", "React", "WebSocket"],
          outcome: "публичный репозиторий + live-дашборд",
          status: "PROD",
          url: "https://samandarmansurkhodjaev2713.github.io/sentinel-edge-smart-system/",
        },
        {
          tag: "HEALTH-TECH · MOBILE",
          name: "CardioGuard",
          problem: "Кардиометаболический риск теряется между разрозненными замерами и бумажными выписками.",
          solution: "Кросс-платформенное приложение: доменная логика оценки риска, i18n RU/UZ, PDF-отчёты, офлайн.",
          role: "Full-stack + Domain",
          stack: ["React Native", "Expo", "TypeScript", "Jest"],
          outcome: "публичный репозиторий + live-демо",
          status: "DEMO",
          url: "https://samandarmansurkhodjaev2713.github.io/cardioguard/",
        },
        {
          tag: "INDUSTRIAL · TELEMETRY",
          name: "BioFlux Observer",
          problem: "Биогаз-станции нужен живой контроль потока, тревог и отчётности — вместо ручных таблиц.",
          solution: "Прототип телеметрического дашборда: метрики в реальном времени, пороги-алармы, отчёты для инвесторов.",
          role: "Frontend + Data",
          stack: ["React", "Recharts", "TypeScript", "Vite"],
          outcome: "промышленный дашборд-прототип",
          status: "PROTO",
          url: "projects/bioflux/",
        },
        {
          tag: "EDTECH · AI-NATIVE",
          name: "Forge / Learning OS",
          problem: "Learning-платформы продают контент, но не показывают реальный навык человека.",
          solution: "AI-native платформа, где обучение превращается в доказательства: миссии, gates, портфолио-кейсы, client-офферы.",
          role: "Founder + Product Engineer",
          stack: ["Next.js 15", "React 19", "Prisma", "Auth.js", "Zod"],
          outcome: "сильная доменная модель, product-first",
          status: "NDA",
          url: "projects/forge/",
        },
        {
          tag: "PROCTORING · DESKTOP",
          name: "BelfProctor",
          problem: "Прокторинг — это не веб-форма: нужен устанавливаемый агент, heartbeat, защищённая телеметрия, admin-контроль.",
          solution: "Windows client-agent + ingestion API + admin-панель: события, статусы, retries, политика мониторинга.",
          role: "Backend + Systems",
          stack: ["C#", "Node.js", "Express", "PostgreSQL", "React"],
          outcome: "система за пределами web, sensitive-данные",
          status: "NDA",
          url: "projects/belfproctor/",
        },
        {
          tag: "AUTOMATION · BROWSER",
          name: "VFS Killer",
          problem: "Браузерные воркфлоу ломаются от таймингов, сессий, прокси и anti-automation — «скрипт с кликами» не выживает.",
          solution: "Browser-automation с diagnostics-first подходом: управление через Telegram, retries, скриншоты, Docker-runtime.",
          role: "Automation Engineer",
          stack: ["Python", "Playwright", "aiogram", "Docker"],
          outcome: "надёжная автоматизация в ломких условиях",
          status: "NDA",
          url: "projects/vfs-killer/",
        },
        {
          tag: "HEALTH-TECH · DESKTOP",
          name: "med-exe",
          problem: "В медицинских расчётах нельзя «примерно работает» — нужны детерминизм, приватность, offline и точность.",
          solution: "Offline desktop-приложение: Rust-ядро с расчётной логикой, Tauri-оболочка, typed IPC, локальный SQLite.",
          role: "Desktop + Core",
          stack: ["Rust", "Tauri", "React", "SQLite"],
          outcome: "offline-first, точность важнее скорости",
          status: "NDA",
          url: "projects/med-exe/",
        },
        {
          tag: "FRONTEND · WEBGL",
          name: "3D Landing",
          problem: "Портфолио-страницы часто статичны и не производят впечатления.",
          solution: "Интерактивный Three.js/WebGL лендинг: 3D-сцена, motion, адаптив, performance-aware реализация.",
          role: "Frontend + Visual",
          stack: ["Three.js", "WebGL", "Vite"],
          outcome: "живое демо на GitHub Pages",
          status: "LIVE",
          url: "https://samandarmansurkhodjaev2713.github.io/3d-landing/",
        },
      ],
      cta: "Смотреть кейс",
    },
    skills: {
      eyebrow: "Stack radar",
      title: "Технический стек",
      lead: "Не зоопарк логотипов — сетка инструментов, которыми реально работаю: full-stack, AI и QA-инженерия.",
      groups: [
        { k: "Frontend", slug: "frontend", items: ["TypeScript", "React", "Next.js", "Vite", "Tailwind", "Three.js"] },
        { k: "Backend", slug: "backend", items: ["Python", "FastAPI", "Node.js", "NestJS", "Rust", "REST · WebSocket"] },
        { k: "AI / Автоматизация", slug: "ai", items: ["OpenAI", "Gemini", "Claude", "RAG", "pgvector", "Telegram-боты"] },
        { k: "Данные / Инфра", slug: "data", items: ["PostgreSQL", "Supabase", "Redis", "Prisma", "SQLx", "Docker"] },
        { k: "Mobile / Desktop / IoT", slug: "mobile", items: ["React Native", "Expo", "Kotlin", "Tauri", "Arduino C++"] },
        { k: "QA-инженерия", slug: "qa", items: ["Test Design", "Playwright", "pytest", "xUnit/Moq", "GitHub Actions", "REST API"] },
      ],
    },
    services: {
      eyebrow: "Services",
      title: "Что можно заказать",
      items: [
        { k: "Web Apps", v: "Полноценные продукты, MVP, SaaS-приложения", io: "spec → prod app" },
        { k: "Landing & Sites", v: "Премиум-лендинги, корпоративные и продуктовые", io: "brief → site" },
        { k: "Telegram Bots", v: "Боты для команд, продаж, автоматизации", io: "task → bot" },
        { k: "AI Automation", v: "Workflow с LLM, агентами, обработкой данных", io: "process → engine" },
        { k: "Dashboards", v: "Админ-панели, CRM, операционные дашборды", io: "data → ops view" },
        { k: "MVP / Prototype", v: "От идеи до работающего прототипа за недели", io: "idea → demo" },
        { k: "Internal Tools", v: "CRM, кабинеты, инструменты для команды", io: "team → tool" },
        { k: "Tech Consulting", v: "Архитектура, аудит, стек, тех-стратегия", io: "question → plan", covers: ["Архитектура и ревью решений", "Выбор стека и технический аудит", "Техстратегия и план запуска"] },
      ],
    },
    cv: {
      eyebrow: "Experience",
      title: "CV / Опыт",
      lead: "Честный список того, что я сделал — без раздутого стажа.",
      timeline: [
        {
          y: "дек 2025 — сейчас",
          role: "QA Engineer · Full-stack Developer",
          org: "TTYL",
          tag: "main",
          points: [
            "TTYL Platform — защищённая локальная платформа (задачи, чат, файлообмен): веду фронтенд и бэкенд, деплой и багфиксы в проде.",
            "QA обеих систем: test plans, чек-листы, Playwright E2E со скриншотами и traces, контроль регрессий перед релизом.",
            "BelfProctor — система учёта активности сотрудников: клиентская часть, серверная логика и обработка данных (xUnit/Moq).",
          ],
          stack: ["TypeScript", "Next.js", "NestJS", "PostgreSQL", "Playwright", "Docker"],
        },
        {
          y: "2025 — сейчас",
          role: "Независимые и коммерческие проекты",
          org: "Собственная практика",
          tag: "product",
          points: [
            "Klawis — AI-продукт для юридической сферы: RAG, цитирование источников, live на klawis.uz.",
            "CoupleOS / Softly — потребительский продукт для пар, live на SoftlyLove.uz.",
            "Task Manage Bot, Sentinel Edge, Marketbot — Telegram-автоматизация, embedded/IoT, event-driven backend.",
          ],
          stack: ["Python", "FastAPI", "Rust", "Arduino C++", "RAG"],
        },
        {
          y: "янв 2023 — апр 2023",
          role: "Специалист по работе с клиентами",
          org: "UniCall",
          tag: "start",
          points: [
            "Консультировал клиентов, решал вопросы, вёл записи в CRM.",
            "Признан лучшим сотрудником месяца за качество коммуникации.",
            "Первый системный опыт работы с клиентами — сейчас помогает вести заказчиков.",
          ],
          stack: [],
        },
      ],
      edu_title: "Образование",
      edu: [
        { y: "2028", k: "Бакалавр Software Engineering · IT Park University (3 курс)" },
      ],
      readme: {
        intro: "Full-stack и AI-разработчик с сильной QA-стороной. Учусь на 3 курсе Software Engineering в IT Park University, работаю QA + full-stack на TTYL Platform и параллельно строю собственные продукты: веб-приложения, Telegram-ботов, AI-инструменты, health-tech и IoT.",
        intro2: "Сильная сторона — соединять разработку, продукт и качество. Не просто пишу код по задаче: разбираюсь, какую проблему решает продукт, где сломается процесс, и довожу до рабочей версии без регрессий.",
        build_title: "что я умею",
        build: [
          "Full-stack — frontend, backend, БД, авторизация, API, дашборды, интеграции, деплой",
          "Backend и архитектура — бизнес-логика, REST/WebSocket, очереди, роли и доступы, файлы, Docker",
          "AI и автоматизация — OpenAI/Gemini/Claude, RAG, pgvector, AI-агенты, Telegram-воркфлоу",
          "QA — test plans, Playwright E2E, pytest, xUnit/Moq, CI/CD, контроль регрессий",
          "Mobile / Desktop / IoT — React Native, Expo, Kotlin, Tauri, Arduino C++",
          "Продукт и UI/UX — разобраться в задаче, собрать MVP, продумать путь пользователя",
        ],
        avail_title: "формат работы",
        avail: "Открыт к full-time, стажировкам, freelance и продуктовым коллаборациям. Сильнее всего там, где важны скорость, инженерная аккуратность, качество и умение довести идею до результата.",
        proof_title: "живые доказательства",
        proof: [
          { k: "klawis.uz", v: "Legal AI · RAG · источники", url: "https://klawis.uz" },
          { k: "softlylove.uz", v: "продукт для пар · live", url: "https://softlylove.uz" },
          { k: "github", v: "публичный код + CI", url: "https://github.com/SamandarMansurkhodjaev2713" },
        ],
      },
    },
    process: {
      eyebrow: "Method",
      title: "Как я работаю",
      lead: "Один пайплайн от первого звонка до saturday-night-prod.",
      steps: [
        { k: "Discovery", v: "Бизнес-цель, метрики, ограничения", out: "бриф + критерии готовности" },
        { k: "Architecture", v: "Стек, контракт, риски", out: "схема системы + API-контракт" },
        { k: "Prototype", v: "Кликабельный прототип ключевых сценариев", out: "интерактивный прототип" },
        { k: "UI / UX", v: "Дизайн под продукт, не под Behance", out: "макеты и UI-компоненты" },
        { k: "Development", v: "Чистый стек, типизация, тесты на критическом пути", out: "рабочий код в репозитории" },
        { k: "AI Automation", v: "LLM-слой, ретривал, эвалы", out: "AI-функции с оценкой качества" },
        { k: "Testing", v: "QA, нагрузка, edge-кейсы", out: "прогон тестов + отчёт" },
        { k: "Deploy", v: "CI/CD, мониторинг, алерты", out: "прод + пайплайн релизов" },
        { k: "Support", v: "Стабилизация и развитие после релиза", out: "сопровождение и итерации" },
      ],
      cli_eyebrow: "live · поток деплоев",
      cli_title: "system.live",
      cli_lead: "Реальные события прод-окружения, обновляются каждые ~20 секунд.",
      cli_sessions: [
        {
          title: "ops — stripe checkout · v2.4.1",
          steps: [
            { kind: "prompt", text: "deploy stripe-checkout v2.4.1 → prod" },
            { kind: "thinking", durationMs: 1500 },
            { kind: "tool", name: "build", arg: "next build · 32 routes · 1.8 MB" },
            { kind: "tool", name: "test",  arg: "vitest · 184 passed · 92% coverage" },
            { kind: "tool", name: "scan",  arg: "snyk · 0 vulnerabilities" },
            { kind: "tool", name: "push",  arg: "registry.fly.io · sha 8f2c1a" },
            { kind: "tool", name: "rollout", arg: "fly machines · canary 10% → 100%" },
            { kind: "output", text: "  health-check 200 · p95 latency 84ms" },
            { kind: "done", text: "✓ deployed · 3m 14s · zero downtime" },
          ],
        },
        {
          title: "ops — telegram voice-task-bot · v1.7.0",
          steps: [
            { kind: "prompt", text: "ship voice-task-bot v1.7.0 → prod" },
            { kind: "thinking", durationMs: 1700 },
            { kind: "tool", name: "build", arg: "docker · python:3.12-slim · 184 MB" },
            { kind: "tool", name: "test",  arg: "pytest · 47 passed · whisper-1 · gpt-4o" },
            { kind: "tool", name: "push",  arg: "ghcr.io/ops/voicebot:1.7.0" },
            { kind: "tool", name: "rollout", arg: "k8s · 3 replicas · rolling update" },
            { kind: "output", text: "  webhook latency p50 220ms · queue 0" },
            { kind: "done", text: "✓ deployed · 2m 41s · 100% healthy" },
          ],
        },
        {
          title: "ops — lead-classification pipeline · v3.1.0",
          steps: [
            { kind: "prompt", text: "promote lead-classifier v3.1.0 → prod" },
            { kind: "thinking", durationMs: 1300 },
            { kind: "tool", name: "build", arg: "modal.app · python · 96 MB" },
            { kind: "tool", name: "eval",  arg: "240 leads · precision 0.94 · recall 0.91" },
            { kind: "tool", name: "push",  arg: "modal-labs · v3.1.0" },
            { kind: "tool", name: "rollout", arg: "n8n workflow · 3 nodes updated" },
            { kind: "output", text: "  ingest rate 412 leads/min · cost $0.0008/lead" },
            { kind: "done", text: "✓ deployed · 1m 58s · CRM in sync" },
          ],
        },
      ],
    },
    builder: {
      eyebrow: "Конструктор",
      title: "Соберите свой проект",
      lead: "Выберите тип и масштаб — на глазах соберётся архитектура, стек и ориентир по срокам и бюджету.",
      step1: "Что строим",
      step2: "Масштаб",
      types: [
        { k: "web", label: "Веб-приложение", note: "продукт · SaaS · портал" },
        { k: "ai", label: "AI-инструмент", note: "LLM · RAG · агенты" },
        { k: "bot", label: "Telegram-бот", note: "продажи · задачи · сервис" },
        { k: "automation", label: "Автоматизация", note: "интеграции · пайплайны" },
      ],
      scales: [
        { k: "mvp", label: "MVP", note: "проверить идею" },
        { k: "prod", label: "Продакшн", note: "рабочая система" },
        { k: "product", label: "Продукт с нуля", note: "всё под ключ" },
      ],
      layers: { client: "Клиент", logic: "Логика", ai: "Интеллект", data: "Данные", infra: "Инфраструктура" },
      sub: { frontend: "Frontend", telegram: "Telegram", triggers: "Триггеры", api: "API", bot: "Бот-логика", pipeline: "Пайплайн", ai: "AI-слой" },
      readout: { stack: "Стек", time: "Срок", budget: "Бюджет" },
      times: { mvp: "1–2 недели", prod: "3–5 недель", product: "1.5–3 месяца" },
      step3: "Что критично",
      priorities: [
        { k: "speed", label: "Скорость", note: "запуск как можно раньше" },
        { k: "design", label: "Дизайн", note: "премиум-интерфейс, анимации" },
        { k: "ai", label: "AI-глубина", note: "эвалы, поиск по смыслу" },
        { k: "scale", label: "Нагрузка", note: "очереди, кэш, масштаб" },
      ],
      verdictLead: { web: "Продуктовый веб-стек", ai: "AI-продукт с ретривалом", bot: "Telegram-сервис на очередях", automation: "Событийная автоматизация" },
      verdictTail: { speed: "заточен под быстрый запуск, меньше слоёв — больше скорости", design: "с упором на дизайн и анимацию интерфейса", ai: "с глубоким AI-слоем: эвалы, векторный поиск, контроль качества", scale: "рассчитан на нагрузку: очереди, кэш, горизонтальное масштабирование" },
      layerNote: { client: "то, что видит пользователь", logic: "правила, API, бизнес-логика", ai: "LLM, поиск по смыслу, эвалы", data: "хранение и состояние", infra: "деплой, доступ, мониторинг" },
      metric: { layers: "слоёв", modules: "модулей" },
      status: { building: "Сборка архитектуры…", ready: "Система собрана" },
      priorityDeliverable: {
        design: "Премиум-интерфейс: микроанимации и выверенные переходы",
        scale: "Готовность к нагрузке: очереди, кэш и CDN",
        ai: "Эвалы и контроль качества AI-ответов",
      },
      deliverables: {
        client: "Интерфейс и адаптив под все экраны",
        logic: "API и бизнес-логика",
        ai: "AI-слой: поиск по смыслу и контроль качества",
        data: "База данных и хранение состояния",
        infra: "Деплой, домен и мониторинг ошибок",
      },
      stages: ["Созвон", "Архитектура", "Сборка", "Запуск"],
      scopeNote: {
        mvp: "Фокус на одной ключевой гипотезе. Тяжёлые интеграции и глубокая аналитика — следующим этапом, когда идея подтвердится.",
        prod: "Полноценная рабочая система. Крупные интеграции сторонних сервисов выношу в отдельный этап со своей оценкой.",
        product: "Всё под ключ — от дизайна до продакшна. Контент и наполнение — на вашей стороне или отдельной услугой.",
      },
      lbl: { includes: "Что входит", stages: "Как идём", boundary: "Не входит в объём" },
      cta_tg: "Обсудить в Telegram",
      cta_form: "Перенести в заявку",
      hint: "Ориентир, а не смета — точные цифры после короткого созвона.",
    },
    faq: {
      eyebrow: "FAQ",
      title: "Частые вопросы",
      lead: "Коротко — то, что обычно спрашивают до старта.",
      items: [
        {
          q: "Сколько стоит проект?",
          a: "Зависит от объёма — от простого лендинга за несколько дней до полноценного продукта с AI-частью за месяцы. После короткого созвона даю вилку по деньгам и срокам, без скрытых наценок.",
        },
        {
          q: "Сколько времени займёт разработка?",
          a: "Работаю быстро и с AI-инструментами: лендинг — за несколько дней, MVP — 1–2 недели, продукт с бэкендом и AI-слоем — от 1.5 месяцев. Точный срок фиксирую после короткого discovery-этапа, не раньше.",
        },
        {
          q: "Вы работаете один или это студия?",
          a: "Один — от дизайна до деплоя и поддержки. Никакой прослойки между вами и разработчиком и никакой агентской наценки. Под большой объём точечно подключаю проверенных специалистов, но за результат отвечаю я.",
        },
        {
          q: "У меня нет технического задания — это проблема?",
          a: "Нет. Большинство приходит с идеей, а не с ТЗ. Проговариваем цель, ограничения и бюджет — архитектуру и план собираю сам, это часть работы, а не отдельная услуга.",
        },
        {
          q: "Как устроена оплата?",
          a: "Обычно поэтапно: аванс перед стартом, остаток — по завершении ключевых этапов. Условия фиксируем письменно до начала работы.",
        },
        {
          q: "Что после запуска — есть поддержка?",
          a: "Да. Раннее сопровождение после релиза включено в проект, дальше — почасовая поддержка или доработки по договорённости.",
        },
        {
          q: "Как быстро можно начать?",
          a: "Обычно готов стартовать в течение нескольких дней после согласования деталей. Быстрее всего обсудить сроки — в Telegram.",
        },
      ],
    },
    trust: {
      eyebrow: "Quality",
      title: "Качество как гарантия",
      lead: "Не «сдал и пропал». Качество встроено в процесс — вот как я держу планку на каждом проекте.",
      note: "качество по умолчанию, не по запросу",
      proof: [
        { k: "Тесты на критическом пути", v: "Playwright E2E, pytest, xUnit/Moq — со скриншотами и traces", tag: "TESTS" },
        { k: "CI/CD на каждый пуш", v: "GitHub Actions: сборка, тесты, линт — красный билд не уезжает в прод", tag: "CI", url: "https://github.com/SamandarMansurkhodjaev2713" },
        { k: "Контроль регрессий", v: "Retest фиксов и проверка отсутствия регрессий перед релизом", tag: "REGRESS" },
        { k: "Строгая типизация", v: "TypeScript и типизированные контракты — ошибки ловятся до рантайма", tag: "TYPES" },
        { k: "Наблюдаемость прода", v: "Логи, traces, мониторинг и алерты — вижу прод, а не догадываюсь", tag: "OBSERV" },
        { k: "Ревью и чистый код", v: "Code review и читаемая архитектура, которую можно поддерживать через год", tag: "REVIEW" },
      ],
    },
    contact: {
      eyebrow: "Deploy request",
      title: "Запустим проект",
      lead: "Опишите задачу — отвечу с архитектурным черновиком и оценкой за 24 часа.",
      form: {
        name: "Имя",
        email: "Email или Telegram",
        scope: "Что вам нужно",
        budget: "Бюджет",
        timeline: "Сроки",
        msg: "Что важно знать",
        msg_placeholder: "Цель, контекст, ограничения. Можно как угодно кратко.",
        submit: "Отправить запрос",
        sending: "Отправляю…",
        sent: "Запрос принят. На связи в течение 24 часов.",
        error: "Не удалось отправить. Напишите в Telegram — отвечу быстрее.",
        telegram: "В Telegram",
        copied: "Заявка скопирована — вставь в чат Telegram",
        copy: "Копировать",
      },
      scope_opts: ["Web App / MVP", "AI Automation", "Telegram Bot", "Dashboard / CRM", "Landing", "Consulting"],
      timeline_opts: ["ASAP", "1–2 недели", "1–2 месяца", "гибко"],
      links: [
        { k: "Telegram", v: "t.me/killallofthem13" },
        { k: "GitHub", v: "github.com/SamandarMansurkhodjaev2713" },
        { k: "Email", v: "sam4k27@gmail.com" },
      ],
    },
    footer: {
      copy: "© 2026 — Executive AI Code Lab",
      built: "собрано на TypeScript, Three.js, React",
      tagline: "От идеи до продукта — один инженер, полный цикл.",
      nav_title: "Навигация",
      contacts_title: "Контакты",
      meta_title: "Инфо",
      meta: ["Ташкент · UTC+5", "Ответ < 24 часов", "RU · UZ · EN (базовый)"],
    },
  },

  en: {
    nav: { about: "About", projects: "Work", skills: "Stack", services: "Services", cv: "CV", faq: "FAQ", contact: "Contact", skip: "Skip to content" },
    hero: {
      eyebrow: "Executive AI Code Lab — v.2026",
      name: "Samandar",
      title_lines: ["Full-stack.", "AI Automation.", "Product Engineer."],
      tagline:
        "I turn a business problem into a working product — and own its quality. Design, code, AI, tests — one person, no handoffs.",
      cta_primary: "Discuss a project",
      cta_secondary: "View work",
      status: "available for projects",
      boot_lines: [
        "init core.engine ... ok",
        "load /modules/full-stack ... ok",
        "load /modules/ai-automation ... ok",
        "compile portfolio.v26 ... ok",
        "deploy READY",
      ],
    },
    signal: {
      eyebrow: "10-second signal",
      title: "Why work with me",
      cards: [
        { code: "01", k: "Full cycle", v: "Design, front, back, deploy — one person, no handoffs between contractors", tail: "one owner" },
        { code: "02", k: "AI inside the product", v: "AI is the core of the system, not a showcase: RAG, agents, quality control", tail: "not for show" },
        { code: "03", k: "Live products", v: "In production, with real users — klawis.uz, softlylove.uz", tail: "in prod" },
        { code: "04", k: "No middlemen", v: "You work directly with me — no agency markup, no broken telephone", tail: "direct" },
        { code: "05", k: "Fast launch", v: "MVP in weeks: AI tooling and experience instead of padded timelines", tail: "weeks, not quarters" },
        { code: "06", k: "I own the result", v: "Not “ship and vanish”: tests, CI, regression control — I take it to a working product and hold the bar", tail: "to the result" },
      ],
    },
    about: {
      eyebrow: "Profile",
      title: "I take the brief. I ship the product.",
      lead:
        "One engineer owns the whole stack: frontend, backend, AI, infra. No vendor handoffs — nothing lost in translation.",
      paragraphs: [
        "I pick the stack the task needs, not the one that's trending. Architecture stays simple so it survives the next year.",
        "AI isn't a demo here — it ships in production. LLM integrations, agents, RAG, eval pipelines.",
      ],
      stats: [
        { v: "1.5+ yr", k: "building" },
        { v: "10+", k: "projects" },
        { v: "3rd yr", k: "Software Engineering" },
        { v: "RU / UZ / EN", k: "working languages" },
      ],
      status_label: "Available · remote · contract & full-time",
      currently_label: "Currently",
      currently: [
        "QA + full-stack on TTYL Platform",
        "public QA portfolio: test design, API, SQL",
        "dostupnoe-pravo — a legal platform in TypeScript",
        "CardioGuard — cross-platform health-tech",
      ],
      recent_label: "Recent commits",
      recent: [
        { when: "2d", tag: "feat", msg: "qa-portfolio — test design, API, SQL, automation" },
        { when: "2d", tag: "feat", msg: "dostupnoe-pravo — legal platform in TypeScript" },
        { when: "3d", tag: "feat", msg: "cardioguard — health-tech, RN + Kotlin" },
      ],
      contrib_label: "contributions · 12 weeks",
      gh_stats: "10+ projects · public code and NDA case studies · Tashkent",
    },
    projects: {
      eyebrow: "Selected work",
      title: "Featured projects",
      items: [
        {
          tag: "AI · LEGAL",
          name: "Klawis — Legal AI Assistant",
          problem: "Legal chatbots sound polished but skip sources and verifiability.",
          solution: "Live AI product with RAG, legal routing and cited sources.",
          role: "Founder + Lead Developer",
          stack: ["FastAPI", "Next.js", "Supabase", "RAG"],
          outcome: "live product at klawis.uz",
          status: "LIVE",
          url: "https://klawis.uz",
        },
        {
          tag: "CONSUMER · FOUNDER",
          name: "CoupleOS / Softly",
          problem: "Relationships need soft structure — rituals and a safe space, not a tracker.",
          solution: "Mobile-first product for couples: private flows, habits, memories.",
          role: "Founder + Full-stack",
          stack: ["Next.js", "Supabase", "PWA"],
          outcome: "live product at SoftlyLove.uz",
          status: "LIVE",
          url: "https://softlylove.uz",
        },
        {
          tag: "ENTERPRISE · ON-PREM",
          name: "TTYL Platform",
          problem: "Teams need collaboration tools without handing data to an external SaaS.",
          solution: "Self-hosted workspace: projects, chat, files, search, audit, realtime, RBAC.",
          role: "Architect + Lead Developer",
          stack: ["NestJS", "Next.js", "PostgreSQL", "Redis", "MinIO"],
          outcome: "on-prem deployment for a closed environment",
          status: "NDA",
          url: "projects/ttyl/",
        },
        {
          tag: "TELEGRAM · RUST",
          name: "Task-manager / Task Manage Bot",
          problem: "Tasks from chats and voice messages get lost without structure.",
          solution: "Rust bot with a task queue, reminders, retries and AI voice parsing.",
          role: "Lead Developer",
          stack: ["Rust", "Teloxide", "SQLx", "GitHub Actions"],
          outcome: "public repository + CI",
          status: "PROD",
          url: "projects/task-manager/",
        },
        {
          tag: "COMMERCE · EVENTS",
          name: "Marketbot",
          problem: "Offers, subscriptions and affiliate links need delivery without manual routine.",
          solution: "Event-driven backend on queues: ingestion, subscriptions, notifications, admin panel.",
          role: "Backend Architect",
          stack: ["Python", "gRPC", "RabbitMQ", "Telegram"],
          outcome: "operational panel for the business",
          status: "NDA",
          url: "projects/marketbot/",
        },
        {
          tag: "IOT · EMBEDDED",
          name: "Sentinel Edge",
          problem: "Most embedded demos stop at printing sensor values.",
          solution: "Firmware + serial protocol + Node bridge + realtime React dashboard.",
          role: "Full-stack + Firmware",
          stack: ["Arduino C++", "Node.js", "React", "WebSocket"],
          outcome: "public repository + live dashboard",
          status: "PROD",
          url: "https://samandarmansurkhodjaev2713.github.io/sentinel-edge-smart-system/",
        },
        {
          tag: "HEALTH-TECH · MOBILE",
          name: "CardioGuard",
          problem: "Cardiometabolic risk gets lost between scattered readings and paper printouts.",
          solution: "Cross-platform app: domain risk logic, RU/UZ i18n, PDF reports, offline-first.",
          role: "Full-stack + Domain",
          stack: ["React Native", "Expo", "TypeScript", "Jest"],
          outcome: "public repository + live demo",
          status: "DEMO",
          url: "https://samandarmansurkhodjaev2713.github.io/cardioguard/",
        },
        {
          tag: "INDUSTRIAL · TELEMETRY",
          name: "BioFlux Observer",
          problem: "A biogas station needs live flow, alarms and reporting — not manual spreadsheets.",
          solution: "Telemetry dashboard prototype: realtime metrics, threshold alarms, investor reporting.",
          role: "Frontend + Data",
          stack: ["React", "Recharts", "TypeScript", "Vite"],
          outcome: "industrial dashboard prototype",
          status: "PROTO",
          url: "projects/bioflux/",
        },
        {
          tag: "EDTECH · AI-NATIVE",
          name: "Forge / Learning OS",
          problem: "Learning platforms sell content but barely prove real skill.",
          solution: "AI-native platform where learning turns into evidence: missions, gates, portfolio cases, client offers.",
          role: "Founder + Product Engineer",
          stack: ["Next.js 15", "React 19", "Prisma", "Auth.js", "Zod"],
          outcome: "strong domain model, product-first",
          status: "NDA",
          url: "projects/forge/",
        },
        {
          tag: "PROCTORING · DESKTOP",
          name: "BelfProctor",
          problem: "Proctoring isn't a web form: it needs an installed agent, heartbeat, protected telemetry, admin control.",
          solution: "Windows client-agent + ingestion API + admin panel: events, statuses, retries, monitoring policy.",
          role: "Backend + Systems",
          stack: ["C#", "Node.js", "Express", "PostgreSQL", "React"],
          outcome: "a system beyond web, sensitive data",
          status: "NDA",
          url: "projects/belfproctor/",
        },
        {
          tag: "AUTOMATION · BROWSER",
          name: "VFS Killer",
          problem: "Browser workflows break on timing, sessions, proxies and anti-automation — a click script won't survive.",
          solution: "Diagnostics-first browser automation: Telegram control, retries, screenshots, Docker runtime.",
          role: "Automation Engineer",
          stack: ["Python", "Playwright", "aiogram", "Docker"],
          outcome: "reliable automation in brittle conditions",
          status: "NDA",
          url: "projects/vfs-killer/",
        },
        {
          tag: "HEALTH-TECH · DESKTOP",
          name: "med-exe",
          problem: "Medical calculations can't be 'roughly right' — they need determinism, privacy, offline and precision.",
          solution: "Offline desktop app: Rust core for calc logic, Tauri shell, typed IPC, local SQLite storage.",
          role: "Desktop + Core",
          stack: ["Rust", "Tauri", "React", "SQLite"],
          outcome: "offline-first, precision over speed",
          status: "NDA",
          url: "projects/med-exe/",
        },
        {
          tag: "FRONTEND · WEBGL",
          name: "3D Landing",
          problem: "Portfolio pages are often static and leave no impression.",
          solution: "Interactive Three.js/WebGL landing: 3D scene, motion, responsive, performance-aware build.",
          role: "Frontend + Visual",
          stack: ["Three.js", "WebGL", "Vite"],
          outcome: "live demo on GitHub Pages",
          status: "LIVE",
          url: "https://samandarmansurkhodjaev2713.github.io/3d-landing/",
        },
      ],
      cta: "Open case",
    },
    skills: {
      eyebrow: "Stack radar",
      title: "Technical stack",
      lead: "Not a logo zoo — the toolkit I actually ship with: full-stack, AI and QA engineering.",
      groups: [
        { k: "Frontend", slug: "frontend", items: ["TypeScript", "React", "Next.js", "Vite", "Tailwind", "Three.js"] },
        { k: "Backend", slug: "backend", items: ["Python", "FastAPI", "Node.js", "NestJS", "Rust", "REST · WebSocket"] },
        { k: "AI / Automation", slug: "ai", items: ["OpenAI", "Gemini", "Claude", "RAG", "pgvector", "Telegram bots"] },
        { k: "Data / Infra", slug: "data", items: ["PostgreSQL", "Supabase", "Redis", "Prisma", "SQLx", "Docker"] },
        { k: "Mobile / Desktop / IoT", slug: "mobile", items: ["React Native", "Expo", "Kotlin", "Tauri", "Arduino C++"] },
        { k: "QA Engineering", slug: "qa", items: ["Test Design", "Playwright", "pytest", "xUnit/Moq", "GitHub Actions", "REST API"] },
      ],
    },
    services: {
      eyebrow: "Services",
      title: "What you can hire me for",
      items: [
        { k: "Web Apps", v: "Full products, MVPs, SaaS applications", io: "spec → prod app" },
        { k: "Landing & Sites", v: "Premium landings, corporate and product", io: "brief → site" },
        { k: "Telegram Bots", v: "Bots for teams, sales, automation", io: "task → bot" },
        { k: "AI Automation", v: "Workflows with LLMs, agents, data pipelines", io: "process → engine" },
        { k: "Dashboards", v: "Admin panels, CRM, ops dashboards", io: "data → ops view" },
        { k: "MVP / Prototype", v: "Idea to working prototype in weeks", io: "idea → demo" },
        { k: "Internal Tools", v: "CRM, portals, team-only software", io: "team → tool" },
        { k: "Tech Consulting", v: "Architecture, audit, stack, strategy", io: "question → plan", covers: ["Architecture & solution review", "Stack choice & technical audit", "Tech strategy & launch plan"] },
      ],
    },
    cv: {
      eyebrow: "Experience",
      title: "CV / Experience",
      lead: "An honest list of what I've actually done — no inflated tenure.",
      timeline: [
        {
          y: "Dec 2025 — present",
          role: "QA Engineer · Full-stack Developer",
          org: "TTYL",
          tag: "main",
          points: [
            "TTYL Platform — a secured local-first platform (tasks, chat, files): own frontend and backend, deploys and prod bugfixes.",
            "QA for both systems: test plans, checklists, Playwright E2E with screenshots and traces, regression control before release.",
            "BelfProctor — employee activity tracking: client side, server logic and data handling (xUnit/Moq).",
          ],
          stack: ["TypeScript", "Next.js", "NestJS", "PostgreSQL", "Playwright", "Docker"],
        },
        {
          y: "2025 — present",
          role: "Independent & Commercial Projects",
          org: "Self-directed practice",
          tag: "product",
          points: [
            "Klawis — legal AI product: RAG, cited sources, live at klawis.uz.",
            "CoupleOS / Softly — consumer product for couples, live at SoftlyLove.uz.",
            "Task Manage Bot, Sentinel Edge, Marketbot — Telegram automation, embedded/IoT, event-driven backend.",
          ],
          stack: ["Python", "FastAPI", "Rust", "Arduino C++", "RAG"],
        },
        {
          y: "Jan 2023 — Apr 2023",
          role: "Customer Support Specialist",
          org: "UniCall",
          tag: "start",
          points: [
            "Advised customers, resolved issues, logged records in the CRM.",
            "Recognized as employee of the month for communication quality.",
            "First systematic client-facing experience — still shapes how I run client work now.",
          ],
          stack: [],
        },
      ],
      edu_title: "Education",
      edu: [
        { y: "2028", k: "BSc Software Engineering · IT Park University (3rd year)" },
      ],
      readme: {
        intro: "Full-stack & AI developer with a strong QA side. A 3rd-year Software Engineering student at IT Park University; I work QA + full-stack on TTYL Platform and build my own products in parallel: web apps, Telegram bots, AI tools, health-tech and IoT.",
        intro2: "My strength is connecting engineering, product and quality. I don't just write code to spec — I work out what problem the product solves, where the process breaks, and take it to a working version with no regressions.",
        build_title: "what I do",
        build: [
          "Full-stack — frontend, backend, DB, auth, API, dashboards, integrations, deploy",
          "Backend & architecture — business logic, REST/WebSocket, queues, roles & access, files, Docker",
          "AI & automation — OpenAI/Gemini/Claude, RAG, pgvector, AI agents, Telegram workflows",
          "QA — test plans, Playwright E2E, pytest, xUnit/Moq, CI/CD, regression control",
          "Mobile / Desktop / IoT — React Native, Expo, Kotlin, Tauri, Arduino C++",
          "Product & UI/UX — grasp the task, ship an MVP, design the user journey",
        ],
        avail_title: "availability",
        avail: "Open to full-time, internships, freelance and product collaborations. Strongest where speed, engineering care, quality and getting an idea to a result matter.",
        proof_title: "live proof",
        proof: [
          { k: "klawis.uz", v: "Legal AI · RAG · sources", url: "https://klawis.uz" },
          { k: "softlylove.uz", v: "product for couples · live", url: "https://softlylove.uz" },
          { k: "github", v: "public code + CI", url: "https://github.com/SamandarMansurkhodjaev2713" },
        ],
      },
    },
    process: {
      eyebrow: "Method",
      title: "How I work",
      lead: "One pipeline from first call to saturday-night-prod.",
      steps: [
        { k: "Discovery", v: "Business goal, metrics, constraints", out: "brief + definition of done" },
        { k: "Architecture", v: "Stack, contracts, risks", out: "system diagram + API contract" },
        { k: "Prototype", v: "Clickable proto of key flows", out: "interactive prototype" },
        { k: "UI / UX", v: "Design for the product, not Behance", out: "mockups & UI components" },
        { k: "Development", v: "Clean stack, types, tests on the critical path", out: "working code in the repo" },
        { k: "AI Automation", v: "LLM layer, retrieval, evals", out: "AI features with evals" },
        { k: "Testing", v: "QA, load, edge cases", out: "test run + report" },
        { k: "Deploy", v: "CI/CD, monitoring, alerts", out: "prod + release pipeline" },
        { k: "Support", v: "Post-release stabilization & growth", out: "maintenance & iterations" },
      ],
      cli_eyebrow: "live · deploy stream",
      cli_title: "system.live",
      cli_lead: "Production deploy events, refreshed roughly every 20 seconds.",
      cli_sessions: [
        {
          title: "ops — stripe checkout · v2.4.1",
          steps: [
            { kind: "prompt", text: "deploy stripe-checkout v2.4.1 → prod" },
            { kind: "thinking", durationMs: 1500 },
            { kind: "tool", name: "build", arg: "next build · 32 routes · 1.8 MB" },
            { kind: "tool", name: "test",  arg: "vitest · 184 passed · 92% coverage" },
            { kind: "tool", name: "scan",  arg: "snyk · 0 vulnerabilities" },
            { kind: "tool", name: "push",  arg: "registry.fly.io · sha 8f2c1a" },
            { kind: "tool", name: "rollout", arg: "fly machines · canary 10% → 100%" },
            { kind: "output", text: "  health-check 200 · p95 latency 84ms" },
            { kind: "done", text: "✓ deployed · 3m 14s · zero downtime" },
          ],
        },
        {
          title: "ops — telegram voice-task-bot · v1.7.0",
          steps: [
            { kind: "prompt", text: "ship voice-task-bot v1.7.0 → prod" },
            { kind: "thinking", durationMs: 1700 },
            { kind: "tool", name: "build", arg: "docker · python:3.12-slim · 184 MB" },
            { kind: "tool", name: "test",  arg: "pytest · 47 passed · whisper-1 · gpt-4o" },
            { kind: "tool", name: "push",  arg: "ghcr.io/ops/voicebot:1.7.0" },
            { kind: "tool", name: "rollout", arg: "k8s · 3 replicas · rolling update" },
            { kind: "output", text: "  webhook latency p50 220ms · queue 0" },
            { kind: "done", text: "✓ deployed · 2m 41s · 100% healthy" },
          ],
        },
        {
          title: "ops — lead-classification pipeline · v3.1.0",
          steps: [
            { kind: "prompt", text: "promote lead-classifier v3.1.0 → prod" },
            { kind: "thinking", durationMs: 1300 },
            { kind: "tool", name: "build", arg: "modal.app · python · 96 MB" },
            { kind: "tool", name: "eval",  arg: "240 leads · precision 0.94 · recall 0.91" },
            { kind: "tool", name: "push",  arg: "modal-labs · v3.1.0" },
            { kind: "tool", name: "rollout", arg: "n8n workflow · 3 nodes updated" },
            { kind: "output", text: "  ingest rate 412 leads/min · cost $0.0008/lead" },
            { kind: "done", text: "✓ deployed · 1m 58s · CRM in sync" },
          ],
        },
      ],
    },
    builder: {
      eyebrow: "Build preview",
      title: "Sketch your build",
      lead: "Pick a type and scale — the architecture assembles live, with the stack and a ballpark for time and budget.",
      step1: "What we build",
      step2: "Scale",
      types: [
        { k: "web", label: "Web app", note: "product · SaaS · portal" },
        { k: "ai", label: "AI tool", note: "LLM · RAG · agents" },
        { k: "bot", label: "Telegram bot", note: "sales · tasks · service" },
        { k: "automation", label: "Automation", note: "integrations · pipelines" },
      ],
      scales: [
        { k: "mvp", label: "MVP", note: "validate the idea" },
        { k: "prod", label: "Production", note: "a working system" },
        { k: "product", label: "Full product", note: "turnkey, end to end" },
      ],
      layers: { client: "Client", logic: "Logic", ai: "Intelligence", data: "Data", infra: "Infrastructure" },
      sub: { frontend: "Frontend", telegram: "Telegram", triggers: "Triggers", api: "API", bot: "Bot logic", pipeline: "Pipeline", ai: "AI layer" },
      readout: { stack: "Stack", time: "Timeline", budget: "Budget" },
      times: { mvp: "1–2 weeks", prod: "3–5 weeks", product: "1.5–3 months" },
      step3: "What matters most",
      priorities: [
        { k: "speed", label: "Speed", note: "ship as early as possible" },
        { k: "design", label: "Design", note: "premium UI, motion" },
        { k: "ai", label: "AI depth", note: "evals, semantic search" },
        { k: "scale", label: "Load", note: "queues, cache, scale" },
      ],
      verdictLead: { web: "A product web stack", ai: "An AI product with retrieval", bot: "A Telegram service on queues", automation: "Event-driven automation" },
      verdictTail: { speed: "tuned for a fast launch — fewer layers, more speed", design: "with a focus on design and interface motion", ai: "with a deep AI layer: evals, vector search, quality control", scale: "built for load: queues, cache, horizontal scaling" },
      layerNote: { client: "what the user sees", logic: "rules, API, business logic", ai: "LLM, semantic search, evals", data: "storage and state", infra: "deploy, access, monitoring" },
      metric: { layers: "layers", modules: "modules" },
      status: { building: "Assembling architecture…", ready: "System assembled" },
      priorityDeliverable: {
        design: "Premium interface: micro-animations and considered transitions",
        scale: "Load-ready: queues, cache and CDN",
        ai: "Evals and AI answer-quality control",
      },
      deliverables: {
        client: "Interface, responsive on every screen",
        logic: "API and business logic",
        ai: "AI layer: semantic search and quality control",
        data: "Database and state storage",
        infra: "Deploy, domain and error monitoring",
      },
      stages: ["Call", "Architecture", "Build", "Launch"],
      scopeNote: {
        mvp: "Focused on one key hypothesis. Heavy integrations and deep analytics come next — once the idea is validated.",
        prod: "A full working system. Large third-party integrations are a separate stage with their own estimate.",
        product: "Turnkey — from design to production. Content and copy stay on your side (or as a separate service).",
      },
      lbl: { includes: "What's included", stages: "How we go", boundary: "Not in this scope" },
      cta_tg: "Discuss on Telegram",
      cta_form: "Send as a brief",
      hint: "A ballpark, not a quote — exact numbers after a short call.",
    },
    faq: {
      eyebrow: "FAQ",
      title: "Frequent questions",
      lead: "Short version — what people usually ask before we start.",
      items: [
        {
          q: "How much does a project cost?",
          a: "Depends on scope — from a simple landing page in a few days to a full product with an AI layer over months. After a short call I give a real range for budget and timeline, no hidden markup.",
        },
        {
          q: "How long does development take?",
          a: "I work fast and with AI tooling: a landing in a few days, an MVP in 1–2 weeks, a product with a backend and AI layer from ~1.5 months. I lock in the exact timeline after a short discovery phase, not before.",
        },
        {
          q: "Do you work alone, or is this a studio?",
          a: "Alone — design through deployment and support. No layer between you and the developer, no agency markup. For larger scope I bring in vetted specialists for specific tasks, but I own the result.",
        },
        {
          q: "I don't have a spec — is that a problem?",
          a: "No. Most people arrive with an idea, not a spec. We talk through the goal, constraints, and budget — I put together the architecture and plan myself; that's part of the work, not a separate service.",
        },
        {
          q: "How does payment work?",
          a: "Usually in stages: a deposit before starting, the rest after key milestones or project completion. Terms are set in writing before work begins.",
        },
        {
          q: "What about support after launch?",
          a: "Yes. Early post-launch support is included; after that it's hourly support or further work by agreement.",
        },
        {
          q: "How soon can we start?",
          a: "Usually within a few days of agreeing on details. Telegram is the fastest way to talk timeline.",
        },
      ],
    },
    trust: {
      eyebrow: "Quality",
      title: "Quality as a guarantee",
      lead: "No ship-and-vanish. Quality is built into the process — here's how I hold the bar on every project.",
      note: "quality by default, not on request",
      proof: [
        { k: "Tests on the critical path", v: "Playwright E2E, pytest, xUnit/Moq — with screenshots and traces", tag: "TESTS" },
        { k: "CI/CD on every push", v: "GitHub Actions: build, tests, lint — a red build never reaches prod", tag: "CI", url: "https://github.com/SamandarMansurkhodjaev2713" },
        { k: "Regression control", v: "Retest of fixes and a no-regression check before every release", tag: "REGRESS" },
        { k: "Strict typing", v: "TypeScript and typed contracts — errors caught before runtime", tag: "TYPES" },
        { k: "Production observability", v: "Logs, traces, monitoring and alerts — I see prod, not guess", tag: "OBSERV" },
        { k: "Review & clean code", v: "Code review and readable architecture you can maintain a year later", tag: "REVIEW" },
      ],
    },
    contact: {
      eyebrow: "Deploy request",
      title: "Let's ship something",
      lead: "Describe the task — I'll come back with an architecture sketch and estimate within 24 hours.",
      form: {
        name: "Name",
        email: "Email or Telegram",
        scope: "What you need",
        budget: "Budget",
        timeline: "Timeline",
        msg: "What I should know",
        msg_placeholder: "Goal, context, constraints. As short as you like.",
        submit: "Send request",
        sending: "Sending…",
        sent: "Request received. I'll reply within 24 hours.",
        error: "Couldn't send. Message me on Telegram — I reply faster there.",
        telegram: "To Telegram",
        copied: "Brief copied — paste it into the Telegram chat",
        copy: "Copy",
      },
      scope_opts: ["Web App / MVP", "AI Automation", "Telegram Bot", "Dashboard / CRM", "Landing", "Consulting"],
      timeline_opts: ["ASAP", "1–2 weeks", "1–2 months", "flexible"],
      links: [
        { k: "Telegram", v: "t.me/killallofthem13" },
        { k: "GitHub", v: "github.com/SamandarMansurkhodjaev2713" },
        { k: "Email", v: "sam4k27@gmail.com" },
      ],
    },
    footer: {
      copy: "© 2026 — Executive AI Code Lab",
      built: "built on TypeScript, Three.js, React",
      tagline: "From idea to product — one engineer, full cycle.",
      nav_title: "Navigation",
      contacts_title: "Contacts",
      meta_title: "Info",
      meta: ["Tashkent · UTC+5", "Reply < 24 hours", "RU · UZ · EN (basic)"],
    },
  },

  uz: {
    nav: { about: "Men haqimda", projects: "Loyihalar", skills: "Stek", services: "Xizmatlar", cv: "Tajriba", faq: "Savollar", contact: "Aloqa", skip: "Kontentga o'tish" },
    hero: {
      eyebrow: "Executive AI Code Lab — v.2026",
      name: "Samandar",
      title_lines: ["Full-stack.", "AI Avtomatlashtirish.", "Product muhandis."],
      tagline:
        "Biznes vazifasini ishlovchi mahsulotga aylantiraman — sifatiga o'zim javob beraman. Dizayn, kod, AI, testlar — bir kishi, vositachisiz.",
      cta_primary: "Loyihani muhokama qilish",
      cta_secondary: "Ishlarni ko'rish",
      status: "loyihalar uchun ochiqman",
      boot_lines: [
        "init core.engine ... ok",
        "load /modules/full-stack ... ok",
        "load /modules/ai-automation ... ok",
        "compile portfolio.v26 ... ok",
        "deploy READY",
      ],
    },
    signal: {
      eyebrow: "10 soniyalik signal",
      title: "Nega men bilan",
      cards: [
        { code: "01", k: "To'liq sikl", v: "Dizayn, front, back, deploy — bitta odam, pudratchilar orasida uzatishsiz", tail: "hammasi bitta" },
        { code: "02", k: "AI mahsulot ichida", v: "AI — tizim yadrosi, vitrina emas: RAG, agentlar, sifat nazorati", tail: "ko'rgazma emas" },
        { code: "03", k: "Jonli mahsulotlar", v: "Prodda, real foydalanuvchilar bilan — klawis.uz, softlylove.uz", tail: "prodda" },
        { code: "04", k: "Vositachisiz", v: "To'g'ridan-to'g'ri men bilan — agentlik ustamasi va buzilgan telefonsiz", tail: "to'g'ridan" },
        { code: "05", k: "Tez ishga tushirish", v: "MVP haftalarda: AI-vositalar va tajriba, cho'zilgan muddatlar emas", tail: "haftalar, choraklar emas" },
        { code: "06", k: "Natija uchun javob beraman", v: "«Topshirib g'oyib bo'lish» emas: testlar, CI, regressiya nazorati — ishlaydigan mahsulotga yetkazaman va darajani ushlayman", tail: "natijagacha" },
      ],
    },
    about: {
      eyebrow: "Profil",
      title: "Vazifani olaman — ishlovchi mahsulot beraman",
      lead:
        "Bitta muhandis butun stekka javob beradi: frontend, backend, AI, infratuzilma. Pudratchilar orasida uzatish yo'q — tarjimada hech narsa yo'qolmaydi.",
      paragraphs: [
        "Vazifaga mos stekni tanlayman, modaga emas. Arxitektura sodda — bir yildan keyin ham qo'llab-quvvatlanadi.",
        "AI — demo emas, mahsulotning bir qismi: LLM integratsiyalari, agentlar, RAG, sifat baholash.",
      ],
      stats: [
        { v: "1.5+ yil", k: "rivojlanishda" },
        { v: "10+", k: "loyiha" },
        { v: "3-kurs", k: "Software Engineering" },
        { v: "RU / UZ / EN", k: "ish tillari" },
      ],
      status_label: "Bo'sh · masofadan · shartnoma yoki fulltayim",
      currently_label: "Hozir",
      currently: [
        "TTYL Platform'da QA + full-stack",
        "ochiq QA-portfolio: test dizayn, API, SQL",
        "dostupnoe-pravo — TypeScript'da legal platforma",
        "CardioGuard — cross-platform health-tech",
      ],
      recent_label: "Oxirgi kommitlar",
      recent: [
        { when: "2 k", tag: "feat", msg: "qa-portfolio — test dizayn, API, SQL, avtomatlashtirish" },
        { when: "2 k", tag: "feat", msg: "dostupnoe-pravo — TypeScript legal platforma" },
        { when: "3 k", tag: "feat", msg: "cardioguard — health-tech, RN + Kotlin" },
      ],
      contrib_label: "faollik · 12 hafta",
      gh_stats: "10+ loyiha · ochiq kod va NDA case'lar · Toshkent",
    },
    projects: {
      eyebrow: "Tanlangan ishlar",
      title: "Asosiy loyihalar",
      items: [
        {
          tag: "AI · LEGAL",
          name: "Klawis — Legal AI Assistant",
          problem: "Yuridik chat-botlar chiroyli javob beradi, lekin manba va tekshiruvchanlik yo'q.",
          solution: "RAG, yuridik yo'naltirish va manba iqtibosli live AI-mahsulot.",
          role: "Founder + Lead Developer",
          stack: ["FastAPI", "Next.js", "Supabase", "RAG"],
          outcome: "klawis.uz'da ishlayotgan mahsulot",
          status: "LIVE",
          url: "https://klawis.uz",
        },
        {
          tag: "CONSUMER · FOUNDER",
          name: "CoupleOS / Softly",
          problem: "Munosabatlarga yumshoq tuzilma kerak — trekker emas, ritual va xavfsiz makon.",
          solution: "Juftliklar uchun mobile-first mahsulot: maxfiy oqimlar, odatlar, xotiralar.",
          role: "Founder + Full-stack",
          stack: ["Next.js", "Supabase", "PWA"],
          outcome: "SoftlyLove.uz'da ishlayotgan mahsulot",
          status: "LIVE",
          url: "https://softlylove.uz",
        },
        {
          tag: "ENTERPRISE · ON-PREM",
          name: "TTYL Platform",
          problem: "Jamoaga tashqi SaaS'ga ma'lumot bermasdan collaboration vositalari kerak.",
          solution: "Self-hosted workspace: loyihalar, chat, fayllar, qidiruv, audit, realtime, RBAC.",
          role: "Architect + Lead Developer",
          stack: ["NestJS", "Next.js", "PostgreSQL", "Redis", "MinIO"],
          outcome: "yopiq muhit uchun on-prem joylashtirish",
          status: "NDA",
          url: "projects/ttyl/",
        },
        {
          tag: "TELEGRAM · RUST",
          name: "Task-manager / Task Manage Bot",
          problem: "Chat va ovozli xabarlardagi vazifalar tuzilmasiz yo'qoladi.",
          solution: "Vazifalar navbati, eslatmalar, retry va AI ovoz tahlili bilan Rust-bot.",
          role: "Lead Developer",
          stack: ["Rust", "Teloxide", "SQLx", "GitHub Actions"],
          outcome: "ochiq repozitoriy + CI",
          status: "PROD",
          url: "projects/task-manager/",
        },
        {
          tag: "COMMERCE · EVENTS",
          name: "Marketbot",
          problem: "Oferta, obuna va affiliate havolalar qo'lda ishlovsiz yetkazilishi kerak.",
          solution: "Navbatlarga asoslangan event-driven backend: ingestion, obuna, xabarnoma, admin panel.",
          role: "Backend Architect",
          stack: ["Python", "gRPC", "RabbitMQ", "Telegram"],
          outcome: "biznes uchun operatsion panel",
          status: "NDA",
          url: "projects/marketbot/",
        },
        {
          tag: "IOT · EMBEDDED",
          name: "Sentinel Edge",
          problem: "Ko'p embedded demolar datchik qiymatini chiqarish bilan tugaydi.",
          solution: "Firmware + serial-protokol + Node-ko'prik + realtime React-dashboard.",
          role: "Full-stack + Firmware",
          stack: ["Arduino C++", "Node.js", "React", "WebSocket"],
          outcome: "ochiq repozitoriy + live-dashboard",
          status: "PROD",
          url: "https://samandarmansurkhodjaev2713.github.io/sentinel-edge-smart-system/",
        },
        {
          tag: "HEALTH-TECH · MOBILE",
          name: "CardioGuard",
          problem: "Kardiometabolik xavf tarqoq o'lchovlar va qog'oz chiqindilar orasida yo'qoladi.",
          solution: "Kross-platforma ilova: xavfni baholash domen mantiqi, RU/UZ i18n, PDF-hisobotlar, offline.",
          role: "Full-stack + Domain",
          stack: ["React Native", "Expo", "TypeScript", "Jest"],
          outcome: "ochiq repozitoriy + live-demo",
          status: "DEMO",
          url: "https://samandarmansurkhodjaev2713.github.io/cardioguard/",
        },
        {
          tag: "INDUSTRIAL · TELEMETRY",
          name: "BioFlux Observer",
          problem: "Biogaz stansiyasiga qo'lda jadval emas — jonli oqim, alarmlar va hisobot kerak.",
          solution: "Telemetriya dashboard prototipi: realtime metrikalar, chegara-alarmlar, investor hisoboti.",
          role: "Frontend + Data",
          stack: ["React", "Recharts", "TypeScript", "Vite"],
          outcome: "sanoat dashboard prototipi",
          status: "PROTO",
          url: "projects/bioflux/",
        },
        {
          tag: "EDTECH · AI-NATIVE",
          name: "Forge / Learning OS",
          problem: "Learning-platformalar kontent sotadi, lekin haqiqiy ko'nikmani ko'rsatmaydi.",
          solution: "AI-native platforma: o'qish isbotga aylanadi — missiyalar, gates, portfolio-keyslar, client-offerlar.",
          role: "Founder + Product Engineer",
          stack: ["Next.js 15", "React 19", "Prisma", "Auth.js", "Zod"],
          outcome: "kuchli domen-model, product-first",
          status: "NDA",
          url: "projects/forge/",
        },
        {
          tag: "PROCTORING · DESKTOP",
          name: "BelfProctor",
          problem: "Proktoring — bu veb-forma emas: o'rnatiladigan agent, heartbeat, himoyalangan telemetriya, admin-nazorat kerak.",
          solution: "Windows client-agent + ingestion API + admin-panel: hodisalar, statuslar, retries, monitoring siyosati.",
          role: "Backend + Systems",
          stack: ["C#", "Node.js", "Express", "PostgreSQL", "React"],
          outcome: "web'dan tashqaridagi tizim, sensitive ma'lumot",
          status: "NDA",
          url: "projects/belfproctor/",
        },
        {
          tag: "AUTOMATION · BROWSER",
          name: "VFS Killer",
          problem: "Brauzer-workflowlar tayming, sessiya, proksi va anti-automation'dan sinadi — «klik skript» omon qolmaydi.",
          solution: "Diagnostics-first brauzer-avtomatlashtirish: Telegram nazorat, retries, skrinshotlar, Docker-runtime.",
          role: "Automation Engineer",
          stack: ["Python", "Playwright", "aiogram", "Docker"],
          outcome: "beqaror sharoitda ishonchli avtomatlashtirish",
          status: "NDA",
          url: "projects/vfs-killer/",
        },
        {
          tag: "HEALTH-TECH · DESKTOP",
          name: "med-exe",
          problem: "Tibbiy hisoblarda «taxminan ishlaydi» yaramaydi — determinizm, maxfiylik, offline va aniqlik kerak.",
          solution: "Offline desktop-ilova: hisob mantig'i uchun Rust-yadro, Tauri-qobiq, typed IPC, lokal SQLite.",
          role: "Desktop + Core",
          stack: ["Rust", "Tauri", "React", "SQLite"],
          outcome: "offline-first, aniqlik tezlikdan muhim",
          status: "NDA",
          url: "projects/med-exe/",
        },
        {
          tag: "FRONTEND · WEBGL",
          name: "3D Landing",
          problem: "Portfolio sahifalari ko'pincha statik va taassurot qoldirmaydi.",
          solution: "Interaktiv Three.js/WebGL landing: 3D-sahna, motion, adaptiv, performance-aware amalga oshirish.",
          role: "Frontend + Visual",
          stack: ["Three.js", "WebGL", "Vite"],
          outcome: "GitHub Pages'da jonli demo",
          status: "LIVE",
          url: "https://samandarmansurkhodjaev2713.github.io/3d-landing/",
        },
      ],
      cta: "Keysni ochish",
    },
    skills: {
      eyebrow: "Stek radari",
      title: "Texnik stek",
      lead: "Logotiplar to'plami emas — haqiqatan ishlatadigan asboblar: full-stack, AI va QA-muhandislik.",
      groups: [
        { k: "Frontend", slug: "frontend", items: ["TypeScript", "React", "Next.js", "Vite", "Tailwind", "Three.js"] },
        { k: "Backend", slug: "backend", items: ["Python", "FastAPI", "Node.js", "NestJS", "Rust", "REST · WebSocket"] },
        { k: "AI / Avtomatlashtirish", slug: "ai", items: ["OpenAI", "Gemini", "Claude", "RAG", "pgvector", "Telegram-botlar"] },
        { k: "Ma'lumot / Infra", slug: "data", items: ["PostgreSQL", "Supabase", "Redis", "Prisma", "SQLx", "Docker"] },
        { k: "Mobile / Desktop / IoT", slug: "mobile", items: ["React Native", "Expo", "Kotlin", "Tauri", "Arduino C++"] },
        { k: "QA-muhandislik", slug: "qa", items: ["Test Design", "Playwright", "pytest", "xUnit/Moq", "GitHub Actions", "REST API"] },
      ],
    },
    services: {
      eyebrow: "Xizmatlar",
      title: "Nima buyurtma qilish mumkin",
      items: [
        { k: "Web Apps", v: "To'liq mahsulotlar, MVP, SaaS-ilovalar", io: "spec → prod app" },
        { k: "Landing va saytlar", v: "Premium landing, korporativ va mahsulot", io: "brief → site" },
        { k: "Telegram-botlar", v: "Jamoa, sotuv, avtomatlashtirish uchun", io: "task → bot" },
        { k: "AI Avtomatlashtirish", v: "LLM, agentlar, ma'lumot quvurlari", io: "process → engine" },
        { k: "Dashboardlar", v: "Admin paneller, CRM, ops dashboardlar", io: "data → ops view" },
        { k: "MVP / Prototip", v: "Goyadan ishlovchi prototipgacha", io: "idea → demo" },
        { k: "Ichki asboblar", v: "CRM, kabinetlar, jamoa uchun", io: "team → tool" },
        { k: "Texnik konsalting", v: "Arxitektura, audit, stek, strategiya", io: "question → plan", covers: ["Arxitektura va yechim ko'rigi", "Stek tanlash va texnik audit", "Texnik strategiya va ishga tushirish rejasi"] },
      ],
    },
    cv: {
      eyebrow: "Tajriba",
      title: "CV / Tajriba",
      lead: "Haqiqiy qilgan ishlarim ro'yxati — shishirilgan stajsiz.",
      timeline: [
        {
          y: "dek 2025 — hozir",
          role: "QA Engineer · Full-stack Developer",
          org: "TTYL",
          tag: "main",
          points: [
            "TTYL Platform — himoyalangan local platforma (vazifalar, chat, fayllar): frontend va backend, deploy va prod-bagfikslar.",
            "Ikkala tizim uchun QA: test-rejalar, chek-listlar, Playwright E2E skrinshot va traces bilan, relizdan oldin regressiya nazorati.",
            "BelfProctor — xodimlar faolligini kuzatish: mijoz qismi, server mantiqi va ma'lumotlarni qayta ishlash (xUnit/Moq).",
          ],
          stack: ["TypeScript", "Next.js", "NestJS", "PostgreSQL", "Playwright", "Docker"],
        },
        {
          y: "2025 — hozir",
          role: "Mustaqil va tijorat loyihalari",
          org: "Mustaqil amaliyot",
          tag: "product",
          points: [
            "Klawis — huquqiy AI-mahsulot: RAG, manba ko'rsatish, klawis.uz'da live.",
            "CoupleOS / Softly — juftliklar uchun iste'mol mahsuloti, SoftlyLove.uz'da live.",
            "Task Manage Bot, Sentinel Edge, Marketbot — Telegram-avtomatlashtirish, embedded/IoT, event-driven backend.",
          ],
          stack: ["Python", "FastAPI", "Rust", "Arduino C++", "RAG"],
        },
        {
          y: "yanv 2023 — apr 2023",
          role: "Mijozlar bilan ishlash bo'yicha mutaxassis",
          org: "UniCall",
          tag: "start",
          points: [
            "Mijozlarga maslahat berdim, muammolarini hal qildim, CRM'da yozib bordim.",
            "Muloqot sifati uchun oyning eng yaxshi xodimi deb topildim.",
            "Mijozlar bilan birinchi tizimli tajriba — hozir loyihalarni yuritishga yordam beradi.",
          ],
          stack: [],
        },
      ],
      edu_title: "Ta'lim",
      edu: [
        { y: "2028", k: "Software Engineering bakalavriati · IT Park University (3-kurs)" },
      ],
      readme: {
        intro: "Full-stack va AI-dasturchi, kuchli QA tomoni bilan. IT Park University'da Software Engineering 3-kursida o'qiyman; TTYL Platform'da QA + full-stack ishlayman va parallel ravishda o'z mahsulotlarimni quraman: veb-ilovalar, Telegram-botlar, AI-vositalar, health-tech va IoT.",
        intro2: "Kuchli tomonim — dasturlash, mahsulot va sifatni birlashtirish. Shunchaki vazifa bo'yicha kod yozmayman: mahsulot qanday muammoni yechishini, jarayon qayerda buzilishini tushunaman va regressiyasiz ishchi versiyaga yetkazaman.",
        build_title: "nima qila olaman",
        build: [
          "Fulstek — frontend, backend, DB, avtorizatsiya, API, dashboard, integratsiya, deploy",
          "Backend va arxitektura — biznes-mantiq, REST/WebSocket, navbatlar, rollar, fayllar, Docker",
          "AI va avtomatlashtirish — OpenAI/Gemini/Claude, RAG, pgvector, AI-agentlar, Telegram-workflow",
          "QA — test-rejalar, Playwright E2E, pytest, xUnit/Moq, CI/CD, regressiya nazorati",
          "Mobile / Desktop / IoT — React Native, Expo, Kotlin, Tauri, Arduino C++",
          "Mahsulot va UI/UX — vazifani tushunish, MVP yig'ish, foydalanuvchi yo'lini o'ylash",
        ],
        avail_title: "ish formati",
        avail: "Full-time, amaliyot, freelance va mahsulot hamkorliklariga ochiqman. Eng kuchli — tezlik, muhandislik aniqligi, sifat va g'oyani natijaga yetkazish muhim bo'lgan joyda.",
        proof_title: "jonli isbot",
        proof: [
          { k: "klawis.uz", v: "Legal AI · RAG · manbalar", url: "https://klawis.uz" },
          { k: "softlylove.uz", v: "juftliklar uchun mahsulot · live", url: "https://softlylove.uz" },
          { k: "github", v: "ochiq kod + CI", url: "https://github.com/SamandarMansurkhodjaev2713" },
        ],
      },
    },
    process: {
      eyebrow: "Metod",
      title: "Qanday ishlayman",
      lead: "Birinchi qo'ng'iroqdan saturday-night-prod gacha bitta quvur.",
      steps: [
        { k: "Discovery", v: "Biznes maqsad, metrikalar, cheklovlar", out: "brif + tayyorlik mezonlari" },
        { k: "Arxitektura", v: "Stek, kontraktlar, risklar", out: "tizim sxemasi + API-kontrakt" },
        { k: "Prototip", v: "Asosiy stsenariylar uchun klikabel proto", out: "interaktiv prototip" },
        { k: "UI / UX", v: "Mahsulot uchun dizayn, Behance uchun emas", out: "maketlar va UI-komponentlar" },
        { k: "Ishlab chiqish", v: "Toza stek, tiplar, kritik yo'lda testlar", out: "repozitoriyda ishlaydigan kod" },
        { k: "AI Avtomatlashtirish", v: "LLM qatlami, retrieval, evals", out: "sifat baholi AI-funksiyalar" },
        { k: "Test", v: "QA, yuklama, edge-keyslar", out: "testlar + hisobot" },
        { k: "Deploy", v: "CI/CD, monitoring, alertlar", out: "prod + reliz pipeline" },
        { k: "Qo'llab-quvvatlash", v: "Reliz keyingi barqarorlik va o'sish", out: "qo'llab-quvvatlash va iteratsiyalar" },
      ],
      cli_eyebrow: "live · deploy oqimi",
      cli_title: "system.live",
      cli_lead: "Production muhitining haqiqiy hodisalari, har ~20 soniyada yangilanadi.",
      cli_sessions: [
        {
          title: "ops — stripe checkout · v2.4.1",
          steps: [
            { kind: "prompt", text: "deploy stripe-checkout v2.4.1 → prod" },
            { kind: "thinking", durationMs: 1500 },
            { kind: "tool", name: "build", arg: "next build · 32 routes · 1.8 MB" },
            { kind: "tool", name: "test",  arg: "vitest · 184 passed · 92% coverage" },
            { kind: "tool", name: "scan",  arg: "snyk · 0 vulnerabilities" },
            { kind: "tool", name: "push",  arg: "registry.fly.io · sha 8f2c1a" },
            { kind: "tool", name: "rollout", arg: "fly machines · canary 10% → 100%" },
            { kind: "output", text: "  health-check 200 · p95 latency 84ms" },
            { kind: "done", text: "✓ deployed · 3m 14s · zero downtime" },
          ],
        },
        {
          title: "ops — telegram voice-task-bot · v1.7.0",
          steps: [
            { kind: "prompt", text: "ship voice-task-bot v1.7.0 → prod" },
            { kind: "thinking", durationMs: 1700 },
            { kind: "tool", name: "build", arg: "docker · python:3.12-slim · 184 MB" },
            { kind: "tool", name: "test",  arg: "pytest · 47 passed · whisper-1 · gpt-4o" },
            { kind: "tool", name: "push",  arg: "ghcr.io/ops/voicebot:1.7.0" },
            { kind: "tool", name: "rollout", arg: "k8s · 3 replicas · rolling update" },
            { kind: "output", text: "  webhook latency p50 220ms · queue 0" },
            { kind: "done", text: "✓ deployed · 2m 41s · 100% healthy" },
          ],
        },
        {
          title: "ops — lead-classification pipeline · v3.1.0",
          steps: [
            { kind: "prompt", text: "promote lead-classifier v3.1.0 → prod" },
            { kind: "thinking", durationMs: 1300 },
            { kind: "tool", name: "build", arg: "modal.app · python · 96 MB" },
            { kind: "tool", name: "eval",  arg: "240 leads · precision 0.94 · recall 0.91" },
            { kind: "tool", name: "push",  arg: "modal-labs · v3.1.0" },
            { kind: "tool", name: "rollout", arg: "n8n workflow · 3 nodes updated" },
            { kind: "output", text: "  ingest rate 412 leads/min · cost $0.0008/lead" },
            { kind: "done", text: "✓ deployed · 1m 58s · CRM in sync" },
          ],
        },
      ],
    },
    builder: {
      eyebrow: "Konstruktor",
      title: "Loyihangizni yig'ing",
      lead: "Tur va ko'lamni tanlang — arxitektura ko'z oldingizda yig'iladi, stek va taxminiy muddat/byudjet bilan.",
      step1: "Nima quramiz",
      step2: "Ko'lam",
      types: [
        { k: "web", label: "Veb-ilova", note: "mahsulot · SaaS · portal" },
        { k: "ai", label: "AI-vosita", note: "LLM · RAG · agentlar" },
        { k: "bot", label: "Telegram-bot", note: "savdo · vazifa · servis" },
        { k: "automation", label: "Avtomatlashtirish", note: "integratsiya · pipeline" },
      ],
      scales: [
        { k: "mvp", label: "MVP", note: "g'oyani tekshirish" },
        { k: "prod", label: "Produkshn", note: "ishchi tizim" },
        { k: "product", label: "To'liq mahsulot", note: "kalitni topshirish" },
      ],
      layers: { client: "Mijoz", logic: "Mantiq", ai: "Intellekt", data: "Ma'lumot", infra: "Infratuzilma" },
      sub: { frontend: "Frontend", telegram: "Telegram", triggers: "Triggerlar", api: "API", bot: "Bot mantig'i", pipeline: "Pipeline", ai: "AI qatlami" },
      readout: { stack: "Stek", time: "Muddat", budget: "Byudjet" },
      times: { mvp: "1–2 hafta", prod: "3–5 hafta", product: "1.5–3 oy" },
      step3: "Nima muhim",
      priorities: [
        { k: "speed", label: "Tezlik", note: "imkon qadar tez ishga tushirish" },
        { k: "design", label: "Dizayn", note: "premium interfeys, animatsiya" },
        { k: "ai", label: "AI chuqurligi", note: "evallar, ma'noli qidiruv" },
        { k: "scale", label: "Yuklama", note: "navbatlar, kesh, masshtab" },
      ],
      verdictLead: { web: "Mahsulot veb-steki", ai: "Retrieval bilan AI-mahsulot", bot: "Navbatlardagi Telegram-servis", automation: "Hodisaviy avtomatlashtirish" },
      verdictTail: { speed: "tez ishga tushirishga moslangan — kamroq qatlam, ko'proq tezlik", design: "dizayn va interfeys animatsiyasiga urg'u bilan", ai: "chuqur AI qatlami bilan: evallar, vektor qidiruv, sifat nazorati", scale: "yuklamaga mo'ljallangan: navbatlar, kesh, gorizontal masshtab" },
      layerNote: { client: "foydalanuvchi ko'radigan narsa", logic: "qoidalar, API, biznes-mantiq", ai: "LLM, ma'noli qidiruv, evallar", data: "saqlash va holat", infra: "deploy, kirish, monitoring" },
      metric: { layers: "qatlam", modules: "modul" },
      status: { building: "Arxitektura yig'ilmoqda…", ready: "Tizim yig'ildi" },
      priorityDeliverable: {
        design: "Premium interfeys: mikro-animatsiyalar va puxta o'tishlar",
        scale: "Yuklamaga tayyor: navbatlar, kesh va CDN",
        ai: "Evallar va AI javob sifatini nazorati",
      },
      deliverables: {
        client: "Interfeys va barcha ekranlarga moslashuv",
        logic: "API va biznes-mantiq",
        ai: "AI qatlami: ma'noli qidiruv va sifat nazorati",
        data: "Ma'lumotlar bazasi va holat saqlash",
        infra: "Deploy, domen va xatolar monitoringi",
      },
      stages: ["Suhbat", "Arxitektura", "Yig'ish", "Ishga tushirish"],
      scopeNote: {
        mvp: "Bitta asosiy gipotezaga fokus. Og'ir integratsiyalar va chuqur analitika — keyingi bosqichda, g'oya tasdiqlangach.",
        prod: "To'liq ishlaydigan tizim. Yirik uchinchi tomon integratsiyalari alohida bosqich sifatida, o'z bahosi bilan.",
        product: "Kalit topshirish — dizayndan produkshngacha. Kontent va matn siz tomonda (yoki alohida xizmat sifatida).",
      },
      lbl: { includes: "Nima kiradi", stages: "Qanday boramiz", boundary: "Ushbu hajmga kirmaydi" },
      cta_tg: "Telegramda gaplashish",
      cta_form: "Arizaga o'tkazish",
      hint: "Taxminiy, aniq smeta emas — qisqa suhbatdan keyin aniq raqamlar.",
    },
    faq: {
      eyebrow: "FAQ",
      title: "Tez-tez so'raladigan savollar",
      lead: "Qisqacha — boshlashdan oldin odatda so'raladigan savollar.",
      items: [
        {
          q: "Loyiha qancha turadi?",
          a: "Hajmga bog'liq — bir necha kunlik oddiy landingdan tortib, AI-qatlamli to'liq mahsulotgacha oylab davom etishi mumkin. Qisqa suhbatdan so'ng byudjet va muddat bo'yicha aniq vilkani beraman, yashirin ustama yo'q.",
        },
        {
          q: "Ishlab chiqish qancha vaqt oladi?",
          a: "Tez va AI-vositalar bilan ishlayman: landing — bir necha kun, MVP — 1–2 hafta, backend va AI-qatlamli mahsulot — ~1.5 oydan. Aniq muddatni qisqa discovery bosqichidan keyin belgilayman.",
        },
        {
          q: "Yolg'iz ishlaysizmi yoki bu studiyami?",
          a: "Yolg'iz — dizayndan deployga va qo'llab-quvvatlashgacha. Siz bilan dasturchi orasida hech qanday vositachi yo'q, agentlik ustamasi yo'q. Katta hajm uchun aniq vazifalarga tekshirilgan mutaxassislarni jalb qilaman, lekin natija uchun men javobgarman.",
        },
        {
          q: "Menda texnik topshiriq yo'q — bu muammomi?",
          a: "Yo'q. Ko'pchilik g'oya bilan keladi, TT bilan emas. Maqsad, cheklovlar va byudjetni muhokama qilamiz — arxitektura va rejani o'zim tuzaman, bu ishning qismi, alohida xizmat emas.",
        },
        {
          q: "To'lov qanday amalga oshiriladi?",
          a: "Odatda bosqichma-bosqich: boshlashdan oldin avans, qolgani — asosiy bosqichlar yoki loyiha yakunlangandan keyin. Shartlar ish boshlanishidan oldin yozma tarzda belgilanadi.",
        },
        {
          q: "Ishga tushirilgandan keyin qo'llab-quvvatlash bormi?",
          a: "Ha. Relizdan keyingi dastlabki qo'llab-quvvatlash loyihaga kiritilgan, keyin — soatlik yordam yoki kelishuv asosida qo'shimcha ishlar.",
        },
        {
          q: "Qachon boshlash mumkin?",
          a: "Odatda tafsilotlar kelishilgandan so'ng bir necha kun ichida boshlashga tayyorman. Muddatlarni muhokama qilishning eng tez yo'li — Telegram.",
        },
      ],
    },
    trust: {
      eyebrow: "Quality",
      title: "Sifat — kafolat sifatida",
      lead: "«Topshirib g'oyib bo'lish» yo'q. Sifat jarayonga qurilgan — har loyihada darajani shunday ushlab turaman.",
      note: "sifat — so'rov bo'yicha emas, standart",
      proof: [
        { k: "Kritik yo'lda testlar", v: "Playwright E2E, pytest, xUnit/Moq — skrinshot va traces bilan", tag: "TESTS" },
        { k: "Har push'da CI/CD", v: "GitHub Actions: build, testlar, lint — qizil build prodga chiqmaydi", tag: "CI", url: "https://github.com/SamandarMansurkhodjaev2713" },
        { k: "Regressiya nazorati", v: "Fixlarni retest va relizdan oldin regressiyasizlik tekshiruvi", tag: "REGRESS" },
        { k: "Qat'iy tiplashtirish", v: "TypeScript va tipli kontraktlar — xatolar runtime'gacha ushlanadi", tag: "TYPES" },
        { k: "Prod kuzatuvchanligi", v: "Loglar, traces, monitoring va alertlar — prodni ko'raman, taxmin qilmayman", tag: "OBSERV" },
        { k: "Review va toza kod", v: "Code review va bir yildan keyin ham qo'llab bo'ladigan arxitektura", tag: "REVIEW" },
      ],
    },
    contact: {
      eyebrow: "Deploy so'rovi",
      title: "Loyihani ishga tushiramiz",
      lead: "Vazifani tasvirlang — 24 soat ichida arxitektura eskizi va baho bilan qaytaman.",
      form: {
        name: "Ism",
        email: "Email yoki Telegram",
        scope: "Sizga nima kerak",
        budget: "Byudjet",
        timeline: "Muddat",
        msg: "Nima muhim",
        msg_placeholder: "Maqsad, kontekst, cheklovlar. Iloji boricha qisqa.",
        submit: "So'rovni yuborish",
        sending: "Yuborilmoqda…",
        sent: "So'rov qabul qilindi. 24 soat ichida bog'lanaman.",
        error: "Yuborib bo'lmadi. Telegram'ga yozing — tezroq javob beraman.",
        telegram: "Telegramga",
        copied: "Ariza nusxalandi — Telegram chatga joylang",
        copy: "Nusxa olish",
      },
      scope_opts: ["Web App / MVP", "AI Avtomatlashtirish", "Telegram Bot", "Dashboard / CRM", "Landing", "Konsalting"],
      timeline_opts: ["ASAP", "1–2 hafta", "1–2 oy", "moslashuvchan"],
      links: [
        { k: "Telegram", v: "t.me/killallofthem13" },
        { k: "GitHub", v: "github.com/SamandarMansurkhodjaev2713" },
        { k: "Email", v: "sam4k27@gmail.com" },
      ],
    },
    footer: {
      copy: "© 2026 — Executive AI Code Lab",
      built: "TypeScript, Three.js, React asosida",
      tagline: "G'oyadan mahsulotgacha — bitta muhandis, to'liq tsikl.",
      nav_title: "Navigatsiya",
      contacts_title: "Kontaktlar",
      meta_title: "Ma'lumot",
      meta: ["Toshkent · UTC+5", "Javob < 24 soat", "RU · UZ · EN (boshlang'ich)"],
    },
  },
};

// ── Project catalog v2 ──────────────────────────────────────────────────────
// The original 13 cases stay authored above. New GitHub work is added here as
// product FAMILIES, not one card per repository: GrowthOps intentionally folds
// the private platform monorepo plus p03/p04/p06 into one coherent product, and
// Dostupnoe Pravo supersedes the older `delo` repository. This keeps the public
// portfolio free of duplicate cards while the source repositories remain
// independently inspectable.
const PROJECT_ADDITIONS = [
  {
    slug: "growthops-ai",
    name: "GrowthOps AI",
    status: "BUILD",
    url: "projects/growthops-ai/",
    github: "https://github.com/SamandarMansurkhodjaev2713/growthops-ai",
    stack: ["TypeScript", "Fastify", "PostgreSQL", "NestJS", "Go", "Python"],
    i18n: {
      ru: {
        tag: "AI AUTOMATION · PLATFORM",
        problem: "Операционные процессы SMB расползаются между таблицами, чатами и памятью руководителя.",
        solution: "Фабрика узких автоматизаций: детерминированное ядро, AI только там, где он оправдан, и человек перед необратимым действием.",
        role: "Product Architect + Lead Engineer",
        outcome: "31 продукт · 1023 теста · 50 live race-checks",
      },
      en: {
        tag: "AI AUTOMATION · PLATFORM",
        problem: "SMB operations fragment across spreadsheets, chats and the owner's memory.",
        solution: "A factory of narrow automations: deterministic cores, AI only where justified, and a human before irreversible action.",
        role: "Product Architect + Lead Engineer",
        outcome: "31 products · 1,023 tests · 50 live race checks",
      },
      uz: {
        tag: "AI AUTOMATION · PLATFORM",
        problem: "SMB jarayonlari jadvallar, chatlar va rahbar xotirasi orasida tarqalib ketadi.",
        solution: "Tor avtomatlashtirishlar fabrikasi: deterministik yadro, AI faqat asosli joyda va qaytarib bo‘lmas harakatdan oldin inson nazorati.",
        role: "Product Architect + Lead Engineer",
        outcome: "31 mahsulot · 1023 test · 50 live race-check",
      },
    },
  },
  {
    slug: "dostupnoe-pravo",
    name: "Доступное Право",
    status: "LIVE",
    url: "https://dostupnoe-pravo-alpha.vercel.app/",
    github: "https://github.com/SamandarMansurkhodjaev2713/dostupnoe-pravo",
    stack: ["Next.js 16", "TypeScript", "Supabase", "PostgreSQL", "Vitest"],
    i18n: {
      ru: {
        tag: "LEGALTECH · CRM",
        problem: "Частная юридическая практика теряет контекст между списком клиентов, заметками, статусами дел и следующим шагом.",
        solution: "Рабочая CRM с таблицей и Kanban, историей статусов, RLS, уведомлениями и изолированной демо-средой.",
        role: "Full-stack + Product + QA",
        outcome: "live CRM · 192 теста · CI",
      },
      en: {
        tag: "LEGALTECH · CRM",
        problem: "A small legal practice loses context between client lists, notes, case status and the next action.",
        solution: "A working CRM with table and Kanban views, status history, RLS, notifications and an isolated demo workspace.",
        role: "Full-stack + Product + QA",
        outcome: "live CRM · 192 tests · CI",
      },
      uz: {
        tag: "LEGALTECH · CRM",
        problem: "Xususiy yuridik amaliyot mijozlar, qaydlar, ish holati va keyingi qadam orasidagi kontekstni yo‘qotadi.",
        solution: "Jadval va Kanban, status tarixi, RLS, bildirishnomalar va izolyatsiyalangan demo muhiti bilan ishlaydigan CRM.",
        role: "Full-stack + Product + QA",
        outcome: "live CRM · 192 test · CI",
      },
    },
  },
  {
    slug: "ai-classroom",
    name: "AI Classroom Intelligence",
    status: "BUILD",
    url: "projects/ai-classroom/",
    github: null,
    stack: ["Python", "FastAPI", "PostgreSQL", "MinIO", "OpenCV", "Docker"],
    i18n: {
      ru: {
        tag: "EDTECH · PRIVACY AI",
        problem: "Оценка занятия превращается в непрозрачный AI-score без доказательств, контекста и права человека пересмотреть вывод.",
        solution: "Локальная evidence-first платформа: события с таймкодом, confidence, качеством данных и обязательным human review.",
        role: "AI Systems + Backend + QA",
        outcome: "on-prem foundation · traceable evidence · review flow",
      },
      en: {
        tag: "EDTECH · PRIVACY AI",
        problem: "Classroom analytics often collapses into an opaque AI score with no evidence, context or human appeal path.",
        solution: "A local evidence-first platform: timestamped events, confidence, data-quality state and mandatory human review.",
        role: "AI Systems + Backend + QA",
        outcome: "on-prem foundation · traceable evidence · review flow",
      },
      uz: {
        tag: "EDTECH · PRIVACY AI",
        problem: "Dars tahlili ko‘pincha dalil, kontekst va inson qayta ko‘rishi imkonisiz yopiq AI-bahoga aylanadi.",
        solution: "Lokal evidence-first platforma: taymkodli voqealar, confidence, ma’lumot sifati va majburiy inson tekshiruvi.",
        role: "AI Systems + Backend + QA",
        outcome: "on-prem foundation · kuzatiladigan dalil · review flow",
      },
    },
  },
  {
    slug: "car-superapp",
    name: "CAR Superapp",
    status: "BUILD",
    url: "projects/car-superapp/",
    github: null,
    stack: ["Next.js", "NestJS", "PostgreSQL", "Prisma", "Redis", "PWA"],
    i18n: {
      ru: {
        tag: "AUTO SERVICE · OPERATIONS",
        problem: "Автосервису сложно держать заказы, филиалы, согласования, медиа, оплату и клиентский статус в одном надёжном процессе.",
        solution: "Multi-tenant PWA для СТО Узбекистана с branch-scoped RLS, модульным монолитом и проверяемыми интеграционными границами.",
        role: "Product Architect + Full-stack + QA",
        outcome: "production foundation · RLS · CI · BUILD",
      },
      en: {
        tag: "AUTO SERVICE · OPERATIONS",
        problem: "Auto workshops struggle to keep orders, branches, approvals, media, payments and customer status in one reliable flow.",
        solution: "A multi-tenant PWA for Uzbekistan workshops with branch-scoped RLS, a modular monolith and verifiable integration boundaries.",
        role: "Product Architect + Full-stack + QA",
        outcome: "production foundation · RLS · CI · BUILD",
      },
      uz: {
        tag: "AUTO SERVICE · OPERATIONS",
        problem: "Avtoservis buyurtma, filial, tasdiq, media, to‘lov va mijoz holatini bitta ishonchli jarayonda ushlashda qiynaladi.",
        solution: "O‘zbekiston STОlari uchun branch-scoped RLS, modulli monolit va tekshiriladigan integratsiya chegaralariga ega multi-tenant PWA.",
        role: "Product Architect + Full-stack + QA",
        outcome: "production foundation · RLS · CI · BUILD",
      },
    },
  },
  {
    slug: "helion",
    name: "Helion",
    status: "LIVE",
    url: "https://samandarmansurkhodjaev2713.github.io/helion/",
    github: "https://github.com/SamandarMansurkhodjaev2713/helion",
    stack: ["React 18", "TypeScript", "Vite", "Canvas", "Tailwind"],
    i18n: {
      ru: {
        tag: "FRONTEND · SCROLLYTELLING",
        problem: "Портфолио-проекту сложно передать масштаб и атмосферу, не утопив пользователя в тяжёлых эффектах.",
        solution: "Кинематографичный сайт космической программы: video scrub, живой starfield, HUD и RU/UZ при контролируемом весе.",
        role: "Creative Frontend + Motion",
        outcome: "live GitHub Pages · CI · strict TypeScript",
      },
      en: {
        tag: "FRONTEND · SCROLLYTELLING",
        problem: "A showcase struggles to communicate scale and atmosphere without burying the visitor under heavy effects.",
        solution: "A cinematic space-program site with video scrubbing, a live starfield, HUD language and RU/UZ localization at a controlled bundle size.",
        role: "Creative Frontend + Motion",
        outcome: "live GitHub Pages · CI · strict TypeScript",
      },
      uz: {
        tag: "FRONTEND · SCROLLYTELLING",
        problem: "Portfolio loyihasi foydalanuvchini og‘ir effektlarga botirmasdan ko‘lam va atmosferani yetkazishi qiyin.",
        solution: "Video scrub, jonli starfield, HUD tili va nazoratli bundle bilan RU/UZ kosmik dastur sayti.",
        role: "Creative Frontend + Motion",
        outcome: "live GitHub Pages · CI · strict TypeScript",
      },
    },
  },
  {
    slug: "stones",
    name: "Stones",
    status: "LIVE",
    url: "https://samandarmansurkhodjaev2713.github.io/stones/",
    github: "https://github.com/SamandarMansurkhodjaev2713/stones",
    stack: ["React", "TypeScript", "GSAP", "Canvas", "Vite"],
    i18n: {
      ru: {
        tag: "EDITORIAL · EXPERIENCE",
        problem: "Обычный лендинг не даёт физического ощущения глубины, времени и материала.",
        solution: "Скроллителлинг-путешествие через геологические эпохи: монохромный арт-дирекшн, depth rail и RU/UZ.",
        role: "Product Design + Creative Frontend",
        outcome: "live GitHub Pages · mobile UX · QA checklist",
      },
      en: {
        tag: "EDITORIAL · EXPERIENCE",
        problem: "A conventional landing page cannot create a physical sense of depth, time and material.",
        solution: "A scrollytelling descent through geological eras with monolithic art direction, a depth rail and RU/UZ localization.",
        role: "Product Design + Creative Frontend",
        outcome: "live GitHub Pages · mobile UX · QA checklist",
      },
      uz: {
        tag: "EDITORIAL · EXPERIENCE",
        problem: "Oddiy landing chuqurlik, vaqt va materialning jismoniy hissini bera olmaydi.",
        solution: "Geologik davrlar bo‘ylab scrollytelling sayohat: monolit art-direction, depth rail va RU/UZ.",
        role: "Product Design + Creative Frontend",
        outcome: "live GitHub Pages · mobile UX · QA checklist",
      },
    },
  },
  {
    slug: "izatullo",
    name: "IZATULO / BEL ALMA",
    status: "LIVE",
    url: "https://izzatullo.uz/",
    stack: ["HTML", "CSS", "JavaScript", "Playwright", "GitHub Pages"],
    i18n: {
      ru: {
        tag: "B2B · MULTILINGUAL",
        problem: "Покупателю угля сложно быстро сравнить фракции, характеристики, документы и путь поставки.",
        solution: "Трёхъязычный B2B-сайт поставщика с каталогом, SEO, заявкой в Telegram и E2E-проверками.",
        role: "Product Design + Frontend + QA",
        outcome: "live RU/UZ/EN · SEO · Playwright E2E",
      },
      en: {
        tag: "B2B · MULTILINGUAL",
        problem: "Coal buyers need a fast way to compare grades, specifications, documents and the delivery process.",
        solution: "A trilingual supplier site with a catalog, SEO, Telegram inquiry flow and end-to-end checks.",
        role: "Product Design + Frontend + QA",
        outcome: "live RU/UZ/EN · SEO · Playwright E2E",
      },
      uz: {
        tag: "B2B · MULTILINGUAL",
        problem: "Ko‘mir xaridoriga fraksiya, texnik xususiyat, hujjat va yetkazib berish yo‘lini tez taqqoslash qiyin.",
        solution: "Katalog, SEO, Telegram so‘rovi va E2E tekshiruvlariga ega uch tilli yetkazib beruvchi sayti.",
        role: "Product Design + Frontend + QA",
        outcome: "live RU/UZ/EN · SEO · Playwright E2E",
      },
    },
  },
  {
    slug: "laplacefx",
    name: "LaplaceFX",
    status: "DEMO",
    url: "projects/laplacefx/",
    github: null,
    stack: ["Python", "FastAPI", "TimescaleDB", "Redis", "Prometheus", "Docker"],
    i18n: {
      ru: {
        tag: "FINTECH · RESEARCH",
        problem: "Торговый сигнал легко выглядит убедительно без измеренного edge, контроля риска и честной статистики.",
        solution: "Research-система для demo-счёта: объяснимый confluence, risk sizing, backtest, walk-forward и эксплуатационная телеметрия.",
        role: "Backend + Research Engineering + QA",
        outcome: "demo trading · risk gates · observability",
      },
      en: {
        tag: "FINTECH · RESEARCH",
        problem: "A trading signal can look convincing without measured edge, risk control or honest statistics.",
        solution: "A demo-account research system with explainable confluence, risk sizing, backtests, walk-forward gates and operational telemetry.",
        role: "Backend + Research Engineering + QA",
        outcome: "demo trading · risk gates · observability",
      },
      uz: {
        tag: "FINTECH · RESEARCH",
        problem: "Trading signali o‘lchangan edge, risk nazorati va halol statistikasiz ham ishonchli ko‘rinishi mumkin.",
        solution: "Demo-hisob uchun izohlanadigan confluence, risk sizing, backtest, walk-forward gate va operatsion telemetriyali research-tizim.",
        role: "Backend + Research Engineering + QA",
        outcome: "demo trading · risk gates · observability",
      },
    },
  },
];

const PROJECT_ORDER = [
  "Klawis — Legal AI Assistant",
  "CoupleOS / Softly",
  "GrowthOps AI",
  "TTYL Platform",
  "Доступное Право",
  "AI Classroom Intelligence",
  "CAR Superapp",
  "Helion",
  "Stones",
  "Sentinel Edge",
  "CardioGuard",
  "Task-manager / Task Manage Bot",
  "Marketbot",
  "IZATULO / BEL ALMA",
  "Forge / Learning OS",
  "BelfProctor",
  "LaplaceFX",
  "BioFlux Observer",
  "VFS Killer",
  "med-exe",
  "3D Landing",
];

const PROJECT_SLUGS = {
  "Klawis — Legal AI Assistant": "klawis",
  "CoupleOS / Softly": "softly",
  "TTYL Platform": "ttyl",
  "Task-manager / Task Manage Bot": "task-manager",
  "Marketbot": "marketbot",
  "Sentinel Edge": "sentinel-edge",
  "CardioGuard": "cardioguard",
  "BioFlux Observer": "bioflux",
  "Forge / Learning OS": "forge",
  "BelfProctor": "belfproctor",
  "VFS Killer": "vfs-killer",
  "med-exe": "med-exe",
  "3D Landing": "3d-landing",
};

const PROJECT_GITHUB = {
  "Task-manager / Task Manage Bot": "https://github.com/SamandarMansurkhodjaev2713/Task-manager",
  "Sentinel Edge": "https://github.com/SamandarMansurkhodjaev2713/sentinel-edge-smart-system",
  "CardioGuard": "https://github.com/SamandarMansurkhodjaev2713/cardioguard",
  "BioFlux Observer": "https://github.com/SamandarMansurkhodjaev2713/bioflux-observer",
  "3D Landing": "https://github.com/SamandarMansurkhodjaev2713/3d-landing",
};

const PROJECT_UI = {
  ru: {
    open_live: "Открыть сайт",
    github: "GitHub",
    collapse: "Свернуть",
    more_prefix: "Показать ещё ",
    more_suffix: "",
    list_label: "Список проектов",
  },
  en: {
    open_live: "Open live site",
    github: "GitHub",
    collapse: "Collapse",
    more_prefix: "Show ",
    more_suffix: " more",
    list_label: "Project list",
  },
  uz: {
    open_live: "Saytni ochish",
    github: "GitHub",
    collapse: "Yig‘ish",
    more_prefix: "Yana ",
    more_suffix: " ta ko‘rsatish",
    list_label: "Loyihalar ro‘yxati",
  },
};

Object.keys(CONTENT).forEach(function hydrateProjectCatalog(lang) {
  const section = CONTENT[lang].projects;
  const byName = new Map();

  section.items.forEach(function addExisting(item) {
    byName.set(item.name, Object.assign({}, item, {
      slug: PROJECT_SLUGS[item.name] || item.slug,
      github: PROJECT_GITHUB[item.name] || item.github || null,
    }));
  });

  PROJECT_ADDITIONS.forEach(function addNew(product) {
    const copy = product.i18n[lang] || product.i18n.ru;
    byName.set(product.name, {
      slug: product.slug,
      tag: copy.tag,
      name: product.name,
      problem: copy.problem,
      solution: copy.solution,
      role: copy.role,
      stack: product.stack.slice(),
      outcome: copy.outcome,
      status: product.status,
      url: product.url,
      github: product.github,
    });
  });

  section.items = PROJECT_ORDER.map(function orderedProject(name) {
    return byName.get(name);
  }).filter(Boolean);
  Object.assign(section, PROJECT_UI[lang]);
});

window.CONTENT = CONTENT;
