/* AUTO-GENERATED by build.js from app.jsx — DO NOT EDIT.
   Edit the .jsx source and re-run `node build.js`. */
// app.jsx — Main app: single Ember theme, fonts, scroll-driven 3D background

const {
  useEffect: useE,
  useRef: useR,
  useState: useS
} = React;

// ── Error Boundary (class component — required by React API)
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      error: null
    };
  }
  static getDerivedStateFromError(err) {
    return {
      error: err
    };
  }
  componentDidCatch(err, info) {
    console.error("[ErrorBoundary]", err, info);
  }
  render() {
    if (this.state.error) {
      return /*#__PURE__*/React.createElement("main", {
        className: "fatal-shell",
        role: "alert"
      }, /*#__PURE__*/React.createElement("span", {
        className: "fatal-code mono"
      }, "RECOVERY \xB7 01"), /*#__PURE__*/React.createElement("h1", null, "\u0418\u043D\u0442\u0435\u0440\u0444\u0435\u0439\u0441 \u043D\u0435 \u043E\u0442\u043A\u0440\u044B\u043B\u0441\u044F"), /*#__PURE__*/React.createElement("p", null, "\u041F\u0440\u043E\u0435\u043A\u0442\u044B \u0438 \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u044B \u0432 \u0431\u0435\u0437\u043E\u043F\u0430\u0441\u043D\u043E\u0441\u0442\u0438. \u041E\u0431\u043D\u043E\u0432\u0438\u0442\u0435 \u0441\u0442\u0440\u0430\u043D\u0438\u0446\u0443 \u2014 \u0435\u0441\u043B\u0438 \u0441\u0431\u043E\u0439 \u043F\u043E\u0432\u0442\u043E\u0440\u0438\u0442\u0441\u044F, \u043D\u0430\u043F\u0438\u0448\u0438\u0442\u0435 \u043C\u043D\u0435 \u043D\u0430\u043F\u0440\u044F\u043C\u0443\u044E."), /*#__PURE__*/React.createElement("div", {
        className: "fatal-actions"
      }, /*#__PURE__*/React.createElement("button", {
        type: "button",
        onClick: () => window.location.reload()
      }, "\u041E\u0431\u043D\u043E\u0432\u0438\u0442\u044C \u0441\u0442\u0440\u0430\u043D\u0438\u0446\u0443"), /*#__PURE__*/React.createElement("a", {
        href: "https://t.me/killallofthem13"
      }, "\u041D\u0430\u043F\u0438\u0441\u0430\u0442\u044C \u0432 Telegram")), /*#__PURE__*/React.createElement("span", {
        className: "fatal-foot mono"
      }, "SAMANDAR \xB7 EXECUTIVE AI CODE LAB"));
    }
    return this.props.children;
  }
}
const LINKS = {
  github: "github.com/SamandarMansurkhodjaev2713",
  telegram: "t.me/killallofthem13",
  email: "sam4k27@gmail.com"
};
const NAV_SECTIONS = ["about", "projects", "skills", "services", "cv", "faq", "contact"];
const FULL_MENU_SECTIONS = ["hero", "signal", "about", "projects", "skills", "services", "cv", "process", "builder", "faq", "trust", "contact"];
const FULL_MENU_LABELS = {
  ru: {
    hero: "Старт",
    signal: "Почему со мной",
    process: "Метод",
    builder: "Конструктор",
    trust: "Гарантия качества"
  },
  en: {
    hero: "Start",
    signal: "Why me",
    process: "Method",
    builder: "Project builder",
    trust: "Quality proof"
  },
  uz: {
    hero: "Boshlanish",
    signal: "Nega men",
    process: "Jarayon",
    builder: "Konstruktor",
    trust: "Sifat kafolati"
  }
};

// ── Haptic helper.
// `navigator.vibrate` is supported on Android Chrome and ~most Android browsers.
// iOS Safari silently no-ops — that's correct, we don't want to fight iOS.
// Calls are short (6-12ms) so they read as "click confirm", not a phone-ringer.
const HAPTIC_MS = {
  tap: 6,
  toggle: 8,
  submit: 14
};
function haptic(kind) {
  const ms = HAPTIC_MS[kind] || HAPTIC_MS.tap;
  if (typeof navigator === "undefined") return;
  if (!navigator.vibrate) return;
  try {
    navigator.vibrate(ms);
  } catch (e) {/* silently ignore — vibration is opportunistic */}
}
const TWEAK_DEFAULTS = /*EDITMODE-BEGIN*/{
  "lang": "ru",
  "theme": "claude",
  "font": "geist",
  "motion": 1,
  "density": "regular"
} /*EDITMODE-END*/;
function useScrollEngine(setActiveSection) {
  useE(() => {
    const progressEl = document.querySelector(".scroll-progress");
    let raf = 0;
    function tick() {
      raf = 0;
      const max = document.documentElement.scrollHeight - window.innerHeight;
      const y = max > 0 ? window.scrollY / max : 0;
      if (progressEl) progressEl.style.transform = `scaleX(${y.toFixed(4)})`;
    }
    function onScroll() {
      if (!raf) raf = requestAnimationFrame(tick);
    }
    window.addEventListener("scroll", onScroll, {
      passive: true
    });
    tick();
    const sections = document.querySelectorAll("section[data-section]");
    const io = new IntersectionObserver(entries => {
      entries.forEach(e => {
        if (e.isIntersecting && e.intersectionRatio > 0.3) {
          const id = e.target.getAttribute("data-section");
          setActiveSection(id);
          // Single source of truth for "which section is the reader in" —
          // acts.js (colour dramaturgy) and future engines subscribe to this.
          try {
            window.dispatchEvent(new CustomEvent("sm:section", {
              detail: {
                id
              }
            }));
          } catch (err) {/* opportunistic */}
        }
      });
    }, {
      threshold: [0.3, 0.5, 0.7]
    });
    sections.forEach(s => io.observe(s));
    return () => {
      window.removeEventListener("scroll", onScroll);
      if (raf) cancelAnimationFrame(raf);
      io.disconnect();
    };
  }, []);
}

// Labels for the section COUNTER — sections that live outside t.nav (they are
// real [data-section] chapters but not primary nav destinations).
const EXTRA_SECTION_LABELS = {
  ru: {
    hero: "Старт",
    signal: "Сигнал",
    process: "Метод",
    builder: "Конструктор",
    trust: "Качество"
  },
  en: {
    hero: "Start",
    signal: "Signal",
    process: "Method",
    builder: "Builder",
    trust: "Quality"
  },
  uz: {
    hero: "Boshlanish",
    signal: "Signal",
    process: "Metod",
    builder: "Konstruktor",
    trust: "Sifat"
  }
};

// "Flight with focus": menu/anchor navigation reads as travel through the
// site's space, not a page scroll. A vignette closes in (body::after via the
// html.is-flying class), bg-fx's own scroll-energy does the motion drama for
// free, and the landing section briefly carries .fly-in so its heading can
// flash its entrance. Native wheel/touch scrolling is untouched — this runs
// ONLY on explicit navigation clicks. Reduced-motion falls back to the plain
// jump (scroll-behavior:auto already handles the scroll itself).
function flyTo(id) {
  const el = document.getElementById(id);
  if (!el) return;
  if (window.SceneCinema && typeof window.SceneCinema.navigate === "function") {
    window.SceneCinema.navigate(id);
    return;
  }
  const reduced = typeof window.matchMedia === "function" && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  try {
    history.replaceState(null, "", "#" + id);
  } catch (e) {/* opportunistic */}
  if (!reduced) {
    document.documentElement.classList.add("is-flying");
    el.classList.add("fly-in");
    window.clearTimeout(flyTo._t1);
    window.clearTimeout(flyTo._t2);
    flyTo._t1 = window.setTimeout(() => document.documentElement.classList.remove("is-flying"), 950);
    flyTo._t2 = window.setTimeout(() => el.classList.remove("fly-in"), 1600);
  }
  try {
    el.scrollIntoView({
      behavior: reduced ? "auto" : "smooth",
      block: "start"
    });
  } catch (e) {
    window.location.hash = id;
  }
}

// Odometer-style digit drum for the section counter: remounting .drum-n on a
// number change (React key) replays the roll-in keyframe — no state to manage.
function Drum({
  value
}) {
  return /*#__PURE__*/React.createElement("span", {
    className: "drum",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("span", {
    key: value,
    className: "drum-n"
  }, value));
}

// Per-chapter accents for the menu preview. Deliberately the SAME values
// acts.js paints when you arrive, so the peek is a promise the page keeps.
// Kept as a plain map rather than read from acts.js: the menu must render
// correctly even if that engine failed to load.
const MENU_ACCENT = {
  hero: "110, 139, 166",
  signal: "110, 139, 166",
  about: "217, 119, 87",
  projects: "205, 122, 74",
  skills: "122, 145, 168",
  services: "196, 160, 108",
  cv: "122, 145, 168",
  process: "122, 145, 168",
  builder: "196, 160, 108",
  faq: "196, 160, 108",
  trust: "200, 155, 94",
  contact: "200, 155, 94"
};
function Nav({
  t,
  lang,
  setLang,
  active
}) {
  const [open, setOpen] = useS(false);
  const [peek, setPeek] = useS(null);
  // Capsule state — the bar condenses into a floating pill once the reader
  // leaves the very top. Passive + rAF-throttled; no layout reads besides scrollY.
  const [capsule, setCapsule] = useS(false);
  // Real chapter order straight from the DOM — single source of truth shared
  // with the dock (same querySelectorAll pattern), so the counter can never
  // disagree with the actual page.
  const [secOrder, setSecOrder] = useS([]);
  const [clock, setClock] = useS("");
  useE(() => {
    setSecOrder([...document.querySelectorAll("section[data-section]")].map(el => el.getAttribute("data-section")));
    let raf = 0;
    function read() {
      raf = 0;
      setCapsule(window.scrollY > 64);
    }
    function onScroll() {
      if (!raf) raf = requestAnimationFrame(read);
    }
    window.addEventListener("scroll", onScroll, {
      passive: true
    });
    read();
    return () => {
      window.removeEventListener("scroll", onScroll);
      if (raf) cancelAnimationFrame(raf);
    };
  }, []);

  // Lock scroll while the fullscreen menu is open; Escape closes. The live
  // Tashkent clock only ticks while the menu is visible (zero idle cost).
  useE(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const onKey = e => {
      if (e.key === "Escape") setOpen(false);
    };
    window.addEventListener("keydown", onKey);
    function tick() {
      const d = new Date(Date.now() + (5 * 60 + new Date().getTimezoneOffset()) * 60000);
      setClock([d.getHours(), d.getMinutes(), d.getSeconds()].map(n => String(n).padStart(2, "0")).join(":"));
    }
    tick();
    const iv = window.setInterval(tick, 1000);
    return () => {
      document.body.style.overflow = prev;
      window.removeEventListener("keydown", onKey);
      window.clearInterval(iv);
    };
  }, [open]);
  const total = secOrder.length || 11;
  const idx = Math.max(0, secOrder.indexOf(active));
  const num = String(idx + 1).padStart(2, "0");
  const extra = EXTRA_SECTION_LABELS[lang] || EXTRA_SECTION_LABELS.ru;
  const activeLabel = t.nav[active] || extra[active] || "";
  const progress = total > 1 ? idx / (total - 1) : 0;
  function go(e, id) {
    e.preventDefault();
    setOpen(false);
    flyTo(id);
  }
  return (
    /*#__PURE__*/
    // The fullscreen menu is a SIBLING of <nav>, not a child. <nav> carries a
    // backdrop-filter, and a filtered element becomes the containing block for
    // its position:fixed descendants — which trapped the "fullscreen" menu
    // inside the 60px bar (it opened, but as a 1280x59 sliver). Keeping it
    // outside is the only robust fix; z-index keeps the burger clickable above it.
    React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("nav", {
      className: `nav ${open ? "nav-open" : ""} ${capsule ? "is-capsule" : ""}`
    }, /*#__PURE__*/React.createElement("div", {
      className: "nav-inner"
    }, /*#__PURE__*/React.createElement("a", {
      href: "#hero",
      className: "brand",
      "data-cursor": "link",
      "data-cursor-label": "\u2191 top",
      onClick: e => go(e, "hero")
    }, /*#__PURE__*/React.createElement("span", {
      className: "brand-mark"
    }), /*#__PURE__*/React.createElement("span", {
      className: "brand-name"
    }, "SAMANDAR", /*#__PURE__*/React.createElement("span", {
      className: "brand-sub"
    }, " \xB7 EXEC.AI.LAB"))), /*#__PURE__*/React.createElement("div", {
      className: "nav-counter mono",
      "aria-hidden": "true"
    }, /*#__PURE__*/React.createElement(Drum, {
      value: num
    }), /*#__PURE__*/React.createElement("span", {
      className: "nav-counter-sep"
    }, "/ ", String(total).padStart(2, "0")), /*#__PURE__*/React.createElement("span", {
      key: active,
      className: "nav-counter-name"
    }, activeLabel), /*#__PURE__*/React.createElement("span", {
      className: "nav-counter-track"
    }, /*#__PURE__*/React.createElement("i", {
      style: {
        transform: `scaleX(${progress})`
      }
    }))), /*#__PURE__*/React.createElement("ul", {
      className: "nav-links"
    }, NAV_SECTIONS.map(k => /*#__PURE__*/React.createElement("li", {
      key: k
    }, /*#__PURE__*/React.createElement("a", {
      href: `#${k}`,
      onClick: e => go(e, k),
      className: active === k ? "active" : "",
      "data-cursor": "link",
      "data-cursor-label": `→ ${t.nav[k]}`
    }, t.nav[k])))), /*#__PURE__*/React.createElement("div", {
      className: "nav-right"
    }, /*#__PURE__*/React.createElement("div", {
      className: "lang",
      role: "group",
      "aria-label": "language"
    }, ["ru", "en", "uz"].map(L => /*#__PURE__*/React.createElement("button", {
      key: L,
      onClick: () => setLang(L),
      className: lang === L ? "active" : "",
      "aria-pressed": lang === L
    }, L.toUpperCase()))), /*#__PURE__*/React.createElement("a", {
      href: "#contact",
      className: "nav-cta",
      "data-magnetic": true,
      "data-cursor": "send",
      "data-cursor-label": "send \u2192 contact",
      onClick: e => go(e, "contact")
    }, /*#__PURE__*/React.createElement("span", {
      className: "nav-cta-dot",
      "aria-hidden": "true"
    }), t.hero.cta_primary), /*#__PURE__*/React.createElement("button", {
      type: "button",
      className: "nav-burger",
      "aria-label": open ? "Close menu" : "Open menu",
      "aria-expanded": open,
      onClick: () => {
        haptic("toggle");
        setOpen(o => !o);
      }
    }, /*#__PURE__*/React.createElement("span", null), /*#__PURE__*/React.createElement("span", null), /*#__PURE__*/React.createElement("span", null))))), /*#__PURE__*/React.createElement("div", {
      className: `nav-menu ${open ? "is-open" : ""}`,
      "aria-hidden": !open
    }, /*#__PURE__*/React.createElement("div", {
      className: "nav-menu-glow",
      "aria-hidden": "true"
    }), /*#__PURE__*/React.createElement("div", {
      className: "nav-menu-inner"
    }, /*#__PURE__*/React.createElement("ul", {
      className: "nav-menu-links",
      onMouseLeave: () => setPeek(null)
    }, FULL_MENU_SECTIONS.map((k, i) => /*#__PURE__*/React.createElement("li", {
      key: k,
      style: {
        "--i": i
      }
    }, /*#__PURE__*/React.createElement("a", {
      href: `#${k}`,
      onClick: e => go(e, k),
      className: active === k ? "active" : "",
      onMouseEnter: () => setPeek({
        k,
        i
      }),
      onFocus: () => setPeek({
        k,
        i
      })
    }, /*#__PURE__*/React.createElement("span", {
      className: "nav-menu-num mono"
    }, String(i + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("span", {
      className: "nav-menu-mask"
    }, /*#__PURE__*/React.createElement("span", {
      className: "nav-menu-word"
    }, t.nav[k] || FULL_MENU_LABELS[lang][k])), /*#__PURE__*/React.createElement("span", {
      className: "nav-menu-arrow",
      "aria-hidden": "true"
    }, "\u2192"))))), /*#__PURE__*/React.createElement("div", {
      className: `nav-peek ${peek ? "is-on" : ""}`,
      "aria-hidden": "true"
    }, /*#__PURE__*/React.createElement("div", {
      className: "nav-peek-wash",
      style: peek ? {
        background: `radial-gradient(ellipse 90% 80% at 50% 20%, rgba(${MENU_ACCENT[peek.k] || "217, 119, 87"}, 0.30), transparent 70%)`
      } : undefined
    }), /*#__PURE__*/React.createElement("div", {
      key: peek ? peek.k : "none",
      className: "nav-peek-body"
    }, /*#__PURE__*/React.createElement("span", {
      className: "nav-peek-num",
      style: peek ? {
        color: `rgb(${MENU_ACCENT[peek.k] || "217, 119, 87"})`
      } : undefined
    }, peek ? String(peek.i + 1).padStart(2, "0") : "00"), /*#__PURE__*/React.createElement("span", {
      className: "nav-peek-name"
    }, peek ? t.nav[peek.k] || FULL_MENU_LABELS[lang][peek.k] : ""))), /*#__PURE__*/React.createElement("div", {
      className: "nav-menu-foot"
    }, /*#__PURE__*/React.createElement("a", {
      href: "#contact",
      className: "nav-menu-cta",
      "data-magnetic": true,
      onClick: e => go(e, "contact")
    }, t.hero.cta_primary, " ", /*#__PURE__*/React.createElement("span", {
      className: "arrow"
    }, "\u2192")), /*#__PURE__*/React.createElement("button", {
      type: "button",
      className: "sound-toggle mono",
      "aria-label": "Toggle UI sound"
    }, /*#__PURE__*/React.createElement("span", {
      className: "sound-toggle-dot",
      "aria-hidden": "true"
    }), "SOUND"), /*#__PURE__*/React.createElement("div", {
      className: "lang nav-menu-lang",
      role: "group",
      "aria-label": "language"
    }, ["ru", "en", "uz"].map(L => /*#__PURE__*/React.createElement("button", {
      key: L,
      onClick: () => setLang(L),
      className: lang === L ? "active" : "",
      "aria-pressed": lang === L
    }, L.toUpperCase()))), /*#__PURE__*/React.createElement("div", {
      className: "nav-menu-tele mono"
    }, /*#__PURE__*/React.createElement("span", null, "TASHKENT \xB7 41.31\xB0N 69.24\xB0E"), /*#__PURE__*/React.createElement("span", null, "UTC+5 \xB7 ", clock), /*#__PURE__*/React.createElement("span", null, "EXECUTIVE AI CODE LAB \xB7 v.2026"))))))
  );
}

// ── Mobile UI overlay primitives ──────────────────────────────────────────
// Both dock + sticky CTA share the same visibility rule: appear after the user
// scrolls past hero, hide near contact. We use the SAME hooks rather than two
// observers to keep the truth source single and avoid races between them.

function useMidScrollVisibility() {
  const [visible, setVisible] = useS(false);
  useE(() => {
    const heroEl = document.getElementById("hero");
    const contactEl = document.getElementById("contact");
    if (!heroEl || !contactEl) return undefined;

    // Truth source: IntersectionObserver where available.
    let inHero = true;
    let inContact = false;
    const io = new IntersectionObserver(entries => {
      entries.forEach(e => {
        if (e.target.id === "hero") inHero = e.isIntersecting;else if (e.target.id === "contact") inContact = e.isIntersecting;
      });
      setVisible(!inHero && !inContact);
    }, {
      threshold: 0.1
    });
    io.observe(heroEl);
    io.observe(contactEl);

    // Scroll-based fallback — covers environments where IO is unreliable
    // (some embedded webviews, headless previews). Computes visibility from
    // bounding rects each rAF-throttled scroll event.
    let raf = 0;
    function recompute() {
      raf = 0;
      const vh = window.innerHeight;
      const heroRect = heroEl.getBoundingClientRect();
      const contactRect = contactEl.getBoundingClientRect();
      const heroVisible = heroRect.top < vh && heroRect.bottom > 0;
      const contactVisible = contactRect.top < vh && contactRect.bottom > 0;
      inHero = heroVisible;
      inContact = contactVisible;
      setVisible(!heroVisible && !contactVisible);
    }
    function onScroll() {
      if (!raf) raf = requestAnimationFrame(recompute);
    }
    window.addEventListener("scroll", onScroll, {
      passive: true
    });
    window.addEventListener("resize", onScroll, {
      passive: true
    });
    recompute();
    return function cleanup() {
      io.disconnect();
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
      if (raf) cancelAnimationFrame(raf);
    };
  }, []);
  return visible;
}

// The page has 11 real [data-section] chapters, but the dock only has room for
// the 7 that mirror the primary nav menu (about/projects/skills/services/cv/
// faq/contact) — signal, process ("Method") and trust ("Quality") ride between
// them with no dot of their own. The OLD logic compared activeSection to
// NAV_SECTIONS with a plain `indexOf`: for any of those 3 "gap" sections that
// returns -1, which silently fell back to index 0 ("about") for BOTH the label
// text and (via a separate, un-synced comparison) left every dot unlit — so a
// reader deep in Method or Quality saw the indicator confidently claim "01 · О
// себе" while no dot agreed with it. That's the "misleading" bug.
// Fix: resolve every real section to the nearest NAV_SECTIONS entry AT OR
// BEFORE it in actual DOM order (standard scrollspy behavior — highlight the
// last landmark the reader has passed) and derive BOTH the dot and the label
// from that single resolved index, so they can never disagree.
function useSectionOrder() {
  const [order, setOrder] = useS(null);
  useE(() => {
    setOrder([...document.querySelectorAll("[data-section]")].map(el => el.getAttribute("data-section")));
  }, []);
  return order;
}
function resolveNavIndex(activeSection, order) {
  if (!order) return 0;
  const pos = order.indexOf(activeSection);
  if (pos === -1) return 0;
  for (let i = pos; i >= 0; i--) {
    const navIdx = NAV_SECTIONS.indexOf(order[i]);
    if (navIdx !== -1) return navIdx;
  }
  return 0; // nothing but hero/signal precede us — next landmark is "about"
}
function MobileScrollDock({
  t,
  lang,
  activeSection,
  visible
}) {
  // 6 dots for the main NAV sections. Tap → smooth scroll + light haptic.
  function onDotClick(id) {
    haptic("tap");
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({
      behavior: "smooth",
      block: "start"
    });
  }
  const order = useSectionOrder();
  const activeIdx = resolveNavIndex(activeSection, order);
  const activeId = NAV_SECTIONS[activeIdx];
  const extra = EXTRA_SECTION_LABELS[lang] || EXTRA_SECTION_LABELS.ru;
  const activeLabel = t.nav && t.nav[activeSection] || extra[activeSection] || t.nav && t.nav[activeId] || "";
  const chapterIdx = Math.max(0, (order || []).indexOf(activeSection));
  return /*#__PURE__*/React.createElement("div", {
    className: `mobile-dock ${visible ? "is-visible" : ""}`,
    role: "navigation",
    "aria-label": "sections"
  }, /*#__PURE__*/React.createElement("ol", {
    className: "mobile-dock-dots"
  }, NAV_SECTIONS.map((id, i) => /*#__PURE__*/React.createElement("li", {
    key: id
  }, /*#__PURE__*/React.createElement("button", {
    type: "button",
    className: `mobile-dock-dot ${i === activeIdx ? "is-active" : ""}`,
    "aria-label": t.nav && t.nav[id] ? t.nav[id] : id,
    onClick: () => onDotClick(id)
  })))), /*#__PURE__*/React.createElement("div", {
    className: "mobile-dock-label mono",
    "aria-live": "polite"
  }, /*#__PURE__*/React.createElement("span", {
    className: "mobile-dock-label-num"
  }, "/", String(chapterIdx + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("span", null, activeLabel)), /*#__PURE__*/React.createElement("a", {
    className: "mobile-dock-cta",
    href: "#contact",
    onClick: () => haptic("toggle")
  }, /*#__PURE__*/React.createElement("span", null, t.hero.cta_primary), /*#__PURE__*/React.createElement("span", {
    className: "arrow",
    "aria-hidden": "true"
  }, "\u2192")));
}
function MobileStickyCta({
  t,
  visible
}) {
  function onTap() {
    haptic("toggle");
  }
  return /*#__PURE__*/React.createElement("a", {
    href: "#contact",
    className: `mobile-sticky-cta ${visible ? "is-visible" : ""}`,
    onClick: onTap,
    "aria-label": t.hero.cta_primary
  }, /*#__PURE__*/React.createElement("span", null, t.hero.cta_primary), /*#__PURE__*/React.createElement("span", {
    className: "arrow"
  }, "\u2192"));
}
function PortfolioTweaks({
  t,
  setTweak
}) {
  const fontOptions = Object.keys(window.FONT_STACKS);
  return /*#__PURE__*/React.createElement(TweaksPanel, null, /*#__PURE__*/React.createElement(TweakSection, {
    label: "Language"
  }), /*#__PURE__*/React.createElement(TweakRadio, {
    label: "Lang",
    value: t.lang,
    options: ["ru", "en", "uz"],
    onChange: v => setTweak("lang", v)
  }), /*#__PURE__*/React.createElement(TweakSection, {
    label: "Font"
  }), /*#__PURE__*/React.createElement(TweakSelect, {
    label: "Font",
    value: t.font,
    options: fontOptions,
    onChange: v => setTweak("font", v)
  }), /*#__PURE__*/React.createElement(TweakSection, {
    label: "Layout"
  }), /*#__PURE__*/React.createElement(TweakRadio, {
    label: "Density",
    value: t.density,
    options: ["compact", "regular", "airy"],
    onChange: v => setTweak("density", v)
  }), /*#__PURE__*/React.createElement(TweakSlider, {
    label: "Motion",
    value: t.motion,
    min: 0,
    max: 1.6,
    step: 0.1,
    onChange: v => setTweak("motion", v)
  }));
}
function App() {
  const [tweaks, setTweak] = useTweaks(TWEAK_DEFAULTS);
  const [activeSection, setActiveSection] = useS("hero");
  const [coreReady, setCoreReady] = useS(false);
  const canvasRef = useR(null);
  const lang = tweaks.lang in window.CONTENT ? tweaks.lang : "ru";
  const t = window.CONTENT[lang];

  // Backfill CV doc fields (id, langs, strengths, foot) so the resume layout
  // renders even if the content bundles haven't been extended yet.
  useE(() => {
    const I18N = {
      ru: {
        id: {
          name: "Самандар",
          role: "Full-Stack · AI Automation · QA",
          meta: ["Ташкент · UTC+5", "Открыт к проектам", "3 курс · Software Engineering"],
          stats: [{
            k: "опыт",
            v: "2 года"
          }, {
            k: "проектов",
            v: "10+"
          }, {
            k: "стек",
            v: "TS / Py / SQL"
          }, {
            k: "ответ",
            v: "< 24h"
          }]
        },
        exp_title: "опыт",
        langs_title: "языки",
        strengths_title: "сильные стороны",
        strengths: [{
          t: "Системное мышление от прод-идеи до прод-деплоя",
          p: "TTYL Platform — от архитектуры и API до деплоя и багфиксов в проде: весь цикл на одном человеке."
        }, {
          t: "AI-интеграции уровня продакшна, не демки",
          p: "Klawis (klawis.uz): RAG, гибридный поиск и цитирование источников в живом юридическом AI-продукте."
        }, {
          t: "Качество как часть разработки, а не отдельный этап",
          p: "QA на TTYL: test plans, Playwright E2E со скриншотами и traces, контроль регрессий перед релизом."
        }, {
          t: "Тёплая коммуникация с клиентами — проверено на практике",
          p: "UniCall: специалист по работе с клиентами, лучший сотрудник месяца за качество коммуникации."
        }],
        langs: [{
          k: "Русский",
          lv: 100,
          label: "native"
        }, {
          k: "Oʻzbek",
          lv: 92,
          label: "свободный"
        }, {
          k: "English",
          lv: 85,
          label: "C1 · продвинутый"
        }],
        foot: "сгенерировано 2026 · подписанная версия по запросу"
      },
      en: {
        id: {
          name: "Samandar",
          role: "Full-Stack · AI Automation · QA",
          meta: ["Tashkent · UTC+5", "Open to projects", "3rd-year · Software Engineering"],
          stats: [{
            k: "experience",
            v: "2 yrs"
          }, {
            k: "projects",
            v: "10+"
          }, {
            k: "stack",
            v: "TS / Py / SQL"
          }, {
            k: "reply",
            v: "< 24h"
          }]
        },
        exp_title: "experience",
        langs_title: "languages",
        strengths_title: "strengths",
        strengths: [{
          t: "End-to-end ownership from product idea to prod deploy",
          p: "TTYL Platform — from architecture and API to deploy and prod bugfixes: the whole cycle on one person."
        }, {
          t: "Production AI integrations, not demos",
          p: "Klawis (klawis.uz): RAG, hybrid search and source citation in a live legal AI product."
        }, {
          t: "Quality baked into building, not a separate stage",
          p: "QA at TTYL: test plans, Playwright E2E with screenshots and traces, regression control before release."
        }, {
          t: "Warm client communication — proven in practice",
          p: "UniCall: customer support specialist, employee of the month for communication quality."
        }],
        langs: [{
          k: "Russian",
          lv: 100,
          label: "native"
        }, {
          k: "Uzbek",
          lv: 92,
          label: "fluent"
        }, {
          k: "English",
          lv: 85,
          label: "C1 · advanced"
        }],
        foot: "generated 2026 · signed copy on request"
      },
      uz: {
        id: {
          name: "Samandar",
          role: "Full-Stack · AI Automation · QA",
          meta: ["Toshkent · UTC+5", "Loyihalarga ochiq", "3-kurs · Software Engineering"],
          stats: [{
            k: "tajriba",
            v: "2 yil"
          }, {
            k: "loyiha",
            v: "10+"
          }, {
            k: "stek",
            v: "TS / Py / SQL"
          }, {
            k: "javob",
            v: "< 24h"
          }]
        },
        exp_title: "tajriba",
        langs_title: "tillar",
        strengths_title: "kuchli tomonlar",
        strengths: [{
          t: "Mahsulot g'oyasidan prod-deploygacha to'liq egalik",
          p: "TTYL Platform — arxitektura va API'dan deploy va prod-bagfikslargacha: butun sikl bitta odamda."
        }, {
          t: "Production darajadagi AI integratsiyalar",
          p: "Klawis (klawis.uz): jonli yuridik AI-mahsulotda RAG, gibrid qidiruv va manba iqtiboslari."
        }, {
          t: "Sifat — bosqich emas, ishlab chiqishning bir qismi",
          p: "TTYL'da QA: test-rejalar, Playwright E2E skrinshot va traces bilan, relizdan oldin regressiya nazorati."
        }, {
          t: "Mijozlar bilan iliq muloqot — amaliyotda sinalgan",
          p: "UniCall: mijozlar bilan ishlash bo'yicha mutaxassis, muloqot sifati uchun oyning eng yaxshi xodimi."
        }],
        langs: [{
          k: "Ruscha",
          lv: 100,
          label: "native"
        }, {
          k: "Oʻzbek",
          lv: 92,
          label: "erkin"
        }, {
          k: "English",
          lv: 85,
          label: "C1 · ilg'or"
        }],
        foot: "2026 yil · imzolangan nusxa so'rov asosida"
      }
    };
    Object.entries(I18N).forEach(([L, patch]) => {
      const cv = window.CONTENT?.[L]?.cv;
      if (!cv) return;
      for (const k of Object.keys(patch)) if (cv[k] == null) cv[k] = patch[k];
    });
  }, []);

  // Publish the single theme identity. Palette values live in CSS so first
  // paint and hydrated paint always share one source of truth.
  useE(() => {
    window.applyTheme(tweaks.theme);
  }, [tweaks.theme]);
  useE(() => {
    window.applyFontStack(tweaks.font);
  }, [tweaks.font]);

  // Deep-link scroll — on a fresh load carrying a #section or #proj-<slug> hash
  // (returning from a product landing, or any shared section link), jump to that
  // target once it has rendered AND become visible. The collapsed projects grid
  // may need a frame to expand (Projects has its own effect for that), so we
  // retry across frames until the element is on-screen. Cards centre in view;
  // sections align to their top (scroll-margin-top clears the fixed nav). The
  // intro loader is already skipped for hashed loads (index.html head-boot), so
  // this lands cleanly instead of after a curtain + top-of-page.
  useE(() => {
    const id = (window.location.hash || "").replace(/^#/, "");
    if (!id) return;
    if ("scrollRestoration" in history) {
      try {
        history.scrollRestoration = "manual";
      } catch (e) {/* opportunistic */}
    }
    let cancelled = false;
    const timers = [];
    function cancelOnIntent() {
      cancelled = true;
    }
    window.addEventListener("wheel", cancelOnIntent, {
      passive: true,
      once: true
    });
    window.addEventListener("touchstart", cancelOnIntent, {
      passive: true,
      once: true
    });
    window.addEventListener("pointerdown", cancelOnIntent, {
      passive: true,
      once: true
    });
    window.addEventListener("keydown", cancelOnIntent, {
      once: true
    });
    function tryScroll() {
      if (cancelled) return;
      const el = document.getElementById(id);
      if (el && el.offsetParent !== null) {
        // Force an instant jump even though the root stylesheet declares
        // smooth scrolling. This prevents the delayed two-stage return that
        // was visible for cards near the end of the 21-item catalog.
        const root = document.documentElement;
        const previous = root.style.scrollBehavior;
        root.style.scrollBehavior = "auto";
        try {
          el.scrollIntoView({
            behavior: "instant",
            block: id.indexOf("proj-") === 0 ? "center" : "start"
          });
        } finally {
          root.style.scrollBehavior = previous;
        }
      }
    }
    // React mount, project expansion and pin-host binding each change layout at
    // a different moment. Re-assert the same deterministic target across those
    // milestones, but stop instantly on any real user intent so the page never
    // fights manual scrolling.
    [0, 120, 360, 760, 1280].forEach(delay => {
      timers.push(window.setTimeout(tryScroll, delay));
    });
    return () => {
      cancelled = true;
      timers.forEach(timer => window.clearTimeout(timer));
      window.removeEventListener("wheel", cancelOnIntent);
      window.removeEventListener("touchstart", cancelOnIntent);
      window.removeEventListener("pointerdown", cancelOnIntent);
      window.removeEventListener("keydown", cancelOnIntent);
    };
  }, []);
  useE(() => {
    document.documentElement.setAttribute("data-density", tweaks.density);
    document.documentElement.setAttribute("lang", lang);
  }, [tweaks.density, lang]);
  useE(() => {
    document.documentElement.style.setProperty("--motion", String(tweaks.motion));
  }, [tweaks.motion]);

  // Apply theme/font once on mount.
  useE(() => {
    window.applyTheme(tweaks.theme);
    window.applyFontStack(tweaks.font);
    setCoreReady(true);
  }, []);
  useScrollEngine(setActiveSection);

  // Motion: init smart cursor + reveal observers after first paint, refresh on lang change.
  // isInViewport check in motion.js handles the "no-flash" problem for visible elements.
  useE(() => {
    document.body.classList.add("page-loaded");
    // One reactive policy owns reduced motion and measured performance. Low
    // tier trims expensive continuous movement through CSS, but never removes
    // semantic DOM or sticky contracts irreversibly — a device may recover and
    // earn a higher tier during the same visit.
    var motionPolicy = window.__SM_MOTION_POLICY || window.__SM_PERF;
    var applyMotionPolicy = function (tier, state) {
      var reduced = !!(state && state.reducedMotion);
      var lite = tier === "low" || reduced;
      document.documentElement.toggleAttribute("data-motion-lite", lite);
      document.documentElement.toggleAttribute("data-reduced-motion", reduced);
    };
    var unsubscribeMotionPolicy = function () {};
    if (motionPolicy && typeof motionPolicy.on === "function") {
      unsubscribeMotionPolicy = motionPolicy.on(applyMotionPolicy);
    } else {
      var prefersReduced = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
      applyMotionPolicy(prefersReduced ? "low" : "high", {
        reducedMotion: prefersReduced
      });
    }
    if (window.Motion) window.Motion.init();
    // Wire the View Transitions API navigator. It binds a global click handler
    // on anchor[href^="#"] and replaces the default scroll with a cinematic
    // cross-fade. Safe to call multiple times — second call is a no-op.
    if (window.SceneCinema && typeof window.SceneCinema.init === "function") {
      window.SceneCinema.init();
    }
    return () => {
      unsubscribeMotionPolicy();
      if (window.SceneCinema && typeof window.SceneCinema.dispose === "function") {
        window.SceneCinema.dispose();
      }
      if (window.Motion && typeof window.Motion.dispose === "function") {
        window.Motion.dispose();
      }
    };
  }, []);
  useE(() => {
    if (!window.Motion) return;
    const id = requestAnimationFrame(() => window.Motion.refresh());
    return () => cancelAnimationFrame(id);
  }, [lang, tweaks.density]);

  // Mid-scroll visibility for mobile dock + sticky CTA.
  const midScrollVisible = useMidScrollVisibility();
  return /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("a", {
    href: "#main",
    className: "skip-link"
  }, t.nav && t.nav.skip || "К содержимому"), /*#__PURE__*/React.createElement("div", {
    className: "bg-noise"
  }), /*#__PURE__*/React.createElement("div", {
    className: "scroll-progress"
  }), /*#__PURE__*/React.createElement(Nav, {
    t: t,
    lang: lang,
    setLang: v => setTweak("lang", v),
    active: activeSection
  }), /*#__PURE__*/React.createElement("main", {
    id: "main"
  }, /*#__PURE__*/React.createElement("div", {
    className: "pin-host pin-host--hero"
  }, /*#__PURE__*/React.createElement(Hero, {
    t: t,
    links: LINKS
  }), /*#__PURE__*/React.createElement(Signal, {
    t: t
  })), /*#__PURE__*/React.createElement(Interlude, {
    data: (t.interludes || [])[0],
    index: 0
  }), /*#__PURE__*/React.createElement(About, {
    t: t
  }), /*#__PURE__*/React.createElement(Projects, {
    t: t
  }), /*#__PURE__*/React.createElement(ProjectBuilder, {
    t: t,
    links: LINKS
  }), /*#__PURE__*/React.createElement(Skills, {
    t: t
  }), /*#__PURE__*/React.createElement("div", {
    className: "pin-host",
    "data-pin": true
  }, /*#__PURE__*/React.createElement(Services, {
    t: t
  }), /*#__PURE__*/React.createElement(CV, {
    t: t,
    links: LINKS
  })), /*#__PURE__*/React.createElement(Process, {
    t: t
  }), /*#__PURE__*/React.createElement(Faq, {
    t: t
  }), /*#__PURE__*/React.createElement("div", {
    className: "pin-host",
    "data-pin": true
  }, /*#__PURE__*/React.createElement(Trust, {
    t: t
  }), /*#__PURE__*/React.createElement(Interlude, {
    data: (t.interludes || [])[1],
    index: 1
  }), /*#__PURE__*/React.createElement(Contact, {
    t: t,
    links: LINKS
  }))), /*#__PURE__*/React.createElement(Footer, {
    t: t,
    links: LINKS
  }), /*#__PURE__*/React.createElement(MobileScrollDock, {
    t: t,
    lang: lang,
    activeSection: activeSection,
    visible: midScrollVisible && activeSection !== "contact"
  }), /*#__PURE__*/React.createElement(PortfolioTweaks, {
    t: tweaks,
    setTweak: setTweak
  }));
}
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(ErrorBoundary, null, /*#__PURE__*/React.createElement(App, null)));