/* AUTO-GENERATED by build.js from app.jsx — DO NOT EDIT.
   Edit the .jsx source and re-run `node build.js`. */
// app.jsx — Main app with scene-engine, themes, fonts, scroll-driven 3D

const {
  useEffect: useE,
  useRef: useR,
  useState: useS
} = React;

// ── Error Boundary (class component — required by React API)
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      error: null
    };
  }
  static getDerivedStateFromError(err) {
    return {
      error: err
    };
  }
  componentDidCatch(err, info) {
    console.error("[ErrorBoundary]", err, info);
  }
  render() {
    if (this.state.error) {
      return React.createElement("div", {
        style: {
          position: "fixed",
          inset: 0,
          background: "#07090B",
          color: "#B8FF3D",
          fontFamily: "monospace",
          fontSize: "13px",
          padding: "80px 40px",
          zIndex: 9999,
          overflowY: "auto",
          whiteSpace: "pre-wrap"
        }
      }, "⚠ RENDER ERROR\n\n" + String(this.state.error) + "\n\n" + (this.state.error.stack || ""));
    }
    return this.props.children;
  }
}
const LINKS = {
  github: "github.com/your-username",
  telegram: "t.me/your-username",
  email: "hello@example.com"
};
const NAV_SECTIONS = ["about", "projects", "skills", "services", "cv", "contact"];

// ── Haptic helper.
// `navigator.vibrate` is supported on Android Chrome and ~most Android browsers.
// iOS Safari silently no-ops — that's correct, we don't want to fight iOS.
// Calls are short (6-12ms) so they read as "click confirm", not a phone-ringer.
const HAPTIC_MS = {
  tap: 6,
  toggle: 8,
  submit: 14
};
function haptic(kind) {
  const ms = HAPTIC_MS[kind] || HAPTIC_MS.tap;
  if (typeof navigator === "undefined") return;
  if (!navigator.vibrate) return;
  try {
    navigator.vibrate(ms);
  } catch (e) {/* silently ignore — vibration is opportunistic */}
}
const TWEAK_DEFAULTS = /*EDITMODE-BEGIN*/{
  "lang": "ru",
  "theme": "claude",
  "font": "geist",
  "motion": 1,
  "density": "regular"
} /*EDITMODE-END*/;
function useScrollEngine(bgFxRef, setActiveSection) {
  useE(() => {
    const progressEl = document.querySelector(".scroll-progress");
    let raf = 0;
    function tick() {
      raf = 0;
      const max = document.documentElement.scrollHeight - window.innerHeight;
      const y = max > 0 ? window.scrollY / max : 0;
      if (progressEl) progressEl.style.width = `${(y * 100).toFixed(2)}%`;
      if (bgFxRef.current && bgFxRef.current.setScroll) bgFxRef.current.setScroll(y);
    }
    function onScroll() {
      if (!raf) raf = requestAnimationFrame(tick);
    }
    window.addEventListener("scroll", onScroll, {
      passive: true
    });
    tick();
    const sections = document.querySelectorAll("section[data-section]");
    const io = new IntersectionObserver(entries => {
      entries.forEach(e => {
        if (e.isIntersecting && e.intersectionRatio > 0.3) {
          const id = e.target.getAttribute("data-section");
          setActiveSection(id);
          if (bgFxRef.current && bgFxRef.current.setSection) bgFxRef.current.setSection(id);
        }
      });
    }, {
      threshold: [0.3, 0.5, 0.7]
    });
    sections.forEach(s => io.observe(s));
    return () => {
      window.removeEventListener("scroll", onScroll);
      if (raf) cancelAnimationFrame(raf);
      io.disconnect();
    };
  }, []);
}

// v54 — three showcased themes selected by the navbar segmented switcher.
// Order is meaningful (left → right): Ember (warm), Cortex (cool),
// Sage (calm). Keys match window.THEMES; "claude" is the internal key for
// the Ember theme (kept for localStorage backward compat).
const NAV_THEME_KEYS = ["claude", "cortex", "sage"];
function Nav({
  t,
  lang,
  setLang,
  active,
  theme,
  setTheme
}) {
  const [open, setOpen] = useS(false);

  // Pick a theme via the choreographed wave transition. The wave starts
  // from the centre of the clicked segment; the actual theme swap runs
  // hidden under the wave's full-coverage frame. Falls back to an instant
  // setTheme if the ThemeTransition module didn't load (graceful degrade).
  function onThemePick(key, ev) {
    if (key === theme) return; // already active — no-op
    if (!NAV_THEME_KEYS.includes(key)) return;
    haptic("toggle");
    const nextDef = window.THEMES && window.THEMES[key] ? window.THEMES[key] : null;
    const applyFn = function applyThemeChoice() {
      setTheme(key);
    };
    if (window.ThemeTransition && typeof window.ThemeTransition.run === "function") {
      let originX;
      let originY;
      if (ev && ev.currentTarget && ev.currentTarget.getBoundingClientRect) {
        const r = ev.currentTarget.getBoundingClientRect();
        originX = r.left + r.width / 2;
        originY = r.top + r.height / 2;
      }
      window.ThemeTransition.run({
        originX: originX,
        originY: originY,
        waveColor: nextDef ? nextDef.bg0 : undefined,
        glowColor: nextDef ? nextDef.accent : undefined,
        onApply: applyFn
      });
    } else {
      applyFn();
    }
  }
  const activeThemeIdx = Math.max(0, NAV_THEME_KEYS.indexOf(theme));

  // Lock scroll while drawer open, restore on close/unmount.
  useE(() => {
    if (!open) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = prev;
    };
  }, [open]);

  // Close drawer when section clicked or Escape pressed.
  useE(() => {
    if (!open) return;
    const onKey = e => {
      if (e.key === "Escape") setOpen(false);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open]);
  return /*#__PURE__*/React.createElement("nav", {
    className: `nav ${open ? "nav-open" : ""}`
  }, /*#__PURE__*/React.createElement("div", {
    className: "nav-inner"
  }, /*#__PURE__*/React.createElement("a", {
    href: "#hero",
    className: "brand",
    "data-cursor": "link",
    "data-cursor-label": "\u2191 top"
  }, /*#__PURE__*/React.createElement("span", {
    className: "brand-mark"
  }), /*#__PURE__*/React.createElement("span", null, "SAMANDAR", /*#__PURE__*/React.createElement("span", {
    className: "brand-sub"
  }, " \xB7 EXEC.AI.LAB"))), /*#__PURE__*/React.createElement("ul", {
    className: "nav-links"
  }, NAV_SECTIONS.map(k => /*#__PURE__*/React.createElement("li", {
    key: k
  }, /*#__PURE__*/React.createElement("a", {
    href: `#${k}`,
    className: active === k ? "active" : "",
    "data-cursor": "link",
    "data-cursor-label": `→ ${t.nav[k]}`
  }, t.nav[k])))), /*#__PURE__*/React.createElement("div", {
    className: "nav-right"
  }, /*#__PURE__*/React.createElement("div", {
    className: "theme-switch",
    role: "group",
    "aria-label": "theme",
    style: {
      "--theme-idx": activeThemeIdx
    }
  }, /*#__PURE__*/React.createElement("span", {
    className: "theme-switch-thumb",
    "aria-hidden": "true"
  }), NAV_THEME_KEYS.map(key => {
    const def = window.THEMES && window.THEMES[key] ? window.THEMES[key] : null;
    const label = def ? def.name : key;
    return /*#__PURE__*/React.createElement("button", {
      key: key,
      type: "button",
      className: `theme-switch-seg theme-switch-seg--${key} ${theme === key ? "is-active" : ""}`,
      "aria-pressed": theme === key,
      "aria-label": `theme: ${label}`,
      title: label,
      onClick: ev => onThemePick(key, ev)
    }, /*#__PURE__*/React.createElement("span", {
      className: "theme-switch-dot",
      "aria-hidden": "true"
    }));
  })), /*#__PURE__*/React.createElement("div", {
    className: "lang",
    role: "group",
    "aria-label": "language"
  }, ["ru", "en", "uz"].map(L => /*#__PURE__*/React.createElement("button", {
    key: L,
    onClick: () => setLang(L),
    className: lang === L ? "active" : "",
    "aria-pressed": lang === L
  }, L.toUpperCase()))), /*#__PURE__*/React.createElement("button", {
    type: "button",
    className: "nav-burger",
    "aria-label": open ? "Close menu" : "Open menu",
    "aria-expanded": open,
    onClick: () => {
      haptic("toggle");
      setOpen(o => !o);
    }
  }, /*#__PURE__*/React.createElement("span", null), /*#__PURE__*/React.createElement("span", null), /*#__PURE__*/React.createElement("span", null)))), /*#__PURE__*/React.createElement("div", {
    className: `nav-drawer ${open ? "is-open" : ""}`,
    "aria-hidden": !open
  }, /*#__PURE__*/React.createElement("ul", {
    className: "nav-drawer-links"
  }, NAV_SECTIONS.map((k, i) => /*#__PURE__*/React.createElement("li", {
    key: k,
    style: {
      "--i": i
    }
  }, /*#__PURE__*/React.createElement("a", {
    href: `#${k}`,
    onClick: () => setOpen(false),
    className: active === k ? "active" : ""
  }, /*#__PURE__*/React.createElement("span", {
    className: "nav-drawer-num"
  }, "/", String(i + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("span", null, t.nav[k]), /*#__PURE__*/React.createElement("span", {
    className: "nav-drawer-arrow"
  }, "\u2192"))))), /*#__PURE__*/React.createElement("div", {
    className: "nav-drawer-foot"
  }, /*#__PURE__*/React.createElement("div", {
    className: "nav-drawer-meta mono"
  }, "EXECUTIVE AI CODE LAB \xB7 v.2026"))));
}

// ── Mobile UI overlay primitives ──────────────────────────────────────────
// Both dock + sticky CTA share the same visibility rule: appear after the user
// scrolls past hero, hide near contact. We use the SAME hooks rather than two
// observers to keep the truth source single and avoid races between them.

function useMidScrollVisibility() {
  const [visible, setVisible] = useS(false);
  useE(() => {
    const heroEl = document.getElementById("hero");
    const contactEl = document.getElementById("contact");
    if (!heroEl || !contactEl) return undefined;

    // Truth source: IntersectionObserver where available.
    let inHero = true;
    let inContact = false;
    const io = new IntersectionObserver(entries => {
      entries.forEach(e => {
        if (e.target.id === "hero") inHero = e.isIntersecting;else if (e.target.id === "contact") inContact = e.isIntersecting;
      });
      setVisible(!inHero && !inContact);
    }, {
      threshold: 0.1
    });
    io.observe(heroEl);
    io.observe(contactEl);

    // Scroll-based fallback — covers environments where IO is unreliable
    // (some embedded webviews, headless previews). Computes visibility from
    // bounding rects each rAF-throttled scroll event.
    let raf = 0;
    function recompute() {
      raf = 0;
      const vh = window.innerHeight;
      const heroRect = heroEl.getBoundingClientRect();
      const contactRect = contactEl.getBoundingClientRect();
      const heroVisible = heroRect.top < vh && heroRect.bottom > 0;
      const contactVisible = contactRect.top < vh && contactRect.bottom > 0;
      inHero = heroVisible;
      inContact = contactVisible;
      setVisible(!heroVisible && !contactVisible);
    }
    function onScroll() {
      if (!raf) raf = requestAnimationFrame(recompute);
    }
    window.addEventListener("scroll", onScroll, {
      passive: true
    });
    window.addEventListener("resize", onScroll, {
      passive: true
    });
    recompute();
    return function cleanup() {
      io.disconnect();
      window.removeEventListener("scroll", onScroll);
      window.removeEventListener("resize", onScroll);
      if (raf) cancelAnimationFrame(raf);
    };
  }, []);
  return visible;
}
function MobileScrollDock({
  t,
  activeSection,
  visible
}) {
  // 6 dots for the main NAV sections. Tap → smooth scroll + light haptic.
  function onDotClick(id) {
    haptic("tap");
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({
      behavior: "smooth",
      block: "start"
    });
  }
  const activeIdx = Math.max(0, NAV_SECTIONS.indexOf(activeSection));
  const activeLabel = activeSection && t.nav && t.nav[activeSection] || t.nav && t.nav[NAV_SECTIONS[0]] || "";
  return /*#__PURE__*/React.createElement("div", {
    className: `mobile-dock ${visible ? "is-visible" : ""}`,
    role: "navigation",
    "aria-label": "sections"
  }, /*#__PURE__*/React.createElement("ol", {
    className: "mobile-dock-dots"
  }, NAV_SECTIONS.map((id, i) => /*#__PURE__*/React.createElement("li", {
    key: id
  }, /*#__PURE__*/React.createElement("button", {
    type: "button",
    className: `mobile-dock-dot ${activeSection === id ? "is-active" : ""}`,
    "aria-label": t.nav && t.nav[id] ? t.nav[id] : id,
    onClick: () => onDotClick(id)
  })))), /*#__PURE__*/React.createElement("div", {
    className: "mobile-dock-label mono",
    "aria-live": "polite"
  }, /*#__PURE__*/React.createElement("span", {
    className: "mobile-dock-label-num"
  }, "/", String(activeIdx + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("span", null, activeLabel)));
}
function MobileStickyCta({
  t,
  visible
}) {
  function onTap() {
    haptic("toggle");
  }
  return /*#__PURE__*/React.createElement("a", {
    href: "#contact",
    className: `mobile-sticky-cta ${visible ? "is-visible" : ""}`,
    onClick: onTap,
    "aria-label": t.hero.cta_primary
  }, /*#__PURE__*/React.createElement("span", null, t.hero.cta_primary), /*#__PURE__*/React.createElement("span", {
    className: "arrow"
  }, "\u2192"));
}
function PortfolioTweaks({
  t,
  setTweak
}) {
  const themeOptions = Object.keys(window.THEMES);
  const fontOptions = Object.keys(window.FONT_STACKS);
  return /*#__PURE__*/React.createElement(TweaksPanel, null, /*#__PURE__*/React.createElement(TweakSection, {
    label: "Language"
  }), /*#__PURE__*/React.createElement(TweakRadio, {
    label: "Lang",
    value: t.lang,
    options: ["ru", "en", "uz"],
    onChange: v => setTweak("lang", v)
  }), /*#__PURE__*/React.createElement(TweakSection, {
    label: "Theme"
  }), /*#__PURE__*/React.createElement(TweakSelect, {
    label: "Theme",
    value: t.theme,
    options: themeOptions,
    onChange: v => setTweak("theme", v)
  }), /*#__PURE__*/React.createElement(TweakSelect, {
    label: "Font",
    value: t.font,
    options: fontOptions,
    onChange: v => setTweak("font", v)
  }), /*#__PURE__*/React.createElement(TweakSection, {
    label: "Layout"
  }), /*#__PURE__*/React.createElement(TweakRadio, {
    label: "Density",
    value: t.density,
    options: ["compact", "regular", "airy"],
    onChange: v => setTweak("density", v)
  }), /*#__PURE__*/React.createElement(TweakSlider, {
    label: "Motion",
    value: t.motion,
    min: 0,
    max: 1.6,
    step: 0.1,
    onChange: v => setTweak("motion", v)
  }));
}
function App() {
  const [tweaks, setTweak] = useTweaks(TWEAK_DEFAULTS);
  const [activeSection, setActiveSection] = useS("hero");
  const [coreReady, setCoreReady] = useS(false);
  const canvasRef = useR(null);
  const bgFxCanvasRef = useR(null);
  const bgFxRef = useR(null);
  const lang = tweaks.lang in window.CONTENT ? tweaks.lang : "ru";
  const t = window.CONTENT[lang];

  // Backfill CV doc fields (id, langs, strengths, foot) so the resume layout
  // renders even if the content bundles haven't been extended yet.
  useE(() => {
    const I18N = {
      ru: {
        id: {
          name: "Самандар",
          role: "Full-Stack · AI Automation · Product Engineer",
          meta: ["Ташкент · UTC+5", "Открыт к проектам", "EN · RU · UZ"],
          stats: [{
            k: "опыт",
            v: "5+ лет"
          }, {
            k: "релизов",
            v: "20+"
          }, {
            k: "стек",
            v: "TS / Py / SQL"
          }, {
            k: "ответ",
            v: "< 24h"
          }]
        },
        exp_title: "опыт",
        langs_title: "языки",
        strengths_title: "сильные стороны",
        strengths: ["Системное мышление от прод-идеи до прод-деплоя", "AI-интеграции уровня продакшна, не демки", "Тёплая, понятная коммуникация на трёх языках", "Самостоятельный темп, без надзора"],
        langs: [{
          k: "Русский",
          lv: 100,
          label: "native"
        }, {
          k: "English",
          lv: 85,
          label: "C1"
        }, {
          k: "Oʻzbek",
          lv: 95,
          label: "fluent"
        }],
        foot: "сгенерировано 2026 · подписанная версия по запросу"
      },
      en: {
        id: {
          name: "Samandar",
          role: "Full-Stack · AI Automation · Product Engineer",
          meta: ["Tashkent · UTC+5", "Open to projects", "EN · RU · UZ"],
          stats: [{
            k: "experience",
            v: "5+ yrs"
          }, {
            k: "releases",
            v: "20+"
          }, {
            k: "stack",
            v: "TS / Py / SQL"
          }, {
            k: "reply",
            v: "< 24h"
          }]
        },
        exp_title: "experience",
        langs_title: "languages",
        strengths_title: "strengths",
        strengths: ["End-to-end ownership from product idea to prod deploy", "Production AI integrations, not demos", "Calm, precise communication across three languages", "Async-first; runs without supervision"],
        langs: [{
          k: "Russian",
          lv: 100,
          label: "native"
        }, {
          k: "English",
          lv: 85,
          label: "C1"
        }, {
          k: "Uzbek",
          lv: 95,
          label: "fluent"
        }],
        foot: "generated 2026 · signed copy on request"
      },
      uz: {
        id: {
          name: "Samandar",
          role: "Full-Stack · AI Automation · Product Engineer",
          meta: ["Toshkent · UTC+5", "Loyihalarga ochiq", "EN · RU · UZ"],
          stats: [{
            k: "tajriba",
            v: "5+ yil"
          }, {
            k: "relizlar",
            v: "20+"
          }, {
            k: "stek",
            v: "TS / Py / SQL"
          }, {
            k: "javob",
            v: "< 24h"
          }]
        },
        exp_title: "tajriba",
        langs_title: "tillar",
        strengths_title: "kuchli tomonlar",
        strengths: ["Mahsulot g'oyasidan prod-deploygacha to'liq egalik", "Production darajadagi AI integratsiyalar", "Uch tilda aniq va xotirjam muloqot", "Mustaqil sur'at, nazoratsiz ishlash"],
        langs: [{
          k: "Ruscha",
          lv: 100,
          label: "native"
        }, {
          k: "English",
          lv: 85,
          label: "C1"
        }, {
          k: "Oʻzbek",
          lv: 100,
          label: "ona tili"
        }],
        foot: "2026 yil · imzolangan nusxa so'rov asosida"
      }
    };
    Object.entries(I18N).forEach(([L, patch]) => {
      const cv = window.CONTENT?.[L]?.cv;
      if (!cv) return;
      for (const k of Object.keys(patch)) if (cv[k] == null) cv[k] = patch[k];
    });
  }, []);

  // Apply theme/font/density. On a theme change we update three things:
  //   1. CSS variables (applyTheme)
  //   2. accent colours on the scene-engine + bg-fx renderers
  //   3. the bg-fx ANIMATION profile (Ember / Cortex / Sage) so the
  //      background's character — spin speed, grid frequency, constellation
  //      density — morphs to match the theme.
  useE(() => {
    const theme = window.applyTheme(tweaks.theme);
    if (bgFxRef.current && theme) {
      bgFxRef.current.setAccent(theme.accent, theme.accent2);
      if (typeof bgFxRef.current.setThemeProfile === "function") {
        bgFxRef.current.setThemeProfile(theme.bgProfile || "ember");
      }
    }
  }, [tweaks.theme]);
  useE(() => {
    window.applyFontStack(tweaks.font);
  }, [tweaks.font]);
  useE(() => {
    document.documentElement.setAttribute("data-density", tweaks.density);
    document.documentElement.setAttribute("lang", lang);
  }, [tweaks.density, lang]);
  useE(() => {
    document.documentElement.style.setProperty("--motion", String(tweaks.motion));
    if (bgFxRef.current && bgFxRef.current.setMotion) bgFxRef.current.setMotion(tweaks.motion);
  }, [tweaks.motion]);

  // Apply theme/font once on mount + init bg-fx canvas
  useE(() => {
    window.applyTheme(tweaks.theme);
    window.applyFontStack(tweaks.font);
    setCoreReady(true);
    if (bgFxCanvasRef.current && window.BgFx) {
      const rootStyles = getComputedStyle(document.documentElement);
      const a1 = rootStyles.getPropertyValue("--accent").trim() || "#D97757";
      const a2 = rootStyles.getPropertyValue("--accent-2").trim() || "#C89B5E";
      // Seed the bg-fx animation profile from the initial theme so the
      // first paint already has the right character (no Ember→X flash).
      const initialTheme = window.THEMES && window.THEMES[tweaks.theme] ? window.THEMES[tweaks.theme] : null;
      bgFxRef.current = window.BgFx.create(bgFxCanvasRef.current, {
        accent: a1,
        accent2: a2,
        motion: tweaks.motion,
        themeProfile: initialTheme ? initialTheme.bgProfile || "ember" : "ember"
      });
    }
    return () => {
      if (bgFxRef.current && bgFxRef.current.dispose) bgFxRef.current.dispose();
      bgFxRef.current = null;
    };
  }, []);
  useScrollEngine(bgFxRef, setActiveSection);

  // Motion: init smart cursor + reveal observers after first paint, refresh on lang change.
  // isInViewport check in motion.js handles the "no-flash" problem for visible elements.
  useE(() => {
    document.body.classList.add("page-loaded");
    if (window.Motion) window.Motion.init();
    // Wire the View Transitions API navigator. It binds a global click handler
    // on anchor[href^="#"] and replaces the default scroll with a cinematic
    // cross-fade. Safe to call multiple times — second call is a no-op.
    if (window.SceneCinema && typeof window.SceneCinema.init === "function") {
      window.SceneCinema.init();
    }
    return () => {
      if (window.SceneCinema && typeof window.SceneCinema.dispose === "function") {
        window.SceneCinema.dispose();
      }
    };
  }, []);
  useE(() => {
    if (!window.Motion) return;
    const id = requestAnimationFrame(() => window.Motion.refresh());
    return () => cancelAnimationFrame(id);
  }, [lang, tweaks.density]);

  // Mid-scroll visibility for mobile dock + sticky CTA.
  const midScrollVisible = useMidScrollVisibility();
  return /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("canvas", {
    ref: bgFxCanvasRef,
    className: "bg-fx-canvas",
    "aria-hidden": "true"
  }), /*#__PURE__*/React.createElement("div", {
    className: "bg-grid"
  }), /*#__PURE__*/React.createElement("div", {
    className: "bg-noise"
  }), /*#__PURE__*/React.createElement("div", {
    className: "scroll-progress"
  }), /*#__PURE__*/React.createElement(Nav, {
    t: t,
    lang: lang,
    setLang: v => setTweak("lang", v),
    active: activeSection,
    theme: tweaks.theme,
    setTheme: v => setTweak("theme", v)
  }), /*#__PURE__*/React.createElement("main", null, /*#__PURE__*/React.createElement(Hero, {
    t: t,
    links: LINKS
  }), /*#__PURE__*/React.createElement(Signal, {
    t: t
  }), /*#__PURE__*/React.createElement(About, {
    t: t
  }), /*#__PURE__*/React.createElement(Projects, {
    t: t
  }), /*#__PURE__*/React.createElement(Skills, {
    t: t
  }), /*#__PURE__*/React.createElement(Services, {
    t: t
  }), /*#__PURE__*/React.createElement(CV, {
    t: t,
    links: LINKS
  }), /*#__PURE__*/React.createElement(Process, {
    t: t
  }), /*#__PURE__*/React.createElement(Trust, {
    t: t
  }), /*#__PURE__*/React.createElement(Contact, {
    t: t,
    links: LINKS
  })), /*#__PURE__*/React.createElement(Footer, {
    t: t,
    links: LINKS
  }), /*#__PURE__*/React.createElement(MobileStickyCta, {
    t: t,
    visible: midScrollVisible
  }), /*#__PURE__*/React.createElement(MobileScrollDock, {
    t: t,
    activeSection: activeSection,
    visible: midScrollVisible
  }), /*#__PURE__*/React.createElement(PortfolioTweaks, {
    t: tweaks,
    setTweak: setTweak
  }));
}
ReactDOM.createRoot(document.getElementById("root")).render(/*#__PURE__*/React.createElement(ErrorBoundary, null, /*#__PURE__*/React.createElement(App, null)));