/* AUTO-GENERATED by build.js from components-2.jsx — DO NOT EDIT.
   Edit the .jsx source and re-run `node build.js`. */
// components-2.jsx — Services, CV, Process, Trust, Contact, Footer

const {
  useEffect: useEffect2,
  useRef: useRef2,
  useState: useState2,
  useMemo: useMemoFromComponents1
} = React;

// ─────────────────────────────────────────────────────────────────────────────
// SERVICES — unique cards, no terminal commands.
//
// Each card has:
//   • A distinctive SVG glyph that visually telegraphs the service category
//   • A varied "hover animation kind" cycled per index so the grid doesn't
//     read as a uniform copy-paste — every card has its own micro-personality
//   • A clean io-pill at the bottom showing the value transform
//
// Glyphs are pure inline SVG (no external icons) so they always inherit the
// current accent color via `currentColor`. They're index-keyed: card N gets
// glyph N. If the content array changes length, glyphs cycle from the start.
// ─────────────────────────────────────────────────────────────────────────────

const SERVICE_HOVER_KINDS = ["lift", "tilt-l", "tilt-r", "glow", "scale", "shift", "edge", "ripple"];

// Inline SVG glyphs — return ReactElement keyed by index. Eight distinct
// concepts mapped to the eight content slots in order.
const SERVICE_GLYPHS = [
// 0 · Web Apps — stacked layers
function GlyphLayers() {
  return /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 40 40",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("rect", {
    x: "6",
    y: "8",
    width: "28",
    height: "6",
    rx: "1"
  }), /*#__PURE__*/React.createElement("rect", {
    x: "6",
    y: "17",
    width: "28",
    height: "6",
    rx: "1"
  }), /*#__PURE__*/React.createElement("rect", {
    x: "6",
    y: "26",
    width: "28",
    height: "6",
    rx: "1"
  }), /*#__PURE__*/React.createElement("line", {
    x1: "11",
    y1: "11",
    x2: "11",
    y2: "11"
  }), /*#__PURE__*/React.createElement("line", {
    x1: "11",
    y1: "20",
    x2: "11",
    y2: "20"
  }), /*#__PURE__*/React.createElement("line", {
    x1: "11",
    y1: "29",
    x2: "11",
    y2: "29"
  }));
},
// 1 · Landing & Sites — page outline + accent block
function GlyphPage() {
  return /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 40 40",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("rect", {
    x: "8",
    y: "6",
    width: "24",
    height: "28",
    rx: "1"
  }), /*#__PURE__*/React.createElement("line", {
    x1: "13",
    y1: "13",
    x2: "27",
    y2: "13"
  }), /*#__PURE__*/React.createElement("line", {
    x1: "13",
    y1: "18",
    x2: "22",
    y2: "18"
  }), /*#__PURE__*/React.createElement("rect", {
    x: "13",
    y: "22",
    width: "14",
    height: "6",
    fill: "currentColor",
    opacity: "0.25",
    stroke: "none"
  }));
},
// 2 · Telegram Bots — speech bubble with dots
function GlyphBubble() {
  return /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 40 40",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("path", {
    d: "M8 10 h24 a2 2 0 0 1 2 2 v14 a2 2 0 0 1 -2 2 H18 l-6 5 v-5 H8 a2 2 0 0 1 -2 -2 V12 a2 2 0 0 1 2 -2 z"
  }), /*#__PURE__*/React.createElement("circle", {
    cx: "14",
    cy: "19",
    r: "1.5",
    fill: "currentColor",
    stroke: "none"
  }), /*#__PURE__*/React.createElement("circle", {
    cx: "20",
    cy: "19",
    r: "1.5",
    fill: "currentColor",
    stroke: "none"
  }), /*#__PURE__*/React.createElement("circle", {
    cx: "26",
    cy: "19",
    r: "1.5",
    fill: "currentColor",
    stroke: "none"
  }));
},
// 3 · AI Automation — node graph
function GlyphNodes() {
  return /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 40 40",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("circle", {
    cx: "10",
    cy: "10",
    r: "3",
    fill: "currentColor",
    stroke: "none"
  }), /*#__PURE__*/React.createElement("circle", {
    cx: "30",
    cy: "10",
    r: "3",
    fill: "currentColor",
    stroke: "none"
  }), /*#__PURE__*/React.createElement("circle", {
    cx: "20",
    cy: "22",
    r: "3",
    fill: "currentColor",
    stroke: "none"
  }), /*#__PURE__*/React.createElement("circle", {
    cx: "10",
    cy: "32",
    r: "3",
    fill: "currentColor",
    stroke: "none"
  }), /*#__PURE__*/React.createElement("circle", {
    cx: "30",
    cy: "32",
    r: "3",
    fill: "currentColor",
    stroke: "none"
  }), /*#__PURE__*/React.createElement("line", {
    x1: "10",
    y1: "10",
    x2: "20",
    y2: "22"
  }), /*#__PURE__*/React.createElement("line", {
    x1: "30",
    y1: "10",
    x2: "20",
    y2: "22"
  }), /*#__PURE__*/React.createElement("line", {
    x1: "20",
    y1: "22",
    x2: "10",
    y2: "32"
  }), /*#__PURE__*/React.createElement("line", {
    x1: "20",
    y1: "22",
    x2: "30",
    y2: "32"
  }));
},
// 4 · Dashboards — bar chart
function GlyphChart() {
  return /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 40 40",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("line", {
    x1: "6",
    y1: "34",
    x2: "34",
    y2: "34"
  }), /*#__PURE__*/React.createElement("rect", {
    x: "9",
    y: "22",
    width: "4",
    height: "12",
    fill: "currentColor",
    opacity: "0.4",
    stroke: "none"
  }), /*#__PURE__*/React.createElement("rect", {
    x: "17",
    y: "14",
    width: "4",
    height: "20",
    fill: "currentColor",
    opacity: "0.7",
    stroke: "none"
  }), /*#__PURE__*/React.createElement("rect", {
    x: "25",
    y: "18",
    width: "4",
    height: "16",
    fill: "currentColor",
    opacity: "0.55",
    stroke: "none"
  }));
},
// 5 · MVP / Prototype — arrow zig-zag (idea → prototype)
function GlyphArrow() {
  return /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 40 40",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("path", {
    d: "M6 28 L14 20 L20 26 L28 14 L34 18"
  }), /*#__PURE__*/React.createElement("path", {
    d: "M28 10 L34 14 L30 20"
  }), /*#__PURE__*/React.createElement("circle", {
    cx: "6",
    cy: "28",
    r: "2",
    fill: "currentColor",
    stroke: "none"
  }));
},
// 6 · Internal Tools — wrench / spanner
function GlyphTool() {
  return /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 40 40",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("path", {
    d: "M27 10 a6 6 0 0 0 -3 11 L9 36 l4 -1 L28 20 a6 6 0 0 0 4 -10 l-3 3 -3 0 0 -3 z"
  }), /*#__PURE__*/React.createElement("circle", {
    cx: "13",
    cy: "32",
    r: "1",
    fill: "currentColor",
    stroke: "none"
  }));
},
// 7 · Tech Consulting — question / dialog
function GlyphChat() {
  return /*#__PURE__*/React.createElement("svg", {
    viewBox: "0 0 40 40",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: "1.5",
    strokeLinecap: "round",
    strokeLinejoin: "round",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("path", {
    d: "M14 10 c-3 0 -6 2 -6 5 c0 2 1 4 3 5 v3 l3 -2 c2 1 4 1 6 0"
  }), /*#__PURE__*/React.createElement("path", {
    d: "M20 17 c0 -3 3 -5 7 -5 c4 0 7 2 7 5 c0 3 -2 5 -5 5 l-4 3 v-3 c-3 -1 -5 -3 -5 -5 z"
  }), /*#__PURE__*/React.createElement("circle", {
    cx: "27",
    cy: "17",
    r: "1",
    fill: "currentColor",
    stroke: "none"
  }));
}];
function ServiceCard({
  item,
  index
}) {
  const cardRef = useRef2(null);
  const hoverKind = SERVICE_HOVER_KINDS[index % SERVICE_HOVER_KINDS.length];
  const Glyph = SERVICE_GLYPHS[index % SERVICE_GLYPHS.length];
  function onMouseMove(e) {
    const el = cardRef.current;
    if (!el || hoverKind !== "tilt-l" && hoverKind !== "tilt-r") return;
    const r = el.getBoundingClientRect();
    const x = (e.clientX - r.left) / r.width - 0.5;
    const y = (e.clientY - r.top) / r.height - 0.5;
    const sign = hoverKind === "tilt-l" ? 1 : -1;
    el.style.setProperty("--rx", `${(-y * 5 * sign).toFixed(2)}deg`);
    el.style.setProperty("--ry", `${(x * 5 * sign).toFixed(2)}deg`);
  }
  function onMouseLeave() {
    const el = cardRef.current;
    if (!el) return;
    el.style.setProperty("--rx", "0deg");
    el.style.setProperty("--ry", "0deg");
  }
  return /*#__PURE__*/React.createElement("article", {
    ref: cardRef,
    className: `service-card card service-card--hover-${hoverKind}`,
    "data-reveal": true,
    "data-reveal-delay": (index * 0.04).toFixed(2),
    onMouseMove: onMouseMove,
    onMouseLeave: onMouseLeave
  }, /*#__PURE__*/React.createElement("div", {
    className: "service-card-head"
  }, /*#__PURE__*/React.createElement("span", {
    className: "service-card-num mono"
  }, "/", String(index + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("span", {
    className: "service-card-badge mono"
  }, item.io)), /*#__PURE__*/React.createElement("div", {
    className: "service-card-glyph",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement(Glyph, null)), /*#__PURE__*/React.createElement("h3", {
    className: "service-card-k"
  }, item.k), /*#__PURE__*/React.createElement("p", {
    className: "service-card-v"
  }, item.v));
}
function Services({
  t
}) {
  const ref = useRevealRoot([t]);
  return /*#__PURE__*/React.createElement("section", {
    "data-section": "services",
    id: "services",
    ref: ref
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell"
  }, /*#__PURE__*/React.createElement(SecHead, {
    num: "05",
    eyebrow: t.services.eyebrow,
    title: t.services.title,
    meta: `${t.services.items.length} services`
  }), /*#__PURE__*/React.createElement("div", {
    className: "services-grid"
  }, t.services.items.map(function renderService(s, i) {
    return /*#__PURE__*/React.createElement(ServiceCard, {
      key: i,
      item: s,
      index: i
    });
  }))));
}

// ─────────────────────────────────────────────────────────────────────────────
// CV — Resume document (proper, printable, mobile-friendly)
// ─────────────────────────────────────────────────────────────────────────────
function CV({
  t,
  links
}) {
  const ref = useRevealRoot([t]);
  const [openIdx, setOpenIdx] = useState2(0);
  // Roles are an accordion: only one open at a time normally. For print we
  // force ALL open so the printed PDF shows the full timeline, then restore
  // the user's previous state after the print dialog closes.
  const restoreOpenIdx = useRef2(0);
  function onPrint() {
    restoreOpenIdx.current = openIdx;
    setOpenIdx(-2); // sentinel: "all open" (any non-numeric index that isn't matched)
    // Use a microtask + rAF so React commits the open-state change before
    // the synchronous window.print() blocks the main thread.
    Promise.resolve().then(function () {
      requestAnimationFrame(function () {
        requestAnimationFrame(function () {
          window.print();
        });
      });
    });
  }

  // afterprint event — restore the previous open role so the on-screen view
  // doesn't stay fully expanded.
  useEffect2(function bindAfterPrint() {
    const handler = function () {
      setOpenIdx(restoreOpenIdx.current);
    };
    window.addEventListener("afterprint", handler);
    return function () {
      window.removeEventListener("afterprint", handler);
    };
  }, []);

  // derive aggregate stats from timeline
  const years = (() => {
    const ys = t.cv.timeline.map(n => parseInt(String(n.y).match(/\d{4}/)?.[0] || "0", 10)).filter(Boolean);
    if (!ys.length) return null;
    return `${Math.min(...ys)}—${Math.max(...ys)}`;
  })();
  return /*#__PURE__*/React.createElement("section", {
    "data-section": "cv",
    id: "cv",
    ref: ref
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell"
  }, /*#__PURE__*/React.createElement(SecHead, {
    num: "06",
    eyebrow: t.cv.eyebrow,
    title: t.cv.title,
    em: t.cv.title.split(" ").pop(),
    meta: `v.2026 · ${years || "active"}`
  }), /*#__PURE__*/React.createElement("article", {
    className: "cv-doc",
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("header", {
    className: "cv-doc-head"
  }, /*#__PURE__*/React.createElement("div", {
    className: "cv-doc-tabs mono",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("span", {
    className: "cv-doc-tab is-active"
  }, "samandar.cv"), /*#__PURE__*/React.createElement("span", {
    className: "cv-doc-tab"
  }, "readme.md")), /*#__PURE__*/React.createElement("div", {
    className: "cv-doc-actions mono"
  }, /*#__PURE__*/React.createElement("button", {
    className: "cv-action",
    type: "button",
    onClick: onPrint,
    "data-cursor": "link",
    "data-cursor-label": "print / pdf"
  }, /*#__PURE__*/React.createElement("span", {
    className: "cv-action-ico",
    "aria-hidden": "true"
  }, "\u2318P"), /*#__PURE__*/React.createElement("span", null, "print \xB7 pdf")), /*#__PURE__*/React.createElement("a", {
    className: "cv-action",
    href: links?.email ? `mailto:${links.email}?subject=CV%20request` : "#",
    "data-cursor": "send",
    "data-cursor-label": "request signed cv"
  }, /*#__PURE__*/React.createElement("span", {
    className: "cv-action-ico",
    "aria-hidden": "true"
  }, "\u2197"), /*#__PURE__*/React.createElement("span", null, "request")))), /*#__PURE__*/React.createElement("div", {
    className: "cv-id"
  }, /*#__PURE__*/React.createElement("div", {
    className: "cv-id-l"
  }, /*#__PURE__*/React.createElement("h3", {
    className: "cv-id-name",
    "data-reveal-words": true
  }, t.cv.id?.name || "Samandar"), /*#__PURE__*/React.createElement("p", {
    className: "cv-id-role"
  }, t.cv.id?.role || t.cv.lead), /*#__PURE__*/React.createElement("div", {
    className: "cv-id-meta mono"
  }, (t.cv.id?.meta || []).map((m, i) => /*#__PURE__*/React.createElement("span", {
    key: i
  }, m)))), /*#__PURE__*/React.createElement("dl", {
    className: "cv-id-stats",
    "aria-label": "stats"
  }, (t.cv.id?.stats || []).map((s, i) => /*#__PURE__*/React.createElement("div", {
    key: i,
    className: "cv-id-stat"
  }, /*#__PURE__*/React.createElement("dt", {
    className: "mono"
  }, s.k), /*#__PURE__*/React.createElement("dd", null, s.v))))), /*#__PURE__*/React.createElement("div", {
    className: "cv-doc-body"
  }, /*#__PURE__*/React.createElement("main", {
    className: "cv-main"
  }, /*#__PURE__*/React.createElement("h4", {
    className: "cv-block-h mono"
  }, t.cv.exp_title || "experience"), /*#__PURE__*/React.createElement("ol", {
    className: "cv-roles"
  }, t.cv.timeline.map((node, i) => {
    const isOpen = openIdx === -2 || openIdx === i;
    return /*#__PURE__*/React.createElement("li", {
      key: i,
      className: `cv-role ${isOpen ? "is-open" : ""}`
    }, /*#__PURE__*/React.createElement("button", {
      className: "cv-role-head",
      type: "button",
      "aria-expanded": isOpen,
      onClick: () => setOpenIdx(isOpen ? -1 : i),
      "data-cursor": "read",
      "data-cursor-label": isOpen ? "collapse" : "expand"
    }, /*#__PURE__*/React.createElement("span", {
      className: "cv-role-y mono"
    }, node.y), /*#__PURE__*/React.createElement("span", {
      className: "cv-role-main"
    }, /*#__PURE__*/React.createElement("span", {
      className: "cv-role-title"
    }, node.role), /*#__PURE__*/React.createElement("span", {
      className: "cv-role-org"
    }, node.org)), /*#__PURE__*/React.createElement("span", {
      className: "cv-role-tag mono"
    }, node.tag), /*#__PURE__*/React.createElement("span", {
      className: "cv-role-chev",
      "aria-hidden": "true"
    }, isOpen ? "−" : "+")), /*#__PURE__*/React.createElement("div", {
      className: "cv-role-body",
      hidden: !isOpen
    }, /*#__PURE__*/React.createElement("ul", {
      className: "cv-points"
    }, node.points.map((p, k) => /*#__PURE__*/React.createElement("li", {
      key: k
    }, p))), node.stack && node.stack.length ? /*#__PURE__*/React.createElement("div", {
      className: "cv-role-stack"
    }, node.stack.map((s, k) => /*#__PURE__*/React.createElement("span", {
      key: k,
      className: "mono cv-chip"
    }, s))) : null));
  }))), /*#__PURE__*/React.createElement("aside", {
    className: "cv-side"
  }, /*#__PURE__*/React.createElement("section", {
    className: "cv-block"
  }, /*#__PURE__*/React.createElement("h4", {
    className: "cv-block-h mono"
  }, t.cv.edu_title), /*#__PURE__*/React.createElement("ul", {
    className: "cv-side-list"
  }, t.cv.edu.map((e, i) => /*#__PURE__*/React.createElement("li", {
    key: i,
    className: "cv-edu-row"
  }, /*#__PURE__*/React.createElement("span", {
    className: "mono cv-edu-y"
  }, e.y), /*#__PURE__*/React.createElement("span", {
    className: "cv-edu-k"
  }, e.k))))), t.cv.strengths?.length ? /*#__PURE__*/React.createElement("section", {
    className: "cv-block"
  }, /*#__PURE__*/React.createElement("h4", {
    className: "cv-block-h mono"
  }, t.cv.strengths_title || "strengths"), /*#__PURE__*/React.createElement("ul", {
    className: "cv-side-list cv-strengths"
  }, t.cv.strengths.map((s, i) => /*#__PURE__*/React.createElement("li", {
    key: i
  }, /*#__PURE__*/React.createElement("span", {
    className: "cv-bullet-mark",
    "aria-hidden": "true"
  }, "\u203A"), s)))) : null, t.cv.langs?.length ? /*#__PURE__*/React.createElement("section", {
    className: "cv-block"
  }, /*#__PURE__*/React.createElement("h4", {
    className: "cv-block-h mono"
  }, t.cv.langs_title || "languages"), /*#__PURE__*/React.createElement("ul", {
    className: "cv-langs"
  }, t.cv.langs.map((l, i) => /*#__PURE__*/React.createElement("li", {
    key: i,
    className: "cv-lang"
  }, /*#__PURE__*/React.createElement("span", null, l.k), /*#__PURE__*/React.createElement("span", {
    className: "cv-lang-bar",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("span", {
    className: "cv-lang-bar-fill",
    style: {
      width: `${l.lv}%`
    }
  })), /*#__PURE__*/React.createElement("span", {
    className: "mono cv-lang-lvl"
  }, l.label))))) : null)), /*#__PURE__*/React.createElement("footer", {
    className: "cv-doc-foot mono"
  }, /*#__PURE__*/React.createElement("span", null, "\u2014 end of file \u2014"), /*#__PURE__*/React.createElement("span", null, t.cv.foot || "generated 2026 · verifiable on request")))));
}

// ─────────────────────────────────────────────────────────────────────────────
// PROCESS — deployment pipeline. Vertical terminal "stages" that flip
//   queued → running (with typewriter command + progress bar) → done (with
//   completion time) as they enter the viewport.
//
// Each stage handles its own typewriter + progress timeline independently so
// state stays simple and the row mounts behave like real CI logs.
// ─────────────────────────────────────────────────────────────────────────────
const PROC_TYPE_INTERVAL_MS = 22; // typewriter cadence
const PROC_RUN_MIN_MS = 520; // visual run-time per stage
const PROC_RUN_VAR_MS = 240;
const PROC_VIEWPORT_TRIGGER_RATIO = 0.4;
const PROC_OUTPUT_SAMPLES = ["ok · ready", "compiled in 84ms", "shipped to prod", "200 · listening", "no regressions", "manifest verified", "queue empty"];
function ProcStage({
  step,
  index,
  refSetter
}) {
  // Stage states: queued (idle) → running (typing + progress) → done (success).
  const [state, setState] = useState2("queued");
  const [typed, setTyped] = useState2("");
  const [progress, setProgress] = useState2(0);
  const stageRef = useRef2(null);
  const timersRef = useRef2({
    typer: 0,
    prog: 0,
    done: 0
  });

  // Combined ref: store internally + report to parent collection.
  function combinedRef(el) {
    stageRef.current = el;
    if (typeof refSetter === "function") refSetter(el);
  }

  // Run typewriter when state flips to "running".
  useEffect2(function runTyper() {
    if (state !== "running") return undefined;
    const cmd = step.cmd;
    let cursor = 0;
    timersRef.current.typer = window.setInterval(function step1() {
      cursor++;
      setTyped(cmd.slice(0, cursor));
      if (cursor >= cmd.length) {
        window.clearInterval(timersRef.current.typer);
        timersRef.current.typer = 0;
      }
    }, PROC_TYPE_INTERVAL_MS);
    return function cleanup() {
      if (timersRef.current.typer) {
        window.clearInterval(timersRef.current.typer);
        timersRef.current.typer = 0;
      }
    };
  }, [state, step.cmd]);

  // Progress bar fills 0 → 100 over PROC_RUN_MIN_MS + variance.
  useEffect2(function runProgress() {
    if (state !== "running") return undefined;
    const totalMs = PROC_RUN_MIN_MS + index % 5 * (PROC_RUN_VAR_MS / 5);
    const startedAt = performance.now();
    function tick(now) {
      const t = Math.min(1, (now - startedAt) / totalMs);
      setProgress(t);
      if (t < 1) {
        timersRef.current.prog = window.requestAnimationFrame(tick);
      } else {
        timersRef.current.prog = 0;
        timersRef.current.done = window.setTimeout(function flipDone() {
          setState("done");
        }, 120);
      }
    }
    timersRef.current.prog = window.requestAnimationFrame(tick);
    return function cleanup() {
      if (timersRef.current.prog) {
        window.cancelAnimationFrame(timersRef.current.prog);
        timersRef.current.prog = 0;
      }
      if (timersRef.current.done) {
        window.clearTimeout(timersRef.current.done);
        timersRef.current.done = 0;
      }
    };
  }, [state, index]);

  // IntersectionObserver — flip queued → running when the row is in view.
  useEffect2(function watchViewport() {
    if (!stageRef.current) return undefined;
    const io = new IntersectionObserver(function onSeen(entries) {
      entries.forEach(function check(e) {
        if (e.isIntersecting && e.intersectionRatio > PROC_VIEWPORT_TRIGGER_RATIO) {
          setState(function (prev) {
            return prev === "queued" ? "running" : prev;
          });
          io.unobserve(e.target);
        }
      });
    }, {
      threshold: [PROC_VIEWPORT_TRIGGER_RATIO, 0.55, 0.7]
    });
    io.observe(stageRef.current);
    return function () {
      io.disconnect();
    };
  }, []);

  // Scroll-based fallback for environments where IO is unreliable.
  useEffect2(function scrollFallback() {
    if (state !== "queued") return undefined;
    let raf = 0;
    function check() {
      raf = 0;
      const el = stageRef.current;
      if (!el) return;
      const r = el.getBoundingClientRect();
      const vh = window.innerHeight;
      if (r.top < vh * 0.7 && r.bottom > vh * 0.15) {
        setState("running");
      }
    }
    function onScroll() {
      if (!raf) raf = window.requestAnimationFrame(check);
    }
    window.addEventListener("scroll", onScroll, {
      passive: true
    });
    check();
    return function () {
      window.removeEventListener("scroll", onScroll);
      if (raf) window.cancelAnimationFrame(raf);
    };
  }, [state]);
  return /*#__PURE__*/React.createElement("li", {
    ref: combinedRef,
    className: `proc-stage proc-stage--${state}`,
    "data-reveal-delay": (index * 0.03).toFixed(2)
  }, /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-gutter mono"
  }, String(index + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("div", {
    className: "proc-stage-main"
  }, /*#__PURE__*/React.createElement("div", {
    className: "proc-stage-cmd mono"
  }, state === "queued" ? /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-cmd-ghost"
  }, step.cmd) : /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("span", null, typed), state === "running" && /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-caret"
  }))), /*#__PURE__*/React.createElement("div", {
    className: "proc-stage-meta"
  }, /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-k"
  }, step.k), /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-arrow"
  }, "\u2192"), /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-v"
  }, step.v)), state === "running" && /*#__PURE__*/React.createElement("div", {
    className: "proc-stage-progress",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("div", {
    className: "proc-stage-progress-fill",
    style: {
      transform: `scaleX(${progress.toFixed(3)})`
    }
  })), state === "done" && /*#__PURE__*/React.createElement("div", {
    className: "proc-stage-output mono"
  }, /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-output-prompt"
  }, "\u203A"), /*#__PURE__*/React.createElement("span", null, step.output))), /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-status mono"
  }, state === "queued" && /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-pill proc-stage-pill--queued"
  }, "queued"), state === "running" && /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-pill proc-stage-pill--running"
  }, /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-spin",
    "aria-hidden": "true"
  }), "running"), state === "done" && /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-pill proc-stage-pill--done"
  }, /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-check",
    "aria-hidden": "true"
  }, "\u2713"), step.ms)));
}
function Process({
  t
}) {
  const ref = useRevealRoot([t]);
  const cliRef = useRef2(null);
  const cliCtrlRef = useRef2(null);
  const pgRef = useRef2(null);
  const pgCtrlRef = useRef2(null);
  const steps = useMemoFromComponents1(function buildSteps() {
    return t.process.steps.map(function buildStep(s, i) {
      const slug = String(s.k || "step").toLowerCase().replace(/[^a-z0-9]+/g, "-");
      const ms = 120 + i * 41 % 230;
      return {
        k: s.k,
        v: s.v,
        cmd: `$ ./pipeline run --stage ${slug}`,
        ms: `${String(ms).padStart(3, "0")}ms`,
        output: PROC_OUTPUT_SAMPLES[i % PROC_OUTPUT_SAMPLES.length]
      };
    });
  }, [t]);

  // Mount the looping Claude Code session terminal. Re-creates on language
  // change so sessions render in the current locale. Pauses itself when
  // off-screen via IntersectionObserver inside the module.
  useEffect2(function mountCli() {
    if (!cliRef.current || !window.CliCinema) return undefined;
    // Defensive: cli_sessions may be missing if content.js was partially
    // updated. Module falls back to bundled English defaults in that case.
    const sessions = t.process && Array.isArray(t.process.cli_sessions) ? t.process.cli_sessions : null;
    cliCtrlRef.current = window.CliCinema.create(cliRef.current, sessions ? {
      sessions: sessions
    } : {});
    return function () {
      if (cliCtrlRef.current && cliCtrlRef.current.dispose) cliCtrlRef.current.dispose();
      cliCtrlRef.current = null;
    };
  }, [t]);

  // v52: replaced ProjectEstimator (felt commercial) with CursorConstellation
  // — non-commercial, "залипательный" interactive canvas. Pure delight,
  // no funnel. Visitor's cursor leaves a trail of glowing particles that
  // gravitate + connect.
  useEffect2(function mountConstellation() {
    if (!pgRef.current || !window.CursorConstellation) return undefined;
    const langGuess = typeof t === "object" && t && t.lang ? t.lang : "ru";
    pgCtrlRef.current = window.CursorConstellation.create(pgRef.current, {
      lang: langGuess
    });
    return function () {
      if (pgCtrlRef.current && pgCtrlRef.current.dispose) pgCtrlRef.current.dispose();
      pgCtrlRef.current = null;
    };
  }, [t]);

  // Localized labels (with fallbacks if cli_* keys are absent in older content).
  const cliEyebrow = t.process && t.process.cli_eyebrow || "live";
  const cliTitle = t.process && t.process.cli_title || "Claude Code";
  const cliLead = t.process && t.process.cli_lead || "";
  return /*#__PURE__*/React.createElement("section", {
    "data-section": "process",
    id: "process",
    ref: ref
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell"
  }, /*#__PURE__*/React.createElement(SecHead, {
    num: "07",
    eyebrow: t.process.eyebrow,
    title: t.process.title,
    meta: "pipeline.run()"
  }), /*#__PURE__*/React.createElement("p", {
    className: "lead-line",
    "data-reveal": true
  }, t.process.lead), /*#__PURE__*/React.createElement("div", {
    className: "proc-terminal card",
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "proc-terminal-head"
  }, /*#__PURE__*/React.createElement("div", {
    className: "proc-terminal-dots"
  }, /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null)), /*#__PURE__*/React.createElement("span", {
    className: "mono proc-terminal-title"
  }, "/usr/local/bin/ship \u2014 pipeline.v26"), /*#__PURE__*/React.createElement("span", {
    className: "mono proc-terminal-meta"
  }, steps.length, " stages")), /*#__PURE__*/React.createElement("ol", {
    className: "proc-terminal-body"
  }, steps.map(function renderStage(s, i) {
    return /*#__PURE__*/React.createElement(ProcStage, {
      key: i,
      step: s,
      index: i
    });
  })), /*#__PURE__*/React.createElement("div", {
    className: "proc-terminal-foot mono"
  }, /*#__PURE__*/React.createElement("span", {
    className: "proc-terminal-prompt"
  }, "\u203A"), /*#__PURE__*/React.createElement("span", null, "READY \xB7 listening on :443"), /*#__PURE__*/React.createElement("span", {
    className: "proc-terminal-cursor"
  }, "\u258C"))), /*#__PURE__*/React.createElement("div", {
    className: "proc-cli-block",
    "data-reveal": true,
    "data-reveal-delay": "0.05"
  }, /*#__PURE__*/React.createElement("header", {
    className: "proc-cli-block-head"
  }, /*#__PURE__*/React.createElement("span", {
    className: "proc-cli-block-eyebrow mono"
  }, cliEyebrow), /*#__PURE__*/React.createElement("h3", {
    className: "proc-cli-block-title"
  }, cliTitle), cliLead ? /*#__PURE__*/React.createElement("p", {
    className: "proc-cli-block-lead"
  }, cliLead) : null), /*#__PURE__*/React.createElement("div", {
    className: "proc-cli-card card"
  }, /*#__PURE__*/React.createElement("div", {
    ref: cliRef
  })))), /*#__PURE__*/React.createElement("div", {
    className: "constellation-section"
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell"
  }, /*#__PURE__*/React.createElement("div", {
    className: "constellation-frame card",
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("div", {
    ref: pgRef
  })))));
}

// ─────────────────────────────────────────────────────────────────────────────
// TRUST — testimonials
// ─────────────────────────────────────────────────────────────────────────────
// Trust signals — aggregate stats shown above the testimonial wall. We don't
// fabricate ratings; the numbers are derived from the testimonial dataset so
// they always match what the visitor can actually read on the cards.
const TRUST_STAR_GLYPH = "★";
const TRUST_STAR_COUNT = 5;
function Trust({
  t
}) {
  const ref = useRevealRoot([t]);
  const items = t.trust && Array.isArray(t.trust.items) ? t.trust.items : [];
  // Aggregate metrics — derived (not hand-set) so they stay honest.
  const totalQuotes = items.length;
  const uniqueRoles = function countUniqueRoles() {
    const seen = new Set();
    for (let i = 0; i < items.length; i++) {
      const r = (items[i].role || "").split(/[·•]/)[0].trim();
      if (r) seen.add(r);
    }
    return seen.size;
  }();
  return /*#__PURE__*/React.createElement("section", {
    "data-section": "trust",
    id: "trust",
    ref: ref
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell"
  }, /*#__PURE__*/React.createElement(SecHead, {
    num: "08",
    eyebrow: t.trust.eyebrow,
    title: t.trust.title,
    meta: `${totalQuotes} · signed`
  }), /*#__PURE__*/React.createElement("p", {
    className: "lead-line",
    "data-reveal": true
  }, t.trust.lead), /*#__PURE__*/React.createElement("div", {
    className: "trust-strip",
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "trust-strip-cell"
  }, /*#__PURE__*/React.createElement("div", {
    className: "trust-strip-stars",
    "aria-label": "rating 5 out of 5"
  }, Array.from({
    length: TRUST_STAR_COUNT
  }).map((_, i) => /*#__PURE__*/React.createElement("span", {
    key: i,
    className: "trust-strip-star"
  }, TRUST_STAR_GLYPH))), /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-val"
  }, "5.0 / 5")), /*#__PURE__*/React.createElement("div", {
    className: "trust-strip-cell"
  }, /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-val"
  }, totalQuotes), /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-k mono"
  }, "quotes")), /*#__PURE__*/React.createElement("div", {
    className: "trust-strip-cell"
  }, /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-val"
  }, uniqueRoles), /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-k mono"
  }, "roles")), /*#__PURE__*/React.createElement("div", {
    className: "trust-strip-cell"
  }, /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-val"
  }, "100%"), /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-k mono"
  }, "on-time"))), /*#__PURE__*/React.createElement("div", {
    className: "trust-grid"
  }, items.map(function renderTrust(it, i) {
    return /*#__PURE__*/React.createElement("figure", {
      key: i,
      className: "trust-card",
      "data-reveal": true,
      "data-reveal-delay": (i * 0.08).toFixed(2)
    }, /*#__PURE__*/React.createElement("span", {
      className: "trust-verified",
      "aria-label": "verified",
      title: "verified"
    }, /*#__PURE__*/React.createElement("svg", {
      viewBox: "0 0 16 16",
      width: "14",
      height: "14",
      fill: "none",
      stroke: "currentColor",
      strokeWidth: "2",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      "aria-hidden": "true"
    }, /*#__PURE__*/React.createElement("path", {
      d: "M2 9 L6 13 L14 4"
    })), /*#__PURE__*/React.createElement("span", {
      className: "mono"
    }, "verified")), /*#__PURE__*/React.createElement("div", {
      className: "trust-quote-mark",
      "aria-hidden": "true"
    }, "\""), /*#__PURE__*/React.createElement("blockquote", {
      className: "trust-q"
    }, it.q), /*#__PURE__*/React.createElement("figcaption", {
      className: "trust-cap"
    }, /*#__PURE__*/React.createElement("div", {
      className: "trust-avatar",
      "aria-hidden": "true"
    }, /*#__PURE__*/React.createElement("span", null, it.who.split(" ").map(function (w) {
      return w[0];
    }).join("").slice(0, 2))), /*#__PURE__*/React.createElement("div", {
      className: "trust-cap-text"
    }, /*#__PURE__*/React.createElement("div", {
      className: "trust-who"
    }, it.who), /*#__PURE__*/React.createElement("div", {
      className: "trust-role mono"
    }, it.role)), /*#__PURE__*/React.createElement("div", {
      className: "trust-stars",
      "aria-label": "5 stars"
    }, Array.from({
      length: TRUST_STAR_COUNT
    }).map(function (_, k) {
      return /*#__PURE__*/React.createElement("span", {
        key: k,
        className: "trust-star"
      }, TRUST_STAR_GLYPH);
    }))));
  }))));
}

// ─────────────────────────────────────────────────────────────────────────────
// CONTACT
// ─────────────────────────────────────────────────────────────────────────────
function Contact({
  t,
  links
}) {
  const ref = useRevealRoot([t]);
  const [sent, setSent] = useState2(false);
  // Multi-select chips for project scope — a single dropdown was hiding the
  // breadth of services. Chips let the visitor click as many as apply, which
  // also reveals the available service categories at a glance.
  const [scopeSet, setScopeSet] = useState2(() => new Set());
  // Budget slider — 5 fixed buckets so we don't ask for awkward exact numbers.
  const BUDGET_BUCKETS = ["< $2k", "$2-5k", "$5-10k", "$10-20k", "$20k+"];
  const [budgetIdx, setBudgetIdx] = useState2(1);
  // Timeline preference — small chip row for urgency, helps scoping.
  const TIMELINE_LABEL = t.contact.form.timeline || "Сроки";
  const TIMELINE_OPTS = t.contact.timeline_opts || ["ASAP", "1–2 недели", "1–2 месяца", "гибко"];
  const [timelineIdx, setTimelineIdx] = useState2(3);
  const BUDGET_LABEL = t.contact.form.budget || "Бюджет";
  function toggleScope(v) {
    setScopeSet(function (prev) {
      const next = new Set(prev);
      if (next.has(v)) next.delete(v);else next.add(v);
      return next;
    });
  }

  // v51: full form reset on submit so the visitor sees a clean slate after
  // the "sent" confirmation expires. We reset the native form (clears
  // <input> / <textarea>) AND all our React state (chip selections, slider,
  // timeline). Previous behaviour kept the text fields populated, which
  // looked broken — the success message overlay didn't visually consume
  // the form below it.
  const SENT_HIDE_DELAY_MS = 4500;
  function onSubmit(e) {
    e.preventDefault();
    const formEl = e.currentTarget;
    setSent(true);
    if (typeof navigator !== "undefined" && navigator.vibrate) {
      try {
        navigator.vibrate(14);
      } catch (err) {/* opportunistic */}
    }
    // Native fields — name/email/textarea.
    try {
      formEl.reset();
    } catch (err) {
      console.warn("[Contact] form.reset failed:", err && err.message);
    }
    // React-controlled state — chips, slider, timeline.
    setScopeSet(new Set());
    setBudgetIdx(1);
    setTimelineIdx(3);
    window.setTimeout(function hideSentBanner() {
      setSent(false);
    }, SENT_HIDE_DELAY_MS);
  }
  return /*#__PURE__*/React.createElement("section", {
    "data-section": "contact",
    id: "contact",
    ref: ref
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell"
  }, /*#__PURE__*/React.createElement(SecHead, {
    num: "09",
    eyebrow: t.contact.eyebrow,
    title: t.contact.title,
    em: t.contact.title.split(" ").pop(),
    meta: "status: receiving"
  }), /*#__PURE__*/React.createElement("p", {
    className: "lead-line",
    "data-reveal": true
  }, t.contact.lead), /*#__PURE__*/React.createElement("div", {
    className: "contact-layout"
  }, /*#__PURE__*/React.createElement("form", {
    className: "contact-form card",
    onSubmit: onSubmit,
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "contact-form-row"
  }, /*#__PURE__*/React.createElement("label", {
    className: "ff"
  }, /*#__PURE__*/React.createElement("span", {
    className: "ff-k mono"
  }, t.contact.form.name), /*#__PURE__*/React.createElement("input", {
    type: "text",
    required: true,
    className: "ff-input",
    autoComplete: "name"
  })), /*#__PURE__*/React.createElement("label", {
    className: "ff"
  }, /*#__PURE__*/React.createElement("span", {
    className: "ff-k mono"
  }, t.contact.form.email), /*#__PURE__*/React.createElement("input", {
    type: "text",
    required: true,
    className: "ff-input",
    autoComplete: "email"
  }))), /*#__PURE__*/React.createElement("div", {
    className: "ff"
  }, /*#__PURE__*/React.createElement("span", {
    className: "ff-k mono"
  }, t.contact.form.scope), /*#__PURE__*/React.createElement("div", {
    className: "ff-chips",
    role: "group",
    "aria-label": t.contact.form.scope
  }, t.contact.scope_opts.map(function renderChip(o, i) {
    const active = scopeSet.has(o);
    return /*#__PURE__*/React.createElement("button", {
      key: i,
      type: "button",
      className: `ff-chip ${active ? "is-active" : ""}`,
      "aria-pressed": active,
      onClick: () => toggleScope(o)
    }, o);
  }))), /*#__PURE__*/React.createElement("div", {
    className: "ff"
  }, /*#__PURE__*/React.createElement("span", {
    className: "ff-k mono"
  }, BUDGET_LABEL, /*#__PURE__*/React.createElement("span", {
    className: "ff-k-val"
  }, BUDGET_BUCKETS[budgetIdx])), /*#__PURE__*/React.createElement("div", {
    className: "ff-range-wrap"
  }, /*#__PURE__*/React.createElement("input", {
    type: "range",
    className: "ff-range",
    min: "0",
    max: BUDGET_BUCKETS.length - 1,
    step: "1",
    value: budgetIdx,
    onChange: e => setBudgetIdx(parseInt(e.target.value, 10)),
    style: {
      "--val-pct": `${budgetIdx / (BUDGET_BUCKETS.length - 1) * 100}%`
    }
  }), /*#__PURE__*/React.createElement("div", {
    className: "ff-range-track-marks",
    "aria-hidden": "true"
  }, BUDGET_BUCKETS.map(function renderMark(_b, i) {
    const cls = i < budgetIdx ? "is-passed" : i === budgetIdx ? "is-current" : "";
    return /*#__PURE__*/React.createElement("span", {
      key: i,
      className: `ff-range-track-mark ${cls}`
    });
  })), /*#__PURE__*/React.createElement("div", {
    className: "ff-range-ticks mono",
    "aria-hidden": "true"
  }, BUDGET_BUCKETS.map(function renderTick(b, i) {
    return /*#__PURE__*/React.createElement("span", {
      key: i,
      className: `ff-range-tick ${i === budgetIdx ? "is-active" : ""}`
    }, b);
  })))), /*#__PURE__*/React.createElement("div", {
    className: "ff"
  }, /*#__PURE__*/React.createElement("span", {
    className: "ff-k mono"
  }, TIMELINE_LABEL), /*#__PURE__*/React.createElement("div", {
    className: "ff-chips",
    role: "radiogroup",
    "aria-label": TIMELINE_LABEL
  }, TIMELINE_OPTS.map(function renderTimeline(o, i) {
    return /*#__PURE__*/React.createElement("button", {
      key: i,
      type: "button",
      role: "radio",
      "aria-checked": i === timelineIdx,
      className: `ff-chip ${i === timelineIdx ? "is-active" : ""}`,
      onClick: () => setTimelineIdx(i)
    }, o);
  }))), /*#__PURE__*/React.createElement("label", {
    className: "ff"
  }, /*#__PURE__*/React.createElement("span", {
    className: "ff-k mono"
  }, t.contact.form.msg), /*#__PURE__*/React.createElement("textarea", {
    required: true,
    rows: "4",
    className: "ff-input ff-textarea",
    placeholder: t.contact.form.msg_placeholder || ""
  })), /*#__PURE__*/React.createElement("button", {
    type: "submit",
    className: `btn btn-primary contact-submit ${sent ? "is-sent" : ""}`,
    disabled: sent
  }, /*#__PURE__*/React.createElement("span", null, sent ? t.contact.form.sent : t.contact.form.submit), /*#__PURE__*/React.createElement("span", {
    className: "arrow"
  }, sent ? "✓" : "→"))), /*#__PURE__*/React.createElement("aside", {
    className: "contact-side",
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "contact-deploy"
  }, /*#__PURE__*/React.createElement("div", {
    className: "mono contact-deploy-head"
  }, /*#__PURE__*/React.createElement("span", {
    className: "chip"
  }, /*#__PURE__*/React.createElement("span", {
    className: "chip-dot"
  }), "ready"), /*#__PURE__*/React.createElement("span", null, "deploy.endpoint")), /*#__PURE__*/React.createElement("div", {
    className: "contact-deploy-body"
  }, t.contact.links.map((l, i) => /*#__PURE__*/React.createElement("a", {
    key: i,
    href: l.k === "Email" ? `mailto:${l.v}` : `https://${l.v}`,
    target: l.k === "Email" ? undefined : "_blank",
    rel: l.k === "Email" ? undefined : "noopener noreferrer",
    className: "contact-link"
  }, /*#__PURE__*/React.createElement("span", {
    className: "mono contact-link-k"
  }, l.k), /*#__PURE__*/React.createElement("span", {
    className: "contact-link-v"
  }, l.v), /*#__PURE__*/React.createElement("span", {
    className: "arrow"
  }, "\u2197"))))), /*#__PURE__*/React.createElement("div", {
    className: "contact-signal"
  }, /*#__PURE__*/React.createElement("div", {
    className: "signal-pulse"
  }, /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null)), /*#__PURE__*/React.createElement("div", {
    className: "signal-meta mono"
  }, /*#__PURE__*/React.createElement("div", null, "UTC+5 \xB7 Tashkent"), /*#__PURE__*/React.createElement("div", null, "response < 24h"), /*#__PURE__*/React.createElement("div", null, "EN \xB7 RU \xB7 UZ")))))));
}

// ─────────────────────────────────────────────────────────────────────────────
// FOOTER
// ─────────────────────────────────────────────────────────────────────────────
function Footer({
  t,
  links
}) {
  return /*#__PURE__*/React.createElement("footer", {
    className: "site-footer"
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell footer-inner"
  }, /*#__PURE__*/React.createElement("div", {
    className: "footer-l"
  }, /*#__PURE__*/React.createElement("div", {
    className: "brand"
  }, /*#__PURE__*/React.createElement("span", {
    className: "brand-mark"
  }), /*#__PURE__*/React.createElement("span", null, "SAMANDAR \xB7 EXEC.AI.LAB")), /*#__PURE__*/React.createElement("div", {
    className: "mono footer-copy"
  }, t.footer.copy)), /*#__PURE__*/React.createElement("div", {
    className: "footer-r mono"
  }, /*#__PURE__*/React.createElement("div", null, t.footer.built), /*#__PURE__*/React.createElement("div", {
    className: "footer-links"
  }, /*#__PURE__*/React.createElement("a", {
    href: `https://${links.github}`,
    target: "_blank",
    rel: "noopener noreferrer"
  }, "github"), /*#__PURE__*/React.createElement("span", null, "\xB7"), /*#__PURE__*/React.createElement("a", {
    href: `https://${links.telegram}`,
    target: "_blank",
    rel: "noopener noreferrer"
  }, "telegram"), /*#__PURE__*/React.createElement("span", null, "\xB7"), /*#__PURE__*/React.createElement("a", {
    href: `mailto:${links.email}`
  }, "email")))));
}
Object.assign(window, {
  Services,
  CV,
  Process,
  Trust,
  Contact,
  Footer
});