/* AUTO-GENERATED by build.js from components-2.jsx — DO NOT EDIT.
   Edit the .jsx source and re-run `node build.js`. */
// components-2.jsx — Services, CV, Process, Trust, Contact, Footer

const {
  useEffect: useEffect2,
  useRef: useRef2,
  useState: useState2,
  useMemo: useMemoFromComponents1
} = React;

// ─────────────────────────────────────────────────────────────────────────────
// SERVICES 2.0 — panel switcher.
//   Desktop: WAI-ARIA tablist (left) + tabpanel (right), roving tabindex,
//            ↑/↓/Home/End, content crossfade on selection.
//   Mobile (≤900px): the SAME data as an accordion (button + aria-expanded +
//            region), one open at a time.
// One component, one DOM — the layout mode (panel vs accordion) is a CSS
// concern; only the ARIA wiring differs, gated by a matchMedia flag so screen
// readers always get the pattern that matches what's on screen.
//
// `io` ("spec → prod app") is the signature detail — rendered as a real
// input→output flow, not a pill. Related project is a HARD index→project map
// (never fuzzy) so we never invent a connection: services without a real
// match (Internal Tools, Tech Consulting) simply omit the block.
// ─────────────────────────────────────────────────────────────────────────────

// Hard map: service index → projects[].name that genuinely delivers it.
// null = no honest 1:1 match → the related block is not rendered.
const SERVICE_RELATED = ["Business Automation Engine",
// 0 Web Apps        → full product build
"Railway Infrastructure Site",
// 1 Landing & Sites → premium landing
"Task Orchestrator Bot",
// 2 Telegram Bots   → team bot
"Business Automation Engine",
// 3 AI Automation   → LLM workflow pipeline
"Biogas Operations Panel",
// 4 Dashboards      → ops dashboard
"Group Voice Task Bot",
// 5 MVP / Prototype → "MVP in 11 days"
null,
// 6 Internal Tools  → no honest 1:1 case
null // 7 Tech Consulting → advisory, no shippable case
];

// Split "spec → prod app" into [input, output] on the arrow.
function splitIo(io) {
  const parts = String(io || "").split("→");
  if (parts.length < 2) return {
    in: "",
    out: String(io || "").trim()
  };
  return {
    in: parts[0].trim(),
    out: parts.slice(1).join("→").trim()
  };
}

// The io flow: INPUT ─token→ OUTPUT. Pure CSS motion; decorative (aria-hidden
// on the rail/token), the words themselves are real, readable text.
function ServiceIoFlow({
  io
}) {
  const io2 = splitIo(io);
  return /*#__PURE__*/React.createElement("div", {
    className: "svc-io",
    "aria-label": `${io2.in} to ${io2.out}`
  }, /*#__PURE__*/React.createElement("span", {
    className: "svc-io-node svc-io-in"
  }, io2.in), /*#__PURE__*/React.createElement("span", {
    className: "svc-io-rail",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("span", {
    className: "svc-io-tok"
  })), /*#__PURE__*/React.createElement("span", {
    className: "svc-io-node svc-io-out"
  }, io2.out));
}
function Services({
  t
}) {
  const ref = useRevealRoot([t]);
  const items = t.services && Array.isArray(t.services.items) ? t.services.items : [];
  const projects = t.projects && Array.isArray(t.projects.items) ? t.projects.items : [];

  // Desktop: selected tab. Mobile: which accordion row is open (-1 = none).
  const [activeIdx, setActiveIdx] = useState2(0);
  const [openIdx, setOpenIdx] = useState2(0);
  const [isMobile, setIsMobile] = useState2(false);
  const tabRefs = useRef2([]);
  useEffect2(function watchLayout() {
    if (typeof window.matchMedia !== "function") return undefined;
    const mq = window.matchMedia("(max-width: 900px)");
    const apply = function () {
      setIsMobile(mq.matches);
    };
    apply();
    if (mq.addEventListener) mq.addEventListener("change", apply);else if (mq.addListener) mq.addListener(apply);
    return function () {
      if (mq.removeEventListener) mq.removeEventListener("change", apply);else if (mq.removeListener) mq.removeListener(apply);
    };
  }, []);
  function relatedFor(index) {
    const name = SERVICE_RELATED[index];
    if (!name) return null;
    for (let i = 0; i < projects.length; i++) {
      if (projects[i].name === name) return projects[i];
    }
    return null;
  }

  // Roving-tabindex keyboard nav for the desktop tablist.
  function onTabKey(e, i) {
    const last = items.length - 1;
    let next = -1;
    if (e.key === "ArrowDown" || e.key === "ArrowRight") next = i >= last ? 0 : i + 1;else if (e.key === "ArrowUp" || e.key === "ArrowLeft") next = i <= 0 ? last : i - 1;else if (e.key === "Home") next = 0;else if (e.key === "End") next = last;else return;
    e.preventDefault();
    setActiveIdx(next);
    const el = tabRefs.current[next];
    if (el && el.focus) el.focus();
  }

  // Shared details renderer (desktop panel + mobile accordion body).
  function renderDetails(s, i) {
    const rel = relatedFor(i);
    return /*#__PURE__*/React.createElement("div", {
      className: "svc-detail-inner"
    }, /*#__PURE__*/React.createElement("p", {
      className: "svc-detail-v"
    }, s.v), /*#__PURE__*/React.createElement(ServiceIoFlow, {
      io: s.io
    }), rel ? /*#__PURE__*/React.createElement("a", {
      className: "svc-related",
      href: "#projects",
      "data-cursor": "link",
      "data-cursor-label": "open case"
    }, /*#__PURE__*/React.createElement("span", {
      className: "svc-related-eyebrow mono"
    }, t.services.related_label || "related case"), /*#__PURE__*/React.createElement("span", {
      className: "svc-related-name"
    }, rel.name), /*#__PURE__*/React.createElement("span", {
      className: "svc-related-meta mono"
    }, /*#__PURE__*/React.createElement("span", {
      className: "svc-related-tag"
    }, rel.tag), rel.outcome ? /*#__PURE__*/React.createElement("span", {
      className: "svc-related-out"
    }, rel.outcome) : null), /*#__PURE__*/React.createElement("span", {
      className: "svc-related-arrow",
      "aria-hidden": "true"
    }, "\u2197")) : null);
  }
  return /*#__PURE__*/React.createElement("section", {
    "data-section": "services",
    id: "services",
    "data-enter": "slide-left",
    ref: ref
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell"
  }, /*#__PURE__*/React.createElement(SecHead, {
    num: "05",
    eyebrow: t.services.eyebrow,
    title: t.services.title,
    meta: `${items.length} services`
  }), /*#__PURE__*/React.createElement("div", {
    className: `svc ${isMobile ? "is-acc" : "is-panel"}`,
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "svc-list",
    role: isMobile ? undefined : "tablist",
    "aria-label": isMobile ? undefined : t.services.title,
    "aria-orientation": isMobile ? undefined : "vertical"
  }, items.map(function renderRow(s, i) {
    const isActive = activeIdx === i;
    const isOpen = openIdx === i;
    if (isMobile) {
      return /*#__PURE__*/React.createElement("div", {
        key: i,
        className: `svc-acc-row ${isOpen ? "is-open" : ""}`
      }, /*#__PURE__*/React.createElement("h3", {
        className: "svc-acc-h"
      }, /*#__PURE__*/React.createElement("button", {
        type: "button",
        className: "svc-acc-head",
        "data-code": String(i + 1).padStart(2, "0"),
        style: {
          "--row-i": i,
          "--row-total": Math.max(1, items.length - 1)
        },
        "aria-expanded": isOpen,
        "aria-controls": `svc-acc-body-${i}`,
        id: `svc-acc-head-${i}`,
        onClick: () => setOpenIdx(isOpen ? -1 : i)
      }, /*#__PURE__*/React.createElement("span", {
        className: "row-ghost",
        "aria-hidden": "true"
      }, String(i + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("span", {
        className: "svc-num mono"
      }, "/", String(i + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("span", {
        className: "svc-k"
      }, s.k), /*#__PURE__*/React.createElement("span", {
        className: "svc-acc-chev",
        "aria-hidden": "true"
      }, isOpen ? "−" : "+"))), /*#__PURE__*/React.createElement("div", {
        className: "svc-acc-body",
        id: `svc-acc-body-${i}`,
        role: "region",
        "aria-labelledby": `svc-acc-head-${i}`,
        hidden: !isOpen
      }, renderDetails(s, i)));
    }
    return /*#__PURE__*/React.createElement("button", {
      key: i,
      type: "button",
      role: "tab",
      id: `svc-tab-${i}`,
      "aria-selected": isActive,
      "aria-controls": `svc-panel-${i}`,
      tabIndex: isActive ? 0 : -1,
      ref: el => {
        tabRefs.current[i] = el;
      },
      className: `svc-tab ${isActive ? "is-active" : ""}`,
      "data-code": String(i + 1).padStart(2, "0"),
      style: {
        "--row-i": i,
        "--row-total": Math.max(1, items.length - 1)
      },
      onClick: () => setActiveIdx(i),
      onKeyDown: e => onTabKey(e, i),
      "data-cursor": "read"
    }, /*#__PURE__*/React.createElement("span", {
      className: "row-ghost",
      "aria-hidden": "true"
    }, String(i + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("span", {
      className: "svc-num mono"
    }, "/", String(i + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("span", {
      className: "svc-k"
    }, s.k), /*#__PURE__*/React.createElement("span", {
      className: "svc-tab-io mono",
      "aria-hidden": "true"
    }, s.io), /*#__PURE__*/React.createElement("span", {
      className: "svc-tab-mark",
      "aria-hidden": "true"
    }));
  })), !isMobile ? /*#__PURE__*/React.createElement("div", {
    className: "svc-panel-wrap"
  }, items.map(function renderPanel(s, i) {
    if (i !== activeIdx) return null;
    return /*#__PURE__*/React.createElement("div", {
      key: i,
      className: "svc-panel",
      role: "tabpanel",
      id: `svc-panel-${i}`,
      "aria-labelledby": `svc-tab-${i}`,
      tabIndex: 0
    }, /*#__PURE__*/React.createElement("div", {
      className: "svc-panel-head"
    }, /*#__PURE__*/React.createElement("span", {
      className: "svc-panel-num mono"
    }, "/", String(i + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("h3", {
      className: "svc-panel-k"
    }, s.k)), renderDetails(s, i));
  })) : null)));
}

// ─────────────────────────────────────────────────────────────────────────────
// CV — Resume document (proper, printable, mobile-friendly)
// ─────────────────────────────────────────────────────────────────────────────
// readme.md view — real GitHub-profile info (bio, breadth, availability, live
// proof), rendered as a rendered-markdown-style doc. Additive to the CV: it
// carries the "who + how I think + what I build across domains" that the
// timeline (roles/dates) doesn't.
function CvReadme({
  r
}) {
  if (!r || !r.intro) return null;
  const build = Array.isArray(r.build) ? r.build : [];
  const proof = Array.isArray(r.proof) ? r.proof : [];
  return /*#__PURE__*/React.createElement("div", {
    className: "cv-readme",
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("p", {
    className: "cv-readme-p"
  }, r.intro), r.intro2 ? /*#__PURE__*/React.createElement("p", {
    className: "cv-readme-p"
  }, r.intro2) : null, build.length ? /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("h4", {
    className: "cv-block-h mono"
  }, r.build_title), /*#__PURE__*/React.createElement("ul", {
    className: "cv-readme-list"
  }, build.map((b, i) => /*#__PURE__*/React.createElement("li", {
    key: i
  }, /*#__PURE__*/React.createElement("span", {
    className: "cv-bullet-mark",
    "aria-hidden": "true"
  }, "\u203A"), b)))) : null, proof.length ? /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("h4", {
    className: "cv-block-h mono"
  }, r.proof_title), /*#__PURE__*/React.createElement("div", {
    className: "cv-readme-proof"
  }, proof.map((p, i) => /*#__PURE__*/React.createElement("a", {
    key: i,
    className: "cv-readme-proof-row",
    href: p.url || "#",
    target: "_blank",
    rel: "noopener noreferrer",
    "data-cursor": "link",
    "data-cursor-label": `open: ${p.k}`
  }, /*#__PURE__*/React.createElement("span", {
    className: "mono cv-readme-proof-k"
  }, p.k), /*#__PURE__*/React.createElement("span", {
    className: "cv-readme-proof-v"
  }, p.v), /*#__PURE__*/React.createElement("span", {
    className: "arrow"
  }, "\u2197"))))) : null, r.avail ? /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("h4", {
    className: "cv-block-h mono"
  }, r.avail_title), /*#__PURE__*/React.createElement("p", {
    className: "cv-readme-p"
  }, r.avail)) : null);
}
function CV({
  t,
  links
}) {
  const ref = useRevealRoot([t]);
  const [openIdx, setOpenIdx] = useState2(0);
  // Which document view is showing: the résumé ("cv") or the GitHub readme.
  const [docTab, setDocTab] = useState2("cv");
  const hasReadme = !!(t.cv && t.cv.readme && t.cv.readme.intro);
  const showReadme = hasReadme && docTab === "readme";
  // Roles are an accordion: only one open at a time normally. For print we
  // force ALL open so the printed PDF shows the full timeline, then restore
  // the user's previous state after the print dialog closes.
  const restoreOpenIdx = useRef2(0);
  function onPrint() {
    restoreOpenIdx.current = openIdx;
    setDocTab("cv"); // the printed PDF is the résumé, never the readme view
    setOpenIdx(-2); // sentinel: "all open" (any non-numeric index that isn't matched)
    // Use a microtask + rAF so React commits the open-state change before
    // the synchronous window.print() blocks the main thread.
    Promise.resolve().then(function () {
      requestAnimationFrame(function () {
        requestAnimationFrame(function () {
          window.print();
        });
      });
    });
  }

  // afterprint event — restore the previous open role so the on-screen view
  // doesn't stay fully expanded.
  useEffect2(function bindAfterPrint() {
    const handler = function () {
      setOpenIdx(restoreOpenIdx.current);
    };
    window.addEventListener("afterprint", handler);
    return function () {
      window.removeEventListener("afterprint", handler);
    };
  }, []);

  // derive aggregate stats from timeline
  const years = (() => {
    const ys = t.cv.timeline.map(n => parseInt(String(n.y).match(/\d{4}/)?.[0] || "0", 10)).filter(Boolean);
    if (!ys.length) return null;
    return `${Math.min(...ys)}—${Math.max(...ys)}`;
  })();
  return /*#__PURE__*/React.createElement("section", {
    "data-section": "cv",
    id: "cv",
    "data-enter": "curtain",
    ref: ref
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell"
  }, /*#__PURE__*/React.createElement(SecHead, {
    num: "06",
    eyebrow: t.cv.eyebrow,
    title: t.cv.title,
    em: t.cv.title.split(" ").pop(),
    meta: `v.2026 · ${years || "active"}`
  }), /*#__PURE__*/React.createElement("article", {
    className: "cv-doc",
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("header", {
    className: "cv-doc-head"
  }, /*#__PURE__*/React.createElement("div", {
    className: "cv-doc-tabs mono",
    role: "tablist",
    "aria-label": "document view"
  }, /*#__PURE__*/React.createElement("button", {
    type: "button",
    role: "tab",
    "aria-selected": !showReadme,
    className: `cv-doc-tab ${!showReadme ? "is-active" : ""}`,
    onClick: () => setDocTab("cv"),
    "data-cursor": "link"
  }, "samandar.cv"), hasReadme ? /*#__PURE__*/React.createElement("button", {
    type: "button",
    role: "tab",
    "aria-selected": showReadme,
    className: `cv-doc-tab ${showReadme ? "is-active" : ""}`,
    onClick: () => setDocTab("readme"),
    "data-cursor": "link"
  }, "readme.md") : null), /*#__PURE__*/React.createElement("div", {
    className: "cv-doc-actions mono"
  }, /*#__PURE__*/React.createElement("button", {
    className: "cv-action",
    type: "button",
    onClick: onPrint,
    "data-cursor": "link",
    "data-cursor-label": "print / pdf"
  }, /*#__PURE__*/React.createElement("span", {
    className: "cv-action-ico",
    "aria-hidden": "true"
  }, "\u2318P"), /*#__PURE__*/React.createElement("span", null, "print \xB7 pdf")), /*#__PURE__*/React.createElement("a", {
    className: "cv-action",
    href: links?.email ? `mailto:${links.email}?subject=CV%20request` : "#",
    "data-cursor": "send",
    "data-cursor-label": "request signed cv"
  }, /*#__PURE__*/React.createElement("span", {
    className: "cv-action-ico",
    "aria-hidden": "true"
  }, "\u2197"), /*#__PURE__*/React.createElement("span", null, "request")))), /*#__PURE__*/React.createElement("div", {
    className: "cv-id"
  }, /*#__PURE__*/React.createElement("div", {
    className: "cv-id-l"
  }, /*#__PURE__*/React.createElement("h3", {
    className: "cv-id-name",
    "data-reveal": true
  }, t.cv.id?.name || "Samandar"), /*#__PURE__*/React.createElement("p", {
    className: "cv-id-role"
  }, t.cv.id?.role || t.cv.lead), /*#__PURE__*/React.createElement("div", {
    className: "cv-id-meta mono"
  }, (t.cv.id?.meta || []).map((m, i) => /*#__PURE__*/React.createElement("span", {
    key: i
  }, m)))), /*#__PURE__*/React.createElement("dl", {
    className: "cv-id-stats",
    "aria-label": "stats"
  }, (t.cv.id?.stats || []).map((s, i) => /*#__PURE__*/React.createElement("div", {
    key: i,
    className: "cv-id-stat"
  }, /*#__PURE__*/React.createElement("dt", {
    className: "mono"
  }, s.k), /*#__PURE__*/React.createElement("dd", null, s.v))))), showReadme ? /*#__PURE__*/React.createElement(CvReadme, {
    r: t.cv.readme
  }) : /*#__PURE__*/React.createElement("div", {
    className: "cv-doc-body"
  }, /*#__PURE__*/React.createElement("main", {
    className: "cv-main"
  }, /*#__PURE__*/React.createElement("h4", {
    className: "cv-block-h mono"
  }, t.cv.exp_title || "experience"), /*#__PURE__*/React.createElement("ol", {
    className: "cv-roles"
  }, t.cv.timeline.map((node, i) => {
    const isOpen = openIdx === -2 || openIdx === i;
    return /*#__PURE__*/React.createElement("li", {
      key: i,
      className: `cv-role ${isOpen ? "is-open" : ""}`
    }, /*#__PURE__*/React.createElement("button", {
      className: "cv-role-head",
      type: "button",
      "aria-expanded": isOpen,
      onClick: () => setOpenIdx(isOpen ? -1 : i),
      "data-cursor": "read",
      "data-cursor-label": isOpen ? "collapse" : "expand"
    }, /*#__PURE__*/React.createElement("span", {
      className: "cv-role-y mono"
    }, node.y), /*#__PURE__*/React.createElement("span", {
      className: "cv-role-main"
    }, /*#__PURE__*/React.createElement("span", {
      className: "cv-role-title"
    }, node.role), /*#__PURE__*/React.createElement("span", {
      className: "cv-role-org"
    }, node.org)), /*#__PURE__*/React.createElement("span", {
      className: "cv-role-tag mono"
    }, node.tag), /*#__PURE__*/React.createElement("span", {
      className: "cv-role-chev",
      "aria-hidden": "true"
    }, isOpen ? "−" : "+")), /*#__PURE__*/React.createElement("div", {
      className: "cv-role-body",
      hidden: !isOpen
    }, /*#__PURE__*/React.createElement("ul", {
      className: "cv-points"
    }, node.points.map((p, k) => /*#__PURE__*/React.createElement("li", {
      key: k
    }, p))), node.stack && node.stack.length ? /*#__PURE__*/React.createElement("div", {
      className: "cv-role-stack"
    }, node.stack.map((s, k) => /*#__PURE__*/React.createElement("span", {
      key: k,
      className: "mono cv-chip"
    }, s))) : null));
  }))), /*#__PURE__*/React.createElement("aside", {
    className: "cv-side"
  }, /*#__PURE__*/React.createElement("section", {
    className: "cv-block"
  }, /*#__PURE__*/React.createElement("h4", {
    className: "cv-block-h mono"
  }, t.cv.edu_title), /*#__PURE__*/React.createElement("ul", {
    className: "cv-side-list"
  }, t.cv.edu.map((e, i) => /*#__PURE__*/React.createElement("li", {
    key: i,
    className: "cv-edu-row"
  }, /*#__PURE__*/React.createElement("span", {
    className: "mono cv-edu-y"
  }, e.y), /*#__PURE__*/React.createElement("span", {
    className: "cv-edu-k"
  }, e.k))))), t.cv.strengths?.length ? /*#__PURE__*/React.createElement("section", {
    className: "cv-block"
  }, /*#__PURE__*/React.createElement("h4", {
    className: "cv-block-h mono"
  }, t.cv.strengths_title || "strengths"), /*#__PURE__*/React.createElement("ul", {
    className: "cv-side-list cv-strengths"
  }, t.cv.strengths.map((s, i) => /*#__PURE__*/React.createElement("li", {
    key: i
  }, /*#__PURE__*/React.createElement("span", {
    className: "cv-bullet-mark",
    "aria-hidden": "true"
  }, "\u203A"), s)))) : null, t.cv.langs?.length ? /*#__PURE__*/React.createElement("section", {
    className: "cv-block"
  }, /*#__PURE__*/React.createElement("h4", {
    className: "cv-block-h mono"
  }, t.cv.langs_title || "languages"), /*#__PURE__*/React.createElement("ul", {
    className: "cv-langs"
  }, t.cv.langs.map((l, i) => /*#__PURE__*/React.createElement("li", {
    key: i,
    className: "cv-lang"
  }, /*#__PURE__*/React.createElement("span", null, l.k), /*#__PURE__*/React.createElement("span", {
    className: "cv-lang-bar",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("span", {
    className: "cv-lang-bar-fill",
    style: {
      width: `${l.lv}%`
    }
  })), /*#__PURE__*/React.createElement("span", {
    className: "mono cv-lang-lvl"
  }, l.label))))) : null)), /*#__PURE__*/React.createElement("footer", {
    className: "cv-doc-foot mono"
  }, /*#__PURE__*/React.createElement("span", null, "\u2014 end of file \u2014"), /*#__PURE__*/React.createElement("span", null, t.cv.foot || "generated 2026 · verifiable on request")))));
}

// ─────────────────────────────────────────────────────────────────────────────
// PROCESS — deployment pipeline. Vertical terminal "stages" that flip
//   queued → running (with typewriter command + progress bar) → done (with
//   completion time) as they enter the viewport.
//
// Each stage handles its own typewriter + progress timeline independently so
// state stays simple and the row mounts behave like real CI logs.
// ─────────────────────────────────────────────────────────────────────────────
const PROC_TYPE_INTERVAL_MS = 22; // typewriter cadence
const PROC_RUN_MIN_MS = 520; // visual run-time per stage
const PROC_RUN_VAR_MS = 240;
const PROC_VIEWPORT_TRIGGER_RATIO = 0.4;
const PROC_OUTPUT_SAMPLES = ["ok · ready", "compiled in 84ms", "shipped to prod", "200 · listening", "no regressions", "manifest verified", "queue empty"];
function ProcStage({
  step,
  index,
  refSetter
}) {
  // Stage states: queued (idle) → running (typing + progress) → done (success).
  const [state, setState] = useState2("queued");
  const [typed, setTyped] = useState2("");
  const [progress, setProgress] = useState2(0);
  const stageRef = useRef2(null);
  const timersRef = useRef2({
    typer: 0,
    prog: 0,
    done: 0
  });

  // Combined ref: store internally + report to parent collection.
  function combinedRef(el) {
    stageRef.current = el;
    if (typeof refSetter === "function") refSetter(el);
  }

  // Run typewriter when state flips to "running".
  useEffect2(function runTyper() {
    if (state !== "running") return undefined;
    const cmd = step.cmd;
    let cursor = 0;
    timersRef.current.typer = window.setInterval(function step1() {
      cursor++;
      setTyped(cmd.slice(0, cursor));
      if (cursor >= cmd.length) {
        window.clearInterval(timersRef.current.typer);
        timersRef.current.typer = 0;
      }
    }, PROC_TYPE_INTERVAL_MS);
    return function cleanup() {
      if (timersRef.current.typer) {
        window.clearInterval(timersRef.current.typer);
        timersRef.current.typer = 0;
      }
    };
  }, [state, step.cmd]);

  // Progress bar fills 0 → 100 over PROC_RUN_MIN_MS + variance.
  useEffect2(function runProgress() {
    if (state !== "running") return undefined;
    const totalMs = PROC_RUN_MIN_MS + index % 5 * (PROC_RUN_VAR_MS / 5);
    const startedAt = performance.now();
    function tick(now) {
      const t = Math.min(1, (now - startedAt) / totalMs);
      setProgress(t);
      if (t < 1) {
        timersRef.current.prog = window.requestAnimationFrame(tick);
      } else {
        timersRef.current.prog = 0;
        timersRef.current.done = window.setTimeout(function flipDone() {
          setState("done");
        }, 120);
      }
    }
    timersRef.current.prog = window.requestAnimationFrame(tick);
    return function cleanup() {
      if (timersRef.current.prog) {
        window.cancelAnimationFrame(timersRef.current.prog);
        timersRef.current.prog = 0;
      }
      if (timersRef.current.done) {
        window.clearTimeout(timersRef.current.done);
        timersRef.current.done = 0;
      }
    };
  }, [state, index]);

  // IntersectionObserver — flip queued → running when the row is in view.
  useEffect2(function watchViewport() {
    if (!stageRef.current) return undefined;
    const io = new IntersectionObserver(function onSeen(entries) {
      entries.forEach(function check(e) {
        if (e.isIntersecting && e.intersectionRatio > PROC_VIEWPORT_TRIGGER_RATIO) {
          setState(function (prev) {
            return prev === "queued" ? "running" : prev;
          });
          io.unobserve(e.target);
        }
      });
    }, {
      threshold: [PROC_VIEWPORT_TRIGGER_RATIO, 0.55, 0.7]
    });
    io.observe(stageRef.current);
    return function () {
      io.disconnect();
    };
  }, []);

  // Scroll-based fallback for environments where IO is unreliable.
  useEffect2(function scrollFallback() {
    if (state !== "queued") return undefined;
    let raf = 0;
    function check() {
      raf = 0;
      const el = stageRef.current;
      if (!el) return;
      const r = el.getBoundingClientRect();
      const vh = window.innerHeight;
      if (r.top < vh * 0.7 && r.bottom > vh * 0.15) {
        setState("running");
      }
    }
    function onScroll() {
      if (!raf) raf = window.requestAnimationFrame(check);
    }
    window.addEventListener("scroll", onScroll, {
      passive: true
    });
    check();
    return function () {
      window.removeEventListener("scroll", onScroll);
      if (raf) window.cancelAnimationFrame(raf);
    };
  }, [state]);
  return /*#__PURE__*/React.createElement("li", {
    ref: combinedRef,
    className: `proc-stage proc-stage--${state}`,
    "data-reveal-delay": (index * 0.06).toFixed(2)
  }, /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-gutter mono"
  }, String(index + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("div", {
    className: "proc-stage-main"
  }, /*#__PURE__*/React.createElement("div", {
    className: "proc-stage-cmd mono"
  }, state === "queued" ? /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-cmd-ghost"
  }, step.cmd) : /*#__PURE__*/React.createElement(React.Fragment, null, /*#__PURE__*/React.createElement("span", null, typed), state === "running" && /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-caret"
  }))), /*#__PURE__*/React.createElement("div", {
    className: "proc-stage-meta"
  }, /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-k"
  }, step.k), /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-arrow"
  }, "\u2192"), /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-v"
  }, step.v)), state === "running" && /*#__PURE__*/React.createElement("div", {
    className: "proc-stage-progress",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("div", {
    className: "proc-stage-progress-fill",
    style: {
      transform: `scaleX(${progress.toFixed(3)})`
    }
  })), state === "done" && /*#__PURE__*/React.createElement("div", {
    className: "proc-stage-output mono"
  }, /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-output-prompt"
  }, "\u203A"), /*#__PURE__*/React.createElement("span", null, step.output))), /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-status mono"
  }, state === "queued" && /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-pill proc-stage-pill--queued"
  }, "queued"), state === "running" && /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-pill proc-stage-pill--running"
  }, /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-spin",
    "aria-hidden": "true"
  }), "running"), state === "done" && /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-pill proc-stage-pill--done"
  }, /*#__PURE__*/React.createElement("span", {
    className: "proc-stage-check",
    "aria-hidden": "true"
  }, "\u2713"), step.ms)));
}
function Process({
  t
}) {
  const ref = useRevealRoot([t]);
  const steps = useMemoFromComponents1(function buildSteps() {
    return t.process.steps.map(function buildStep(s, i) {
      const slug = String(s.k || "step").toLowerCase().replace(/[^a-z0-9]+/g, "-");
      const ms = 120 + i * 41 % 230;
      return {
        k: s.k,
        v: s.v,
        cmd: `$ ./pipeline run --stage ${slug}`,
        ms: `${String(ms).padStart(3, "0")}ms`,
        output: PROC_OUTPUT_SAMPLES[i % PROC_OUTPUT_SAMPLES.length]
      };
    });
  }, [t]);
  return /*#__PURE__*/React.createElement("section", {
    "data-section": "process",
    id: "process",
    "data-enter": "line-stagger",
    ref: ref
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell"
  }, /*#__PURE__*/React.createElement(SecHead, {
    num: "07",
    eyebrow: t.process.eyebrow,
    title: t.process.title,
    meta: "pipeline.run()"
  }), /*#__PURE__*/React.createElement("p", {
    className: "lead-line",
    "data-reveal": true
  }, t.process.lead), /*#__PURE__*/React.createElement("div", {
    className: "proc-terminal card",
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "proc-terminal-head"
  }, /*#__PURE__*/React.createElement("div", {
    className: "proc-terminal-dots"
  }, /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null)), /*#__PURE__*/React.createElement("span", {
    className: "mono proc-terminal-title"
  }, "/usr/local/bin/ship \u2014 pipeline.v26"), /*#__PURE__*/React.createElement("span", {
    className: "mono proc-terminal-meta"
  }, steps.length, " stages")), /*#__PURE__*/React.createElement("ol", {
    className: "proc-terminal-body"
  }, steps.map(function renderStage(s, i) {
    return /*#__PURE__*/React.createElement(ProcStage, {
      key: i,
      step: s,
      index: i
    });
  })), /*#__PURE__*/React.createElement("div", {
    className: "proc-terminal-foot mono"
  }, /*#__PURE__*/React.createElement("span", {
    className: "proc-terminal-prompt"
  }, "\u203A"), /*#__PURE__*/React.createElement("span", null, "READY \xB7 listening on :443"), /*#__PURE__*/React.createElement("span", {
    className: "proc-terminal-cursor"
  }, "\u258C")))));
}

// ─────────────────────────────────────────────────────────────────────────────
// PROJECT BUILDER — "Живой конструктор проекта"
// The site's signature interactive + lead magnet. The visitor picks a project
// TYPE and SCALE; a warm architecture blueprint assembles live (a layered
// "system cake": client → logic → intelligence → data → infrastructure) while
// a readout crystallizes (stack · timeline · budget). CTAs: a Telegram
// deep-link and a handoff that pre-fills the Contact form via a window
// CustomEvent ("sm:builder-config").
//
// Why a layer stack, not measured SVG connectors: every layer is a fixed slot
// toggled by `is-active` (grid-rows 0fr→1fr collapse — the same trick the FAQ
// and Signal accordions use), so there is ZERO DOM-coordinate math, it
// animates smoothly, and it can never misalign on resize or font swap.
// ─────────────────────────────────────────────────────────────────────────────

// Neutral (language-independent) tech vocabulary — real tools, matched to what
// the rest of the site already claims (see skills.groups / projects[].stack).
const BUILDER_TECH = {
  frontend: ["Next.js", "React", "Tailwind"],
  telegram: ["Bot API", "Web App"],
  triggers: ["Webhooks", "n8n", "Cron"],
  api: ["FastAPI", "Node", "tRPC"],
  bot: ["Node", "Python", "Queue"],
  pipeline: ["Python", "Workers", "Queue"],
  ai: ["Claude", "GPT-4o", "LangChain", "RAG"]
};

// Maps scale → the Contact form's budget bucket index
// (["< $200","$200-600","$600-1.5k","$1.5-3k","$3k+"]) plus a display range.
// Ranges confirmed directly against the actual Uzbekistan market (client's
// own numbers, 2026-07) — even the FIRST pricing pass (grounded in solo/
// CIS-remote research) still read as agency-inflated for local UZ clients.
const BUILDER_SCALE_META = {
  mvp: {
    budgetIdx: 1,
    budget: "$250–1k"
  },
  prod: {
    budgetIdx: 2,
    budget: "$500–2k"
  },
  product: {
    budgetIdx: 4,
    budget: "$2–5k"
  }
};
function builderDedupe(arr) {
  const seen = {};
  const out = [];
  for (let i = 0; i < arr.length; i++) {
    if (!seen[arr[i]]) {
      seen[arr[i]] = 1;
      out.push(arr[i]);
    }
  }
  return out;
}

// Pure function: which layers exist + their tech, given (type, scale, priority).
// priority ("что критично") meaningfully bends the stack — this is the depth the
// client asked for, not cosmetic: e.g. AI-depth forces the intelligence layer on
// even for a plain web app; Load adds queues/CDN/cache; Design adds motion libs.
function builderModel(typeKey, scaleKey, priorityKey, sub) {
  const isAIType = typeKey === "ai" || typeKey === "automation";
  const isAI = isAIType || priorityKey === "ai";
  const prod = scaleKey === "prod" || scaleKey === "product";
  const product = scaleKey === "product";
  const heavyLoad = priorityKey === "scale";
  const designFirst = priorityKey === "design";
  let clientSub, clientTech;
  if (typeKey === "bot") {
    clientSub = sub.telegram;
    clientTech = BUILDER_TECH.telegram.slice();
  } else if (typeKey === "automation") {
    clientSub = sub.triggers;
    clientTech = BUILDER_TECH.triggers.slice();
  } else {
    clientSub = sub.frontend;
    clientTech = BUILDER_TECH.frontend.slice();
  }
  if (designFirst && typeKey !== "bot" && typeKey !== "automation") clientTech.push("Framer Motion", "GSAP");
  let logicSub, logicTech;
  if (typeKey === "bot") {
    logicSub = sub.bot;
    logicTech = BUILDER_TECH.bot.slice();
  } else if (typeKey === "automation") {
    logicSub = sub.pipeline;
    logicTech = BUILDER_TECH.pipeline.slice();
  } else {
    logicSub = sub.api;
    logicTech = BUILDER_TECH.api.slice();
  }
  const aiTech = BUILDER_TECH.ai.slice();
  if (priorityKey === "ai") aiTech.push("Evals");
  const dataTech = ["Postgres"];
  if (prod || heavyLoad) dataTech.push("Redis");
  if (isAI) dataTech.push("pgvector");
  const infraTech = ["Docker", "Deploy"];
  if (prod) infraTech.push("Auth · RBAC", "Sentry", "GitHub Actions");
  if (product) infraTech.push("Analytics");
  if (heavyLoad) infraTech.push("Queue", "CDN", "Load balancer");
  return [{
    id: "client",
    sub: clientSub,
    tech: builderDedupe(clientTech),
    active: true
  }, {
    id: "logic",
    sub: logicSub,
    tech: builderDedupe(logicTech),
    active: true
  }, {
    id: "ai",
    sub: sub.ai,
    tech: builderDedupe(aiTech),
    active: isAI
  }, {
    id: "data",
    sub: "",
    tech: builderDedupe(dataTech),
    active: true
  }, {
    id: "infra",
    sub: "",
    tech: builderDedupe(infraTech),
    active: true
  }];
}

// One representative tech per active layer, in flow order — the readout summary.
function builderStackSummary(layers) {
  const picks = [];
  layers.forEach(function pick(L) {
    if (L.active && L.tech && L.tech.length) picks.push(L.tech[0]);
  });
  return picks.join(" · ");
}

// Builder type → Contact scope_opts label (for chip pre-select on handoff).
const BUILDER_SCOPE_MAP = {
  web: "Web App / MVP",
  ai: "AI Automation",
  bot: "Telegram Bot",
  automation: "AI Automation"
};
function ProjectBuilder({
  t,
  links
}) {
  const ref = useRevealRoot([t]);
  const b = t.builder;
  const [typeKey, setTypeKey] = useState2("web");
  const [scaleKey, setScaleKey] = useState2("mvp");
  const [priorityKey, setPriorityKey] = useState2("speed");
  // Sequential-assembly driver: `shown` counts how many active layers have
  // dropped into place. On any choice change we reset to 0 and re-reveal them
  // top-down on a timer, so the system visibly RE-ASSEMBLES every time.
  const [shown, setShown] = useState2(0);

  // Defensive: if a content bundle predates the builder v2 block, render nothing
  // rather than throwing (keeps older cached content.js from white-screening).
  if (!b || !b.priorities || !b.verdictLead) return null;
  const layers = builderModel(typeKey, scaleKey, priorityKey, b.sub);
  const scaleMeta = BUILDER_SCALE_META[scaleKey] || BUILDER_SCALE_META.mvp;
  const stackSummary = builderStackSummary(layers);
  const timeText = b.times && b.times[scaleKey] || "";
  const activeCount = layers.reduce(function (n, L) {
    return n + (L.active ? 1 : 0);
  }, 0);
  const moduleCount = layers.reduce(function (n, L) {
    return n + (L.active ? L.tech.length : 0);
  }, 0);
  const verdict = (b.verdictLead[typeKey] || "") + " — " + (b.verdictTail[priorityKey] || "");
  useEffect2(function runAssembly() {
    const reduce = typeof window.matchMedia === "function" && window.matchMedia("(prefers-reduced-motion: reduce)").matches || document.documentElement.hasAttribute("data-motion-lite");
    if (reduce) {
      setShown(activeCount);
      return undefined;
    }
    setShown(0);
    const timers = [];
    let i = 0;
    function step() {
      i += 1;
      setShown(i);
      if (i < activeCount) timers.push(window.setTimeout(step, 130));
    }
    timers.push(window.setTimeout(step, 90));
    return function () {
      timers.forEach(function (id) {
        window.clearTimeout(id);
      });
    };
    // Re-run on any choice change (activeCount captures type/priority AI toggling).
  }, [typeKey, scaleKey, priorityKey, activeCount]);
  function pick(list, k) {
    const f = list.filter(function (x) {
      return x.k === k;
    })[0];
    return f ? f.label : k;
  }
  function summaryLine() {
    return pick(b.types, typeKey) + " · " + pick(b.scales, scaleKey) + " · " + pick(b.priorities, priorityKey) + "\n" + verdict + "\n" + b.readout.stack + ": " + stackSummary + "\n" + b.readout.time + ": " + timeText + " · " + b.readout.budget + ": " + scaleMeta.budget;
  }
  function onHandoff() {
    if (typeof navigator !== "undefined" && navigator.vibrate) {
      try {
        navigator.vibrate(8);
      } catch (err) {/* opportunistic */}
    }
    try {
      window.dispatchEvent(new CustomEvent("sm:builder-config", {
        detail: {
          scope: BUILDER_SCOPE_MAP[typeKey],
          budgetIdx: scaleMeta.budgetIdx,
          summary: summaryLine()
        }
      }));
    } catch (err) {/* opportunistic */}
    const el = document.getElementById("contact");
    if (el) el.scrollIntoView({
      behavior: "smooth",
      block: "start"
    });
  }

  // Assign each active layer its position among the active set so the cascade
  // (and the `shown` gate) can reveal them strictly top-down.
  let activeIdx = -1;
  const rows = layers.map(function (L) {
    let ai = -1;
    if (L.active) {
      activeIdx += 1;
      ai = activeIdx;
    }
    return {
      L: L,
      activeIdx: ai,
      shown: L.active && ai < shown
    };
  });
  return /*#__PURE__*/React.createElement("section", {
    id: "builder",
    className: "builder-sec",
    "data-enter": "assemble",
    ref: ref
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell"
  }, /*#__PURE__*/React.createElement(SecHead, {
    eyebrow: b.eyebrow,
    title: b.title,
    meta: "build.preview()"
  }), /*#__PURE__*/React.createElement("p", {
    className: "lead-line",
    "data-reveal": true
  }, b.lead), /*#__PURE__*/React.createElement("div", {
    className: "builder card",
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "builder-choices"
  }, /*#__PURE__*/React.createElement("div", {
    className: "builder-step"
  }, /*#__PURE__*/React.createElement("div", {
    className: "builder-step-k mono"
  }, /*#__PURE__*/React.createElement("span", {
    className: "builder-step-n"
  }, "01"), b.step1), /*#__PURE__*/React.createElement("div", {
    className: "builder-opts builder-opts--type"
  }, b.types.map(function renderType(o) {
    const on = typeKey === o.k;
    return /*#__PURE__*/React.createElement("button", {
      key: o.k,
      type: "button",
      className: `builder-opt ${on ? "is-active" : ""}`,
      "aria-pressed": on,
      onClick: function () {
        setTypeKey(o.k);
      }
    }, /*#__PURE__*/React.createElement("span", {
      className: "builder-opt-label"
    }, o.label), /*#__PURE__*/React.createElement("span", {
      className: "builder-opt-note mono"
    }, o.note));
  }))), /*#__PURE__*/React.createElement("div", {
    className: "builder-step"
  }, /*#__PURE__*/React.createElement("div", {
    className: "builder-step-k mono"
  }, /*#__PURE__*/React.createElement("span", {
    className: "builder-step-n"
  }, "02"), b.step2), /*#__PURE__*/React.createElement("div", {
    className: "builder-opts builder-opts--scale"
  }, b.scales.map(function renderScale(o) {
    const on = scaleKey === o.k;
    return /*#__PURE__*/React.createElement("button", {
      key: o.k,
      type: "button",
      className: `builder-opt builder-opt--pill ${on ? "is-active" : ""}`,
      "aria-pressed": on,
      onClick: function () {
        setScaleKey(o.k);
      }
    }, /*#__PURE__*/React.createElement("span", {
      className: "builder-opt-label"
    }, o.label), /*#__PURE__*/React.createElement("span", {
      className: "builder-opt-note mono"
    }, o.note));
  }))), /*#__PURE__*/React.createElement("div", {
    className: "builder-step"
  }, /*#__PURE__*/React.createElement("div", {
    className: "builder-step-k mono"
  }, /*#__PURE__*/React.createElement("span", {
    className: "builder-step-n"
  }, "03"), b.step3), /*#__PURE__*/React.createElement("div", {
    className: "builder-opts builder-opts--prio"
  }, b.priorities.map(function renderPrio(o) {
    const on = priorityKey === o.k;
    return /*#__PURE__*/React.createElement("button", {
      key: o.k,
      type: "button",
      className: `builder-opt builder-opt--pill ${on ? "is-active" : ""}`,
      "aria-pressed": on,
      onClick: function () {
        setPriorityKey(o.k);
      }
    }, /*#__PURE__*/React.createElement("span", {
      className: "builder-opt-label"
    }, o.label), /*#__PURE__*/React.createElement("span", {
      className: "builder-opt-note mono"
    }, o.note));
  })))), /*#__PURE__*/React.createElement("div", {
    className: "builder-stage",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("div", {
    className: "builder-metric mono"
  }, /*#__PURE__*/React.createElement("span", {
    className: "builder-metric-dot"
  }), activeCount, " ", b.metric.layers, " \xB7 ", moduleCount, " ", b.metric.modules), /*#__PURE__*/React.createElement("div", {
    className: "builder-layers"
  }, /*#__PURE__*/React.createElement("span", {
    className: "builder-backbone"
  }), /*#__PURE__*/React.createElement("span", {
    className: "builder-flow"
  }), rows.filter(function keepShown(r) {
    return r.shown;
  }).map(function renderLayer(r) {
    const L = r.L;
    return /*#__PURE__*/React.createElement("div", {
      key: L.id,
      className: `builder-layer builder-layer--${L.id}`,
      style: {
        "--li": r.activeIdx
      }
    }, /*#__PURE__*/React.createElement("div", {
      className: "builder-layer-body"
    }, /*#__PURE__*/React.createElement("div", {
      className: "builder-layer-head"
    }, /*#__PURE__*/React.createElement("span", {
      className: "builder-layer-name mono"
    }, b.layers[L.id]), L.sub ? /*#__PURE__*/React.createElement("span", {
      className: "builder-layer-sub"
    }, L.sub) : null), b.layerNote && b.layerNote[L.id] ? /*#__PURE__*/React.createElement("div", {
      className: "builder-layer-note"
    }, b.layerNote[L.id]) : null, /*#__PURE__*/React.createElement("div", {
      className: "builder-layer-tech"
    }, L.tech.map(function renderChip(tch, i) {
      return /*#__PURE__*/React.createElement("span", {
        key: i,
        className: "builder-chip mono",
        style: {
          "--ci": i
        }
      }, tch);
    }))));
  }))), /*#__PURE__*/React.createElement("div", {
    className: "builder-readout-block"
  }, /*#__PURE__*/React.createElement("div", {
    className: "builder-readout",
    "aria-live": "polite"
  }, /*#__PURE__*/React.createElement("div", {
    className: "builder-readout-row"
  }, /*#__PURE__*/React.createElement("span", {
    className: "builder-readout-k mono"
  }, b.readout.stack), /*#__PURE__*/React.createElement("span", {
    className: "builder-readout-v mono",
    key: "s" + stackSummary
  }, stackSummary)), /*#__PURE__*/React.createElement("div", {
    className: "builder-readout-row"
  }, /*#__PURE__*/React.createElement("span", {
    className: "builder-readout-k mono"
  }, b.readout.time), /*#__PURE__*/React.createElement("span", {
    className: "builder-readout-v mono",
    key: "t" + timeText
  }, timeText)), /*#__PURE__*/React.createElement("div", {
    className: "builder-readout-row"
  }, /*#__PURE__*/React.createElement("span", {
    className: "builder-readout-k mono"
  }, b.readout.budget), /*#__PURE__*/React.createElement("span", {
    className: "builder-readout-v mono",
    key: "b" + scaleMeta.budget
  }, scaleMeta.budget))), /*#__PURE__*/React.createElement("div", {
    className: "builder-verdict",
    key: verdict
  }, /*#__PURE__*/React.createElement("span", {
    className: "builder-verdict-mark",
    "aria-hidden": "true"
  }, "\u201C"), /*#__PURE__*/React.createElement("p", {
    className: "builder-verdict-text"
  }, verdict))), /*#__PURE__*/React.createElement("div", {
    className: "builder-cta-block"
  }, /*#__PURE__*/React.createElement("div", {
    className: "builder-cta"
  }, /*#__PURE__*/React.createElement("a", {
    className: "btn btn-primary builder-cta-tg",
    href: `https://${links.telegram}`,
    target: "_blank",
    rel: "noopener noreferrer"
  }, /*#__PURE__*/React.createElement("span", null, b.cta_tg), /*#__PURE__*/React.createElement("span", {
    className: "arrow"
  }, "\u2192")), /*#__PURE__*/React.createElement("button", {
    type: "button",
    className: "builder-cta-alt",
    onClick: onHandoff
  }, b.cta_form, " ", /*#__PURE__*/React.createElement("span", {
    className: "arrow"
  }, "\u2192"))), /*#__PURE__*/React.createElement("div", {
    className: "builder-hint mono"
  }, b.hint)))));
}

// ─────────────────────────────────────────────────────────────────────────────
// FAQ — accordion of common client questions. Single-open-at-a-time, click/tap
// only (no hover-preview — this is a utilitarian Q&A list, not the editorial
// browsing Signal owns). First question starts open so the interaction pattern
// is visible without requiring a click.
// ─────────────────────────────────────────────────────────────────────────────
function FaqRow({
  item,
  index,
  open,
  onToggle
}) {
  return /*#__PURE__*/React.createElement("div", {
    className: `faq-row${open ? " is-open" : ""}`
  }, /*#__PURE__*/React.createElement("button", {
    type: "button",
    className: "faq-row-head",
    "aria-expanded": open,
    "aria-controls": `faq-a-${index}`,
    onClick: () => onToggle(index)
  }, /*#__PURE__*/React.createElement("span", {
    className: "faq-row-num mono"
  }, String(index + 1).padStart(2, "0")), /*#__PURE__*/React.createElement("span", {
    className: "faq-row-q"
  }, item.q), /*#__PURE__*/React.createElement("span", {
    className: "faq-row-icon",
    "aria-hidden": "true"
  }, /*#__PURE__*/React.createElement("span", {
    className: "faq-row-icon-h"
  }), /*#__PURE__*/React.createElement("span", {
    className: "faq-row-icon-v"
  }))), /*#__PURE__*/React.createElement("div", {
    className: "faq-row-detail",
    id: `faq-a-${index}`
  }, /*#__PURE__*/React.createElement("div", {
    className: "faq-row-detail-inner"
  }, /*#__PURE__*/React.createElement("p", {
    className: "faq-row-a"
  }, item.a))));
}
function Faq({
  t
}) {
  const ref = useRevealRoot([t]);
  const [openIndex, setOpenIndex] = useState2(0);
  const items = t.faq && Array.isArray(t.faq.items) ? t.faq.items : [];
  function handleToggle(i) {
    setOpenIndex(prev => prev === i ? -1 : i);
  }
  return /*#__PURE__*/React.createElement("section", {
    "data-section": "faq",
    id: "faq",
    "data-enter": "assemble",
    ref: ref
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell"
  }, /*#__PURE__*/React.createElement(SecHead, {
    num: "08",
    eyebrow: t.faq.eyebrow,
    title: t.faq.title,
    meta: `${items.length} · Q&A`
  }), /*#__PURE__*/React.createElement("p", {
    className: "lead-line",
    "data-reveal": true
  }, t.faq.lead), /*#__PURE__*/React.createElement("div", {
    className: "faq-list",
    "data-reveal": true
  }, items.map(function renderFaq(item, i) {
    return /*#__PURE__*/React.createElement(FaqRow, {
      key: i,
      item: item,
      index: i,
      open: openIndex === i,
      onToggle: handleToggle
    });
  }))));
}

// ─────────────────────────────────────────────────────────────────────────────
// TRUST — testimonials
// ─────────────────────────────────────────────────────────────────────────────
// Honesty rule: every number in this section must be traceable to the actual
// dataset below, or explicitly labeled as illustrative. No star ratings, no
// "verified" badges, no on-time percentages — none of that is measured yet.
// When real client quotes replace the placeholders, this same strip keeps
// working (totalQuotes/uniqueRoles recompute) and the "illustrative" note
// can be deleted in one place (t.trust.note).

function Trust({
  t
}) {
  const ref = useRevealRoot([t]);
  const items = t.trust && Array.isArray(t.trust.items) ? t.trust.items : [];
  // Aggregate metrics — derived (not hand-set) so they stay honest.
  const totalQuotes = items.length;
  const uniqueRoles = function countUniqueRoles() {
    const seen = new Set();
    for (let i = 0; i < items.length; i++) {
      const r = (items[i].role || "").split(/[·•]/)[0].trim();
      if (r) seen.add(r);
    }
    return seen.size;
  }();
  const years = function spanYears() {
    const seen = new Set();
    for (let i = 0; i < items.length; i++) {
      const m = (items[i].role || "").match(/(20\d\d)/);
      if (m) seen.add(m[1]);
    }
    return Array.from(seen).sort();
  }();
  const yearLabel = years.length >= 2 ? `${years[0]}–${years[years.length - 1]}` : years[0] || "";
  return /*#__PURE__*/React.createElement("section", {
    "data-section": "trust",
    id: "trust",
    "data-enter": "slide-right",
    ref: ref
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell"
  }, /*#__PURE__*/React.createElement(SecHead, {
    num: "09",
    eyebrow: t.trust.eyebrow,
    title: t.trust.title,
    meta: `${totalQuotes} · signed`
  }), /*#__PURE__*/React.createElement("p", {
    className: "lead-line",
    "data-reveal": true
  }, t.trust.lead), /*#__PURE__*/React.createElement("div", {
    className: "trust-strip",
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "trust-strip-cell"
  }, /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-val"
  }, totalQuotes), /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-k mono"
  }, t.trust.kQuotes || "quotes")), /*#__PURE__*/React.createElement("div", {
    className: "trust-strip-cell"
  }, /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-val"
  }, uniqueRoles), /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-k mono"
  }, t.trust.kRoles || "roles")), yearLabel ? /*#__PURE__*/React.createElement("div", {
    className: "trust-strip-cell"
  }, /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-val"
  }, yearLabel), /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-k mono"
  }, t.trust.kSpan || "span")) : null, t.trust.note ? /*#__PURE__*/React.createElement("div", {
    className: "trust-strip-cell trust-strip-note"
  }, /*#__PURE__*/React.createElement("span", {
    className: "trust-strip-flag mono"
  }, t.trust.note)) : null), /*#__PURE__*/React.createElement("div", {
    className: "trust-grid"
  }, items.map(function renderTrust(it, i) {
    return /*#__PURE__*/React.createElement("figure", {
      key: i,
      className: "trust-card",
      "data-reveal": true,
      "data-reveal-from": "translateY(20px) scale(.98)",
      "data-reveal-delay": (i * 0.08).toFixed(2)
    }, /*#__PURE__*/React.createElement("div", {
      className: "trust-quote-mark",
      "aria-hidden": "true"
    }, "\""), /*#__PURE__*/React.createElement("blockquote", {
      className: "trust-q"
    }, it.q), /*#__PURE__*/React.createElement("figcaption", {
      className: "trust-cap"
    }, /*#__PURE__*/React.createElement("div", {
      className: "trust-avatar",
      "aria-hidden": "true"
    }, /*#__PURE__*/React.createElement("span", null, it.who.split(" ").map(function (w) {
      return w[0];
    }).join("").slice(0, 2))), /*#__PURE__*/React.createElement("div", {
      className: "trust-cap-text"
    }, /*#__PURE__*/React.createElement("div", {
      className: "trust-who"
    }, it.who), /*#__PURE__*/React.createElement("div", {
      className: "trust-role mono"
    }, it.role))));
  }))));
}

// ─────────────────────────────────────────────────────────────────────────────
// CONTACT
// ─────────────────────────────────────────────────────────────────────────────
// Contact form delivery endpoint. Create a free form at https://formspree.io
// and replace YOUR_FORM_ID with the real id (e.g. "xeozabcd"). Until then the
// form runs in "demo" mode — it shows an optimistic success WITHOUT actually
// sending, so the UI is never broken while the endpoint is unconfigured.
const CONTACT_FORM_ENDPOINT = "https://formspree.io/f/YOUR_FORM_ID";
const FORM_ENDPOINT_CONFIGURED = CONTACT_FORM_ENDPOINT.indexOf("YOUR_FORM_ID") === -1;
const CONTACT_FETCH_TIMEOUT_MS = 12000;
function Contact({
  t,
  links
}) {
  const ref = useRevealRoot([t]);
  const [sent, setSent] = useState2(false);
  const [sending, setSending] = useState2(false);
  const [errorMsg, setErrorMsg] = useState2("");
  // Multi-select chips for project scope — a single dropdown was hiding the
  // breadth of services. Chips let the visitor click as many as apply, which
  // also reveals the available service categories at a glance.
  const [scopeSet, setScopeSet] = useState2(() => new Set());
  // Budget slider — 5 fixed buckets so we don't ask for awkward exact numbers.
  // Confirmed directly against the real Uzbekistan market (client's own
  // numbers, 2026-07) — see BUILDER_SCALE_META above for the same pass.
  const BUDGET_BUCKETS = ["< $200", "$200-600", "$600-1.5k", "$1.5-3k", "$3k+"];
  const [budgetIdx, setBudgetIdx] = useState2(1);
  // Timeline preference — small chip row for urgency, helps scoping.
  const TIMELINE_LABEL = t.contact.form.timeline || "Сроки";
  const TIMELINE_OPTS = t.contact.timeline_opts || ["ASAP", "1–2 недели", "1–2 месяца", "гибко"];
  const [timelineIdx, setTimelineIdx] = useState2(3);
  const BUDGET_LABEL = t.contact.form.budget || "Бюджет";
  // Handoff target: the project builder above dispatches "sm:builder-config"
  // when the visitor clicks "перенести в заявку" — we pre-fill the matching
  // scope chip, budget bucket, and drop a summary into the message field so
  // they land on a form that already understands their build.
  const msgRef = useRef2(null);
  useEffect2(function builderHandoff() {
    function onConfig(e) {
      const d = e && e.detail;
      if (!d) return;
      if (d.scope) setScopeSet(new Set([d.scope]));
      if (typeof d.budgetIdx === "number") setBudgetIdx(d.budgetIdx);
      if (d.summary && msgRef.current) {
        msgRef.current.value = d.summary;
        // nudge the reveal/validation state so the filled field looks alive
        try {
          msgRef.current.dispatchEvent(new Event("input", {
            bubbles: true
          }));
        } catch (err) {/* opportunistic */}
      }
    }
    window.addEventListener("sm:builder-config", onConfig);
    return function () {
      window.removeEventListener("sm:builder-config", onConfig);
    };
  }, []);
  function toggleScope(v) {
    setScopeSet(function (prev) {
      const next = new Set(prev);
      if (next.has(v)) next.delete(v);else next.add(v);
      return next;
    });
  }

  // v51: full form reset on submit so the visitor sees a clean slate after
  // the "sent" confirmation expires. We reset the native form (clears
  // <input> / <textarea>) AND all our React state (chip selections, slider,
  // timeline). Previous behaviour kept the text fields populated, which
  // looked broken — the success message overlay didn't visually consume
  // the form below it.
  const SENT_HIDE_DELAY_MS = 4500;
  const FORM_ERROR_FALLBACK = t.contact.form && t.contact.form.error || "Не удалось отправить — напишите в Telegram.";

  // Mark sent + wipe the form (native fields + React-controlled chips/slider).
  function finishSent(formEl) {
    setSent(true);
    if (typeof navigator !== "undefined" && navigator.vibrate) {
      try {
        navigator.vibrate(14);
      } catch (err) {/* opportunistic */}
    }
    try {
      formEl.reset();
    } catch (err) {
      console.warn("[Contact] form.reset failed:", err && err.message);
    }
    setScopeSet(new Set());
    setBudgetIdx(1);
    setTimelineIdx(3);
    window.setTimeout(function hideSentBanner() {
      setSent(false);
    }, SENT_HIDE_DELAY_MS);
  }
  function onSubmit(e) {
    e.preventDefault();
    const formEl = e.currentTarget;
    setErrorMsg("");

    // Collect native fields (name/email/message via their `name=` attrs) plus
    // the React-controlled selections that aren't native inputs.
    const fd = new FormData(formEl);
    fd.append("scope", Array.from(scopeSet).join(", "));
    fd.append("budget", BUDGET_BUCKETS[budgetIdx]);
    fd.append("timeline", TIMELINE_OPTS[timelineIdx]);

    // Demo mode (endpoint not configured) — optimistic success, no network.
    if (!FORM_ENDPOINT_CONFIGURED) {
      finishSent(formEl);
      return;
    }

    // Real delivery via Formspree — with a hard timeout so a hung network
    // can't leave the button stuck in "sending" forever (R-02).
    setSending(true);
    const controller = "AbortController" in window ? new AbortController() : null;
    const timeoutId = window.setTimeout(function () {
      if (controller) controller.abort();
    }, CONTACT_FETCH_TIMEOUT_MS);
    const opts = {
      method: "POST",
      body: fd,
      headers: {
        "Accept": "application/json"
      }
    };
    if (controller) opts.signal = controller.signal;
    fetch(CONTACT_FORM_ENDPOINT, opts).then(function (res) {
      window.clearTimeout(timeoutId);
      setSending(false);
      if (res.ok) {
        finishSent(formEl);
        return undefined;
      }
      return res.json().catch(function () {
        return null;
      }).then(function (data) {
        setErrorMsg(data && data.error || FORM_ERROR_FALLBACK);
      });
    }).catch(function (err) {
      window.clearTimeout(timeoutId);
      setSending(false);
      console.warn("[Contact] submit failed:", err && err.message);
      setErrorMsg(FORM_ERROR_FALLBACK);
    });
  }
  return /*#__PURE__*/React.createElement("section", {
    "data-section": "contact",
    id: "contact",
    "data-enter": "rise-bright",
    ref: ref
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell"
  }, /*#__PURE__*/React.createElement(SecHead, {
    num: "10",
    eyebrow: t.contact.eyebrow,
    title: t.contact.title,
    em: t.contact.title.split(" ").pop(),
    meta: "status: receiving"
  }), /*#__PURE__*/React.createElement("p", {
    className: "lead-line",
    "data-reveal": true
  }, t.contact.lead), /*#__PURE__*/React.createElement("div", {
    className: "contact-layout"
  }, /*#__PURE__*/React.createElement("form", {
    className: "contact-form card",
    onSubmit: onSubmit,
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "contact-form-row"
  }, /*#__PURE__*/React.createElement("label", {
    className: "ff"
  }, /*#__PURE__*/React.createElement("span", {
    className: "ff-k mono"
  }, t.contact.form.name), /*#__PURE__*/React.createElement("input", {
    type: "text",
    name: "name",
    required: true,
    className: "ff-input",
    autoComplete: "name"
  })), /*#__PURE__*/React.createElement("label", {
    className: "ff"
  }, /*#__PURE__*/React.createElement("span", {
    className: "ff-k mono"
  }, t.contact.form.email), /*#__PURE__*/React.createElement("input", {
    type: "text",
    name: "email",
    required: true,
    className: "ff-input",
    autoComplete: "email"
  }))), /*#__PURE__*/React.createElement("div", {
    className: "ff"
  }, /*#__PURE__*/React.createElement("span", {
    className: "ff-k mono"
  }, t.contact.form.scope), /*#__PURE__*/React.createElement("div", {
    className: "ff-chips",
    role: "group",
    "aria-label": t.contact.form.scope
  }, t.contact.scope_opts.map(function renderChip(o, i) {
    const active = scopeSet.has(o);
    return /*#__PURE__*/React.createElement("button", {
      key: i,
      type: "button",
      className: `ff-chip ${active ? "is-active" : ""}`,
      "aria-pressed": active,
      onClick: () => toggleScope(o)
    }, o);
  }))), /*#__PURE__*/React.createElement("div", {
    className: "ff"
  }, /*#__PURE__*/React.createElement("span", {
    className: "ff-k mono"
  }, BUDGET_LABEL, /*#__PURE__*/React.createElement("span", {
    className: "ff-k-val"
  }, BUDGET_BUCKETS[budgetIdx])), /*#__PURE__*/React.createElement("div", {
    className: "ff-range-wrap"
  }, /*#__PURE__*/React.createElement("input", {
    type: "range",
    className: "ff-range",
    min: "0",
    max: BUDGET_BUCKETS.length - 1,
    step: "1",
    value: budgetIdx,
    onChange: e => setBudgetIdx(parseInt(e.target.value, 10)),
    style: {
      "--val-pct": `${budgetIdx / (BUDGET_BUCKETS.length - 1) * 100}%`
    }
  }), /*#__PURE__*/React.createElement("div", {
    className: "ff-range-track-marks",
    "aria-hidden": "true"
  }, BUDGET_BUCKETS.map(function renderMark(_b, i) {
    const cls = i < budgetIdx ? "is-passed" : i === budgetIdx ? "is-current" : "";
    return /*#__PURE__*/React.createElement("span", {
      key: i,
      className: `ff-range-track-mark ${cls}`
    });
  })), /*#__PURE__*/React.createElement("div", {
    className: "ff-range-ticks mono",
    "aria-hidden": "true"
  }, BUDGET_BUCKETS.map(function renderTick(b, i) {
    return /*#__PURE__*/React.createElement("span", {
      key: i,
      className: `ff-range-tick ${i === budgetIdx ? "is-active" : ""}`
    }, b);
  })))), /*#__PURE__*/React.createElement("div", {
    className: "ff"
  }, /*#__PURE__*/React.createElement("span", {
    className: "ff-k mono"
  }, TIMELINE_LABEL), /*#__PURE__*/React.createElement("div", {
    className: "ff-chips",
    role: "radiogroup",
    "aria-label": TIMELINE_LABEL
  }, TIMELINE_OPTS.map(function renderTimeline(o, i) {
    return /*#__PURE__*/React.createElement("button", {
      key: i,
      type: "button",
      role: "radio",
      "aria-checked": i === timelineIdx,
      className: `ff-chip ${i === timelineIdx ? "is-active" : ""}`,
      onClick: () => setTimelineIdx(i)
    }, o);
  }))), /*#__PURE__*/React.createElement("label", {
    className: "ff"
  }, /*#__PURE__*/React.createElement("span", {
    className: "ff-k mono"
  }, t.contact.form.msg), /*#__PURE__*/React.createElement("textarea", {
    ref: msgRef,
    name: "message",
    required: true,
    rows: "4",
    className: "ff-input ff-textarea",
    placeholder: t.contact.form.msg_placeholder || ""
  })), errorMsg ? /*#__PURE__*/React.createElement("div", {
    className: "contact-form-error mono",
    role: "alert"
  }, errorMsg) : null, /*#__PURE__*/React.createElement("button", {
    type: "submit",
    className: `btn btn-primary contact-submit ${sent ? "is-sent" : ""}`,
    disabled: sent || sending
  }, /*#__PURE__*/React.createElement("span", null, sending ? t.contact.form.sending || "Отправка…" : sent ? t.contact.form.sent : t.contact.form.submit), /*#__PURE__*/React.createElement("span", {
    className: "arrow"
  }, sent ? "✓" : "→"))), /*#__PURE__*/React.createElement("aside", {
    className: "contact-side",
    "data-reveal": true
  }, /*#__PURE__*/React.createElement("div", {
    className: "contact-deploy"
  }, /*#__PURE__*/React.createElement("div", {
    className: "mono contact-deploy-head"
  }, /*#__PURE__*/React.createElement("span", {
    className: "chip"
  }, /*#__PURE__*/React.createElement("span", {
    className: "chip-dot"
  }), "ready"), /*#__PURE__*/React.createElement("span", null, "deploy.endpoint")), /*#__PURE__*/React.createElement("div", {
    className: "contact-deploy-body"
  }, t.contact.links.map((l, i) => /*#__PURE__*/React.createElement("a", {
    key: i,
    href: l.k === "Email" ? `mailto:${l.v}` : `https://${l.v}`,
    target: l.k === "Email" ? undefined : "_blank",
    rel: l.k === "Email" ? undefined : "noopener noreferrer",
    className: "contact-link"
  }, /*#__PURE__*/React.createElement("span", {
    className: "mono contact-link-k"
  }, l.k), /*#__PURE__*/React.createElement("span", {
    className: "contact-link-v"
  }, l.v), /*#__PURE__*/React.createElement("span", {
    className: "arrow"
  }, "\u2197"))))), /*#__PURE__*/React.createElement("div", {
    className: "contact-signal"
  }, /*#__PURE__*/React.createElement("div", {
    className: "signal-pulse"
  }, /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null), /*#__PURE__*/React.createElement("i", null)), /*#__PURE__*/React.createElement("div", {
    className: "signal-meta mono"
  }, /*#__PURE__*/React.createElement("div", null, "UTC+5 \xB7 Tashkent"), /*#__PURE__*/React.createElement("div", null, "response < 24h"), /*#__PURE__*/React.createElement("div", null, "EN \xB7 RU \xB7 UZ")))))));
}

// ─────────────────────────────────────────────────────────────────────────────
// FOOTER
// ─────────────────────────────────────────────────────────────────────────────
function Footer({
  t,
  links
}) {
  return /*#__PURE__*/React.createElement("footer", {
    className: "site-footer"
  }, /*#__PURE__*/React.createElement("div", {
    className: "shell footer-inner"
  }, /*#__PURE__*/React.createElement("div", {
    className: "footer-l"
  }, /*#__PURE__*/React.createElement("div", {
    className: "brand"
  }, /*#__PURE__*/React.createElement("span", {
    className: "brand-mark"
  }), /*#__PURE__*/React.createElement("span", null, "SAMANDAR \xB7 EXEC.AI.LAB")), /*#__PURE__*/React.createElement("div", {
    className: "mono footer-copy"
  }, t.footer.copy)), /*#__PURE__*/React.createElement("div", {
    className: "footer-r mono"
  }, /*#__PURE__*/React.createElement("div", null, t.footer.built), /*#__PURE__*/React.createElement("div", {
    className: "footer-links"
  }, /*#__PURE__*/React.createElement("a", {
    href: `https://${links.github}`,
    target: "_blank",
    rel: "noopener noreferrer"
  }, "github"), /*#__PURE__*/React.createElement("span", null, "\xB7"), /*#__PURE__*/React.createElement("a", {
    href: `https://${links.telegram}`,
    target: "_blank",
    rel: "noopener noreferrer"
  }, "telegram"), /*#__PURE__*/React.createElement("span", null, "\xB7"), /*#__PURE__*/React.createElement("a", {
    href: `mailto:${links.email}`
  }, "email")))));
}
Object.assign(window, {
  Services,
  CV,
  Process,
  ProjectBuilder,
  Trust,
  Contact,
  Footer
});