/* landings-new.js — audited 2026 additions kept separate for reviewability.
 * Merged into LANDINGS by landings-data.js in both Node and browser builds.
 */
(function newLandingsModule(root) {
  "use strict";

  var NEW_LANDINGS = {
    "vacation-control": {
      slug: "vacation-control",
      visual: "vacation-control.webp",
      name: "Vacation Control Agent",
      status: "BUILD",
      private: true,
      stack: ["Python", "aiogram", "SQLite", "openpyxl", "python-docx", "pytest"],
      github: null,
      qa: "https://github.com/SamandarMansurkhodjaev2713/qa-engineering-portfolio",
      flow: ["Excel schedule", "Workflow state", "Word document", "Sequential confirm", "Audit + recovery"],
      i18n: {
        ru: {
          tag: "HR OPS · DOCUMENT AUTOMATION",
          role: "Product Engineer + Automation + QA",
          signal: "Отпуск проходит один контролируемый маршрут — от строки в графике до документа и подтверждённого завершения, без потерянных случаев и повторных сообщений.",
          quick: [
            { v: "Excel schedule → Word order → sequential confirmation" },
            { v: "72 автоматических теста · SQLite state · retry/dedupe" },
            { v: "Публичный кейс полностью очищен от ФИО и данных компании" },
          ],
          what: "Vacation Control Agent — приватный Telegram-инструмент для HR-операций. Он читает утверждённый график отпусков, подготавливает документ, ведёт последовательное подтверждение действий и сохраняет незавершённый процесс между перезапусками.",
          problem: "Ручной процесс существует сразу в таблице, шаблоне приказа, сообщениях и памяти ответственного сотрудника. Из-за этого легко повторно отправить уведомление, пропустить подтверждение или потерять случай после сбоя.",
          architecture: "Импорт отделён от workflow-ядра: Excel-адаптер нормализует запись, document service создаёт Word-файл, конечный автомат управляет этапами, SQLite хранит состояние и idempotency keys, а Telegram-слой только доставляет команды и подтверждения.",
          why: "Детерминированное ядро позволяет повторить обработку безопасно: рестарт не начинает отпуск заново, а сетевой retry не создаёт второй документ или второе уведомление. Формат входной таблицы и канал доставки можно менять независимо от бизнес-последовательности.",
          unique: "Ценность не в генерации файла как таковой, а в контроле незакрытого процесса. Агент знает, какой шаг подтверждён, что ожидается дальше и почему повторный event нельзя применить второй раз.",
          employer: "Кейс показывает ownership всего операционного контура: интеграция с привычными офисными форматами, state machine, документы, Telegram UX, восстановление после ошибок и privacy-first публичная коммуникация.",
          quality: "72 теста проверяют парсинг графика, переходы состояний, генерацию документа, повторную доставку, дедупликацию и восстановление после рестарта. Границы адаптеров позволяют тестировать workflow без реального Telegram и без персональных данных.",
          boundary: "В публичную страницу не попадают реальные ФИО, строки отпускного графика, внутренний Word-шаблон, организация, bot username и chat identifiers. Это безопасное описание инженерного решения, а не публикация HR-данных или исходного private repository.",
        },
        en: {
          tag: "HR OPS · DOCUMENT AUTOMATION",
          role: "Product Engineer + Automation + QA",
          signal: "Leave follows one controlled path — from a schedule row to a document and confirmed completion, without lost cases or duplicate messages.",
          quick: [
            { v: "Excel schedule → Word order → sequential confirmation" },
            { v: "72 automated tests · SQLite state · retry/dedupe" },
            { v: "The public case is fully stripped of names and company data" },
          ],
          what: "Vacation Control Agent is a private Telegram tool for HR operations. It reads an approved leave schedule, prepares the document, drives sequential confirmation and persists unfinished work across restarts.",
          problem: "The manual process lives in a spreadsheet, an order template, chat messages and one employee's memory. A confirmation can be missed, a notification duplicated or an open case lost after failure.",
          architecture: "Import is separated from the workflow core: an Excel adapter normalizes records, a document service creates the Word file, a state machine owns the sequence, SQLite stores state and idempotency keys, and Telegram only transports commands and confirmations.",
          why: "A deterministic core makes replay safe: a restart does not begin the leave process again, and a network retry cannot create a second document or message. The spreadsheet format and delivery channel can change without rewriting the business sequence.",
          unique: "The value is not merely generating a file; it is controlling an unfinished process. The agent knows which step is confirmed, what is expected next and why a repeated event cannot be applied twice.",
          employer: "The case demonstrates end-to-end operational ownership: familiar office formats, state machines, document automation, Telegram UX, recovery and privacy-first public communication.",
          quality: "Seventy-two tests cover schedule parsing, state transitions, document generation, redelivery, deduplication and restart recovery. Adapter boundaries let the workflow run without real Telegram or personal data.",
          boundary: "The public page exposes no employee names, leave rows, internal Word template, organization identity, bot username or chat identifiers. It is a safe engineering case, not a publication of HR data or private source.",
        },
        uz: {
          tag: "HR OPS · DOCUMENT AUTOMATION",
          role: "Product Engineer + Automation + QA",
          signal: "Ta’til jadval satridan hujjat va tasdiqlangan yakungacha bitta boshqariladigan yo‘ldan o‘tadi — yo‘qolgan holat va takroriy xabarlarsiz.",
          quick: [
            { v: "Excel schedule → Word order → sequential confirmation" },
            { v: "72 avtomatik test · SQLite state · retry/dedupe" },
            { v: "Ochiq keys ism va kompaniya ma’lumotlaridan to‘liq tozalangan" },
          ],
          what: "Vacation Control Agent — HR operatsiyalari uchun private Telegram vositasi. U tasdiqlangan ta’til jadvalini o‘qiydi, hujjat tayyorlaydi, ketma-ket tasdiqlashni boshqaradi va tugallanmagan jarayonni restartlar orasida saqlaydi.",
          problem: "Qo‘lda jarayon jadval, buyruq shabloni, chat va mas’ul xodim xotirasi orasida yashaydi. Tasdiq o‘tkazib yuborilishi, xabar takrorlanishi yoki xatodan keyin ochiq holat yo‘qolishi mumkin.",
          architecture: "Import workflow-yadrodan ajratilgan: Excel-adapter yozuvni normallashtiradi, document service Word-fayl yaratadi, state machine ketma-ketlikni boshqaradi, SQLite state va idempotency key’larni saqlaydi, Telegram esa faqat buyruq va tasdiqlarni yetkazadi.",
          why: "Deterministik yadro qayta ishlashni xavfsiz qiladi: restart ta’til jarayonini boshidan boshlamaydi, tarmoq retry esa ikkinchi hujjat yoki xabar yaratmaydi. Jadval formati va kanal biznes ketma-ketligidan mustaqil o‘zgaradi.",
          unique: "Qiymat shunchaki fayl yaratishda emas, tugallanmagan jarayonni nazorat qilishda. Agent qaysi qadam tasdiqlanganini, keyin nima kutilayotganini va takroriy event nega qayta qo‘llanmasligini biladi.",
          employer: "Keys butun operatsion konturni boshqarishni ko‘rsatadi: ofis formatlari, state machine, hujjatlar, Telegram UX, recovery va privacy-first ochiq kommunikatsiya.",
          quality: "72 test jadval parsing’i, state o‘tishlari, hujjat yaratish, qayta yetkazish, dedupe va restartdan tiklanishni qoplaydi. Adapter chegaralari workflow’ni real Telegram va shaxsiy ma’lumotsiz testlash imkonini beradi.",
          boundary: "Ochiq sahifada xodim ismlari, ta’til jadvali satrlari, ichki Word-shablon, tashkilot, bot username yoki chat identifiers yo‘q. Bu HR-ma’lumot yoki private source nashri emas, xavfsiz muhandislik keysi.",
        },
      },
    },

    "b24-sales-analyst": {
      slug: "b24-sales-analyst",
      visual: "b24-sales-analyst.webp",
      name: "B24 Sales Analyst",
      status: "BUILD",
      private: true,
      stack: ["Python", "Bitrix24 API", "SQLite", "SQL", "Telegram", "pytest"],
      github: null,
      qa: "https://github.com/SamandarMansurkhodjaev2713/qa-engineering-portfolio",
      flow: ["Bitrix24 read", "Normalized snapshot", "SQL metrics", "CRM reconcile", "LLM explanation"],
      i18n: {
        ru: {
          tag: "CRM ANALYTICS · DECISION SUPPORT",
          role: "Backend + Data Engineering + QA",
          signal: "Цифры считает код и сверяет CRM; языковая модель получает право объяснять результат, но не придумывать метрики.",
          quick: [
            { v: "Read-only Bitrix24 sync · deterministic SQL metrics" },
            { v: "80 тестов · reconciliation · masked secrets" },
            { v: "Day / week / month Telegram reports без доступа на запись" },
          ],
          what: "B24 Sales Analyst — приватный read-only агент, который синхронизирует сделки из Bitrix24, строит проверяемые day/week/month метрики и доставляет краткое объяснение руководителю в Telegram.",
          problem: "Ручные отчёты отнимают время, а «AI-аналитик», который сам вычисляет значения из текста, создаёт новый риск: красивое объяснение нельзя свести с CRM и отделить от галлюцинации.",
          architecture: "Bitrix24 adapter работает только на чтение и сохраняет нормализованный snapshot в SQLite. SQL-layer вычисляет метрики и контрольные суммы, reconciliation сравнивает их с CRM, после чего LLM получает уже готовый JSON facts и не имеет доступа к расчётам.",
          why: "Разделение calculation и explanation делает отчёт воспроизводимым. Даже если модель недоступна, цифры остаются; если explanation выглядит спорно, оператор может проверить каждое значение по deterministic query и source snapshot.",
          unique: "LLM сознательно лишён права быть системой расчёта. Он улучшает читаемость уже доказанного результата, а read-only integration, reconciliation и masked logs уменьшают blast radius.",
          employer: "Кейс демонстрирует зрелую границу AI: API-интеграция, data pipeline, SQL-модель, observability, безопасная доставка и умение не использовать LLM там, где нужна точность.",
          quality: "80 тестов покрывают синхронизацию, pagination, mapping, SQL-метрики, периоды, повторный импорт, CRM reconciliation, деградацию LLM и masking. Секреты и персональные поля не попадают в логи и публичные fixtures.",
          boundary: "Не публикуются CRM endpoint, webhook, названия клиентов и сотрудников, суммы сделок, реальные показатели, chat ID и структура портала. Публичные примеры используют абстрактные потоки без возможности восстановить данные компании.",
        },
        en: {
          tag: "CRM ANALYTICS · DECISION SUPPORT",
          role: "Backend + Data Engineering + QA",
          signal: "Code calculates the numbers and reconciles them with the CRM; the language model may explain the result, never invent the metrics.",
          quick: [
            { v: "Read-only Bitrix24 sync · deterministic SQL metrics" },
            { v: "80 tests · reconciliation · masked secrets" },
            { v: "Day / week / month Telegram reports with no write access" },
          ],
          what: "B24 Sales Analyst is a private read-only agent that synchronizes Bitrix24 deals, builds verifiable day/week/month metrics and delivers a concise explanation to a manager in Telegram.",
          problem: "Manual reporting consumes time, while an “AI analyst” that calculates from prose creates a new risk: polished explanations cannot be reconciled with the CRM or separated from hallucination.",
          architecture: "A read-only Bitrix24 adapter stores a normalized snapshot in SQLite. The SQL layer computes metrics and control totals, reconciliation compares them with the CRM, and only then does the LLM receive an immutable JSON facts payload with no calculation access.",
          why: "Separating calculation from explanation makes a report reproducible. Numbers survive an unavailable model, and every disputed statement can be traced to a deterministic query and source snapshot.",
          unique: "The LLM is deliberately denied the role of calculation system. It improves the readability of a proven result, while read-only integration, reconciliation and masked logs reduce the blast radius.",
          employer: "The case demonstrates a mature AI boundary: API integration, a data pipeline, SQL modelling, observability, safe delivery and the discipline not to use an LLM where exactness is required.",
          quality: "Eighty tests cover synchronization, pagination, mapping, SQL metrics, periods, re-import, CRM reconciliation, LLM degradation and masking. Secrets and personal fields never enter logs or public fixtures.",
          boundary: "The case does not expose a CRM endpoint, webhook, client or employee names, deal amounts, real business metrics, chat IDs or portal structure. Public examples remain abstract and cannot reconstruct company data.",
        },
        uz: {
          tag: "CRM ANALYTICS · DECISION SUPPORT",
          role: "Backend + Data Engineering + QA",
          signal: "Raqamlarni kod hisoblaydi va CRM bilan tekshiradi; til modeli natijani izohlaydi, metrikani o‘ylab topmaydi.",
          quick: [
            { v: "Read-only Bitrix24 sync · deterministic SQL metrics" },
            { v: "80 test · reconciliation · masked secrets" },
            { v: "Yozish huquqisiz day / week / month Telegram report" },
          ],
          what: "B24 Sales Analyst — Bitrix24 bitimlarini sinxronlaydigan, tekshiriladigan kun/hafta/oy metrikalarini tuzadigan va qisqa izohni Telegram orqali rahbarga yetkazadigan private read-only agent.",
          problem: "Qo‘lda report vaqt oladi, matndan raqam hisoblaydigan “AI-analitik” esa yangi xavf yaratadi: chiroyli izohni CRM bilan solishtirish va hallucination’dan ajratish qiyin.",
          architecture: "Read-only Bitrix24 adapter normallashtirilgan snapshot’ni SQLite’da saqlaydi. SQL-layer metrika va control total’larni hisoblaydi, reconciliation CRM bilan solishtiradi, shundan keyingina LLM hisoblash huquqisiz tayyor JSON facts oladi.",
          why: "Calculation va explanation ajratilishi report’ni takrorlanuvchi qiladi. Model ishlamasa ham raqamlar qoladi; bahsli jumlani deterministic query va source snapshot orqali tekshirish mumkin.",
          unique: "LLM ataylab hisoblash tizimi rolidan chetlatilgan. U isbotlangan natijani o‘qishni osonlashtiradi, read-only integratsiya, reconciliation va masked log esa blast radius’ni kamaytiradi.",
          employer: "Keys yetuk AI-chegarani ko‘rsatadi: API-integratsiya, data pipeline, SQL-model, observability, xavfsiz yetkazish va aniqlik kerak joyda LLM ishlatmaslik intizomi.",
          quality: "80 test sync, pagination, mapping, SQL-metrika, period, qayta import, CRM reconciliation, LLM degradatsiya va masking’ni qoplaydi. Secret va shaxsiy maydon log yoki public fixture’ga kirmaydi.",
          boundary: "CRM endpoint, webhook, mijoz va xodim nomlari, bitim summalari, real ko‘rsatkichlar, chat ID va portal tuzilmasi ochilmaydi. Ochiq misollardan kompaniya ma’lumotini tiklab bo‘lmaydi.",
        },
      },
    },

    "chat-app": {
      slug: "chat-app",
      visual: "chat-app.webp",
      name: "ChAT — Offline-first Messenger",
      status: "PROTOTYPE",
      private: false,
      stack: ["React Native", "Expo", "TypeScript", "Firebase", "SQLite", "Jest"],
      github: "https://github.com/SamandarMansurkhodjaev2713/ChAT-app",
      qa: "https://github.com/SamandarMansurkhodjaev2713/ChAT-app",
      flow: ["Local message", "SQLite outbox", "Sync worker", "Firebase rules", "Delivery evidence"],
      i18n: {
        ru: {
          tag: "MOBILE · OFFLINE-FIRST · SECURITY",
          role: "Mobile Architecture + Full-stack + QA",
          signal: "Сообщение сначала становится надёжной локальной операцией — и только потом сетевым обещанием.",
          quick: [
            { v: "SQLite outbox · idempotency · bounded retry" },
            { v: "171 client + 28 Functions + 35 rules checks" },
            { v: "Server-side OTP · rate limit · timing-safe compare" },
          ],
          what: "ChAT — публичный React Native прототип мессенджера, спроектированный вокруг нестабильной сети: локальная outbox-очередь, повторная доставка без дублей, realtime-синхронизация и проверяемые Firebase access rules.",
          problem: "Happy-path чат выглядит простым, пока соединение не пропадает между нажатием «отправить» и подтверждением сервера. Тогда сообщение может исчезнуть, появиться дважды или остаться в ложном статусе, а слабые security rules откроют чужие данные.",
          architecture: "Feature-модули изолируют domain и adapters. SQLite хранит durable outbox, каждое сообщение имеет стабильный idempotency key, sync worker применяет bounded backoff, а Firebase services отвечают за auth, realtime, media и server-side OTP. ESLint запрещает обход архитектурных границ.",
          why: "Local-first state делает UI честным: pending, failed и delivered — реальные состояния, а не optimistic decoration. Idempotency отделяет повторную доставку от повторного создания, security rules тестируются в emulator до подключения production backend.",
          unique: "Надёжность сообщения рассматривается как протокол, а не как spinner. Offline outbox, server verification и lint-enforced boundaries дают проверяемые гарантии ещё до появления production-инфраструктуры.",
          employer: "Кейс показывает mobile systems thinking: локальное хранилище, распределённое состояние, безопасность, serverless backend, архитектурные контракты и честное управление незавершённостью.",
          quality: "171 client test, 28 Functions tests и 35 emulator security-rule checks покрывают outbox, retry, idempotency, OTP, rate limit и права доступа. Документация честно фиксирует непроведённый physical-device pass и отсутствие production backend.",
          boundary: "Это prototype/open-source case, не запущенный production messenger. Реальный production backend и полноценный прогон на физических устройствах ещё не подтверждены; реальные переписки, медиа и пользовательские данные в демонстрацию не входят.",
        },
        en: {
          tag: "MOBILE · OFFLINE-FIRST · SECURITY",
          role: "Mobile Architecture + Full-stack + QA",
          signal: "A message becomes a reliable local operation before it becomes a network promise.",
          quick: [
            { v: "SQLite outbox · idempotency · bounded retry" },
            { v: "171 client + 28 Functions + 35 rules checks" },
            { v: "Server-side OTP · rate limit · timing-safe compare" },
          ],
          what: "ChAT is a public React Native messenger prototype designed around unstable networks: a durable local outbox, duplicate-safe redelivery, realtime synchronization and verifiable Firebase access rules.",
          problem: "A happy-path chat looks simple until connectivity disappears between tapping send and server acknowledgement. A message can vanish, duplicate or remain in a false state, while weak security rules may expose another user's data.",
          architecture: "Feature modules isolate domain logic and adapters. SQLite stores a durable outbox, each message owns a stable idempotency key, a sync worker applies bounded backoff, and Firebase services provide auth, realtime, media and server-side OTP. ESLint prevents architectural boundary bypasses.",
          why: "Local-first state keeps the UI honest: pending, failed and delivered are real states, not optimistic decoration. Idempotency separates redelivery from recreation, and security rules run in the emulator before any production backend.",
          unique: "Message reliability is treated as a protocol, not a spinner. An offline outbox, server verification and lint-enforced boundaries provide verifiable guarantees before production infrastructure exists.",
          employer: "The case demonstrates mobile systems thinking: local persistence, distributed state, security, serverless backend, architecture contracts and honest management of unfinished work.",
          quality: "The repository documents 171 client tests, 28 Functions tests and 35 emulator security-rule checks covering outbox, retries, idempotency, OTP, rate limiting and access. It also states that a physical-device pass and production backend are not yet complete.",
          boundary: "This is a prototype/open-source case, not a production messenger. A real production backend and full physical-device coverage remain unverified; real conversations, media and user data are outside the demo.",
        },
        uz: {
          tag: "MOBILE · OFFLINE-FIRST · SECURITY",
          role: "Mobile Architecture + Full-stack + QA",
          signal: "Xabar avval ishonchli lokal operatsiyaga, keyin esa tarmoq va’dasiga aylanadi.",
          quick: [
            { v: "SQLite outbox · idempotency · bounded retry" },
            { v: "171 client + 28 Functions + 35 rules checks" },
            { v: "Server-side OTP · rate limit · timing-safe compare" },
          ],
          what: "ChAT — beqaror tarmoq atrofida loyihalangan ochiq React Native messenger prototipi: durable lokal outbox, dubldan himoyalangan qayta yetkazish, realtime sync va tekshiriladigan Firebase access rules.",
          problem: "Happy-path chat «yuborish» bosilishi va server tasdig‘i orasida aloqa uzilmaguncha oddiy ko‘rinadi. Shunda xabar yo‘qolishi, takrorlanishi yoki noto‘g‘ri statusda qolishi, zaif security rules esa begona ma’lumotni ochishi mumkin.",
          architecture: "Feature-modullar domain va adapterlarni ajratadi. SQLite durable outbox’ni saqlaydi, har xabarda barqaror idempotency key bor, sync worker bounded backoff ishlatadi, Firebase services esa auth, realtime, media va server-side OTP’ni beradi. ESLint arxitektura chegarasini chetlab o‘tishni taqiqlaydi.",
          why: "Local-first state UI’ni halol qiladi: pending, failed va delivered — optimistic bezak emas, real holatlar. Idempotency qayta yetkazishni qayta yaratishdan ajratadi, security rules production backend’dan oldin emulator’da testlanadi.",
          unique: "Xabar ishonchliligi spinner emas, protokol sifatida ko‘riladi. Offline outbox, server verification va lint-enforced boundaries production infratuzilmasigacha tekshiriladigan kafolat beradi.",
          employer: "Keys mobile systems thinking’ni ko‘rsatadi: lokal storage, taqsimlangan state, xavfsizlik, serverless backend, arxitektura kontraktlari va tugallanmagan ishni halol boshqarish.",
          quality: "171 client test, 28 Functions test va 35 emulator security-rule check outbox, retry, idempotency, OTP, rate limit va access’ni qoplaydi. Hujjat physical-device pass va production backend hali tugallanmaganini ochiq aytadi.",
          boundary: "Bu production messenger emas, prototype/open-source case. Real production backend va to‘liq physical-device coverage tasdiqlanmagan; real yozishma, media va user data demo tarkibiga kirmaydi.",
        },
      },
    },
  };

  root.NEW_LANDINGS = NEW_LANDINGS;
  if (typeof module !== "undefined" && module.exports) module.exports = NEW_LANDINGS;
})(typeof window !== "undefined" ? window : (typeof globalThis !== "undefined" ? globalThis : {}));
